### ISSUE TITLE
[Feature] Fetch list of trading pairs from exchange API when possible

### ISSUE THREAD

**Issue by michaelc9** [hummingbot/hummingbot#1005]
**Feature Suggestion**
The bot should fetch trading pair information and not rely on regex for parsing trading pairs. 

**Impact**
When a new trading pair is added to any exchange with a new base/quote token that is not recognized by the symbol splitter regex, that pair will not be tradable and will result in error is the market classes.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0gva) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
@Nullably AFAIK the bot already do this right? Can we close this issue?

**Comment by Nullably** [comment]
I think this issue refers to how we split symbols (to base and quote) on trading pairs, not about fetching trading pairs (we already do this). 
See https://github.com/CoinAlpha/hummingbot/issues/3232

Yep, we'll need to fix this eventually as regex can no longer be used to do the split (mainly on Binance and other exchanges where there is no separator between symbols)

This also mean `convert_from_exchange_symbol` cannot be used before we fetch trading pairs.
