### ISSUE TITLE
Randomise quantity per order between values

### ISSUE THREAD

**Issue by josephdenne** [hummingbot/hummingbot#1428]
**Feature Suggestion**
The ability to use random quantities between two set values for orders for market making strategies. 

**Impact**
The desired behaviour will make it harder for individuals to game the market making bot, lowering the risk to running Hummingbot.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd139v) by [Unito](https://www.unito.io)

**Comment by dietzam** [comment]
I would like to add to the above proposal and suggest to also randomize within a parameter driven boundary the time in market.

**Comment by phbrgnomo** [comment]
Can't this be implemented as a script?

Since `order_amount` is already accessible by scripts i think it wouldn't be hard to create a script to do this.

@mifeng close this issue or change it to scripts?
