### ISSUE TITLE
Triangular arbitrage

### ISSUE THREAD

**Issue by mifeng** [hummingbot/hummingbot#1709]
See discussion at https://www.reddit.com/r/Hummingbot/comments/fd34rq/old_forum_on_triangular_arbitrage/

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd17yt) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
The first implementation of this strategy should be contained in a single exchange, so we can test and tune it, before allowing it on multiple connectors.

Here is another repo (in Javascript though) for reference: https://github.com/bmino/binance-triangle-arbitrage

The inputs and logic should be simple:

- What is the connector?
- What is the asset/crypto?
- What is the execution strategy? (Linear/parallel)
- What is the min profitability?
- What is the fee %? (add this value to minimum profit)
