### ISSUE TITLE
Bittrex credits

### ISSUE THREAD

**Issue by haferman** [hummingbot/hummingbot#1806]
**Feature Suggestion**
Bittrex credits are described here:
https://bittrex.zendesk.com/hc/en-us/articles/360032214811-Learn-More-About-Bittrex-Credits

Credits are earned by making trades. So doing market-making earns a lot of credits. Each credit is worth $0.01 USD toward trading commissions.

**Impact**
The impact would be to reduce overall trading fees on Bittrex.

**Additional context**
Here is what the Bittrex site says:

> You can use Bittrex Credits when placing orders from the v3 API by including "UseAwards": true in the request body. Note that the order will fail if you do not have sufficient Bittrex Credits available. You can get your current Bittrex Credits balance by querying any of the balance APIs and looking for BTXCRD.

So, it would take some work, but there could be a hummingbot flag that would check for Bittrex Credits and if available, use them.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1aa8) by [Unito](https://www.unito.io)

**Comment by mifeng** [comment]
If we are using the Bittrex v3 API in Hummingbot, then this should be a straightforward change: add a bool global configuration variable and set `UseAwards` to it when trading on Bittrex
