### ISSUE TITLE
[BUG] Broken pipe error on script

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#2123]
**Describe the bug**
Run a strategy with a script, after long period of time, stop and start the bot and I get below errors
![image](https://user-images.githubusercontent.com/37262506/88769915-a0792f80-d1af-11ea-8346-ca8b50730ea4.png)

The screen became unresponsive, and had to kill the session with `screen -X -S [session_name] kill` command.

**Steps To Reproduce**
Unfortunately, I am still unable to reproduce this.

After a quick search on the error, someone suggested to put a bit of time sleep before closing multiprocess queues.
https://bugs.python.org/issue35844
Just added it as a note here.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak52z) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
I've seen this today on 3 out of 5 bots that had been running for 10 days or so. Error occurred when running "stop" command from UI. Was able to double-ctrl-c quit the bots ok

**Comment by rapcmia** [comment]
Closing ticket since the fix already applied, see link [here](https://github.com/hummingbot/hummingbot/pull/2610)
