### ISSUE TITLE
[BUG] Command config market [value] not working

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#2125]
**Describe the bug**

As indicated in the [docs,](https://docs.hummingbot.io/operation/commands/config/#config-key-value) we can reconfigure a parameter on a single line by doing `config [key] [value]`. Tested on all pure market making params and worked except for ``config market`` and ``config price_source_market``.

``config market [value]``
``config price_source_market [value]``

**Steps To Reproduce**

Enter ``config market [value]`` or ``config price_source_market [value]`` on your PMM strategy.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/88789323-33729380-d1c9-11ea-9617-ad8627551554.png)
![image](https://user-images.githubusercontent.com/64377055/88789243-176ef200-d1c9-11ea-95da-c21b958c305c.png)

**Release version**

version-0.29.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak532) by [Unito](https://www.unito.io)

**Comment by Clint-G13** [comment]
Same behavior for market pairs on both Cross exchange and Arbitrage strategy;
Cross Exchange:
![XEMM](https://user-images.githubusercontent.com/57189990/88834286-36d84000-d206-11ea-991b-88f845ba3962.JPG)
Arbitrage:
![ARB](https://user-images.githubusercontent.com/57189990/88834302-3b045d80-d206-11ea-8d8b-2afc2e5282dc.JPG)

**Comment by sigit2306** [comment]
Same behavior for `config market [value]` where the hyphen is emitted
![01](https://user-images.githubusercontent.com/12313129/88894847-c287b600-d272-11ea-9676-269247bcaa0f.png)

but the bot shows different behavior for config price_source_market [value] where the hyphen is emitted.
Right pane doesn't generate message, while left pane (running logs) generates message.
![02](https://user-images.githubusercontent.com/12313129/88894881-cddae180-d272-11ea-80b6-5b3580cd7c0e.png)

**Comment by sigit2306** [comment]
Another similar one-line command  issue but not on `config market` or `config_price_source_market`, 
It's on `config paper_trade_account_balance`
![01](https://user-images.githubusercontent.com/12313129/89164862-d8aeb280-d5a1-11ea-9c1d-b36204a15ea2.png)

**Comment by nikspz** [comment]
Failed to initialize one line command for changing market (Example: `config market XRP-USDT`)

Steps:
Enter config market [value] or config price_source_market [value] on your strategy (upon checking all strategies affected)

Actual:
For the active pair, Bot showing that `pair is not active market on the exchange` and showing promt for manually search another pair.

Expected:
User could change the market with one line of code

![image](https://user-images.githubusercontent.com/83953535/160802207-5781ddc3-bfe0-4ae9-aee6-c46e865016dc.png)
