### ISSUE TITLE
[Feature] - Min order amount enhancement

### ISSUE THREAD

**Issue by thomasyit** [hummingbot/hummingbot#2138]
**Feature Suggestion**

The min order will fluctuate due market volatility and if user only wants to trade the minimum amount, the bot can easily go into no-trade mode - "no active market orders"   user might assume that bot is running market orders,  for example: a coin is $2, min trade amount is$10, only 5 coins is min requirement but if coin falls down to $1, 10 coins becomes the new requirement.

Suggest that user can set the min order to be dynamic upon every order refresh. Settings suggestion: set 0 for the min order to always trade at the min order for every trade refresh.

**dependencies**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak53v) by [Unito](https://www.unito.io)

**Comment by avdeepak87** [comment]
I faced the issue with order amount too. I wish to have this feature anytime soon!

**Comment by phbrgnomo** [comment]
Related issue: [#2490](https://github.com/CoinAlpha/hummingbot/issues/2490)
