### ISSUE TITLE
[BUG] Possible issue reconnecting to network while using scripts

### ISSUE THREAD

**Issue by dietzam** [hummingbot/hummingbot#2164]
**Describe the bug**
// This is running a recent Development version using the script facility. The bot was running fine for almost 12 hours. The script was performing also as expected. The script is a modified version of '**spreads adjusted on volatility**'. From the log it appears that there was a network issue at some stage, and the reconnecting with the script did not work properly. The cloud-instance was not responding and had to be killed and restarted.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up your configuration file with these parameters: ...
1. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
//Development maybe 1 day old

**Attachments**
// log (shortend)
    script output (shortend)
[log.txt](https://github.com/CoinAlpha/hummingbot/files/5031875/log.txt)
[logs_script_out.txt](https://github.com/CoinAlpha/hummingbot/files/5031876/logs_script_out.txt)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak57v) by [Unito](https://www.unito.io)

**Comment by dietzam** [comment]
this has happend again, same scenario


[Log extract.txt](https://github.com/CoinAlpha/hummingbot/files/5094044/Log.extract.txt)

**Comment by rapcmia** [comment]
hi @dietzam just checking if this is still a ongoing issue when using the scripts on development branch? Thank you

**Comment by dietzam** [comment]
No
