### ISSUE TITLE
[Feature] reverse trading pairs

### ISSUE THREAD

**Issue by itsmequik** [hummingbot/hummingbot#2279]
**Feature Suggestion**
Add an option to reverse a trading pair. I. e.: Inverse the trading pair ETH-BTC to BTC-ETH 

Some Exchanges for example use ETH-BTC and other exchanges use BTC-ETH. So it would be great to be able to inverse one of the trading pairs so its possible to run a cross exchange arbitrage bot.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak6bh) by [Unito](https://www.unito.io)

**Comment by vic-en** [comment]
@itsmequik 
Each connectors in Hummingbot have functionalities to handle trading pairs conversion.
So all connectors convert from/to the standard/simplified Hummingbot pair format which is in `{BASE}-{QUOTE}`.
Users need not worry themselves about pair conversion as connectors do that automatically.

**Comment by itsmequik** [comment]
ok. This is my conversation with mike on discord:
![Capture](https://user-images.githubusercontent.com/22601305/92313320-c376da80-efca-11ea-8fff-83729545a208.JPG)
