### ISSUE TITLE
[Feature]  Remove Docker `exit` requirement for loading scripts

### ISSUE THREAD

**Issue by unchainedio** [hummingbot/hummingbot#2294]
**Feature Suggestion**

// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.

When adding a script to your hummingbot instance, it requires `exit` and `start`.  This is very time consuming, it should only require a strategy `start`/`stop`

Changing a loaded script should also require max  effort, `start`/ `stop`.  If u can make it pick up the changes in a less intrusive way even better.  ie. it should pick up changes every interval or something.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to test scripts faster instead of having to kill a docker instance each time i want to change a script variable.   Testing scripts requires trial and error and each time you want to test something out, u currently must `exit`, this is a very heavy process and causes history/data loss.

**Additional context**

this is an error i got when i loaded the sample variability script that comes with hummingbot

https://discordapp.com/channels/530578568154054663/745411770042155122/752936665596690593

only way i was able to load this script was `exit`

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak6ht) by [Unito](https://www.unito.io)

**Comment by sigit2306** [comment]
re: remove docker `exit` requirement for loading scripts
I did a test on hb v0.31.0 from docker build, it doesn't need to exit when changing to another script, just `stop` the bot and `start` it again
![image](https://user-images.githubusercontent.com/12313129/92990035-d32e7b80-f502-11ea-9a4a-d52414605cb7.png)


re: error got when loaded the sample variability script that comes with hummingbot
I didn't get the error. But something is different, base on screenshot https://discordapp.com/channels/530578568154054663/745411770042155122/752940029080371220  the market pair was DASHBTC (that cause the error) while on Binance the market pair format is DASH-BTC, did you perhaps changed the exchange on the same bot, i.e. from Coinbase to Binance, and didn't change the market pair?
Can you share here the logs file
