### ISSUE TITLE
[BUG] Cross market making - Buying high selling low

### ISSUE THREAD

**Issue by cryptogasm** [hummingbot/hummingbot#2310]
**Describe the bug**

* Cross market making - Buying high selling low
* also notice that 4-5 seconds on trading

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/68583926/92878589-d6603380-f43e-11ea-9256-f1c6e33dccac.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/68583926/92878553-ca747180-f43e-11ea-84d6-ad23da888b75.png)
![image](https://user-images.githubusercontent.com/68583926/92880518-aca80c00-f440-11ea-84b6-e28574b32132.png)

**Release version**
0.31.0 / dev-0.32.0

**Attachments**

[logs_xemm-ethusdt.log](https://github.com/CoinAlpha/hummingbot/files/5207246/logs_xemm-ethusdt.log)
[trades_xemm-ethusdt_csv.log](https://github.com/CoinAlpha/hummingbot/files/5207247/trades_xemm-ethusdt_csv.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**
CryptoGasm

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak6pw) by [Unito](https://www.unito.io)

**Comment by PtrckM** [comment]
- Tested on live trade and bot is behaving as expected, it seems that this issue is happening when running on paper trade only

![image](https://user-images.githubusercontent.com/54516858/103622278-70f5fc80-4f71-11eb-8721-6997ee9cbb13.png)

**Comment by mss7082** [comment]
I have this issue as well and I am not in paper mode.

![image](https://user-images.githubusercontent.com/6820077/118729435-d4503f00-b82d-11eb-8120-289b3acefd17.png)

![image](https://user-images.githubusercontent.com/6820077/118729456-df0ad400-b82d-11eb-8fb3-4b77ad2618e6.png)

![image](https://user-images.githubusercontent.com/6820077/118729465-e5994b80-b82d-11eb-832a-0f07e4bb745d.png)


[logs_conf_xemm_dot_17052021_2.log](https://github.com/CoinAlpha/hummingbot/files/6504673/logs_conf_xemm_dot_17052021_2.log)

[trades_conf_xemm_dot_17052021_2.csv](https://github.com/CoinAlpha/hummingbot/files/6504682/trades_conf_xemm_dot_17052021_2.csv)

**Comment by rapcmia** [comment]
I tried to replicate the using mss7082's config and got the same results

XEMM Strategy would normally sell an asset on taker exchange then places a buy order with a lower value. I noticed it sell order at `37.297` on Binance which I assume should place a buy order on Kucoin a bit lower but no go, it created `37.5102` instead (filled). 

Kucoin (maker):
![image](https://user-images.githubusercontent.com/73840223/118791612-72451780-b8c9-11eb-9ced-b8facdd2f5b4.png)

Binance (taker):
![image](https://user-images.githubusercontent.com/73840223/118791719-8ee14f80-b8c9-11eb-8a80-3917a7ef97ec.png)

It seems that it works ok when it looks to buy assets on taker exchange and then places a sell order with higher value. For Kucoin this time a sell order of `37.4617` and then `37.248` on Binance

Kucoin (maker):
![image](https://user-images.githubusercontent.com/73840223/118794088-cf41cd00-b8cb-11eb-87cc-982c8c9ea784.png)

Binance (taker):
![image](https://user-images.githubusercontent.com/73840223/118793991-b802df80-b8cb-11eb-9608-217dd200bb77.png)

Attached:
[logs_xemm-2310.log](https://github.com/CoinAlpha/hummingbot/files/6507719/logs_xemm-2310.log)
