### ISSUE TITLE
[Feature] Reserve balance

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#2322]
**Why**
When I do market making on Binance, I want to reserve certain amount of BNB to pay for trade fees, currently there is no easy way for me to do this while market making on BNB pairs. 

**Feature Suggestion**
A new feature to specify how much balance of a certain token on a particular exchange is to be reserved and not to be used by the bot. It will have similar structure as `balance_asset_limit` in the global config file.

```
reserve_balance:
  binance:
    BNB: 2.0
```

The bot will apply this parameter on available balance before `balance limit`, examples (based on `reserve_balance setting` above)

* BNB available = 10, balance limit =10 --> BNB bot can use = 8
* BNB available = 12, balance limit =10 --> BNB bot can use = 10
* BNB available = 10, no balance limit setting --> BNB bot can use = 8

There is no need to make this parameter configurable through CLI, config file manual update is sufficient at this point.

**Impact**
The feature will be very useful for traders who want to reserve certain token balance for particular usage (e.g. paying for fee, or staking) while making sure he/she can still fully utilize the rest of the token for market making.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak6yv) by [Unito](https://www.unito.io)

**Comment by ZeroCool940711** [comment]
I think it would be nice to be able to reserve some BNB balance for fees as @Nullably mentioned before but also would be nice to be able to buy more BNB automatically if we are running low on it, that way if we are trading for example BTC-USD and using BNB for fees when we have less than certain amount Hummingbot would use part of the gained profit/return or a reserved amount of USD or other currency to buy more BNB that will be used for trading fees, an example of how this could be would be like to have configurable options like @Nullably mentioned:
```
reserved_balance:
  binance:
    BNB: 1.0
    USD: 1.0
    profit_percent: 1.0
    minimum_BNB: 2.0
```
These values would be in % mostly so they are relative to the total balance of their respective currency, in the case of `profit_percent` it would use for example 1% of the profit we have made by running the bot to later buy more BNB and use it for fees, the same would be for USD or any other currency we add there to that list, the bot will periodically check the current BNB balance and if it's lower than the `minimum_BNB` value it will use those currencies listed under `reserved_balance` to buy more BNB automatically.
