### ISSUE TITLE
[BUG] Order is not placed silently when order amount is too low

### ISSUE THREAD

**Issue by bitphage** [hummingbot/hummingbot#2339]
**Describe the bug**

If `order_amount` is low enough to not fit to exchange requirement, it's being quantized to 0 and not placed silently. I'm expecting to see an error like "Your order amount value is too low".

I added some logging to proof me right:

```
2020-09-16 17:00:42,002 - 20667 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - initial: 9.0, quantized: 0
```

```diff
--- a/hummingbot/strategy/pure_market_making/pure_market_making.pyx
+++ b/hummingbot/strategy/pure_market_making/pure_market_making.pyx
@@ -633,10 +633,12 @@ cdef class PureMarketMakingStrategy(StrategyBase):
         for level in range(0, self._sell_levels):
             price = self.get_price() * (Decimal("1") + self._ask_spread + (level * self._order_level_spread))
             price = market.c_quantize_order_price(self.trading_pair, price)
-            size = self._order_amount + (self._order_level_amount * level)
-            size = market.c_quantize_order_amount(self.trading_pair, size)
+            size_initial = self._order_amount + (self._order_level_amount * level)
+            size = market.c_quantize_order_amount(self.trading_pair, size_initial)
             if size > 0:
                 sells.append(PriceSize(price, size))
+            else:
+                self.logger().info(f'initial: {size_initial}, quantized: {size}')
 
         return Proposal(buys, sells)
```

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak78p) by [Unito](https://www.unito.io)

**Comment by bitphage** [comment]
Checked current development, it won't allow to start with too low order amount:
`18:18:14 - root - Invalid value 5.0 for config variable order_amount`

Though, the `order_amount` can still be too low in case asset price was dropped and previously valid amount became too low. That's how I actually discovered the issue.

**Comment by phbrgnomo** [comment]
This also happens if you lower the limit on the conf_global.yml file, where you could input an `order_amount` lower than the exchanges allow.

Haven't checked, but this could also happen with `arbitrage` strategy, since the exchanges can have different minimum amounts, so we should add an error report there too.
