### ISSUE TITLE
[Feature] order_amount and order_level_amount as decimal

### ISSUE THREAD

**Issue by krisj** [hummingbot/hummingbot#2351]
**Feature Suggestion**

I'd love to be able to choose between a proportional (pct based like it is now) and fixed decimal spread size, both for bid/ask_spread spreads as well as order_level_spread individually. Same with minimum_spread

**Impact**

This would be very useful for low cap coins with large minimum step.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak7fj) by [Unito](https://www.unito.io)

**Comment by French-tooms** [comment]
@krisj I agree, putting a % setting for order_amount would be really nice and make it easier to build longer-lasting strategies

**Comment by French-tooms** [comment]
@Nullably Is there an ETA for this?

**Comment by Nullably** [comment]
@krisj Thanks for the suggestion. Yep agree, this would be useful.
@French-tooms Our project manager will take a look and see if and how it will fit into our roadmap. Sorry, can't give you ETA at the moment.
