### ISSUE TITLE
[Feature] Adding logs if the bot cant trade due to min order discrepancy

### ISSUE THREAD

**Issue by avdeepak87** [hummingbot/hummingbot#2372]
**Feature Suggestion**
Today i could see the bot suddenly stopped making orders and I didn't not know why. when i contacted support they suggested to check the order_amount parameter. To my bad it was less than the minimum order. Can we have a feature to display in logs if the order couldn't be placed due to the mismatch in the minimum order and order amount. 

**Impact**

The desired behavior will allow me to know why bot is not making orders and sitting idle.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak7x3) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
Also Covered on Issue [#2339](https://github.com/CoinAlpha/hummingbot/issues/2339)
