### ISSUE TITLE
[BUG] Hummingbot overwriting external exchange price feed

### ISSUE THREAD

**Issue by gabririgo** [hummingbot/hummingbot#2409]
**Describe the bug**
after the latest release, a bot got taken a rogue order. After investigating the root, it turns out that the strategy config file has been overwritten as follows:

# The price source (current_market/external_market/custom_api).
price_source: current_market

while price feed has always been "external" on all strategies (making market on 0x mesh).

I will later complete the description of the bug. Please note I already warned in the past about the dangers of overwriting config files with new updates without letting the operator know or go through the settings manually. This has resulted in a 540$ loss on a single 1000$ order.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up your configuration file with these parameters: ...
1. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak8en) by [Unito](https://www.unito.io)

**Comment by sigit2306** [comment]
Hi gabririgo, can you please provide more detailed information, screenshots, bot logs, and strategy configuration file. 
Does the bot use a modified script?
What version the previous bot that was used before updating?
What hummingbot build are you running on, docker or source build?

**Comment by gabririgo** [comment]
> Hi gabririgo, can you please provide more detailed information, screenshots, bot logs, and strategy configuration file.
> Does the bot use a modified script?
> What version the previous bot that was used before updating?
> What hummingbot build are you running on, docker or source build?

sure I will provide as much info as possible, I am fully focussed on a project right now and cannot revert before being done with it, however please make sure you check also with other testers and advise the other market makers to double check on the config file should they use external price feeds. Hope my loss can at least save other makers from potential losses.
