### ISSUE TITLE
[Refactor] Loopring outstanding refactoring tasks.

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#2423]
The current Loopring connector has a few minor refactoring tasks which should be addressed in our Hummingbot future release.

* Code doesn't conform to Flake8 coding convention
* `ethsnarks2` should be a package on its own
* Outstanding Todo in the code should be addressed.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak8k7) by [Unito](https://www.unito.io)

**Comment by TheHolyRoger** [comment]
_clears throat_ it does at least conform to flake8 now as of this PR @Nullably ;) https://github.com/CoinAlpha/hummingbot/pull/2414

**Comment by Nullably** [comment]
@TheHolyRoger Thanks a lot!
