### ISSUE TITLE
[Feature] Add a module similar to scripts that will allow the users to create their own indicators

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#2427]
**Feature Suggestion**
Create a module similar do script_base.py (could be called indicator_base.py) to allow the users to create/import custom python code to calculate indicators

That way, scripts would call results from indicators codes and send the commands to the main bot functions.

**Impact**
This would allow users to create their own indicators or use the vast library of python indicators available, that could be reused on any amount of scripts.

**Additional context**
From #2405 comment:

The data flow would be something like:

The main bot module collect the data -> TA module use the data to calculate the Indicator (like scripts do) -> Script use the return data from TA module to send the modifications to the bot.

For professionals, this could be a more interesting and efficient way to apply Indicators, since the data is collected directly from the source (the exchange) and also allow the trader to implement their indicators based on tick data, instead of candles, and reduce the processing time.

Depending on the pair and the exchange, i have seen some discrepancies from Tradingview and the data of an exchange (like volume).

Another advantage would be that advanced users could create their Indicators using their own customized information source, instead of only price and volume, allowing the implementation of more quant strategies.

Also, since this would be on python, a separate module for Technical Indicators also allows the use of the vast library of code already available on the web.

Two things would be needed for this architecture:

* The bot would need to have a way to store and call more information from the exchange to feed the TA module (volume per tick, for example)
* The bot would need to transform the tick data into common format used by indicators (transform tick data do candles (OHLC table)) - There is code available [here ](https://medium.com/swlh/retrieving-full-historical-data-for-every-cryptocurrency-on-binance-bitmex-using-the-python-apis-27b47fd8137f) that could be used as a base
* Similar to scripts, we would need a documentation hub to show the functions as a reference guide for developers.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak8mg) by [Unito](https://www.unito.io)

**Comment by krisj** [comment]
> * The bot would need to transform the tick data into common format used by indicators (transform tick data do candles (OHLC table)) - There is code available [here ](https://medium.com/swlh/retrieving-full-historical-data-for-every-cryptocurrency-on-binance-bitmex-using-the-python-apis-27b47fd8137f) that could be used as a base

You would also want to establish how to deal with the OHLCV. Some indicators and configurations would need history. As you know HB doesn't store tick history and thus on the start of the bot it could mean waiting a long time until OHLC is built. So it might make sense to request the initial OHLCV data via API - the question then is - does it go back to the connector (meaning - having to implement candle data request in the connectors). And how is it being stored locally? DB or file? Configurable?

We are looking at all this ourselves but if HB had it implemented it would be amazing of course.

From our current research it does not seem a like a trivial feature to implement though. Quite a bit of work needs to be done from what I can tell.

**Comment by GrandGarcon** [comment]
Hi  ,  first of thanks @phbrgnomo  for  mentioning the issue . in addition to above , i am intrested in addingthe support for RSI stochastic  strategy via scripting for an custom connector . thanks
