### ISSUE TITLE
[Feature] Direct script Integration

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#2448]
**Why**
Currently scripts run in its own separated sub process to the Hummingbot, and the communication is done through multiprocess queues. The problems with this model since we started using scripts are:

* It doesn't work on both Windows and Mac binaries #2034 
* It is hard to debug
* Users often get broken pipe error #2123
* Exposure to additional objects and their properties in HB needs updates to the script interface, users will have to wait for a release.

**Feature Suggestion**
I propose a direct script integration with HB by having it lives in the same process as the HB and let it have direct access to other object in HB (queues are no longer needed). This will solve most of the problems mentioned above.

**Impact**
One of the main reasons we had a script in a sub process was that we can't fully trusted scripts to be working correctly and that could corrupt the whole HB. But since scripts have become more essential part of the trading strategy, one could argue if the script fails perhaps the whole HB operation should be aborted and the script should be fixed before continue on.

**Suggested Tasks**
In the `/hummingbot/script/`

* Remove all the queues, script_interface and script_process
* Integrate script object directly with `script_iterator` 
* Modify `script_base` to get direct exposure to the current running `strategy` object.

_Note_ these tasks are from initial investigation, you might need to modify them as needed when actually implementing this.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakgaf) by [Unito](https://www.unito.io)

**Comment by bitphage** [comment]
I would suggest to run script from asyncio.Task wrapper like this:

```python
def wrapper(script):
    try:
        await script()
    except Exception:
        log.exception('script finished with exception:')

asyncio.create_task(wrapper(some_script))
```
