### ISSUE TITLE
[Feature] New script examples - BTFD, DCA, Pullback and more

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#2450]
**Feature Suggestion**
New basic scripts examples that illustrate how HB can be used for common position sizing strategies.

_BTFD_
Buy the dip - an accumulation strategy that buys when the price dips, define the dips as when current price is below 20 days MA and 24 h price change is below -5%.

_DCA_
Dollar Cost Average - an accumulation strategy that buys the same amount of token in fixed dollar amount on a regular schedule, e.g. buy $100 worth of BTC every Monday at 10 AM.

_Pullback_ 
Shows how a user can use a script to set up a multi level conditions strategy. Let's assume BTC has been going up steadily, the user expects the price to reach a certain level (at X price) then it will pullback to Y price before the trend resumes. What the user can do is predefine multi level conditions as - if price rises to X, sell BTC, then after that when price drops to Y, buy back the same amount - and let the bot execute on the plan.

_Wall Alerts_
Shows how HB can be used to scan an order book for buy/sell walls and alert the user. The walls can be defined as a large order volume (maybe 10% of average daily trading volume) at a single price level.

_Prerequisites_
#2449 
#2448

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakgbh) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
![Captura de tela 2021-02-19 09 26 25](https://user-images.githubusercontent.com/34484531/108504461-a9893580-7294-11eb-9215-7e661d200894.png)

for DCA, the above (or some variant) configuration would work like that.

@Nullably could we turn this configuration into a new strategy file?

I am thinking about something that non-traders could use, and don't want to go through the hassle of figuring out what is the best configuration to make the bot execute a DCA strategy.

**Comment by krisj** [comment]
I think this is a great idea! some very conservative but actually ready to set-forget type samples. To wet the appetite so to speak. They would be more in the "alpha" category than market-making, but useful none the less.
