### ISSUE TITLE
[Feature] Display order spreads away from mid price while using other price reference

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#2455]
**Describe the bug**

As seen on the picture, the spread calculated of the open order with `status` command is using the `last_own_traded_price` as the price to calculate the spread.

This can be confusing for the users, and it is hard to visualize what is the bot order position related to the current market price.

the Spread shown on status should still use `mid_price` or `last_price` to calculate the % Spread relative to the current market price.

**Steps To Reproduce**
execute bot with `price_type` = `last_own_traded_price`

**Screenshots**
![Captura de tela 2020-10-08 09 58 07](https://user-images.githubusercontent.com/34484531/95462004-4df58580-094d-11eb-943e-8b33b07c33e3.png)

**Release version**
0.32

**Attachments**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakgh5) by [Unito](https://www.unito.io)

**Comment by Nullably** [comment]
By definition, spreads are calculated from the ref price not mid price, when a user configures 1% bid spread using `last_own_trade` price type that is not 1% spread from mid price. Changing this definition will also confuse users.

So this is not a bug. 

We could add a new column `spread (mid price)` if there'd be more informative but I'd rather first wait and see real users feedbacks.
