### ISSUE TITLE
[BUG] Taker order is not created on xemm if maker order is filled during cancellation request

### ISSUE THREAD

**Issue by supervik** [hummingbot/hummingbot#2501]
**Describe the bug**
Sometimes the maker's order is filled right in between when the bot has already decided that the maker order is no longer profitable but it has not canceled it yet. The process is approximately the following:

1. The bot calculates that the order is no longer profitable
1. The bot sends to the maker market cancellation request
1. The order is being filled
1. No successful confirmation of the order cancellation from the market received because there is no such an order anymore
1. The bot continues its usual routines 
As a result, the taker order is not created. Hedging opportunities missed and inventories unbalanced.

**Steps To Reproduce**
It's difficult to reproduce the bug because it can't be predicted when the order will be filled. It is not a major issue but is very annoying.

**Screenshots**
On the screenshot below, the maker order is filled at 2:05:36. 
An order filled event was not created.
![logs!UNITO-UNDERSCORE!hb](https://user-images.githubusercontent.com/57992574/96875592-08be7100-1480-11eb-9a5d-617453336cbd.png)

[logs_hb.txt](https://github.com/CoinAlpha/hummingbot/files/5422957/logs_hb.txt)

**Release version**
0.32.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakj2b) by [Unito](https://www.unito.io)

**Comment by fengkiej** [comment]
Experiencing similar issue, any idea how to fix this?
