### ISSUE TITLE
Allow multiple scripts in HB client

### ISSUE THREAD

**Issue by jason-hb** [hummingbot/hummingbot#2532]
**Feature Suggestion**
Provide the ability for multiple script files to be used in the HB client. The current configuration only allows for a single script file and sometimes combining multiple functions within a single script is difficult and/or inefficient

**Impact**
The desired behavior will allow me to run multiple scripts accomplishing dedicated tasks. For example, one script can adjust spreads dynamically based on volatility while another can set a dynamic price band around the trading activity

**Additional context**
Discussed with Mike F. about creating sample single script that performed more than one function and he preferred to modify the code to allow multiple scripts

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakqzc) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
You can do this currently surely? You have a single main script that implements the ScriptBase API which then farms out to other scripts to perform dedicated functions?

**Comment by phbrgnomo** [comment]
Could this be achieved with `import <other script name>`?

**Comment by zappra** [comment]
Yep, you just need to use scripts as the base path, eg. from scripts.my_script import my_class, assuming you have a file scripts/my_script.py
