### ISSUE TITLE
Enable scripts to update inventory_target_base_pct

### ISSUE THREAD

**Issue by 0ffs** [hummingbot/hummingbot#2544]
**Feature Suggestion**
I would like a fully automated functionality through scripts to update the inventory_target_base_pct field in the pure market making strategy. The solution cannot require a restart of the bot or a start and stop of the bot.

My goal is to manage my inventory risk in a controlled fashion. I would like to keep on average the same # of tokens as when I started market making. In order to achieve this today I'm updating the inventory_target_base_pct manually every day. This makes it impossible for me to go on vacation without access to my bots.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakr82) by [Unito](https://www.unito.io)

**Comment by TradeClaw** [comment]
I was wondering why there wasn't a parameter called **inventory_target_base_amount** since that can't be too hard to do compared to the whole percentage thing.

It's mayhem running more than a few bots on the same account, which you need to do for the liquidity mining rewards, when one dumps hard and uses up the whole budget for the others.

And ideally an inventory_target_base_combined boolean to optionally take both into account.

**Comment by 0ffs** [comment]
Hey,
Thx for adding me. I would also add that anyone with a decent capital and risk management mentality wants to track both the loss and gain on the original asset purchase and the market making + rewards. The only way I can track it at least a little bit is if I keep the # of tokens I invested in a market making strategy constant. Having an inventory base amount field for both market and asset would be fantastic for me.
Cheers,
Offs
    On Thursday, 5 November 2020, 16:04:27 CET, TradeClaw <notifications@github.com> wrote:  
 
 


I was wondering why there wasn't a parameter called inventory_target_base_amount since that can't be too hard to do compared to the whole percentage thing.

It's mayhem running more than a few bots on the same account, which you need to do for the liquidity mining rewards, when one dumps hard and uses up the whole budget for the others.

And ideally an inventory_target_base_combined boolean to optionally take both into account.
