### ISSUE TITLE
[Feature] Add mark_price as a price_type to derivatives

### ISSUE THREAD

**Issue by TradeClaw** [hummingbot/hummingbot#2578]
**Feature Suggestion**
Add mark_price as a price_type to derivatives
https://binance-docs.github.io/apidocs/futures/en/#mark-price

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to correctly market make on contract trading.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakrrt) by [Unito](https://www.unito.io)

**Comment by krisj** [comment]
or, external spot price should be configurable too - currently I believe that is not possible as Hummingbot want a derivative type for external price too, spot doesn't seem to be allowed.

**Comment by TradeClaw** [comment]
> or, external spot price should be configurable too - currently I believe that is not possible as Hummingbot want a derivative type for external price too, spot doesn't seem to be allowed.

Does the external derivatives price even work for you?
The bot did nothing when I set the external price source for the production Binance Futures on a testnet bot.

**Comment by krisj** [comment]
> > or, external spot price should be configurable too - currently I believe that is not possible as Hummingbot want a derivative type for external price too, spot doesn't seem to be allowed.
> 
> Does the external derivatives price even work for you?
> The bot did nothing when I set the external price source for the production Binance Futures on a testnet bot.

When I tested a few development iterations back it did not work no. I vaguely remember that it was placing trades but the spread was off completely so I stopped testing that.
