### ISSUE TITLE
[Feature] Allow hummingbot to place orders on one side

### ISSUE THREAD

**Issue by glenntomas** [hummingbot/hummingbot#2612]
Users have been asking for a feature that can place orders on one side, currently balance limit doesn't do it because when i set balance limit to 0 at first it didn't create orders on the other side of the pair but when the buy order from the other side gets filled the other side starts to create orders because it already acquired balance from the filled order.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakt8d) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
You can effectively do this by specifying an artificially large spread on the opposite side.. ie. if you want to generate viable sell orders only then set the bid spread to 99%

**Comment by TradeClaw** [comment]
> You can effectively do this by specifying an artificially large spread on the opposite side.. ie. if you want to generate viable sell orders only then set the bid spread to 99%

This is also how I do it, I run a buy-bot with a large ask_spread so it just buys up the quote with time
