### ISSUE TITLE
[Feature] Auto stop on market trend

### ISSUE THREAD

**Issue by glenntomas** [hummingbot/hummingbot#2628]
Users are asking if there's a way for the bot to stop automatically if the price starts to trend and start to break out in either direction?

I set my bot that is only useful for a range bound market and I want it to stop if the price starts to trend one way. Currently the kill switch is only tied to profitability of the session.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1raktt0) by [Unito](https://www.unito.io)

**Comment by TradeClaw** [comment]
How do you propose to determine that trend?

**Comment by ChristianFeldmannHamm** [comment]
I think there are different ways to detect a negative trend, a simple one would be to check the fulfilment of the hanging buys. For example, if 2 or 3 hanging buys are fulfilled one after the other without a sell being fulfilled, this could indicate a downtrend and all other hanging buys could be deleted.
