### ISSUE TITLE
Create developer docs for protocol connectors

### ISSUE THREAD

**Issue by mifeng** [hummingbot/hummingbot#2639]
# Why
Adding new protocol connectors is complex because a developer has to update both https://github.com/coinalpha/gateway-api and https://github.com/coinalpha/hummingbot. Both internally and for external developers in the future, a resource that outlines how the two repositories work together and what aspects of the connector should go into each component would be very helpful.

Since we will have Balancer, Uniswap, and Terra when v0.34 is released, we should able to create developer docs based on these 3 initial connectors:

* flowchart of the 2 components, showing what info is passed btw the 2
* step-by-step walkthrough of the "fetch price" flow
* step-by-step walkthrough of the "execute trade" flow
* files to change in both gateway and client

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1raku7w) by [Unito](https://www.unito.io)

**Comment by mifeng** [comment]
https://www.notion.so/hummingbot/Gateway-Reference-WIP-36c54ce6535344dcb5528edcb79bf7e6

**Comment by dennisocana** [comment]
Bumping all stories related to updating the developer documentation.

**Comment by mifeng** [comment]
Gateway documentation from Doon: https://www.notion.so/hummingbot/Gateway-V2-9173d9e102a6436584969dce695f3906
