### ISSUE TITLE
XEMM: Able to set maximum distance from midpoint

### ISSUE THREAD

**Issue by leocape** [hummingbot/hummingbot#2762]
**Feature Suggestion**
Add a parameter in the XEMM config that sets the maximum distance from the midpoint at which to cancel the order.
(This is the 'other end of the stick' of the existing `cancel_order_threshold: 0.5` parameter)

eg. 

cancel-order-threshold-min: 0.2%   # cancels orders when profitability is less than 0.2%
cancel-order-threshold-max: 1%    # cancels orders when profitability is greater than 1%

**Impact**
The benefit of this feature is that when making market on less liquid exchanges, it keeps the bot's orders within a competitive range of the liquid exchange - ie. keeping the price/arb reasonably consistent between the two exchanges. Without this feature, the bot can have orders that are too far from the midpoint, which:

a) becomes unattractive to market takers, and 
b) allows other makers to place orders that are closer to the midpoint, winning the taker orders.

Note: the `adjust_order_enabled` parameter partially solves b) above, but is at the mercy of what the other market maker sets their prices at - often too far / "greedy" from the midpoint, which then makes the market unattractive as a whole.

**Additional context**
It would be nice to have the `min_profitability` also get a counter `max_profitability`, but I find that in most cases I have `active_order_canceling: false` because its best for the bot to set a boundary of the orders to play within eg start at 0.5%, then cancel at 0.2%. So adding in the new feature of cancel at 1% would allow the bot to play in the range of 0.2% to 1%

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakw9p) by [Unito](https://www.unito.io)

**Comment by mhrvth** [comment]
Were you able to verify that a) and b) are actually true?

**Comment by leocape** [comment]
Yes as I work at an exchange :)
