### ISSUE TITLE
Connector with Indodax exchange

### ISSUE THREAD

**Issue by hckhunk** [hummingbot/hummingbot#2767]
## Exchange Details :pencil2:
* **Indodax**:
* **https://indodax.com/en/**:
* **https://indodax.com/trade_api**: 
* **Centralised**: [ ] Centralized [ ] Decentralized
* **No. I trade there actively**: Are you affiliated with the exchange? [ ] yes [ ] no 
  * If yes, what is your role?

## Rationale / impact :pencil2:
Indodax is one of the best fiat currency connected exchange with Indonesian Rupiah. Massive arbitrage opportunity. It has close to 2 Million users from what I last checked.

## Additional information :pencil2:
(Provide any other useful information that may be helpful to know about this exchange)

- - -
:warning: **_Note: do not modify below here_**

## Developer notes
This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
* [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
* [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
1. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  1. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  1. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
1. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  1. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
* Python
* Previous Cython experience is a plus (optional)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakwcu) by [Unito](https://www.unito.io)

**Comment by bonez56** [comment]
I would also find an Indodax connector very useful.
