### ISSUE TITLE
Allow users to execute hedging strategies when using the pmm strategy

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#2798]
**Feature Suggestion**
Delta-hedge is a strategy where the market maker hedge his spot positions by executing an opposing order on a derivative market of the same asset he is market making.

The objective is to reduce the risks. For example, when a buy order is executed on the spot market, the market maker execute a short order on the derivative market. The total profit of both operations should be zero, and the market maker total inventory value wouldn't change over time.

**Impact**
This would add another tool for professional traders and hedge funds on hummingbot.
If possible, we could have a simpler version for non-professional users.

**Additional context**

References:

https://web.ma.utexas.edu/users/mcudina/m339w-slides-market-making-delta-hedging.pdf
https://web.ma.utexas.edu/users/mcudina/m339w-delta-hedging-continued.pdf
https://www.investopedia.com/terms/d/deltahedging.asp

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakwyp) by [Unito](https://www.unito.io)

**Comment by KaneM2** [comment]
I would also be interested in seeing this feature implemented

**Comment by jellebuth** [comment]
Would love to see this strategy. It looks a bit like cross exchange market making to me. What I do personally is doing cross exchange market making op for example Maker market: Binance: LINK/TUSD (less liquid), Taker market: Binance LINK/USDT (more liquid), and hedge my position with the same inventory amount that i have in LINK. Therefore I do not have inventory risk. My inventory will stay the same as it will try to sell LINK with either TUSD or USDT and do the opposite with the other base pair.

Let me know if u need any input, keep up the good work!
