### ISSUE TITLE
Exclude gains from future trades 

### ISSUE THREAD

**Issue by dbrdirect** [hummingbot/hummingbot#2800]
**Feature Suggestion**
Feature: Hold_Gains- Exclude gains from future trades and only trade using original starting balance. ex: If your wallet starts with USD 2000 and a buy/sell takes place that increases your wallet/trading balance to USD 2050, Then the following trade limit remains at USD 2000. The subsequent trades will add up to a max of USD 2000 leaving the gains off-limits for available trading funds.

**Impact**
The desired behavior will allow me to keep gains if the markets drop too quickly. Although the kill switch feature can prevent this from happening, it also closes all positions and halts trading, preventing the ability to continue trading on the way back up.

**Additional context**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakx1e) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
Isn't this already achieved with `balance_limit` ? If not, could you elaborate more on the desired behavior?
