### ISSUE TITLE
Perpetual MM strategy Hedged mode not renewing/replacing orders when one side opens a position

### ISSUE THREAD

**Issue by krisj** [hummingbot/hummingbot#2813]
**Describe the bug**

In Hedged mode, especially when running multiple order levels, HB stops replacing/renewing the orders on the side that takes the 1st profit. It effectively gets stuck on 1 side until both, short and long have closed the positions.

In Hedged modes basic implementation I think both long/short sides should be completely independent of each other.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. create a Perpetual mm strategy on Binance
1. set Hedged mode
1. set multiple order levels (for example 3)
1. set orders levels at 0.5%
1. set profit-taking position management
1. set both long/short profit-taking spread to for example 0.25%
1. observe the side which takes the profit 1st will stop removing/renewing orders until the other side's position takes profit/closes

**Release version**
dev-0.35.0

Optional: your discord username:onoff

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakx7n) by [Unito](https://www.unito.io)

**Comment by vic-en** [comment]
@krisj similar to my response on #2814, position management and the normal order creation/refresh features are not designed to run simultaneously. However, creating an order while a position is active can be possible when script is enabled for the perpetual strategy.

**Comment by krisj** [comment]
> creating an order while a position is active can be possible when script is enabled for the perpetual strategy.

@vic-en can you elaborate? You mean I should be able to use external script like in pure MM strategies to create custom orders? thanks in advance...

**Comment by vic-en** [comment]
Replaced the `bug` label with an `enhancement` label.
Possible enhancement is either to open Perpetual MM to script of create an exception in the usual order refresh cycle in the strategy. Decision on which to go with depends on information gotten from scoping top derivative exchanges, specifically how they handle position/contract modes.
