### ISSUE TITLE
Perp MM - Hedged account mode isolation issue

### ISSUE THREAD

**Issue by krisj** [hummingbot/hummingbot#2814]
**Describe the bug**
I would like to run 2 x HB instances on the same pair on the same account in a Hedged account mode. Manually you can create short/long positions on the exchange without issue. They remain completely separate. Hummingbot has some sort of a conflict and 2 bots cannot seem to coexist on the same pair even in Hedged mode.

This could be connected to [#2813](https://github.com/CoinAlpha/hummingbot/issues/2813) ?

**Release version**
dev-0.35.0

**Optional: your discord username:onoff

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakxa7) by [Unito](https://www.unito.io)

**Comment by vic-en** [comment]
@krisj This isn't a bug. The logic for the perpetual strategy is designed to halt the normal order creation/refresh cycle once an active position is detected on the pair being used. So two bots running on a pair would have issues if one has an open position. Btw, more issues would definitely come up(and need to be handled) if 2 bots are allowed to work simultaneously. It'll be absolutely difficult to manage position that way. A bot can open a position and the other would reduce/close it or one opens and the other increases it.

**Comment by vic-en** [comment]
If you have an objection, kindly give more details and steps to be implemented, considering the existing design of the strategy.
Otherwise, this ticket would have to be closed.

**Comment by krisj** [comment]
> @krisj This isn't a bug. The logic for the perpetual strategy is designed to halt the normal order creation/refresh cycle once an active position is detected on the pair being used. So two bots running on a pair would have issues if one has an open position. Btw, more issues would definitely come up(and need to be handled) if 2 bots are allowed to work simultaneously. It'll be absolutely difficult to manage position that way. A bot can open a position and the other would reduce/close it or one opens and the other increases it.

@vic-en thanks for the response Victor! I understand that this would really be an issue with the One-Way account mode but Hedged account surely treats long/short positions as completely separate at least from the Exchange side. There are 2 separate positions to manage, not single like in "One-Way" account mode. Hence the "Hedged" in the title.

Might try to catch you on Discord... to discuss?

**Comment by dennisocana** [comment]
@krisj we simplified this strategy in the latest release. Are you still experiencing this limitation in the current version 0.46?
