### ISSUE TITLE
Pure Market Making - Backtesting with tick-by-tick history data.

### ISSUE THREAD

**Issue by jonatasfreitasv** [hummingbot/hummingbot#2816]
**Feature Suggestion**
Some way of make backtesting using `pure_market_making` with tick-by-tick historical data.

**Impact**
Have an idea if the parameters are minimally correct to profit.

**Additional context**
I believe it is very complicated to get historical data tick-by-tick, but I wouldn't mind paying for a service like this -> https://tardis.dev.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakxcg) by [Unito](https://www.unito.io)

**Comment by mifeng** [comment]
Here's a relevant comment in an older ticket (https://github.com/CoinAlpha/hummingbot/issues/2446#issuecomment-968181874):

> There are already open source Python-based backtesting engines for stocks like https://www.backtrader.com and https://github.com/quantopian/zipline. However, since those tools are in Python, backtesting is slow. I think it's possible to build an integration between them and Hummingbot if someone from the community is interested in drafting a spec. I would recommend `backtrader` since we have some familiarity with it and can give feedback on it.

While we are launching Hummingbot Pro (our closed source backtesting + data solution aimed at professional and serious individual users)  next year, we also want to support community efforts to build or integrate backtesting into the open source Hummingbot codebase. This is why we recently announced plans to have the Hummingbot Foundation steer how the open source Hummingbot codebase evolves.
