### ISSUE TITLE
Hanging Orders - Not hang buy order

### ISSUE THREAD

**Issue by jonatasfreitasv** [hummingbot/hummingbot#2824]
What is the best way to prevent buy/bid hang orders?

Example:
Tick1
sell = 2$
buy = 1$

buy filled

Tick2
hang sell = 2$
sell = 1.8$
buy = 0.5$

sell filled

Tick3
hang sell = 2$
sell = 1.4$
buy = 0.2$

hang sell filled

Tick4
sell = 2$
buy = 1$

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakxn5) by [Unito](https://www.unito.io)

**Comment by jonatasfreitasv** [comment]
If comment this block? This work? Prevent hang buy orders?

https://github.com/CoinAlpha/hummingbot/blob/069624e41ab1c488f21a5ad1140c2b8c953bfebd/hummingbot/strategy/perpetual_market_making/perpetual_market_making.pyx#L1070-L1072

**Comment by bonez56** [comment]
> 
> 
> If comment this block? This work? Prevent hang buy orders?
> 
> https://github.com/CoinAlpha/hummingbot/blob/069624e41ab1c488f21a5ad1140c2b8c953bfebd/hummingbot/strategy/perpetual_market_making/perpetual_market_making.pyx#L1070-L1072

This doesn't seem to work for me, I edited pure_market_making.pyx and commented out those 3 lines, but still end up with BUY hanging orders.

**Comment by guiguid** [comment]
hi,
this remove hanging buy order creation : 
/hummingbot/strategy)/hanging_orders_tracker.py
`diff ./hummingbot/strategy/hanging_orders_tracker.py ./hummingbot/strategy/hanging_orders_tracker.py.old 
377c377
<                 if unfilled_order in self.strategy.active_orders and not unfilled_order.is_buy:
---
>                 if unfilled_order in self.strategy.active_orders:`
