### ISSUE TITLE
Nonlinear order level calculation feature to introduce geometric order levels

### ISSUE THREAD

**Issue by krisj** [hummingbot/hummingbot#2825]
**Feature Suggestion**

A suggestion to implement non-linear order levels in both Pure and Perpetual market-making strategies.

**Impact**

Currently the order levels are configured as a linear scale and the only way to override that is via scripts. I wonder if it would make sense to implement this feature in the strategies instead of external scripts for convenience as well as a possibility to change that on the fly/live.

Proposition would be to allow user to configure something like order_level_type : [linear,geometric,exponential,log,power]
Then order_level_amount would be either arithmetic value as it is now (also default?), or geometric parameter based on which function drives it. I believe this would be very useful for everyone.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakxpn) by [Unito](https://www.unito.io)

**Comment by keithbaum** [comment]
Hi @krisj,
We are introducing log spaced order levels in avellaneda strategy
