### ISSUE TITLE
Does not validate ethereum_token_list_url

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#2835]
**Describe the bug**

* Does not validate or check the provided url token list

**Steps To Reproduce**

* by default the value of `ethereum_token_list_url` is `https://wispy-bird-88a7.uniswap.workers.dev/?url=http://tokens.1inch.eth.link` to edit `ethereum_token_list_url` on hummingbot do 
`config ethereum_token_list_url`

![image](https://user-images.githubusercontent.com/54516858/104411050-a7043380-55a4-11eb-9f92-3d4c723dedc7.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/104412497-5b06be00-55a7-11eb-8d46-cfd44e7c74c5.png)

**Release version**
0.34.0 / 0.35.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakxwa) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Closing ticket, Client now support gateway-v2
