### ISSUE TITLE
Unable to override order prices via scripts

### ISSUE THREAD

**Issue by bitphage** [hummingbot/hummingbot#2873]
`order_override` PMM param is allowed to be changed in via scripts, but it's not provides the ability to override order prices, only amounts. This possibility would be beneficial.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1raky8m) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
You can set the spread and order amount via order override?

Unless you mean the ability to set an absolute price, which is something I've added in my own repo, quite useful

**Comment by bitphage** [comment]
Yes, I've meant setting price explicitly.
