### ISSUE TITLE
Supply PMM params to the `ScriptBase.__init__`

### ISSUE THREAD

**Issue by bitphage** [hummingbot/hummingbot#2874]
Currently `__init__` does not accepts current PMM params, so you have to construct hacks in script's `on_tick` to set initial attributes, example:

```python
    def on_tick(self):

        # Separate and store the assets of the market the bot is working on
        if self.base_asset is None or self.quote_asset is None:
            self.base_asset, self.quote_asset = self.pmm_market_info.trading_pair.split("-")
```

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakyaj) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
Another minor annoyance is that core Hummingbot will have initialised itself before the script has finished initialising, potentially placing an initial set of orders using wrong parameters. I added a 10 second delay in my repo to work around this and allow the script to push initial parameters

I use the same approach as above in my scripts, ie. the first tick is used to set everything up. I'm pretty sure the inter process queues haven't been fully setup during __init__ either, so you can't call eg. self.notify
