### ISSUE TITLE
Spreads defined on orders with level > 1 in order_override are not applied to orders placed when order_optimize is active

### ISSUE THREAD

**Issue by RobinR1** [hummingbot/hummingbot#2879]
[conf_pure_mm_1.yml.gz](https://github.com/CoinAlpha/hummingbot/files/5880729/conf_pure_mm_1.yml.gz)

**Describe the bug**
When `order_optimization_enabled` is set to `true` and `order_override` is set in a script or config with more than one level of orders, the custom spread defined on the order levels > 1 is discarded and/or recalculated to something around 0.0009% more than the order of level 1 instead of the custom entered spread for that order.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Create a script where `order_override` is set with a dict containing orders of multiple levels and different spreads. For example:

```
self.pmm_parameters.order_override = {"order_1": ["buy", "5", self.pmm_parameters.order_amount],                     
                                      "order_2": ["buy", "10", self.pmm_parameters.order_amount], }
```

or use attached pure_mm config

1. Set up your configuration file with these parameters: 
  * Script enabled: yes (not required with attached config)
  * Script file: your script  (not required with attached config)
  * order_optimization_enabled: true
1. Start the bot in pure market making strategy
1. Wait for orders to be refreshed and your `order_override` to kick in
1. Check spread of placed orders with `status` -> sell order level 1 will have spread of 5%, sell order level 2 will also have spread 5% but price will be about 0.0009% higher

The same happens if you add 2 buy orders with different spread to the above `order_override` dict: level 1 buy will get correct spread, level 2 buy will be slightly lower, but not the spread as defined in `order_override`.

**Screenshots**
not required

**Release version**
0.35.0 and dev-0.36.0

**Attachments**

* conf_pure_mm_1.conf

**Optional: your discord username: Ro.r**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakyeq) by [Unito](https://www.unito.io)

**Comment by RobinR1** [comment]
Checked if behaviour is the same when applying order_override using config instead of script:
conf_global:
```
script_enabled: false
```
conf_pure_mm_1:
```
order_override:
  order_1: [buy, 5, 10]
  order_2: [buy, 10, 10]
  order_3: [sell, 3, 10]
  order_4: [sell, 6, 10
```

Result: 
```
 Orders:
     Level  Type        Price Spread Amount (Orig)  Amount (Adj) Age
         2  sell 0.0003776121  2.99%          10.0            10  n/a
         1  sell 0.0003776083  2.99%          10.0            10  n/a
         1   buy 0.0003482795  5.01%          10.0            10  n/a
         2   buy  0.000348276  5.01%          10.0            10  n/a
```

**Comment by krisj** [comment]
is issue [#1962 ](https://github.com/CoinAlpha/hummingbot/issues/1962) possibly a duplicate?

**Comment by zappra** [comment]
Interesting, from #1962:

"Afterwards, 2nd order level should be wider than the adjusted order by order_level_spread"

Now I note from the attached .conf file that order_level_spread is 0.001, which makes sense of the results, although probably not the desired result if you're setting order levels explictly using order override?

**Comment by RC-13** [comment]
@RobinR1 Are you still experiencing this behavior without the script? Seems to work fine on my side:
![image](https://user-images.githubusercontent.com/57189990/107493065-26971980-6bc8-11eb-9fb6-fd5d301d49bd.png)
```
order_override:
   order_1: [sell, 1.2, 2]
   order_2: [sell, 1.5, 3]
   order_3: [sell, 1.8, 3]
```
Also, I believe that order_override is currently not yet open for script: https://github.com/CoinAlpha/hummingbot/blob/d18887c4210d53cbd643c333e9777a2a61b83d5c/hummingbot/script/script_interface.py#L90
