### ISSUE TITLE
Inconsistent order creation on Bitfinex caused by delay on balance update

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#2883]
**Describe the bug**
Some orders are not created during certain cycles on Bitfinex because it thinks balance is not enough to create a new set of orders.

-In the logs it shows in timestamp `2021-01-28 06:37:10,001` orders on both sides were created.
-Then in the next cycle at `2021-01-28 06:37:43,045` it only created a sell order.
-Afterwards it returned to creating a buy and a sell order at `2021-01-28 06:38:15,001`.

![](https://user-images.githubusercontent.com/64377055/106104573-94315780-617d-11eb-9c5a-719dd4964288.png)

**Steps To Reproduce**

1. Run a pure market making bot on Bitfinex
1. Set the order amount to just 60% or above of your total balance on each side.
1. Wait for orders to refresh.

**Screenshots**
![](https://user-images.githubusercontent.com/64377055/106103341-c2159c80-617b-11eb-8221-0afb56816b67.png)

**Release version**
development-0.36.0

**Attachments**
Logs: [bitfinex.log](https://github.com/CoinAlpha/hummingbot/files/5885515/bitfinex.log)
Config: [bitfinex.txt](https://github.com/CoinAlpha/hummingbot/files/5885518/bitfinex.txt)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakym3) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
I've notice this as well on the bitfinex test bot, there was a delay when the cpu usage suddenly spike.
Sample screenshot when CPU usage spike:
![Bitfinex1](https://user-images.githubusercontent.com/57189990/106269965-37f73200-6268-11eb-9208-94ad8c973cbb.png)

after the spike, 
![Bitfinex](https://user-images.githubusercontent.com/57189990/106269984-404f6d00-6268-11eb-9a6d-973c07499d8c.png)
