### ISSUE TITLE
Add liquidity rewards under history command

### ISSUE THREAD

**Issue by pierostz** [hummingbot/hummingbot#2909]
When you run the history and history --verbose command in the miner terminal you get the Profit & Loss based on the trades and fees. This does not give a clear image of ones Profit or Loss if the pair traded supported for liquidity mining.

My suggestion is under history command, add to the equation the liquidity rewards for a clearer P&L picture.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakyxg) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
@Nullably could you check if this would be possible with the liquidity mining strategy?

**Comment by zappra** [comment]
@phbrgnomo @Nullably was there any progress on this? Is it anywhere in the roadmap?

**Comment by Nullably** [comment]
Yes, this is possible on any strategy. 
So far we have been using only public APIs of the Hummingbot Miner. For private APIs, e.g. getting miner's rewards, we'll need to design the whole integration on how we connect and keep the API key and secret, where and what information should we display, etc..

**Comment by zappra** [comment]
Ah right the public info would be market volume, yield etc, used for fund allocation? I'm interested in scraping miner reward info for PnL calculation
