### ISSUE TITLE
Perpetual MM insufficient balance error when running at high frequency

### ISSUE THREAD

**Issue by krisj** [hummingbot/hummingbot#2920]
**Describe the bug**

When running with a low filled_order_delay (7 in this case) on Binance Futures - HB doesn't get the right account balance, resulting in "insufficient balance" error and only part of all level trades are placed. The negative number looks particularly suspicious.

![image](https://user-images.githubusercontent.com/590660/106936232-3cae6100-6714-11eb-8384-67aa1c613921.png)

**Steps To Reproduce**
perpetual MM strategy on Binance Futurues as per screenshot. Running on a low latency to Binance 3.7 GHz VPS.

**Screenshots**
![](https://user-images.githubusercontent.com/590660/106936614-b6464f00-6714-11eb-88fa-5d92793f9f13.png)

**Release version**
dev-0.36.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakz7m) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Hi krisj, I believe this is expected behavior when you're running multiple levels. It occurs when the bot detected that the current quote balance is less than the total of all orders when created so it omits the opposite position, by the way, this happens even if using the default value of `order_filled_delay`. For the negative value displayed on the logs, I believe this would be your balance if there is an open loss or once you get liquidated.

**Comment by krisj** [comment]
> Hi krisj, I believe this is expected behavior when you're running multiple levels. It occurs when the bot detected that the current quote balance is less than the total of all orders when created so it omits the opposite position

Hmm, well, I a was not expecting this although I understand that it is due to some internal timings where Hummingbot seems to read the available margin nearly before the last order level is cancelled from the previous cycle. Is it due to async and not waiting enough perhaps? 

>, by the way, this happens even if using the default value of `order_filled_delay`.

you are correct, I initially thought it was due to low `order_filled_delay`. But the issue occurs at the moment straight after `order_filled_delay` has been waited out. So, when HB is cancelling the order levels (both sides) and places the new orders, it seems to randomly run into the "insufficient balance" error. As if it read the available balance before all previous orders were confirmed as cancelled. Could it be that it is because binance does not release the balance back to it's own API during order cancellation?

>For the negative value displayed on the logs, I believe this would be your balance if there is an open loss or once you get liquidated.

I don't know where is it getting the negative number from - I have plenty of margin and no open loss on the account when this happens. If I manually stop/start the bot it is able to perfectly place all order levels. In fact it runs perfectly fine until it randomly runs into this... It doesn't happen if I leave margin that is at least 2 x the entire initial margin requirement.

I will try to add some more context/info if I can later today/tomorrow.
