### ISSUE TITLE
3 bugs with arbitrage strategy in real mode

### ISSUE THREAD

**Issue by totva** [hummingbot/hummingbot#2929]
**Describe the bug**
I am trying arbitrage strategy in real mode and I attach screenshot and log with 3 issues/bugs:

1. I guess the order size was not calculated right because Binance error "account has insufficient balance for requested action"
1. The bot sold all my XRP in Binance and did nothing on Bitfinex, several times.
1. Unable to send any order to Bitfinex (I tried with 2 different API pairs, it connects, it checks prices and balances and it detects arbitrage oportunities but it does not submit any order susscessfully, see screenshot and log)

**Screenshots**
Added

**Release version**
0.35.0

**Attachments**

* arbitrage strategy config file
[conf_arb_real1.yml.txt](https://github.com/CoinAlpha/hummingbot/files/5940552/conf_arb_real1.yml.txt)
* arbitrage strategy log file
[logs_conf_arb_real1.log](https://github.com/CoinAlpha/hummingbot/files/5940557/logs_conf_arb_real1.log)
It's long (was running for hours...), I suggest going straight to the end
* screenshot
![Screenshot from 2021-02-08 00-51-27](https://user-images.githubusercontent.com/16940095/107164154-fecc6980-69ad-11eb-9207-03fc2bdde779.png)

**Optional: your discord username:**
pebblewheels

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakzjc) by [Unito](https://www.unito.io)

**Comment by PtrckM** [comment]
- for question 3, there is a known issue on bitfinex https://github.com/CoinAlpha/hummingbot/issues/2856 where bot unable to create/submit orders.
