### ISSUE TITLE
/bin/ stands for binary and you have python files in it?

### ISSUE THREAD

**Issue by bigbizze** [hummingbot/hummingbot#2958]
Just figured you'd probably want to rename this folder /src/ or something, as convention (and English) generally has the /bin/ folder containing compiled binary files... not python files lol

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram09j) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Closing ticket since Binary has been removed on Hummingbot version 1.0.0
