### ISSUE TITLE
LM strategy - incorrect order age and fails to cancel with low refresh time

### ISSUE THREAD

**Issue by JeremyKono** [hummingbot/hummingbot#2960]
Steps to reproduce the issue:

Create a
liquidity_mining
strategy
Put in multiple pairs.
Set
order_refresh_time
to 1s
Set
order_refresh_tolerance_pct
to -1
Run
status --live
observe the age of the order (optional)
Then use
stop
after a few minutes.

As you can see in the screenshot, the order's age is not showing up properly. it should be 23:59:00 or 00:00:00
In the 3rd screenshot the orders are getting stuck in the bot but not in the exchange. Attached are the 2 log files to check.

2021-02-17 14:24:02,588 - 1399 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
File "/Users/jeremykono/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
return await c
File "/Users/jeremykono/hummingbot/hummingbot/client/command/stop_command.py", line 37, in stop_loop
self.clock.remove_iterator(self.strategy)
File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list

no orders are stuck in the exchange.

Upon restarting the bot, the bot won't start at all.

Version: 0.36.0Installation type: Source and docker build

firo-docs.txt

logs_firo-docs.log.2021-02-16.txt

logs_firo-docs.log

WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!

Optional: your discord username:

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram0ba) by [Unito](https://www.unito.io)

**Comment by Nullably** [comment]
Generally the strategy (or any strategy actually) should be used this way where many orders are issued and canceled every second (order_refresh_time = 1 and order_refresh_tolerance = -1).
I think what happened is the Binance connector tries to throttle out going requests (to keep it within API request limit) but couldn't keep up, so there are many outstanding inflight orders to create and to cancel. I can dig deeper into this but I think this is not a priority.

**Comment by dennisocana** [comment]
@Nullably do you think it would be a good idea to set a minimum value for the `order_refresh_time` parameter for these similar cases?

**Comment by Nullably** [comment]
@dennisocana 
The `order_refresh_time` works with `order_refresh_tolerance`, you can set the refresh time to be very low, e.g. 1 second, as long as you set the refresh tolerance to somewhat high, e.g. 0.2% or above. This also depends on the number of markets as well, e.g. refresh_time of 2 s and tolerance of 0% should work fine for 1 market but not 10. 
The goal is to not refresh orders too often. But we don't know what the optimal or minimum is, so I don't think we should put in the restriction here.
