### ISSUE TITLE
New command/communication channel for docker instances

### ISSUE THREAD

**Issue by zappra** [hummingbot/hummingbot#2965]
From this question on Discord:

https://discord.com/channels/530578568154054663/530578568154054665/811814840624218122

It would be really useful to have something similar to the Telegram integration that allows sending/receiving, but that is more amenable to automation via eg.  bash scripting or other non-Hummingbot process

Example stories

I want to be able to send a stop command to a running docker instance so I can execute a graceful shutdown/restart via a bash script

I want to scrape PnL info from a running instance so I can create a custom management UI

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram0ca) by [Unito](https://www.unito.io)

**Comment by krisj** [comment]
I have a feeling that the #2405 when implemented would solve this and many other needs. Sending commands to a docker instance from the host machine there would be a few ways to achieve it but the best practice would be a microservice style ASGI API exposed on a particular port I think. It would be very universal too. It would be up to the users to either keep it local or open to WAN via proxy or port mapping or whatever is the most secure proper way. Let's keep pushing it forward!
