### ISSUE TITLE
Bittrex - Fails to recognize the minimum order amount 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#2988]
**Describe the bug**
ADA-USD on Bittrex fails to recognize the minimum order amount which results in not placing orders, stuck on log :

```
2021-02-25 00:05:34,753 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Saved ADA-USD snapshots.
```

**Steps To Reproduce**

* Create a Pure Market-Making strategy on Bittrex and use default config
* Market ADA-USD, set order_amount to Bittrex minimum trade-size of `21`
* Notice Hummingbot will not place orders. If you increase the order amount more than `24` it will work

You can find the Bittrex ADA `MinTradeSize` here: https://bittrex.com/api/v1.1/public/getmarkets

Order amount at 21
![image](https://user-images.githubusercontent.com/73840223/109090659-442ebc00-774e-11eb-9395-5610812fc1f2.png)

Order amount at 30 and it placed an order
![image](https://user-images.githubusercontent.com/73840223/109090841-a7205300-774e-11eb-8cac-95499129e4a9.png)

Order amount at 24 on dev-0.37.0 and it placed an order
![image](https://user-images.githubusercontent.com/73840223/109089622-8525d100-774c-11eb-88f8-45e763e34eaa.png)

When we created manual order to check, it requires a quantity of 21 or greater
![image](https://user-images.githubusercontent.com/73840223/109091482-d6838f80-774f-11eb-92b1-e2b72fa83a7e.png)

**Release version**
0.36.0 / dev-0.37.0

**Attachments**
[logs_pmm-dvdaz.log](https://github.com/CoinAlpha/hummingbot/files/6040014/logs_pmm-dvdaz.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram0wx) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
While testing Bittrex, I've also noticed that the minimum order amount for the other pairs is not recognized as well. For example for `ETH-USDT`, the order amount is set to `0.003` but the bot will only create orders at `0.007` 

Order amount : 0.003
![image](https://user-images.githubusercontent.com/73840223/132121639-d35dd0a8-38ec-4127-b7d1-6a7a57cfdd77.png)

Order amount: 0.007
![image](https://user-images.githubusercontent.com/73840223/132121699-3e9fb509-08ed-4ef5-800e-b0bb72f6a5dc.png)

However, it's letting me create limit orders on the Bittrex portal using `0.003`. I also tested other pairs `ETH-BTC` and `BTC-USDT` and getting the same issue.

![image](https://user-images.githubusercontent.com/73840223/132121972-8b74f0dd-6057-4df5-a86d-48e4a327d229.png)

Attached:
[pmm-test.zip](https://github.com/CoinAlpha/hummingbot/files/7111332/pmm-test.zip)

**Comment by nikspz** [comment]
Upon checking, the issue still showing in 0.45.0, For ETH-USDT, the order amount is set to 0.003 but the bot will only create orders at 0.007
![image](https://user-images.githubusercontent.com/83953535/140003981-403c0a53-e146-43a6-b21f-9953c62aeb7d.png)

![image](https://user-images.githubusercontent.com/83953535/140004073-ce4d4e69-e463-4f93-bcc0-8a342db2f4b5.png)

**Comment by cardosofede** [comment]
@rapcmia @nikspz is this issue solved?

**Comment by nikspz** [comment]
@cardosofede No, the issue still showing using Bittrex

**Comment by nikspz** [comment]
Issue not showing now for ETH-USD Pair. Bot placing orders with 0.001 order amount 
![image](https://user-images.githubusercontent.com/83953535/178329072-b3c6be65-577b-4900-8d7b-706e1443e24e.png)
