### ISSUE TITLE
Probit - inconsistent order creation due to balance latency

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#2993]
**Describe the bug**
Order levels are not getting created correctly due to latency with balance update. There are times that this happens as well even when just using a single level. It happens both on Probit Global and Probit Korea

**Steps To Reproduce**

1. Create a pure market making strategy and use Probit as the exchange
1.  Set multiple levels to easily replicate the issue
1.  Start bot and run `status --live`

**Screenshots**
Image from older commit:
![probit](https://user-images.githubusercontent.com/57189990/109297985-daa5cf00-786d-11eb-903b-6e96cd646430.gif)

Image after commit: 94ebf5186397bbf318eaccd6f80ba5b20ff569fe
![Probit inconsistent order creation](https://user-images.githubusercontent.com/57189990/109297456-fa88c300-786c-11eb-9722-786303a38d7e.gif)

**Release version**
dev 0.37.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram10j) by [Unito](https://www.unito.io)

**Comment by ChynamaE** [comment]
https://www.probit.com/r/90490277

**Comment by nikspz** [comment]
@MementoRC This issue could be tested/fixed by community
Since probit currently is Bronze connector it is not maintained by Hummingbot Foundation but may be maintained by a community member/members

**Comment by ChynamaE** [comment]
Would be nice if this stuff just magically did itself!

**Comment by rapcmia** [comment]
Connector has been removed
