### ISSUE TITLE
Skip Order Refresh When Current Price Is Within Range Of Buy/Sell Limit Order Price

### ISSUE THREAD

**Issue by glenndilen** [hummingbot/hummingbot#2994]
**Feature Suggestion**
To add a config option that allows the order refresh to be skipped for a cycle, if the current price is within a % range of the Buy/Sell order price.

**Impact**
I have noticed many times, that the bot will get so close to closing an order with profit, but the orders will refresh before the bot has a chance to reach the order price.

By skipping the order refresh cycle when the current price is within a % range of the target buy/sell price - the bot will have a much better chance of hitting the original order price before refreshing.

If the price is not within this range, the order refresh cycle will continue as normal.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram122) by [Unito](https://www.unito.io)

**Comment by krisj** [comment]
is `order_refresh_tolerance_pct` unable to achieve this for you?

**Comment by glenndilen** [comment]
@krisj I have tried to achieve with the `order_refresh_tolerance_pct` but this value only works with market change.

What I need is a value which says - if the current price is within X % of the sell/nuy point price - don't do the order refresh.

**Comment by krisj** [comment]
@glenndilen have you tried different `price_type`? like `last_own_trade` for example? Is that close to what you are after but not really?

**Comment by glenndilen** [comment]
@krisj no that doesn't really help.

I just want to stop order refreshing if current price is near to limit order point - so the not actually closes the order instead of refreshing and putting the limit even higher or lower.
