### ISSUE TITLE
Pure MM - Ghost orders after orders are partially filled

### ISSUE THREAD

**Issue by Aliori1** [hummingbot/hummingbot#3001]
**Describe the bug**
// A clear and concise description of what the bug is.
i dont see a sell order on binance but when i do status on humming bot it show a sell order. it been happening for the past couple of days dont know why but on the other bot im running on the same pair but on version 0.35.0 its perfectly fine 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up your configuration file with these parameters: ...
1. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![Screenshot (189)](https://user-images.githubusercontent.com/35888324/109396346-1c07ae80-7942-11eb-9b2e-50209f9206c5.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.36.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_real2334.log](https://github.com/CoinAlpha/hummingbot/files/6055083/logs_real2334.log)
i cant put my config file here because it says file type not support so im going to to take a screenshot 
![Screenshot (190)](https://user-images.githubusercontent.com/35888324/109396419-7d2f8200-7942-11eb-8fe2-d553301f5a2d.png)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**
omar142#7643

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram7zp) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Hi @Aliori1 

I tried to use the same config but with different order amount and the bot has been running more than 10mins now. I will have to monitor for few more days and will get back to you for the results. Currently the orders are still available on both Hummingbot and Binance 
![image](https://user-images.githubusercontent.com/73840223/109405921-e4375000-79af-11eb-963d-14b065ddd74d.png)

**Comment by rapcmia** [comment]
Tried to replicate the issue and got the same behavior. 

Steps To Reproduce:
- Create Pure Market Making 
- Same configuration with the user but with FIRO/BTC pair
- Create the best bid or ask for orders (any side will do)
- Orders created must be partially filled, then stop the bot
- Start the bot again, will get the logs `recreating missing trade-in TrafeFill`
- Status shows that orders are created on bot but not on exchange

Run status on Hummingbot
![image](https://user-images.githubusercontent.com/73840223/109598762-eab2fc80-7b54-11eb-8d54-61a6c44e7a0c.png)

Exchange open orders
![image](https://user-images.githubusercontent.com/73840223/109598458-4af56e80-7b54-11eb-8223-06ca243f7880.png)

Release version
v0.36.0

Logs:
[logs_issue-3001.log](https://github.com/CoinAlpha/hummingbot/files/6066195/logs_issue-3001.log)
