### ISSUE TITLE
Loopring - Incorrect bid spread calculation

### ISSUE THREAD

**Issue by dietzam** [hummingbot/hummingbot#3016]
**Describe the bug**

This issue happens when there is an extremely small spread between buy and sell, as it happens often for stable coins. In this case it is between DAI and USDT. The buying is 1.0000 and the selling at 1.0001. See below attachment of the Loopring Orderbook. 

The issue is the buying order calculation never gets to equal the top buying price of 1.0000.  The bot calculates as bid 0.9999 even with a buying spread set to 0.001. (Setting the bid spread even lower does not make any difference).

The calculation of the sell order price is correct.

**Steps To Reproduce**
Run the bot with using the Loopring API using the attached config.

**Screenshots**
1 Loopring Orderbook at time of issue occuring.
2 Status of bot showing the order bid calculation.
3 Config used
![Screenshot 2021-03-04 151448](https://user-images.githubusercontent.com/8992858/109912980-3e624900-7d01-11eb-85c4-3ae855f717a6.png)
![Screenshot 2021-03-04 151307](https://user-images.githubusercontent.com/8992858/109912996-46ba8400-7d01-11eb-8150-ffb9cbaaa61e.png)
![Screenshot 2021-03-04 154910](https://user-images.githubusercontent.com/8992858/109913023-50dc8280-7d01-11eb-8233-f25db3b97255.png)

**Release version**
// 0.36.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram8ef) by [Unito](https://www.unito.io)

**Comment by krisj** [comment]
@dietzam don't forget the bid-ask spreads are set as percentages. Your midprice in this example is 1.00005, so a bid spread of 0.001 will land it at 0.99904995. Try a bid_spread of 0.00005
I am also not seeing how the ask spread is working correctly in your example. It says you don't have a DAI balance and the is only a buy order on the book in the HB screenshot.

**Comment by dietzam** [comment]
> @dietzam interesting... perhaps it's flooring instead of rouning during quantization.
> 
> I am also not seeing how the ask spread is working correctly in your example. It says you don't have a DAI balance and the is only a buy order on the book in the HB screenshot.

the issue (of incorrect buy order amount) remains even if there is a DAI balance that allows for creating a sell.

**Comment by beeste117** [comment]
I have seen the exact same issue. One comment I'll make is that it seems to correctly assign the bid price and spread when using Paper Trade, but not when using live market making
![image](https://user-images.githubusercontent.com/79761526/110838515-8be63500-8270-11eb-86d1-c8b443f29ae4.png)


![image](https://user-images.githubusercontent.com/79761526/110838566-9dc7d800-8270-11eb-86df-80bc801c1047.png)
![image](https://user-images.githubusercontent.com/79761526/110838567-9dc7d800-8270-11eb-89b6-e6259e613287.png)

**Comment by Perream2** [comment]
Thanks, 

I see that this was flagged a while ago, still facing this issue on USDC/USDT trading pair

**Comment by Perream2** [comment]
@RC-13 I see you mention in #3068 that you weren't able to reproduce this issue. It seems to be persisting. see #4934

**Comment by rapcmia** [comment]
Loopring has been removed from connector list
