### ISSUE TITLE
Feature request - individual order_amount bid/ask

### ISSUE THREAD

**Issue by tronder88** [hummingbot/hummingbot#3023]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.

Implement bid_order_amount and ask_order_amount so that order_amount can be individually controlled.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to control the inventory better than current inventory skew does. as this feature will enable control over order_amount on each side through skripts.

**Additional context**
Sometime one does not want to sell 100% of what was bought as to build inventory on both sides when market making.
This feature will enable more control over bid/ask, and also allow different types of market making strategies, which will further strengthen Hummingbot as a featured software

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram8jh) by [Unito](https://www.unito.io)

**Comment by krisj** [comment]
just wanted to point out that this is already possible with order_override

**Comment by tronder88** [comment]
> just wanted to point out that this is already possible with order_override

Thank you, with variable or set number? i.e. possible to set order amount as a function and not 0.5 ETH fixed for each buy/sell order.... Script documents are a bit, lacking in terms of descriptions of what is possible

**Comment by krisj** [comment]
> > just wanted to point out that this is already possible with order_override
> 
> Thank you, with variable or set number? i.e. possible to set order amount as a function and not 0.5 ETH fixed for each buy/sell order.... Script documents are a bit, lacking in terms of descriptions of what is possible

https://docs.hummingbot.io/strategies/order-override/#gatsby-focus-wrapper

**Comment by tronder88** [comment]
> > > just wanted to point out that this is already possible with order_override
> > 
> > 
> > Thank you, with variable or set number? i.e. possible to set order amount as a function and not 0.5 ETH fixed for each buy/sell order.... Script documents are a bit, lacking in terms of descriptions of what is possible
> 
> https://docs.hummingbot.io/strategies/order-override/

This one does not explain anything else than fixed inputs... not variable which I need.

Thanks for the link, but I am no closer to a solution for my issue
