### ISSUE TITLE
[feat] Allow spot-perpetual strategy to scan more than one asset for opportunities

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3049]
**Feature Suggestion**
Allow more than 1 asset to be scanned for opportunities on the new `spot_perpetual` arbitrage strategy.

The user would input what base assets he wants the bot to scan for opportunities. For example, inputing ETH, BTC and YFI, the bot would check for price divergences on all three assets.

One point of decision is what should be done with the quote asset on the spot side. (on the derivative, is expected that the pairs will all be quoted on the same asset)

User could be limited to only one quote asset (USDT, USD, BUSD, USDC, etc), or be allowed to add more than one quote asset.

More than one asset could be more complicated, due to how the bot would handle the trades.

**Impact**
This would reduce the number of bot instances the user would have to run to take advantage of a wider range of assets.

**Additional context**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram8y8) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Status?
