### ISSUE TITLE
Create new liquidity mining quickstart guide

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#3072]
# Why
We want new users to have a good experience running Hummingbot and earning rewards with liquidity mining. Currently there's a regular [quickstart guide](https://hummingbot.io/academy/quickstart/) along with a [liquidty mining guide](https://hummingbot.io/academy/liquidity-mining/). These are redundant and can be replaced with an updated, simpler guide.

# What
Following the script of [this video](https://youtu.be/ME5osB8sX_s), create a new version of liquidity mining quickstart guide with the following general steps:

1. Create API keys
1. Add read-only API key to Miner
1. Install Hummingbot (macOS or Windows installer)
1. Add trade API key to Hummingbot
1. Run bot and see rewards on Miner

I suggest making this a single, lengthy guide for now. Afterwards, we can decide whether to break it up or not.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram947) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@fengtality The first two link in the issues no longer exists and there are plenty of videos about LM on the site, do we still need this?
