### ISSUE TITLE
Expose live UI update feature to scripts

### ISSUE THREAD

**Issue by zappra** [hummingbot/hummingbot#3075]
**Feature Suggestion**
Some existing commands offer a  --live option that takes over the UI to display live data. For example status and order_book.

Scripts can already communicate with the UI via ScriptBase.notify. Scripts could be given a command or other hint to begin/end formatting for live output.

**Impact**
This would be a nice way of debugging/visualising script code that performs per-tick processing

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram98p) by [Unito](https://www.unito.io)

**Comment by krisj** [comment]
+1

**Comment by MementoRC** [comment]
@cardosofede Is this not already implemented with the format_status()?

**Comment by cardosofede** [comment]
@krisj @zappra this is implemented, if you want, run the script example called format_status.py. It shows in real time the volume of the order book +1% and -1% from the mid price
