### ISSUE TITLE
Simplify arbitrage strategies, by combining the `arbitrage.yml` and `amm_arb` on one single file.

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3082]
Evaluate the possibility of turning both arbitrage strategies into a single file to simplify the client interface.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram9bf) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Is this still relevant?
