### ISSUE TITLE
bot did not insert further short orders and did not update the prices of the long orders 

### ISSUE THREAD

**Issue by foxxcrypto** [hummingbot/hummingbot#3088]
After five short trades were open, no more were entered on the short side and five long orders remained active on the long side but were no longer updated with the correct spread.

thanks. bye.
[logs_conf_perpetual_market_making_1.zip](https://github.com/CoinAlpha/hummingbot/files/6155881/logs_conf_perpetual_market_making_1.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram9et) by [Unito](https://www.unito.io)

**Comment by john-hummingbot-support** [comment]
Hi @foxxcrypto, can i get your config for this?

**Comment by foxxcrypto** [comment]
here my config
![hummingbot_config](https://user-images.githubusercontent.com/48240112/112714841-ba087d80-8edc-11eb-9c7f-23f71f13d433.PNG)

**Comment by rapcmia** [comment]
Hi @foxxcrypto thanks for the update, please lend us some time to check this config again. Thank you

**Comment by rapcmia** [comment]
Upon checking this again, the logs indicated that most of your short orders are filled and might be inline with the market's downtrend. I suggest to test and set the `stop_lost_spread` and see how this helps your bot.

**Comment by rapcmia** [comment]
Hi, @foxxcrypto our team added improvements and changes on Perpetual market-making on the current version 0.46.0 that can help resolve this issue. We suggest trying to look into it again and open a new Github ticket in case there are issues. Tagging this ticket as closed now.
