### ISSUE TITLE
On `perpetual_market_making` add the option to close the trade if the price reach the mid point between open orders

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3089]
**Feature Suggestion**
On `perpetual_market_making`, when both starting short and long orders are executed (open), there is a profitable opportunity if the price reaches the middle point between both orders.

We should add an option to the strategy named `close_positions_on_the_middle`.

If set to true:

When BOTH starting positions (short and long) are filled/executed, the bot will monitor if the price reaches the mid point between both positions.

If the midpoint is reached, the bot will create limit orders (or Taker, if `close_position_order_type` is set to True) on the mid price.

The expected profit will be equal to half the total spread.

If `order_levels` is > 1, all the levels must be filled for this exit to be available.

**Impact**
Adds a bit less risky exit for the strategy.

**Additional context**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram9fn) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Is this still relevant?
