### ISSUE TITLE
Improve Liquidity Mining strategy

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3092]
Research and create requirements of what can be improved on the liquidity mining strategy

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram9j5) by [Unito](https://www.unito.io)

**Comment by drumer979** [comment]
Hello. I created ticket #3078 where i put some sugestions.

**Comment by MementoRC** [comment]
@cardosofede Status?
