### ISSUE TITLE
Price type: "inventory cost" is flawed and inventoryCost seems to be calculated incorrectly

### ISSUE THREAD

**Issue by florinteodorescu** [hummingbot/hummingbot#3196]
**Describe the bug**
// A clear and concise description of what the bug is.
My expectation when using price type:inventoryCost is to always SELL with a profit, but that doesn't seem to happen. I've noticed this for some time now since I was leaving bots to run for a couple of days and even in markets with a price that was constantly increasing the bot would sometimes end up with a loss. I couldn't wrap my head around what was happening. One thing was clear, I was seeing the bot buy at price X and then sell at X-y (so, with a loss).

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

It finally became clearer what was happening when I ran with the following settings:

pure_market_making strategy
bid/ask spread: 0.3
amount: 1000000 (this is just a very big amount to compound the profits with each trade and constantly increase the trade amount)
ping_pong_enabled True
add_transaction_costs True

What made it clear for me was the trade below:

* please notice that InventoryCost was 0.2031053 and the bot was trying to buy in again at 0.20438
* after the trade, the InventoryCost was 0.2032046. This is slightly below the 0.20438 price at which the entry was made.
* given that I'm trading with my entire inventory at once, I'm expecting that the inventory cost will always be the last BUY-in price
* given the above, inventoryPrice seems to be calculated incorrectly

**BEFORE TRADE:**
  Markets:

```
   Exchange    Market  Best Bid  Best Ask  Ref Price (InventoryCost)
```

```
 crypto_com  CRO-USDC   0.20438    0.2047                  **0.2031053**
```

  Assets:

```
                          CRO     USDC
```

```
 Total Balance        13916.4 205.0298
```

```
 Available Balance          0   0.2054
```

```
 Current Value (USDC) 2846.46 205.0298
```

```
 Current %              93.3%     6.7%
```

  Orders:

```
 Level Type   Price Spread Amount (Orig)  Amount (Adj)       Age
```

```
     1  buy 0.20438  0.08%    10000000.0      1004.178  00:11:15
```

Script status: short_volatility: 0.00%  long_volatility: 0.00%

Maker BUY order 1004.178 CRO @ **0.20438** USDC is filled.

**AFTER TRADE:**
  Markets:

```
   Exchange    Market  Best Bid  Best Ask  Ref Price (InventoryCost)
```

```
 crypto_com  CRO-USDC   0.20395   0.20451                  **0.2032046**
```

  Assets:

```
                           CRO   USDC
```

```
 Total Balance        14917.57 0.2054
```

```
 Available Balance           0 0.2054
```

```
 Current Value (USDC) 3046.615 0.2054
```

```
 Current %              100.0%   0.0%
```

  Orders:

```
 Level  Type   Price Spread Amount (Orig)  Amount (Adj)       Age
```

```
     1  sell 0.20505  0.40%    10000000.0       984.964  00:00:07
```

Please take the following example to better understand why this difference in inventoryCost is important: (please note that all the numbers purely fictional and not exact and are just used to better visualise the problem)

* lets say the bot inventoryCost is 1000
* the price increases dramatically to 2000 in a short duration and the bot buys in again with the entire inventory at 2000
* the inventory cost would probably not be set to 2000, but somewhere between 1000 and 2000, but closer to 2000. Lets say 1800
* the bot than sells at 0.3% over the inventoryCost which is 1805.4 So instead of a 0.3% profit, the bot incurs a heavy loss.

**Screenshots**
// If applicable, add screenshots to help explain your problem.

Just to make things even clearer, this is a screenshot of my bot after 88 trades that should be "always-profitable".
NOTE: Keep in mind that I'm always trading with my entire (allocated) inventory at once and I've made the screenshot after a SELL order which should give me at least a 0.3% profit compared to the last buy-in.

![image](https://user-images.githubusercontent.com/21148177/114145794-7a4f8600-991f-11eb-81a2-85e7e858a61d.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
using version dev-0.38.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

Please let me know if further information is needed.
P.S. I hope I attached the correct logs.
[logs_conf_pure_pp_paper.log](https://github.com/CoinAlpha/hummingbot/files/6286694/logs_conf_pure_pp_paper.log)
[logs_conf_pure_pp_paper.log.2021-04-07.log](https://github.com/CoinAlpha/hummingbot/files/6286695/logs_conf_pure_pp_paper.log.2021-04-07.log)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramauy) by [Unito](https://www.unito.io)

**Comment by sidmontanez** [comment]
Hi @florinteodorescu  

Could you send me a copy of your `config` so I could further look into details for the values that was set and for me to replicate this concern. Thanks

**Comment by phbrgnomo** [comment]
@bitphage could you take a look at this issue also?

**Comment by bitphage** [comment]
> What made it clear for me was the trade below:
> 
> * please notice that InventoryCost was 0.2031053 and the bot was trying to buy in again at 0.20438
> * after the trade, the InventoryCost was 0.2032046. This is slightly below the 0.20438 price at which the entry was made.
> * given that I'm trading with my entire inventory at once, I'm expecting that the inventory cost will always be the last BUY-in price

If you're starting one-sided with 100 USDC and 0 CRO and buy order was filled an price X, so yes, inventory cost would be also X. But looking to what you're saying it seems that you got multiple buy orders at different prices, so final inventory cost is weighted-average of multiple buys.


> Please take the following example to better understand why this difference in inventoryCost is important: (please note that all the numbers purely fictional and not exact and are just used to better visualise the problem)
> 
> * lets say the bot inventoryCost is 1000
> * the price increases dramatically to 2000 in a short duration and the bot buys in again with the entire inventory at 2000
> * the inventory cost would probably not be set to 2000, but somewhere between 1000 and 2000, but closer to 2000. Lets say 1800
> * the bot than sells at 0.3% over the inventoryCost which is 1805.4 So instead of a 0.3% profit, the bot incurs a heavy loss.

In this example, if you have inventoryCost = 1000, this means a) there were some coins already bought at this price, or b) if there are no coins (all sold), this inventoryCost value is not influencing next weighted-average calculation.
Next, if buy order would filled at 2000, inventoryCost will be adjusted using weighted average calculation. This means that if you had 0 coins previously, new inventoryCost cost will be exactly 2000 (not 1800), but if you own some, it will be somewhere between 1000 and 2000.

 
> ![image](https://user-images.githubusercontent.com/21148177/114145794-7a4f8600-991f-11eb-81a2-85e7e858a61d.png)

Note that this is a comparison against "buy and hodl" strategy, so it doesn't mean that you have negative realized PnL. E.g. with this strategy we can always expect raise of portfolio USD value, but it's not guaranteed to outperform "buy and hodl" always.

> P.S. I hope I attached the correct logs.
> [logs_conf_pure_pp_paper.log](https://github.com/CoinAlpha/hummingbot/files/6286694/logs_conf_pure_pp_paper.log)
> [logs_conf_pure_pp_paper.log.2021-04-07.log](https://github.com/CoinAlpha/hummingbot/files/6286695/logs_conf_pure_pp_paper.log.2021-04-07.log)

From your logs, I see that order side is not always alternated, e.g. here are 2 subsequent sell orders:

```
2021-04-08 21:06:22,763 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (CRO-USDC) Maker buy order HBOT-B-CRO-USDC-1617914911002174 (996.187 CRO @ 0.20136 USDC) has been completely filled. [clock=2021-04-08 21:06:22+00:00]\
2021-04-08 21:50:42,683 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (CRO-USDC) Maker sell order HBOT-S-CRO-USDC-1617917789001967 (996.187 CRO @ 0.20209 USDC) has been completely filled. [clock=2021-04-08 21:50:42+00:00]\
2021-04-08 23:58:29,874 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (CRO-USDC) Maker sell order HBOT-S-CRO-USDC-1617926268002031 (252.217 CRO @ 0.20392 USDC) has been completely filled. [clock=2021-04-08 23:58:29+00:00]
```
It's unclear where these additional 252.217 CRO came from whether you have pretty huge amount configured, and so the whole inventory should be used for each order.

Also my advice is try starting with 0 CRO (one-sided) and watch bot's behavior, also watch `history --verbose` command to see exact trades. To be 100%, it would be actually nice to compare hummingbot-calculated inventory price VS externally calculated price using account historical data fetched via exchange API. What I actually suspect, that there could be some trade events missed by the bot. This would definitely affect price calculation.

**Comment by MementoRC** [comment]
@cardosofede Follow-up?
