### ISSUE TITLE
Avoiding buy-high-sell-low by allowing only buy orders to expire (order_refresh_time & max_order_age) 

### ISSUE THREAD

**Issue by lsrodri** [hummingbot/hummingbot#3200]
**Feature Suggestion**

Hi all,

I have been setting order_refresh_time and max_order_age to huge integers to avoid the issue of an expiring order allowing the bot to sell for less than I bought. I have tried using ping_pong_enabled for that, but it only protects against it without expiration. So a great way to avoid the buy-high-sell-low issue would be to restrict order expiring to buying orders

**Impact**

I believe this would enable the bot to avoid selling at loss as long as we don't mind waiting for the market to get back to our price.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramayp) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Is this not the `hanging_orders` feature?
