### ISSUE TITLE
Externalize core hummingbot events to Kafka

### ISSUE THREAD

**Issue by galen211** [hummingbot/hummingbot#3203]
**Feature Suggestion**
Give users the ability to specify a Kafka broker to externalize core hummingbot events into Kafka topics.  Enrich events with the strategy name.

**Impact**
Some users want to run multiple headless instances of hummingbot to trade many strategies simultaneously.  Currently, there is no way to have a consolidated streaming view of strategy execution across all instances.

**Additional context**
Kafka is trivial to stand up through offerings like Confluent Cloud and offers powerful surrounding tools like ksqldb (https://ksqldb.io/) as well as managed sink connectors (BigQuery, Postgres, etc).  Confluent also maintains an official python client (https://github.com/confluentinc/confluent-kafka-python), which can be used with any Kafka broker.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramb1n) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Are we still pursuing Kafka, or are we prefering MQTT and @TheHolyRoger @klpanagi orchestration framework?
