### ISSUE TITLE
takeprofit/trailingTP/stoploss for pure_market_making

### ISSUE THREAD

**Issue by Skay200** [hummingbot/hummingbot#3219]
i am sadly no coder, i am looking into it! for the meantime i really miss and stoploss/TP/TTP for the pure marker maker
it would cause many people to be more profitable i you'd be able to set a take profit %
the perpetual market has both of these functions, wouldn't almost be as easy as copy pasting them?
for instance i am trading on kucoin but i am sourcing from binance, wich means the price wont exactly be the same, i would like to be able to take a tp below the midline so they are fast profits with low risk

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramb7p) by [Unito](https://www.unito.io)

**Comment by dendenski** [comment]
@Skay200, As far as I know, it is not as easy as copy-pasting as the perpetual market. Binance perpetual has its built-in system for taking profit and trailing stop, the bot is just implementing the functionality of it.

**Comment by MementoRC** [comment]
@cardosofede Script?
