### ISSUE TITLE
Separate market making P&L and inventory P&L

### ISSUE THREAD

**Issue by dracpet** [hummingbot/hummingbot#3221]
**Feature Suggestion**

Separate trading/market making P&L and inventory P&L. Maybe trading P&L is positive but inventory P&L for assets held to implement strategy is negative. Negative inventory P&L is not very relevant for long term holders of inventory assets and is hopefully temporary. In this case would be nice to see how positive trading P&L is compensating for negative inventory P&L or increasing positive inventory P&L for long term holder. 

Trading P&L is also realized P&L and inventory P&L is unrealized P&L. 

In the Hold Portfolio stats, comparison to a 100% base asset hold position would also be useful. For example: 100% ETH hold portfolio value / initial % ETH - initial % USDT hold portfolio value / Current portfolio value. This would answer the question: How much better/worse is market making for an asset versus just holding the asset or the initial combination of assets needed for market making?

**Impact**

More detailed/extensive evaluation of the strategy's performance and relevant opportunity costs.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramb8m) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede External excel calculator?

**Comment by cardosofede** [comment]
@dracpet if you want, create a proposal in the discord group with the information that you want with the formulas needed and if the community is aligned we can implement that feature
