### ISSUE TITLE
Perpetual Market Making: Automatic Order Amount Calculation based on Account Balance, Current Price and Leverage

### ISSUE THREAD

**Issue by mss7082** [hummingbot/hummingbot#3224]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.

In Perpetual Market Making, I believe it would add value to have a flag marked True or False to enable order amount calculated and updated just before HB submits a  new buy/sell limit order from the account balance (Which HB already has access to), current price and the leverage which already an input provided by the user)

As an example.

Account Balance = 10000USDT
Leverage = 100
BTC-USDTPREP current price = 60,665USDT

Options presented, in addition to the existing options,  to users when they use the create command and enter  perpetual market making as the strategy.

auto_calculate_order_amount? Yes
What is the % of account balance to risk per trade? 1%
Leverage? 100

On the back end.

Amount of account balance to risk per trade = Account balance * 0.01 = 100USDT
Actual amount to trade with based on Leverage = amount to risk * Leverage = 100 * 100 = 10000USDT

Order Amount = 10,000 / current price of the asset = 10000 / 60665 = 0.1647BTC

This would be calculated every time the limit order needs to be refreshed or new limit orders needs to be placed.

If Hedge Mode is enabled, this technically becomes 2%, but still 1% per trade, but the order amount would be the same for the long limit order as well as the short limit order based on the account balance before the orders are submitted.

Using the above example.
Limit Long order amount = 0.1647BTC
Limit Short order amount = 0.1647BTC

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behaviour will allow me to ...

Since the order amount would be dynamic, this adds a layer of risk management and position sizing to HB.

This would help prevent the user from having to manually adjust the order amount of the account drops from 10000 to 9000 and still wants to risk just 1% of the account balance per trade.

As the user losses more money, the order amount reduces dynamically, and when the account  balance increases to 10500 for example, the user can take advantage of compounding where the risk is still 1% of the account balance but the order amount increases dynamically for increased profit.

**Additional context**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramb9b) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Follow-up?

**Comment by cardosofede** [comment]
@mss7082 I like this feature but you will need to create a solution for it or fund a bounty for a community member, I recommend you to go to the Discord channel and add that in the proposal-discussion channel
