### ISSUE TITLE
Price data accessibility & Indicators module

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3250]
## What?
Market prices information in the form of Candle data is highly valuable for traders.

Each candle information contain the following information:

**Time stamp**

* What is the open and close date/time of the candle. (i.e. a 1 min candle contains the price information between 00:00 and 00:01)

**Open price**

* The price at the moment the time frame start (00:00)

**Close price**

* The price at the moment the time frame ends (00:01)

**High price**

* The highest value the price reached between the open and close time of the candle (between 00:00 and 00:01)

**Low price**

* The lowest value the price reached between the open and close time of the candle (between 00:00 and 00:01)

**Volume**

* The amount of traded volume on that candle time frame

Price candle data is also referenced as OHLCV (Open-High-Low-Close-Volume)

**Scripts should have access to that type of information for strategy customization, by using the tick data transformed to OHLCV data.**

## Why?
Along with traded volume information, OHLC data is the main type of data used to create and calculate market indicators.

For market makers it would be useful, for example, to calculate trending indicators like moving averages, RSI, Stochcastic and others to send instructions to the bot to change spreads on one side to follow the trend.

Although some indicators could be calculated using the tick data already collected by the bot, the lack of the 4 values [Open-High-Low-Close] data over time would restrict the type of indicators that could be created.

For example, there is a lot of different ways to calculate volatility:

The "traditional" volatility formula uses the close value of each candle during a chosen timeframe, while _Garman-Klass_ volatility also uses the value of Highs and Lows during the same time period.

**Allowing users access to the price data structured as OHLCV data allow an easier way to create custom indicators that will send orders to change the bot behaviour**

### Where to collect the data from?
First step is to gather the price data that will be used to populate the candle data array.

There are two moments the price data will be populated:

1 - Pull historical data from an "oracle"

Exchanges (i.e. Binance) allows anyone to run API calls to pull data related to price/volume information from a market pair since the day of its listing (aka `kline` function).

Ideally, the user should be able to pull this data from the connector he is running the bot.

Upsides:

* Immediately store a defined data size that could immediately be used by the script.

Downsides:

* Might take too long to download and store and process the data
* API connection problems would prevent the data from being downloaded

1.1 - Storing the data

* The data must be stored in a way that would allow its use after the bot is closed and opened. (an external .csv file could be the solution here)
* The identification of the data must be related to:
  * Exchange where the data was pulled from
  * Trading pair
  * Candle timeframe
* If the function to populate the OHLCV is called inside a strategy/script but a price data file already exists, the function will only add the new information to the file
* (optional) To improve the performance of data download, we could add an option for the user to specify what is the starting date
* The price data must be stored in a database-style, where the timestamp will be used as reference:

File: `OHLCV-5m-Binance-BTCUSDT.csv`

| timestamp            | Open | High  | Low | Close |  Volume |
|----|----|----|----|----|----|
| 2021/04/28 15:45 | 54843.70| 54843.71 | 54643.45 | 54690.76| 152 |
| 2021/04/28 15:40 | 54888.98| 54903.69 | 54812.81 | 54843.71| 208 |
| 2021/04/28 15:35 | 54816.32| 55042.78 |54814.44|54888.99| 208 |

* It is important that, each timestamp is indexed in a way that the most recent candle is the data with the lowest value
  * Using the example above:
    * Index 3 - 15:35 timestamp
    * Index 2 - 15:40 timestamp
    * Index 1 - 15:45 timestamp
    * Index 0 - Current candle in formation

2 - Update the OHLCV data

There are two possible approaches:
  2.1 - Update the data directly from the "oracle"
  2.2 - Update the data using the tick data already collected by the bot.

2.1 -  Update the data directly from the "oracle"

Using this approach, the bot would read the data from the connector everytime a new candle would be formed.

If the functions is creating 5 minutes candle data, the bot would pull new information every 5 minutes, to populate the price data file.

2.2 - Use the tick data already collected by the bot

Hummingbot already collects tick data to execute the strategies. This data could be used to populate the candle data array.

Upsides

* This would remove the need to rely on one specific data "oracle".
* The price data collected would match the situation of the market the bot is running on

Downsides

* If we use only the tick data collected by the bot, it would have to run for some time to gather enough data to create longer time frame candles, and to have enough candle data to be useful. (i.e. the first 15 min candle would be formed only after 15 min of the bot running, and it would take 1 hour to have enough data to calculate a moving average of the last 4 periods)

### Transforming the data
As mentioned, candle data should be structured in an array form (probably a list of tuples), where the index of the array indication how far the candle is from current time, (with index 0 being the current candle that is being formed), and the information stored as (Open, High, Low, Close).

Example:

Candle size: 1 min

Current time: 15:56

Candle Index: 0

Current candle data: (100, 110, 90, [void or current price])

Time: 15:55

Candle Index: 1

Current candle data: (90, 100, 85, 100)

Time: 15:54

Candle Index: 2 

Current candle data: (80, 95, 50, 90)

Final Array:

1_min_candle_data = [(100,110, 90, ?) , (90, 100, 85, 100) , (80, 95, 50, 90)]

```
                                   {Index 0}                {Index 1}               {Index 2}
```

### Using the information
This candle data should be available through one or more functions, where the input must be an Index (or range of indexes) and which price the user want to retrieve (open, high, low or close).

Using the data example above:

 `price.close(2)` would return the value of `90`

`price.low(0,2)` would return the list `[90, 85, 50]`

On this format, users could create, for example, a moving average function of the last 3 candle open prices:

```python
def moving_average();
	sum_price = price.open(0) + price.open(1) + price.open(2)
	average = sum_price / 3
```

## Impact?
Candle data information opens up a lot of possibilities regarding customization.

The access of this type of data empower the user to change bot parameters based on price information, for example, detecting the trend direction to change the spread size on one of the sides.

This also open up the possibility of customizing the bot to behave in a more "traditional trading" way: For example, an user could implement a Moving Average Crossing strategy where it would order the bot to set the `bid_spread` to 0.01 and the `ask_spread` to his wanted take profit value when a crossing happens.

## References
[Script to pull historic data from Binance and Bitmex](https://github.com/phbrgnomo/CryptoTradingTools/blob/main/BinanceData/PullData.py)

[PR to add candle data to be used with scripts](https://github.com/CoinAlpha/hummingbot/pull/2981/files)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rambjc) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
User feedback on discord:

> it is useless and not necessary but why can't Hummingbot integrate Tradingview directly using webhooks instead of users paying a tone of money to throw together a makeshift  ( telegram, ConfluxBot, tradingview  &  hummingbot ) . That is a lot of things that can go wrong and have to be monitored. By adding a built-in indicator module in hummingbot then you really do not need tradingview & confluxBot at all . Tradingview is completely useless in actual trading apart from visualization for newbies. In Crypto World, Hummingbot has access to OrderBook and tick by tick datastream , which can be used to create any indicator for trading in combination with liquidity mining or PMM  including strategies that can use  different timeframe bins ( ticks, (1 , 5, 10) Secs,  (1,3,5,10,15,30) Mins, (1,4,12) Hrs, etc ) . I prefer a fast and simple all built-in hummingbot

**Comment by zappra** [comment]
A couple of comments based on my experience:

I'm not sure you need to write the candle data out to a database, if users want to do other analysis on historical data it's only a few lines of python to pull eg. a month's worth candles. If you're relying on data written out during bot execution you'll inevitably end up with gaps in the data due to stopping/restarting. Similarly priming the bot on startup with enough candle data from the exchange to support common indicators only takes a second or two. 

Linking with a good indicators lib is important, I guess TaLib would be the obvious choice although worth considering that you want something that supports regularly updating indicator values rather than say computing a whole ton of values in one go in a pandas dataframe or something, which would chew up a lot of memory and performance.

I cheat a bit with volume - I use the initial set of candles from the exchange to populate volume, and then per tick order updates to compute in real time

Really the big barrier to making this a core module is the fact that customization scripts run in a separate process. Looking at that first would really make it easier to expose stuff like this to users.

**Comment by MementoRC** [comment]
@cardosofede TWAP exists and now we have the klines, close?
