### ISSUE TITLE
FIFO optimization

### ISSUE THREAD

**Issue by krisj** [hummingbot/hummingbot#3294]
**Feature Suggestion**

I would love to see a certain FIFO optimization introduced to the Market Making strategies.
Currently, the strategies cancel and replace orders even if they are exactly the same since and at the same rate/price. This leads to a very unfavourable trade execution due to the FIFO principle most exchange's matching engines implement.

I propose that there is a FIFO switch introduced with a single threshold parameter. Like so for example:

`fifo_optimization_enabled` = `true/false` // simply a switch to enable/disable this mechanism
`fifo_threshold` = `<rate>/<percentage>` // a threshold which if exceeded, the normal rules would apply, otherwise - use the fifo optimization and leave the limit order intact. Note 

**Impact**

This would increase order fill rate and profitability in most strategies as orders would fill faster. Some lower cap and low sat pairs especially would benefit but not exclusive to these.

Another benefit would be decreasing the exchange API as well as Humminbot operators machine resource load as orders would be replaced less often and only if the amount/rate changes past the threshold set by the user.

**Additional context**

I will add some more info/context later.. In a hurry...

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramcfc) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
I don't really use it but isn't this what "order_refresh_tolerance_pct" does?

**Comment by krisj** [comment]
yea it's warm but not quite. `order_refresh_tolerance_pct ` leaves both bid/ask orders (the entire cycle) untouched unless **the reference price moves outside this threshold**. I am proposing another threshold that filters which orders if any would need replacing (independent of side) after the refresh cycle is triggered based on **the delta of current limit order rate and the proposed new limit order rate is larger than the threshold and independent of all other orders (this is done for each new proposed order)** in the refresh cycle.

So in other words - a nuanced filter that saves certain orders from being unnecessarily replaced at the same rate/amount which can be caused by quick rate retracements, sudden changes in the spread thus moving the reference price (e.g. mid price) and so on. You could have a macro regime in the market where bids in the book remain at the same level and only asks oscilate for  while (and vice versa). Without this filter/feature HB would replace orders without checking if the new order would be actually at exactly (I also propose a threshold) the same rate and amount or not.

Am I making any sense here? 😅

**Comment by zappra** [comment]
That makes sense yes! :)

**Comment by MementoRC** [comment]
@cardosofede Is this not best implemented in a Script, perhaps as a proposal for students? - Not an Issue, right?

**Comment by cardosofede** [comment]
@zappra @krisj I implemented a component called PositionExecutor for Perps. Soon I would like to implement it for Spot and that component can address what you are looking for.
Essentially, each order has a take profit, stop loss, and time limit managed by the bot, so it will let you close the cycle of a filled order and improve the logic of your strategy.
