### ISSUE TITLE
Create an example strategy file that uses the OHLCV price data functions

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3304]
## What
Create an example strategy that make use of the price data implemented in #3300.

Inputs needed:

`what is the candle time frame (1m, 5m, 1h, etc)?`

* This will define how the downloaded data will be stored.

## How
This example strategy doesn't have to execute any trade, but should print the price data function working:

* Print the amount of data downloaded (candles, size, seconds to download)
* Print the last candle information (the candle with index (1): `Last formed candle data: Timestamp: xx:xx:xx Open: xxxx Close: xxx High: xxx Low:xxx Volume: xxx
* Calculate a simple moving average of the last 5 candles using the open price and print the result.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramcv6) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede This is done, correct?
