### ISSUE TITLE
Create Connector Tester

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#3312]
A new generic connector tester 
see https://www.notion.so/hummingbot/Automated-testing-tools-for-QA-49b1bf33ea374083a738243d0bc0ea09

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramd1p) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@Nullably @rapcmia @cardosofede I cannot access the notion link, is this still an opened and desired enhancement?
