### ISSUE TITLE
XEMM - Takers fund availability check

### ISSUE THREAD

**Issue by jellebuth** [hummingbot/hummingbot#3313]
**Feature Suggestion**

 A feature for Cross exchange market making to properly manage your funds. The bot does not check funds availability on the taker market. Sometimes the bot makes trades on the maker market without hedging it on the taker market because there are not enough funds. I suggest the following features for inventory management:

* fund availability check on the taker market (most important one), if funds too low, no maker sell or buy order (depending on the funds that are too low).
* ping pong strategy
* allocate funds to the bot. Allocate funds on maker & taker exchange + amount in base currency + amount in other currency

// A succinct description of **how you want to achieve the desired behavior**.

* A simple availability check that checks availability of funds on the taker exchange. If base currency is too low, it will not place any limit sell order on the maker exchange, but only limit buy orders. Also the other way around. 

I don't know if this check is done before every trade. This could make the bot slower. Otherwise temporarily checking funds is also fine. As long as it shuts off the specific limit buy or sell order on the maker exchange.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.

The desired behavior will allow me to run multiple bots with the same base pair without having to focus and manage the funds too much. Als good for capital efficiency as you don't have to hold an excessive amount of coins on the taker exchange.

**Additional context**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramd2t) by [Unito](https://www.unito.io)

**Comment by jellebuth** [comment]
another feature tho manage the inventory could be to set a min_profitability for buy and sell orders separately. If the bot mostly fills buy orders on the makers side, you could manually lower the min profitability for the sell orders.

**Comment by mhrvth** [comment]
Is this still relevant? It looks like it does check now balance before placing a taker market order:

![image](https://user-images.githubusercontent.com/7762229/166641373-19ce74de-6f37-4395-afd7-ad2dc93c1379.png)

**Comment by jellebuth** [comment]
Hi,

Yes should be good, thanks!

Jelle

**Comment by MementoRC** [comment]
@jellebuth @rapcmia We should close, correct?
