### ISSUE TITLE
RateOracle and rate command NGN price discrepancy

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#3318]
**Describe the bug**

* Created a github ticket for tracking.
* RateOracle and rate command NGN price discrepancy 
* Unable to show price using rate command

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/54516858/117142114-ed92cd80-ade1-11eb-9e6d-9c57dfb0bb08.png)
![image](https://user-images.githubusercontent.com/54516858/117142136-f2f01800-ade1-11eb-82c1-1c483e2518d6.png)

**Screenshots**

* hummingbot client NGN-USDT
![image](https://user-images.githubusercontent.com/54516858/117142244-11561380-ade2-11eb-8672-1ea52ca25022.png)
![image](https://user-images.githubusercontent.com/54516858/117141409-149ccf80-ade1-11eb-99ca-b4847002134e.png)
* [coingecko](https://www.coingecko.com/en/coins/tether/ngn)
![image](https://user-images.githubusercontent.com/54516858/117141480-2a11f980-ade1-11eb-8ec6-74159c890a3e.png)
* [coinmarketcap](https://coinmarketcap.com/converter/)
![image](https://user-images.githubusercontent.com/54516858/117141538-3d24c980-ade1-11eb-92ab-d7a5175b56ca.png)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramd65) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Price now showing ok as of version 1.18.0
![image](https://github.com/hummingbot/hummingbot/assets/73840223/40229a81-c70b-4b4e-b16e-ba7af40afd7d)
