### ISSUE TITLE
Gateway - Unable to run Terra gateway without using Balancer/Uniswap

### ISSUE THREAD

**Issue by uknj** [hummingbot/hummingbot#3319]
Describe the bugCreating a new terra gateway while choosing to not setup Balancer or Uniswap results in the gateway being unable to start. This affects docker version

Steps To Reproduce

Here are the steps to reproduce the issue (see error log in the section below):

Setup a new bot (configuration at this stage is irrelevant).
Generate the certificates.
Create a new gateway using the appropriate docker script.
Select the appropriate directory for the bot you have created above.
When you are asked to "setup Balancer or Uniswap", select No (N).
Complete the remaining steps as you normally would.
Once the gateway is created, run the ./start script.
The gateway will not be running. If you attempt to run it with either docker or the start script, the below error will occur.

This error does not occur if you setup the Uniswap and Balancer option set to Yes (Y)....Error log

Error: Invalid network
at Ethereum._callee7$ (/usr/src/app/src/services/eth.js:148:15)
at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:63:40)
at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:293:22)
at Generator.next (/usr/src/app/node_modules/regenerator-runtime/runtime.js:118:21)
at asyncGeneratorStep (/usr/src/app/src/services/eth.js:14:103)
at _next (/usr/src/app/src/services/eth.js:16:194)
at /usr/src/app/src/services/eth.js:16:364
at new Promise (<anonymous>)
at Ethereum.<anonymous> (/usr/src/app/src/services/eth.js:16:97)
at Ethereum.getERC20TokenList (/usr/src/app/src/services/eth.js:425:35)

Release versionVersion 0.38.1.

Optional: your discord username:uknj#2857

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramd7m) by [Unito](https://www.unito.io)

**Comment by dendenski** [comment]
To confirm the issue, I use the latest gateway for AWS docker, the gateway instance shutdown by itself after creating a terra only gateway.
![image](https://user-images.githubusercontent.com/65387749/117206622-a9292100-ae25-11eb-820a-646157451be3.png)
starting the gateway instance will produce this error.
![image](https://user-images.githubusercontent.com/65387749/117206855-ef7e8000-ae25-11eb-8cb0-0f2d8b646cd9.png)

**Comment by dennisocana** [comment]
> This error does not occur if you setup the Uniswap and Balancer option set to Yes (Y)

@dendenski can you also confirm this and show screenshots? Thanks.

**Comment by dendenski** [comment]
@dennisocana , the gateway instance did not shutdown when uniswap/balancer is set to Yes(Y)
![image](https://user-images.githubusercontent.com/65387749/117228001-b3a9e180-ae4a-11eb-9e28-12e8627e8f5a.png)
![image](https://user-images.githubusercontent.com/65387749/117228708-25365f80-ae4c-11eb-9e93-d74795c65ad5.png)

**Comment by dendenski** [comment]
Same issue using development image, gateway shuts down after a few seconds.
![image](https://user-images.githubusercontent.com/65387749/117231005-dc34da00-ae50-11eb-8062-65be028b4f6f.png)

**Comment by PtrckM** [comment]
- Also when using gateway-api as source just configuring TERRA_LCD_URL, TERRA_CHAIN, CERT_PATH, CERT_PASSPHRASE and LOG_PATH will also cause the gateway to crashed.

- Also noticeable when using docker build gateway-api `./create-gateway.sh` script
   - even if you choose No for Balancer and Uniswap script still continue to ask the ff:
      - eth node to used
      - eth token list
      - eth gas price lookup settings
      - additional uniswap and balancer settings

**Comment by dennisocana** [comment]
@PtrckM please create separate stories for those two issues.
