### ISSUE TITLE
Failed to start after changing exchange

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#3323]
**Describe the bug**

* Bot unable to start and recognize api/connector after changing exchange when using strategies like liquidity_mining, pure_market_making, arbitrage, cross_exchange_market_making and avellaneda_market_making.

**Steps To Reproduce**
Example for `liquidity_mining`

1. connect kucoin
1. create then choose Liquidity Mining Strategy
1. spot connector binance
1. list your markets
1. set your asset base/quote
1. enter size
1. enter spread
1. enter target base/quote
1. save your config
1. config exchange -> enter kucoin
1. start

![image](https://user-images.githubusercontent.com/54516858/117248935-4eb6b180-ae73-11eb-9091-bfb8404340e1.png)
![image](https://user-images.githubusercontent.com/54516858/117249291-eb794f00-ae73-11eb-8bbc-090be72aed58.png)
![image](https://user-images.githubusercontent.com/54516858/117249017-773eab80-ae73-11eb-8289-49f229f17c0c.png)

DEMO:
https://user-images.githubusercontent.com/54516858/117248432-8b35dd80-ae72-11eb-9c5d-9c582363cb17.mp4

Workaround:

1. exit bot
1. launch bot
1. import strategy
1. start

https://user-images.githubusercontent.com/54516858/117248728-07302580-ae73-11eb-916e-d7d0c6887881.mp4

**Release version**
0.38.0 / 0.38.1 / dev-0.39.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramdar) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Tested with Kucoin, Binance, and Ascendex by creating simple config for PMM, LM and Arbitrage strategies then run `status` command. Change `exchange` or `markets`(for arbitrage) and then check status or start the bot, it seems to work ok for the current, staging, and dev branch. Tagging this ticket as resolved.
