### ISSUE TITLE
Gateway-api source crashed when filling only environment for terra

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#3326]
**Describe the bug**

* When trying to use only terra and not configuring balancer settings, uniswap settings and ethereum will crashed the gateway.

**Steps To Reproduce**

1. generate certs on hummingbot
1. follow gateway source installation [here](https://docs.hummingbot.io/gateway/installation/)
1. edit .env and configure the following: TERRA_LCD_URL, TERRA_CHAIN, CERT_PATH, CERT_PASSPHRASE and LOG_PATH
1. start your gateway

![image](https://user-images.githubusercontent.com/54516858/117276351-643ad400-ae91-11eb-8ae1-0782981931e4.png)

![image](https://user-images.githubusercontent.com/54516858/117276528-91878200-ae91-11eb-8fa3-4b79b1365380.png)

![image](https://user-images.githubusercontent.com/54516858/117275273-71a38e80-ae90-11eb-8dc0-350f64575e06.png)

**Release version**
client: 0.38.0 / 0.38.1 / dev-0.39.0
gateway: v0.5.0

similar: https://github.com/CoinAlpha/hummingbot/issues/3319

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramdbw) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Closing ticket, gateway-v2 is now available on staging and development branch. However, Terra is not yet available and there are plans to be added on future releases
