### ISSUE TITLE
create-gateway script when using terra

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#3327]
**Describe the bug**

* If you only want to use Terra and choose No for Balancer and Uniswap script will still continue to ask for Balancer, Uniswap and ethereum settings. Ethereum RPC node is also unskippable, After entering your rpc node, choosing N or default values then enter Y for terra usage, lastly enter your cert passphrase will cause the gateway to crashed.
* See gateway docker installation [here](https://docs.hummingbot.io/gateway/installation/)

**Steps To Reproduce**

1. execute`./create-gateway.sh`
1. select gateway version
1. enter name of gateway instance
1. enter path of hummingbot files
1. enter N for `Do you want to setup Balancer or Uniswap? [Y/N] (default "Y") >>>`
1. script will continue to ask for:
  * Enter the Ethereum RPC node URL to connect to (unskippable)
  * Enter the token list url available
  * Enable dynamic Ethereum gas price lookup
  * Enter fixed gas price
  * Enter the maximum Balancer swap pool
  * Enter the allowed slippage

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/117280748-7dde1a80-ae95-11eb-88bd-447ad8ca65d9.png)
![image](https://user-images.githubusercontent.com/54516858/117280915-afef7c80-ae95-11eb-8b72-ae01db11ecd2.png)
![image](https://user-images.githubusercontent.com/54516858/117280989-c09ff280-ae95-11eb-95b3-e46cae2144bc.png)

**Release version**
gateway: v0.5.0

similar: https://github.com/CoinAlpha/hummingbot/issues/3319

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramdcw) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Closing ticket, gateway-v2 is now available on staging and development branch. However, Terra is not yet available and there are plans to be added on future releases
