### ISSUE TITLE
Addition of BTCUSDT & ETHUSDT USDⓈ-M quarterly delivery futures to the binance perpetual connector.

### ISSUE THREAD

**Issue by cgsanchez** [hummingbot/hummingbot#3330]
**Feature Suggestion**

It would be very nice to be able to run Hummingbot on the ETHUSDT and BTCUSDT quarterly delivery futures in Binance's USDⓈ-M futures exchange.

From looking at the code for the connector (but from my ignorance of the rest of Hummingbot's structure) it should be just a matter of naming since the connector should be able to handle these pairs already. Perhaps I am underestimating the amount of work needed in the rest of the code for it to be able to recognise say USDT_210625 as a currency.

I tried hacking the currency name validations in the perpetual conector without success. My attempt was very feeble though. 

**Impact**

USDT quarterly delivery futures seem to have a nice spread for high frequency MM and it would be great to try Hummingbot at these. This would perhaps be the basis for a COIN-Ⓜ futures conector eventually.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramdht) by [Unito](https://www.unito.io)

**Comment by pk13** [comment]
+1 on this. Super useful

**Comment by MementoRC** [comment]
@cardosofede Status?
