### ISSUE TITLE
Perpetual Feature; Create new Long / Short Order if Position is fulliled

### ISSUE THREAD

**Issue by JayPsy420** [hummingbot/hummingbot#3345]
**Feature Suggestion**
In the hedge mode there should be an option to recreate the order if it has been executed.
So that it is not necessary to wait for the stoploss or the closing of the order of the opposite side.

**Impact**
This allows more successful trades to be executed in hedge mode and allows you to get further with smaller stakes.

**Additional context**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rame2f) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede This is implemented, correct?
