### ISSUE TITLE
liquidity_mining strategy - unable to create order when using quote asset

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#3353]
**Describe the bug**

* Unable to create order when using quote asset on [liquidity_mining](https://docs.hummingbot.io/strategies/liquidity-mining/) strategy.
* Affected exchanges: bittrex, beaxy and bitfinex

**Steps To Reproduce**

1. create a strategy using liquidity_mining
1. select any of affected spot connector
1. What asset (base or quote) do you want to use to provide liquidity? >>> use your quote token (make sure can make order on either buy or sell side)
1. start strategy

**Screenshots**

* balance
![image](https://user-images.githubusercontent.com/54516858/117804799-cd07bf00-b28a-11eb-9b58-673ee2fe1ef1.png)
* using quote token asset
![image](https://user-images.githubusercontent.com/54516858/117805776-f70db100-b28b-11eb-919c-c962490fe8c9.png)
* using base token asset
![image](https://user-images.githubusercontent.com/54516858/117805955-33d9a800-b28c-11eb-8705-3675896508dc.png)

**Release version**
0.38.1 / dev-0.39.0

**Attachments**
[logs_lm_bittrex_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/6458763/logs_lm_bittrex_eth-usdt.log)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramjpb) by [Unito](https://www.unito.io)

**Comment by PtrckM** [comment]
- bittrex is working now :white_check_mark: 
![image](https://user-images.githubusercontent.com/54516858/118763754-f63bd700-b8aa-11eb-859d-45b075b61de7.png)

- beaxy :x: 
- bitfinex :x:

**Comment by rapcmia** [comment]
Closing this ticket for now as we have not yet updated the affected connectors.
