### ISSUE TITLE
Question About Custom Scripts

### ISSUE THREAD

**Issue by rogueops** [hummingbot/hummingbot#3362]
I am getting into custom scripts and using a couple of the pre-made ones to see how it all works. I am about to try out dynamic_price_band_script.py and have a couple of questions. First, when running a script does the bot go by the settings in the strategy first or does the strat and the custom script work together and one will override the other as in dynamic_price_band_script.py will prevent a sell or buy if the band is hit to prevent bad trades or if the bid/ask is hit the bot will make the trade regardless of what is set in dynamic_price_band_script.py? Secondly, can only one script at a time be used/run? I plan to write a custom script for the kill switch and would like to know if I can disable the kill switch in the strat config and the custom script will still do its job and also what pmm parameter is for just the current return percentage? I only see all_total_balances listed in the docs and want to work with just the current return percent if possble. If I need to pull that value from all_total_balances just want to know before going down the wrong road.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramjtf) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
I'm not familiar with the price band script but in general the scripts override the running strategy parameters, ie. if in your config your bid_spread is 1.0, but the script sets 1.5, then 1.5 will get used, but your config will remain unchanged. There's one possible exception to this, which is the very first set of orders created, which typically get issued before the script has started running.

With custom kill scripts bear in mind you can't currently stop the strategy from a script, or cancel open orders, but you can set buy and sell levels to 0 to prevent any further orders being placed
