### ISSUE TITLE
Futures arbitrage supports long and short futures hedging

### ISSUE THREAD

**Issue by wechatshort** [hummingbot/hummingbot#3372]
**Feature Suggestion**
Futures arbitrage strategy can support long futures and short futures hedging

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
This can achieve higher capital rate efficiency and remuneration, if i don't have token.

**Additional context**
![68747470733a2f2f68756d6d696e67626f742e696f2f7374617469632f62613965393065383834613365636638616135373837343661326265323664622f36306562322f68626f742d636f6e6669672e706e67](https://user-images.githubusercontent.com/72927037/118223820-a5943a80-b4b4-11eb-91ca-488c847e98a1.png)

spot_connector, derivative_connector can support each other

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramjwm) by [Unito](https://www.unito.io)

**Comment by DanBenHa** [comment]
Doesn't it already do that? See the first section of the doc https://docs.hummingbot.io/strategies/spot-perpetual-arb/

**Comment by MementoRC** [comment]
@cardosofede Can we evaluate/ask community and close?
