### ISSUE TITLE
Feature Request - Multiple Order Levels on Liquidity Mining

### ISSUE THREAD

**Issue by bdrex95** [hummingbot/hummingbot#3380]
**Feature Suggestion**

Add the ability to set multiple order levels on liquidity mining strategy.  This feature already exists on pure market making strategy, so (in theory) the code would simply need to be added to the liquidity mining strategy.

**Impact**
This would allow the liquidity miner strategy to work more like the pure market making strategy, but on multiple coin pairs.  This will allow greater control for the miners with their orders, especially to catch a quick market spike.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramk2m) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede I do not think this is wise in a H strategy and should be implemented at the user's risk with a ScriptStrategy. Discussion in forum or discord?

**Comment by cardosofede** [comment]
@MementoRC agree, this can be implemented in a script and it's very easy to do so.
