### ISSUE TITLE
Reported P&L

### ISSUE THREAD

**Issue by rogueops** [hummingbot/hummingbot#3405]
I was watching my bot trade all day and noticed the last 2 trades were losses, but the Return P&L showed a positive increase in the percent and amount. These were the trades

BUY 100 @ 0.67 = 67

## SELL 100 @ 0.65 = 65
P&L = -2
Bot Reported: 2

Shouldn't the bot show positive when the buy is lower then the sell and negative when its the reverse like the above?

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramkbj) by [Unito](https://www.unito.io)

**Comment by geloadviento** [comment]
Hi! @rogueops, Bottom nav bar is based on the last trade and the history shows the return % after the current price change. You can also refer to this link for more infortmation: https://docs.hummingbot.io/features/performance-history/#average-price

**Comment by geloadviento** [comment]
Hi! @rogueops, Are you referring to the history and nav bar? Bottom nav bar is based on the last trade and the history shows the return % after the current price change. You can also refer to this link for more infortmation: https://docs.hummingbot.io/features/performance-history/#return-percentage

**Comment by rogueops** [comment]
according to that doc the bottom bar is based on the last trade price so per my bot the last trade was 

BUY 100 @ 67 = 67.00 USD

then later it filled a sell order as follows

SELL 100 @ 65 = 65.00

the bot reports the above as a gain when it should be a loss as I bought high and sold low, right?

**Comment by subimpact** [comment]
im having the same issue as well
![image](https://user-images.githubusercontent.com/15685593/119168864-f0edb080-ba93-11eb-8692-d3a1674e8a48.png)

**Comment by sidmontanez** [comment]
Hi @rogueops This could be due to a surge from the market price to why the percentage shows a different value. But from the Return % example that on the bottom of the nav bar, it's supposed to show a negative value based from the 2 past trades that you've mentioned. Could you also send a screenshot of your bottom nav bar that shows the value for your Return %?

**Comment by sidmontanez** [comment]
Hi @subimpact I just want to confirm based on the screenshot that you've sent, would that be a consecutive `status` command initiated? Could you send us a screenshot of your whole terminal so we could take a look at the time stamp and `history` of your past trades? Thanks

**Comment by rogueops** [comment]
is there a command to show the active orders it is going to close as in it makes a sell order at 60 and to close that order it would do a buy, at least that what it looks like the bot is doing to calc the return P&L.

**Comment by rogueops** [comment]
got something new, i reset the bot so it had 0 trades with a 0% P&L and when it did just one buy the P&L went negative

**Comment by teddyarangorin** [comment]
Hi @rogueops, for now there is no existing command for the one you described. With regards to your concern on the fresh bot, it will show as negative with one buy since your base asset has been reduced.

**Comment by MementoRC** [comment]
@cardosofede Are we not recommending using the excel calculator for PnL?

**Comment by cardosofede** [comment]
the PNL calculation of the bot is more like a market making approach. It's comparing the value of doing nothing, versus the current value of the portfolio affected by the current prices.
If you want too see the performance I will recommend you to use the post process tool: https://github.com/hummingbot/community-tools/tree/main/Hummingbot-Postprocess
