### ISSUE TITLE
FTX not trading when having staked funds

### ISSUE THREAD

**Issue by TradeClaw** [hummingbot/hummingbot#3407]
**Describe the bug**
Staked funds are counted as inventory, HB does nothing when your staked funds are above inventory target.
No output is given, no "cannot place order", no "inventory target reached".
It does not buy in that case so remains a 0 available funds starting balance of the asset.

**Steps To Reproduce**

1. Have staked funds, f.e. FTT
1. Have a low amount of available balance for FTT, USD amount lower than the staked FTT USD value
1. I used Avellaneda Market Making on FTT-USD, 2% inventory target
1. Start, 60sec volatility warm-up and then...nothing happens
(works on everything where I don't have staked funds)

**Screenshots**
![image](https://user-images.githubusercontent.com/63117227/118785652-56258400-b891-11eb-9df6-5527876916e8.png)

**Release version**
0.39.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramkf3) by [Unito](https://www.unito.io)

**Comment by geloadviento** [comment]
Hi @TradeClaw, To better understand your concern can you elaborate what you meant by "staked funds"?

**Comment by mss7082** [comment]
Create a subaccount as a workaround, and transfer the unstaked FTT and your USD to the subaccount. Then add the subaccount API keys to hummingbot. That way, HB only sees the balance in the subaccount.

**Comment by nikspz** [comment]
Closed that issue as FTX going to be removed as connector in 1.10.0 Release
