### ISSUE TITLE
Avellaneda Strategy - bot stopped tracking placed orders for long running bots

### ISSUE THREAD

**Issue by dendenski** [hummingbot/hummingbot#3423]
**Describe the bug**
Stopped tracking placed orders for long running bots.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up your configuration file with these parameters: 
![image](https://user-images.githubusercontent.com/65387749/119198517-0b3b8480-babc-11eb-8daa-6239e4792039.png)
1. Start the bot.
1. Run the bot for a few days.

**Screenshots**
No active orders on status
![image](https://user-images.githubusercontent.com/65387749/119198616-345c1500-babc-11eb-8053-f0de01a39398.png)
Orders created by the bot remained on the order book but not showing on bot status.
![image](https://user-images.githubusercontent.com/65387749/119198741-6cfbee80-babc-11eb-9788-116cb6ef29ea.png)

**Release version**
0.39.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[avellaneda_binance.zip](https://github.com/CoinAlpha/hummingbot/files/6525116/avellaneda_binance.zip)
It seems that the issue happen when this log shows up.
![image](https://user-images.githubusercontent.com/65387749/119199103-13e08a80-babd-11eb-9cad-7182844023c4.png)
Stopping the bot does not cancel the orders on exchange.
![image](https://user-images.githubusercontent.com/65387749/119199301-6a4dc900-babd-11eb-8087-fabef988edfc.png)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramknx) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
We did a fix on this strategy recetly (0.42). Could you let us know if it improved your issue?

**Comment by RC-13** [comment]
Switched our Binance test bot to Avellaneda MM for monitoring, we will update this ticket after few days.

**Comment by nikspz** [comment]
can't reproduce, please try to use the latest development (1.11.0)
