### ISSUE TITLE
PerpFi Connector - `get_quote_price` is not calculated in base currency

### ISSUE THREAD

**Issue by KristofJuhasz96** [hummingbot/hummingbot#3443]
**Describe the bug**

When calling perfi_connector.get_quote_price()  (tried for ETH-USDC) the buy price is not calculated with the base currency amount as described in docs, but with the quote currency amount. For sell price, it is calculated in the base currency.

**Steps To Reproduce**

Go to test_perfi_connector.py and run `async def _test_get_quote_price(self):` with ETH-USDC with 1000 ETH. The buy price will be false value, calculated with 1000 USDC rather thant ETH.

**Release version**
version = "20210518"

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rammau) by [Unito](https://www.unito.io)

**Comment by KristofJuhasz96** [comment]
Hello @sidmontanez , I am not running the terminal, I was testing the connector using the`test/connector/perpfi/test_perfi_connector.py/test_get_quote_price`.

**Comment by MementoRC** [comment]
@cardosofede Close?
