### ISSUE TITLE
Improve active orders initialization during market states recovery

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#3454]
As a user I need the client application to recover all orders that were active.
Currently the start process recovers the active orders using the markets states. But in some scenarios of network issues the last market state snapshot could be missing some orders (maybe because they were removed from the inflight orders collection but they were not cancelled or removed by the exchange). 
As a complement to the current recovery process the client should also query the database for all orders that where updated in the last 24 hours, that are in any of the possible active states (ie.: the is_done message would return false). For all the orders that are not currently in the the inflight orders collections we should send a request to the exchange querying for its current status and if the order is no longer in the exchange, it should be disregarded.
NOTE: we may reuse the logic of the process that updates the status of the orders.

**Impact**
The functionality should be included in all the connectors

**Additional context**
The functionality is intended to solve issues like: https://github.com/CoinAlpha/hummingbot/issues/3374

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rammg6) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Moving to backlog for further discussion.

**Comment by dennisocana** [comment]
Paulo will create stories related to the number 3 and 4 approaches indicated in this epic https://github.com/CoinAlpha/hummingbot/issues/3470

**Comment by phbrgnomo** [comment]
QA needs to implement standard tests to investigate and identify the source of the desync.

An investigation ticket will be created related to this story.

**Comment by MementoRC** [comment]
@cardosofede This can be closed, right?
