### ISSUE TITLE
Detect active orders not being tracked during order status update process

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#3455]
As a user I would like the client to detect orders that are still alive in the exchange after the client has cancelled them.

We can take the opportunity to validate this type of inconsistency during the _update_order_status() process. In almost all the current implementations, when the process cycles the orders and the status responses from the exchange for each of them, if the order is no longer included in the inflight orders collection, the response is not analyzed.
For the cases were the order is no longer an inflight order (is not being tracked) and the status in the exchange according to the response is an active status we need to do one of the following things:

* Start tracking the order again
or
* Send a request to the exchange to cancel that order
The might need to define the approach to follow based on the information that we still have about the untracked order (it might not be possible to recreate it)

**DoD:** if an order is no longer being tracked but the client receives a valid status response for it from the exchange, it should either be tracked again or should be cancelled in the exchange.

**Impact**
This change impacts all the connectors. We might want to implement it first in some of them, to test the result.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rammmy) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede The root feature was removed, close?
