### ISSUE TITLE
Cancel only active orders during outstanding orders cancellation

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#3456]
As a user I would like to avoid sending unnecessary requests to the exchange.
As a user it is important for me that the stop action is consistent and leaves the client ready to start working again.

Reviewing the code we found out that some connectors filter the orders for which they will request cancellations to the exchange in the _cancel_outstanding_orders() process (see cancel_all(timeout)). But other connectors request cancellation for or the inflight orders, without applying any filter.

The process should only cancel orders with any of the possible active statuses. Any order that has already been filled, cancelled, has expired or has been rejected (ie: it is not active) should not be included in the list of orders to cancel.

**DoD:** during cancellation of outstanding orders the client should only submit cancellations requests to the exchange for the orders that are in an active state.

**Impact**
This should be implemented in all connectors that currently don't filter the orders to be cancelled. To reduce the scope of the task we could agree to implement the change in a fixed number of them first, and see how the change behaves.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rammnt) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Is this still relevant with connector v2.1?
