### ISSUE TITLE
Multi-market multi pair arbitrage

### ISSUE THREAD

**Issue by gionkunz** [hummingbot/hummingbot#3461]
**Feature Suggestion**
I would even go that far and implement an auto-arbitrage mode where the bot is connecting to all connectors, check available balances, and monitor arbitrage opportunities automatically for available funds in any pair. So it would trade x pairs in n markets.

**Impact**
In terms of overall profitability, this change would be great. We could not only do arbitrage across many spot markets at the same time, but also trade any pair for which there is balance in the connectors. This would simply allow to add balance to 10 currencies on many spot markets and let the bot do the rest :-)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rammr4) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Script?
