### ISSUE TITLE
Market opportunity live status

### ISSUE THREAD

**Issue by gionkunz** [hummingbot/hummingbot#3462]
**Feature Suggestion**
I'm finding myself a lot trying to find pairs with good enough volume but still not so much that arbitrage is difficult. Also, it's cumbersome to figure out exchange fees manually. At the moment, I swap some test amounts and then just run a bot to see some statistics with status --live over time and check if there are many opportunities. I could also monitor the markets on two platforms and check for the bid / ask. It would be a fantastic feature of Hummingbot to have a market overview where I see profitability in a live view for multiple compatible pairs. This way we could monitor in one place, if there's a pair between two spot markets, with good opportunities

**Impact**
Arbitrage opportunity overview would help tremendously to evaluate which trading pair would be worth going for on particular spot markets.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rammrt) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Script?

**Comment by cardosofede** [comment]
@MementoRC yes, this can be done by a script. Last Botcamp Cohort one student did it.
