### ISSUE TITLE
Refactor of orders tracking/syncronization between client and connectors

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3470]
As described on bugs #2955 and #3374, there are some recurring issues related to tracking orders on exchanges and synchronizing them with the information hummingbot client.

After investigation realized by aarmoa on issue #3414, 4 approaches to the refactor were recommended.

We will run the following process for this refactor:

1 - Implement approach #1:
> 1 - At the moment of doing the startup, besides restoring the market state (self.markets_recorder.restore_market_states(config_path, market)) we could also run a refresh of orders from the DB, and include as inflight orders those that were not part of the market state and are still alive in the exchange (suggestion to tackle issue https://github.com/CoinAlpha/hummingbot/issues/3374)

* reference issue: #3454

2 - Approaches #3 & #4 will be worked after the results of approach #1.
> 3 -The method HummingbotApplication>>_cancel_outstanding_orders() should be improved to only cancel orders with any of the possible active statuses. Any order that has already been filled, cancelled, has expired or has been rejected (ie: it is not active) should not be included in the list of orders to cancel. The logic is really in the cancel_all(timeout) in every connector. In several implementations the logic already takes current status into account. That should be extracted and used in all connectors.
> 4 - For the connectors that implement _update_order_status() we might change the logic when a response from the exchange was received for a particular order, but the order is no longer an inflight order.
Currently if the order is not in the inflight list, the response from the exchange is ignored. But I think we should take care of the scenario where we receive a response from the exchange and the order is no longer in the inflight list. If that is the case we might need to request a cancelation to the exchange (it might not be possible to recreate the order and insert it back into the inflight list because we don’t have the required information to recreate the order object in the response from all the exchanges)

* reference issues: #3455 & #3456

3 - Approaches #3 & #4 require changes on all connectors code. Each connector will have a specific issue related to the changes, with Liquidity mining & most used connectors taking priority on implementation

4 - Documentation must be updated to reflect the updates, and connectors to be implemented with the changes to avoid future refactor

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rammwa) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Is this still relevant after v2.1?
