### ISSUE TITLE
Add function to get last trade values to base script

### ISSUE THREAD

**Issue by josseossa** [hummingbot/hummingbot#3493]
**Feature Suggestion**
Include a function that allows to get the information of the last trades in current run a method of the script base, 

**Impact**
This allows to program decisions based on the last buy/sell price and also include a profit or lose register of the current script session
**Additional context**
By having the last trade on buy and having the difference with the last buy I can keep the record of how much I have won/lose in the current sesión and can make the script to decide base on this.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramn3x) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede This has been implemented, correct?

**Comment by cardosofede** [comment]
@MementoRC yeah, get_price_by_type
