### ISSUE TITLE
Raspberry Pi - Incompatibility with update helper script

### ISSUE THREAD

**Issue by jclsn** [hummingbot/hummingbot#3515]
**Describe the bug**
It is not possible to update the docker container's bot by typing ``latest`` nor can you type the latest version e.g. ``version-0.39.1-arm_beta`` manually. The only way to update the bot is to remove the docker container and reinstall it via ``create.sh``.
When typing the version of the currently installed bot ``version-0.39.0-arm_beta`` instead, it just reinstalls that version.

**Steps To Reproduce**
Install deprecated version on Raspberry Pi and try to update via the mentioned method above.

**Screenshots**
![image](https://user-images.githubusercontent.com/19779511/120886420-2515b500-c5ee-11eb-8344-319b672d6c90.png)

**Release version**
version-0.39.0-arm_beta

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramnny) by [Unito](https://www.unito.io)

**Comment by lexahb** [comment]
Hi! As we checked on our end, we were able to upgrade with no issues. Are all the other containers stopped prior to upgrading? If not, please stop them first. Also, use `version-0.x.x-arm_beta` instead of `latest` when asked.

**Comment by glenntomas** [comment]
Hi @coldspark29! I've tried it on my end and `./update.sh` didn't also work. You have to create an instance `./create.sh` and choose `version-0.39.1-arm_beta` to use the latest version.

**Comment by dennisocana** [comment]
This requires modifying the `update.sh` helper script to fix.

**Comment by coldspark29** [comment]
@dennisocana Alright, let me know when you have updated the script and I will be happy to test. I don't update my 10 containers atm, because it is just plain painful to do this every two weeks
