### ISSUE TITLE
Cant add my token for amm_arb

### ISSUE THREAD

**Issue by alexgev** [hummingbot/hummingbot#3543]
I try to add amm_arb with pair with my token and weth on uniswap, i have this pair and my token listed on coingecko https://tokens.coingecko.com/uniswap/all.json and i set this link to ETHEREUM_TOKEN_LIST_URL in gateway-instance configuration process, i also try to create erc20_tokens_override.json, but i also get and error "[PAIR] is not an active market on uniswap"

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rampt9) by [Unito](https://www.unito.io)

**Comment by glenntomas** [comment]
@alexgev Are you using hummingbot source and gateway source? If so, you can modify these files (https://github.com/CoinAlpha/gateway-api/blob/master/src/static/uniswap_route_tokens.json), (https://github.com/CoinAlpha/hummingbot/blob/master/conf/erc20_tokens_override.json). Let us know if it works. Thanks!

**Comment by alexgev** [comment]
i using docker containers with hummingbot and gateway, i attached to containers and i tried to add my token in https://github.com/CoinAlpha/gateway-api/blob/master/src/static/uniswap_route_tokens.json and https://github.com/CoinAlpha/hummingbot/blob/master/conf/erc20_tokens_override.json, restart my containers, but i also get an error 
![image](https://user-images.githubusercontent.com/22056338/121341130-0898b600-c929-11eb-83f2-a124167fe812.png)

**Comment by glenntomas** [comment]
@alexgev Can you please try to use the hummingbot source build and modify these files again
(https://github.com/CoinAlpha/gateway-api/blob/master/src/static/uniswap_route_tokens.json), (https://github.com/CoinAlpha/hummingbot/blob/master/conf/erc20_tokens_override.json).

After that try running these commands on your terminal:
```
cd hummingbot
conda activate hummingbot
./compile
bin/hummingbot.py
```

**Comment by ZgodaRafal** [comment]
Hi @glenntomas 
I try to add my token by updating uniswap_route_tokens.json but I saw you removed the file erc20_tokens_override.json in this commit https://github.com/CoinAlpha/hummingbot/commit/c478acc5257bf458126dc856f8e6154e105426f1

I build from source, have the variable ETHEREUM_TOKEN_LIST_URL with my token inside and I also have the error "is not an active market on uniswap" 
Do you have any solution ?

**Comment by glenntomas** [comment]
@ZgodaRafal Hi! That's correct by adding your token in `uniswap_route_tokens.json`. As per my colleague, you can edit the `ETHEREUM_TOKEN_LIST_URL` that's inside the `conf_global.yml` and enter the URL that your token is listed or make it an incorrect URL (e.g `https://wispy-bird-88a7.uniswap.workers.dev/?url=http://tokens.1inch.eth.linkxxx`). You can also submit a feature request [here](https://github.com/CoinAlpha/hummingbot/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) to make custom token pair for both testnet and mainnet.
