### ISSUE TITLE
Ability to use scripts in Perpetual Market Making

### ISSUE THREAD

**Issue by andrewsiah** [hummingbot/hummingbot#3597]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.
Currently, Pure Market Making supports the addition of script base. I currently use it while adding some technical analysis and have found it to be largely profitable. It'll be great if I can use the script base in perpetual market making as well.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to ...
Instill certain custom logics and behaviors into perpetual market making.

**Additional context**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramqg0) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Scripts can be made with perpetual connectors now, see https://docs.hummingbot.org/scripts/
