### ISSUE TITLE
Add unit tests to Binance connector

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#3642]
Create unit tests for the Binance connector (or exchange).
This unit tests will serve as an example on how to tests connectors for other developers in the community.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramqyg) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
NDAX Unit tests have already been implemented and will be used as examples. This epic and the related stories will be on hold with low priority.
