### ISSUE TITLE
Liquidity Mining Reserved Amounts

### ISSUE THREAD

**Issue by RBennett42** [hummingbot/hummingbot#3647]
**Feature Suggestion**
As a liquidity miner who likes to leverage as much of my allotted inventory as possible using Inventory Skew, I would like to be able to set an amount of either part of a trading pair that inventory skew will not attempt to bid with.

**Impact**
This behavior will allow me to avoid API errors where the exchange on which I am trading. For other users, it will allow them to offer a larger percent of their holdings for liquidity mining without worrying that they will wind up with less than a desired minimum amount of a token.

**Additional context**
KuCoin's API in particular is grumpy about this behavior. In my specific case, inventory skew was attempting to place orders for almost but not quite all of my USDT. These orders were being rejected by KuCoin even though they were for less USDT than I had, and while I am using KCS for transaction fees. In my specific case, setting a minimum of 3 USDT to hold onto would allow me to be confident that my bot stays running even if it gets near the endpoints of my allowed inventory range.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramqzw) by [Unito](https://www.unito.io)

**Comment by cardosofede** [comment]
Hey @RBennett42, you can create a poll in our discord to discuss about this with more community members and create a PRP with the solution
