### ISSUE TITLE
could not fetch balances from Gateway API

### ISSUE THREAD

**Issue by wenchaopeng** [hummingbot/hummingbot#3649]
**Describe the bug**
I ran a spot_perpetual_arbitrage robot. The exchanges I chose were binance and perpetual_Finance, but it didn’t take long for an error:'could not fetch balances from Gateway API', and then the price of perpetual_Finance would not be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/33342928/123743032-3301e180-d8df-11eb-964d-b0d9c837a31d.png)

**Release version**

* hummingbot version: 0.40.0
* Operating System:Ubuntu 20.04.2 LTS

**Attachments**
[logs_conf_spot_perpetual_arbitrage_1.log](https://github.com/CoinAlpha/hummingbot/files/6730909/logs_conf_spot_perpetual_arbitrage_1.log)

```
##########################################
###   Spot-Perpetual Arbitrage strategy config   ###
##########################################

template_version: 2
strategy: spot_perpetual_arbitrage

# The following configuations are only required for the AMM arbitrage trading strategy

# Connectors and markets parameters
spot_connector: binance
spot_market: ETH-USDT
derivative_connector: perpetual_finance
derivative_market: ETH-USDC

order_amount: 0.05

derivative_leverage: 5

# Spread required before first arbitrage can take place, expressed in percentage value, e.g. 1 = 1%
min_divergence: 0.5

# Spread required after first arbitrage before second arbitreage can take place, expressed in percentage value, e.g. 1 = 1%
min_convergence: 0.1

# A buffer for which to adjust order price for higher chance of the order getting filled.
# This is important for AMM which transaction takes a long time where a slippage is acceptable rather having
# the transaction get rejected. The submitted order price will be adjust higher (by percentage value) for buy order
# and lower for sell order. (Enter 1 for 1%)
spot_market_slippage_buffer: 0.1

# A buffer to add to the price to account for slippage when buying/selling on second connector market
# (Enter 1 for 1%)
derivative_market_slippage_buffer: 0.1

# A flag (true/false), if true the bot would only execute second arbitrage once funding payment is received provided second arbitrage wasn't executed before funding period.
maximize_funding_rate: false

# cool off period between arbitrage cycles
next_arbitrage_cycle_delay: 120

```

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramr05) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Hi @wenchaopeng, I happened to noticed the same error on our long term testbots `Could not fetch balances from gateway API` and tried to check both client and gateway logs. The closest I can think of is gateway failing to get the balances on Perp_fi server thats why we are getting the error. 

Just checking if you can try to run another test and provide me your client and gateway logs? I assume you are running docker and the gateway logs should be on the same hummingbot_logs folder. See sample below:
![image](https://user-images.githubusercontent.com/73840223/131819119-73885659-9ccc-478d-a3b8-b221afd0e31c.png)

**Comment by HFLeon** [comment]
strategy "uniswap_v3_lp" Also got the same error
