### ISSUE TITLE
BitMEX Perpetual Connector

### ISSUE THREAD

**Issue by dennisocana** [hummingbot/hummingbot#3662]
Build new BitMEX perpetual connector targeted to release this August (v0.42) or September (v0.43).

Official site: https://www.bitmex.com/
API docs: https://www.bitmex.com/app/apiOverview
Perpetual contracts guide: https://www.bitmex.com/app/perpetualContractsGuide

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramr5c) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Bitmex perpetual connector has been added
