### ISSUE TITLE
Create a `pause` and `resume` command

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3668]
## What must be implemented
With a `pause` command, the bot must cancel the current orders (except for hanging orders) and stop creating new orders, but all other (hanging orders refresh, calculation of indicators like volatility should continue to happen in the background) 

After typing `resume` the orders would start to be created again.

## Definition of done

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramra8) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Pause and resume feature has been removed https://github.com/hummingbot/hummingbot/pull/6008
