### ISSUE TITLE
Add unit tests for BinanceTime

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#3673]
As a developer I need that the functionality provided by the class BinanceTime is covered by unit tests. The tests should avoid connecting or interacting to external systems, in order to be run as part of the GitHub validation suite.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramrhu) by [Unito](https://www.unito.io)

**Comment by petioptrv** [comment]
@aarmoa If no one has started on this, I'd like to take it on
