### ISSUE TITLE
Add unit tests for functions in binance_utils module

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#3674]
As a developer I need that the functionality provided by the binance_utils module is covered by unit tests. The tests should avoid connecting or interacting to external systems, in order to be run as part of the GitHub validation suite.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramrje) by [Unito](https://www.unito.io)

**Comment by aarmoa** [comment]
As a developer I need that the functionality provided by the binance_utils module is covered by unit tests. The tests should avoid connecting or interacting to external systems, in order to be run as part of the GitHub validation suite.

**Comment by petioptrv** [comment]
I can add tests for this (and `binance_perpetual_utils`) to my PR #3634. Currently, the two paths not tested are the special pairs path and the failing-to-parse-a-pair path.
