### ISSUE TITLE
AscendEx - Order books not updated when number of markets is over 10

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#3702]
**Describe the bug**
When running a strategy where over 10 Ascend EX order books are loaded, e.g. Liquidity Mining strategy, none of the order books gets any updates and the strategy continues trading on the static order books .

**Steps To Reproduce**

* Create a Liquidity Mining strategy on Ascend Ex
* Config markets to any 11 trading pairs
* Start the strategy
* Run `orderbook --market XXX-YYY` where XXX-YYY is any loaded market 
* Notice that the order book never changes

![image](https://user-images.githubusercontent.com/37262506/124893472-57f80200-e00d-11eb-972c-5d6b3c70436c.png)

Note:
When debug the connector on `hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py` , you can see an error message returned from Ascend Ex, but the bot doesn't raise nor log the error. 

![image](https://user-images.githubusercontent.com/37262506/124894500-4a8f4780-e00e-11eb-8b82-409fcb73d7f9.png)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramrw8) by [Unito](https://www.unito.io)

**Comment by johndainy** [comment]
This user (**VuQuach#7599**) also reported that the orderbook/mid price are not being updated(at least for a while) so the order are getting in and out eligible spread of the actual price(display says they are within spread of the incorrect mid price) when using 10+ bits. He have13 pairs when it wasn't working, with 8 it does.

**Comment by CrimsonJacket** [comment]
According to AscendEx [documentation](https://ascendex.github.io/ascendex-pro-api/#how-to-subscribe), they implement a limit of 10 markets per connection.

**Comment by rapcmia** [comment]
Closing ticket, as per Ascendex docs it can only limit up to 10 markets per connection
![image](https://user-images.githubusercontent.com/73840223/155658906-b085dc0f-2d38-48aa-bc14-00ddfd8d916c.png)
