### ISSUE TITLE
FTX US Connector

### ISSUE THREAD

**Issue by moesy** [hummingbot/hummingbot#3709]
**Describe the bug**
The FTX Connector does not currently support FTX.us

**Steps To Reproduce**
Here are the steps to reproduce the issue:
1. connect hummingbot to the FTX exchange
2. Enter api Keys
3. There should be an additional flag asking users if they want ftx.com or ftx.us

**Other***
I believe ftx.us and ftx.com have the same API structure. The only  change that should be needed to make this work is using ```ftx.us``` v.s. ```ftx.com``` as the hostname based on user setting. A small subset of users may need to connect to both at the same time however that is probably  unlikely.

**Comment by dennisocana** [comment]
@moesy thanks for the suggestion. This is not a bug but a feature/connector request i.e.it needs to be created similar to our Binance and Binance US connectors.

**Comment by josh-cogburn** [comment]
I can't connect to FTX.US and this feature has been sitting on the back burner for several months now.

**Comment by nikspz** [comment]
FTX will be removed as a connector in 1.10.0 Release, the PR to delete already pushed to development https://github.com/hummingbot/hummingbot/pull/5893
