### ISSUE TITLE
Setting the Bid/Ask orders to open as Stop Limit

### ISSUE THREAD

**Issue by TimaTiGo** [hummingbot/hummingbot#3724]
Is it possible to edit the Perpetual Market Making strategy to make the bid/ask orders open as Stop Limit instead of Limit and Market (on Binance)?
This modification will allow trading the trend since buying will be above the mid price and vice-versa, I know it is risky but I want to try it
My coding skills are not great and when I tried to edit the source files the bot crashed because the PMM strategy failed to load, if someone can give me a hint where to start I'll be thankful.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramt29) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
This is possible to be created using https://docs.hummingbot.org/scripts/ 
Also, You might like to check our https://docs.hummingbot.org/botcamp/ hummingbot's official training course 🙇🏼
