### ISSUE TITLE
Liquid - Error parsing the trading_pair rule

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#3751]
**Describe the bug**
Getting an `Error parsing the trading_pair rule` upon starting the bot when running a pure market making or avellaneda market making strategy using Liquid. Currently I don't see any impact with the bot's perfomance, creating a ticket for tracking purposes.

![](https://user-images.githubusercontent.com/64377055/126110631-729493e7-9039-46ad-9aa3-5a3f407681f9.png)

```python
2021-07-19 04:49:54,068 - 16965 - hummingbot.connector.exchange.liquid.liquid_exchange - ERROR - Error parsing the trading_pair rule None. Skipping.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/liquid/liquid_exchange.pyx", line 506, in hummingbot.connector.exchange.liquid.liquid_exchange.LiquidExchange._format_trading_rules
    min_order_size = rule.get("minimum_order_quantity")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Steps To Reproduce**

1. Create and run a pure market making or avellaneda market making strategy using Liquid

**Release version**
v0.41.0

**Attachments**
Logs and config: [liquid.zip](https://github.com/CoinAlpha/hummingbot/files/6838358/liquid.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramtbm) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
It seems that the issue is affecting the display for the order_amount since there is an issue getting the trading rule, the amount is immediately labelled as adjusted amount instead of original amount:
![image](https://user-images.githubusercontent.com/57189990/136136355-ade92981-948d-4698-aa1e-3c0f0289f682.png)

**Comment by rapcmia** [comment]
Connector not supported
