### ISSUE TITLE
Hide extra logging messages for orders that are below exchange minimum

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#3774]
**Feature Suggestion**
Hide extra logging warning messages when submitting an order that is below the exchange minimum allowable trade size. For example: 
![image](https://user-images.githubusercontent.com/57189990/126582459-73cd20fc-973d-4cdb-8a94-1fd188a97a12.png)
This behavior currently occurs on the following connectors:

* Ascendex
* Digifinex
* Gate.io
* Coinbase
* KuCoin 

**Impact**
This will reduce clutter in the status window and reduce storage usage for the logs.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramtt8) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Although I think this error message is useful, I agree that repeatedly displaying this on every cycle is not good for UI/UX. A better way would be to display this error message only once, during the first attempt to create orders.

For example:

Cycle 1 - Order is too small. Display "Error submitting order to exchange" in logs
Cycle 2 - If order in the current and previous cycle is too small, do not display error message
