### ISSUE TITLE
FTX Perpetual

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#3819]
## Details
Exchange Link: https://ftx.com/
API documentation: https://help.ftx.com/hc/en-us/articles/360028807171-API-docs

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramue2) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Several developers from the community have reached out to express their interest in building this connector and we may no longer do this task ourselves. We will reopen if needed.

**Comment by dennisocana** [comment]
We plan to support this connector in the next 3-6 months.

**Comment by nikspz** [comment]
Closed that issue as FTX (and FTX perpetual) going to be removed as connector in 1.10.0 Release
