### ISSUE TITLE
Spot Perpetual Arbitrage -  spot limit order not being filled when price moves quickly

### ISSUE THREAD

**Issue by JK5768** [hummingbot/hummingbot#3831]
Using the Spot Perpetual Arbitrage strategy a spot limit order is placed while at the same time a futures market order is placed. The issue with this is that sometimes the limit order is not filled as the price moves away quickly and then the bot can get stuck for a long period waiting for the limit order price to be reached again (which could potentially never happen). The futures market order is filled though immediately. The end result could be a very negative position left open.

**Steps To Reproduce**
Configure spot perpetual arbitrage then start strategy and leave bot running.

**Release version**
0.41.0

[logs_unfi_spot_perpetual_arbitrage.log](https://github.com/CoinAlpha/hummingbot/files/6907086/logs_unfi_spot_perpetual_arbitrage.log)

[unfi_spot_perpetual_arbitrage.txt](https://github.com/CoinAlpha/hummingbot/files/6907106/unfi_spot_perpetual_arbitrage.txt)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramuhm) by [Unito](https://www.unito.io)

**Comment by kevin9733** [comment]
I also have the same problem there is a way to configure only market orders?

**Comment by kevin9733** [comment]
or else add an exception that says if the limit order is not executed after 1 s to send a market order

**Comment by nikspz** [comment]
hi @kevin9733 I don't think that we have that feature now.
You may submit a feature request for this on our Github page - https://github.com/CoinAlpha/hummingbot/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=
Or you may vote for this one to give it more priority:
Please check this blog about vote for bugs to help hummingbot improve performance in the future
https://hummingbot.io/blog/2021-06-help-us-improve-hummingbot-vote-for-bugs

**Comment by rapcmia** [comment]
Hi @JK5768 we recently release version 0.45.0 and made some changes as well for spot-perpetual-arbitrage on previous versions, just checking if you have tried it again and still experience the same issue? Thank you

**Comment by rapcmia** [comment]
Hi, @JK5768 we have not received any response since the last comment regarding the issue for Spot Perpetual- Arbitrage. Please be advised that there have been improvements added to the strategy on our latest version which is 0.46.0 that could fix the reported issue. We'll be tagging this ticket as resolved, please feel free to comment or open a ticket if found any issues. Thank you
