### ISSUE TITLE
Balance limit improvement

### ISSUE THREAD

**Issue by leastchaos** [hummingbot/hummingbot#3835]
**Feature Suggestion**
Improve balance limit such that it is based on total base/qoute asset value in base asset, or maybe just in USDT terms.

**Impact**
Usually we want to fixed a certain portion of our balance to a certain market. 
e.g when you use "balance limit ascend_ex usdt 100" at the start with no ETH on a market ETH-USDT. 
The bot would only entered some trade until you got 100usdt worth of ETH. 
if you stop and start the bot at this point, the bot would enter a sell of 100usdt of ETH and another buy of 100usdt.
The total amount would be 200usdt. 

It would be much better if we could fixed the total balance to be at 100USDT so that whenever we make a change in the config of the bot that require stop and start, we do not need to make sure the qoute is 0 or manually recalculate the balance we need each time 

**Additional context**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramumd) by [Unito](https://www.unito.io)

**Comment by fallenangel3k** [comment]
I agree to you, should be implemented.
