### ISSUE TITLE
XEMM - Failure to complete taker trades between Kucoin and Binance

### ISSUE THREAD

**Issue by bsmeaton** [hummingbot/hummingbot#3849]
**Describe the bug**
When using the Cross exchange market making strategy with Kucoin as maker market and Binance as Taker market during periods of volatility within trading binance can often fail to place orders. The strategy does not seem to allow for repeated atempts to fill market order trades on the taker side if the order does not complete.

In addition to this and specifically when using kucoin and binance taker trades during these times are placed as limit orders on the taker side rather than market orders, which leaves the limit order open for long periods of time and can often go unfilled.

**Steps To Reproduce**
During periods of volatility on pairs such as FRONT/BTC placing market orders on binance will produce an error message on the app/ website of "price changes/volatility are too high to place trade", or something similar.

The use of the XEMM strategy with FRONT/BTC between Kucoin(as maker) and Binance(as taker) during periods of volatile trading will at times lead to a failure of the taker trade filling after then maker trade has filled.

The use of the XEMM strategy with FRONT/BTC between Kucoin(as maker) and Binance(as taker) during periods of volatile trading will at times lead to taker trades being placed as limit orders rather than market orders. This is shown in the attachment binancelimit.txt which shows after a limit order has been filled on the maker side the strategy then creates a limit order on the taker side (Instead of a market order).

Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up your configuration file with these parameters: Standard XEMM setup with FRONT/BTC, Kucoin as maker, binance as taker2.
1.  Start the bot using this command: start?
1. Wait a few days or weeks with bot running and inventories which should remain exactly balanced each side of market will be come skewed due to failure of some taker orders.

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.41.0
**Attachments**
Attached config and log file snippet showing limit orders being produced
[binancelimit.txt](https://github.com/CoinAlpha/hummingbot/files/6929146/binancelimit.txt)
[conf_xemm_1.txt](https://github.com/CoinAlpha/hummingbot/files/6929147/conf_xemm_1.txt)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

bensmeat

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramuth) by [Unito](https://www.unito.io)

**Comment by cali-tomas** [comment]
Hi @bsmeaton, Thank you for sharing this. Our team will run a testbot and try to replicate the issue. May I know what build of bot you are using? (binary, source, Docker)

**Comment by bsmeaton** [comment]
Hi I am running on RPi 4 on Docker

**Comment by leastchaos** [comment]
I have the same issue using Ascendex and binance, binance taker orders sometimes does not fill,

**Comment by gerald-hb** [comment]
Hello @bsmeaton Is this particular with FRONT-BTC or any pair? I will try to run a testbot on another pair and see if we can replicate the same issue.
@leastchaos Can you also share your `config` and `logs`?

**Comment by bsmeaton** [comment]
No this is on all kucoin pairs. Config and log files already uploaded

**Comment by bsmeaton** [comment]
![image](https://user-images.githubusercontent.com/11870584/128591052-5453cdd0-c8a0-41f4-ab3f-c55ec23bbe17.png)

This issue appears to be linked to the quantity of order placed on the taker side, if the order is too large and the volatility too great binance will fail to place the order (the screenshot shows a failure to place a manual market order through app). For the FRONT pairs an taker order size of at least 1000 Front would be needed to replicate this issue during market volatility.

**Comment by gerald-hb** [comment]
@bsmeaton Can you share your latest `logs` so we can check?

**Comment by leastchaos** [comment]
hello @gerald-hb, please ignore my comment, different issue from this.

**Comment by cryptorevizor** [comment]
[logs_tron_xemm.log](https://github.com/CoinAlpha/hummingbot/files/7123717/logs_tron_xemm.log)
the same problem with binance and ascendex

**Comment by cryptorevizor** [comment]
please ream more in discord https://discord.com/channels/530578568154054663/884861311102627871
in Support - cross exchange market making thread 07 of September

**Comment by bsmeaton** [comment]
I've recently moved from running on Raspberry Pi to AWS and this problem happens far less. I assume it may be related to slow internet speed or processing on my RPi even so I feel the code should check that taker has completed successfully and repeat the taker trade process if not.

**Comment by bsmeaton** [comment]
Docker, but the issue is due to the placing of limit orders at the market price rather than a true taker order on the XEMM strategy. These don't always immediately get filled. A possible solution is using a 'slippage buffer' ie adjust the limit price for the taker trade by say 1% to make sure they definitely get filled. Would really appreciate this being implemented.

**Comment by rapcmia** [comment]
Hi @bsmeaton good day,
There have been changes on Cross-Exchange MM on past Hummingbot release with addition of `slippage buffer` to its current configuration. We would like to know if this is still an ongoing issue for you? Thank you

**Comment by bsmeaton** [comment]
Hi

The completion of taker trades on the strategy is still fairly unreliable
with frequent manual balancing (A few times a week, required)

Kind regards

Ben

**Comment by leocape** [comment]
@bsmeaton does that still happen for you even if you set a large slippage buffer of say 20%?
