### ISSUE TITLE
OKEx - Filled order getting logged twice on client

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#3862]
**Describe the bug**
Similar to issue #3317, while doing some tests with OKEx, the filled trade got logged twice after restarting the strategy. However, if you check the trade history from the exchange, only one filled record is available. This also provides wrong info for the aggregated data in datadog since the information send is duplicated.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Run a pure market-making strategy and wait for an order to get filled.
1. Once a fill happens, immediately stop the strategy. In my case, I stopped the bot when I got the last confirmation message `okex_exchange - The SELL OrderType.LIMIT_MAKER order ID has completed according to order delta websocket API.`
1. Configure your market to another strategy or start the strategy a few seconds from stopping.
1. Check the log pane and it will return the previous filled message.
1. Run `history --verbose` to check if the same trade has been re-logged.

...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/128456291-929ae10d-090d-4900-8b34-db31af2e31d6.png)
![Okex-trade-history](https://user-images.githubusercontent.com/57189990/128456312-1eb30e39-f850-43c9-802f-633859701575.png)
![aggregated data](https://user-images.githubusercontent.com/57189990/128456647-f1127b86-8922-4f3b-b335-b9b8b859ec27.gif)

**Release version**
0.41.0

**Attachments**
[logs_conf_pure_mm_3.log](https://github.com/CoinAlpha/hummingbot/files/6943016/logs_conf_pure_mm_3.log)
[sqlite and csv.zip](https://github.com/CoinAlpha/hummingbot/files/6943024/sqlite.and.csv.zip)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramuxv) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Tested but unable to replicate. The ticket closed for now and will reopen if happens again
