### ISSUE TITLE
Pure MM - Fails to accurately detect available balance and only creates order on one side

### ISSUE THREAD

**Issue by petioptrv** [hummingbot/hummingbot#3951]
**Describe the bug**
During QA testing of #3946, it was observed that PMM will sometimes create orders only on one side while nothing should be preventing it from creating both sides (see the video at the end of the this [comment](https://github.com/CoinAlpha/hummingbot/pull/3946#issuecomment-900230673)). Looking at the log output, the orders were all successfully cancelled, but the exchange then received a request to place orders only on one side. The supposition is that the orders are filtered in pmm's `c_tick` method, and most-likely in `c_apply_budget_constraint`, which will filter orders out silently (no logging).

**Steps To Reproduce**
Create a multi-level PMM strategy on NDAX and let run.

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
dev-0.43.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramzje) by [Unito](https://www.unito.io)

**Comment by rxlxrxsx** [comment]
Adding screenshots to the ticket for reference. With order levels set to 2 it should create 2 orders on both sides but there are instances that it only creates a set of orders even with enough balance.

<img width="1421" alt="Screen Shot 2021-08-23 at 1 02 58 PM" src="https://user-images.githubusercontent.com/64377055/130393529-5c004b52-55da-42ba-b438-3280b4fa52a2.png">
<img width="1423" alt="Screen Shot 2021-08-23 at 1 03 16 PM" src="https://user-images.githubusercontent.com/64377055/130393543-0dc89626-3743-4d74-837b-f2186d94fa8e.png">

**Comment by rolandgem** [comment]
any updates on this ? @dennisocana
