### ISSUE TITLE
Implement `gateway create` command in Hummingbot

### ISSUE THREAD

**Issue by martinkou** [hummingbot/hummingbot#4139]
## Why
See the Hummingbot Setup Experience section of https://www.notion.so/hummingbot/First-Time-User-Experience-6efacde002604881b81b079352d6845e

## What
1. Add a `gateway create` command, that does the following:
  1. Check whether there's an existing gateway configuration. If yes - ask whether to erase the existing gateway configuration (along with the existing Docker container if there's one). If not, proceed to the next step.
  1. Check whether Docker is available in the current operating environment. If not, print an error telling the user to install Docker for his OS. Otherwise, proceed to the next step.
    1. Assumes that user installs Gateway Docker
    1. Gateway from source is a separate flow
  1. Check, and create if not existing, the SSL certificates for both Hummingbot and gateway.
    1. Ask for the SSL private key passphrase for creating the SSL certificates.
    1. Store the passphrase in password encrypted format on Hummingbot config side.
    1. Store the passphrase in a plain text file with `0600` permissions on gateway config side.
  1. Ask for the Infura API key, or Ethereum node URL from user
    1. Think about users should add other chains after Ethereum
      1. Infura: ask for infura key, use infura bool?, RPC URL if not infura (accommodate other providers besides Infura like Alchemy, etc?)
      1. Michael Feng will propose schema
      1. Handling WS: can't parse it from URL. If you ask users for provider name and key, it's easier to handle different chains, etc
  1. Check, and create if not existing, the Docker container for running Hummingbot gateway.
  1. For setup questions - whenever reasonable defaults are available (e.g. use main net for Ethereum, auto-calculate names for Docker containers, etc.), the setup prompt should just use the default without asking the user. Only essential parameters like Infura API key and SSL certificate passphrase should need user intervention. If the user wants to change other detailed parameters, e.g. he wants to switch to Kovan, he should use `gateway config`.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran3q0) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
Task will be broken down into 6 smaller tasks (i - vi). points estimation will be callet to each separated task.

- How to make clear inside the client that progress is being made (bot is not frozen)? - Possibly use log pane
- pass docker information directly to the client
