### ISSUE TITLE
Add help messages for all `gateway` commands

### ISSUE THREAD

**Issue by martinkou** [hummingbot/hummingbot#4142]
## Why
See the "Hummingbot Setup Experience" section of https://www.notion.so/hummingbot/First-Time-User-Experience-6efacde002604881b81b079352d6845e

## What
* Add help messages for all gateway commands.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran3tn) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
Need specification of what must be added to the help messages.
- gateway create
- gateway status
- gateway config
(any extra commands that exists)

**Comment by Nullably** [comment]
* There is an outstanding bug on client where `--help` doesn't work on any command - #4915 
* Each config should have its own help message, one way to do this is to add a `description` field for each config in its config json schema files. Then we'll need to publish this on `/config` route.
* The client will then display this help message somehow, we need to specify the `how` here. 
* At 2, this story is likely underestimated.
