### ISSUE TITLE
Update the Kraken throttler rate limits to decay-based

### ISSUE THREAD

**Issue by petioptrv** [hummingbot/hummingbot#4178]
As a Kraken connector user, I want to use the entirety of API calls available for my account subscription.

## Details
The Kraken API uses [decay-based](https://docs.kraken.com/rest/#section/Rate-Limits/REST-API-Rate-Limits) rate limits rather than sliding time window ones. Currently, the Kraken connector limits API calls to 20 per minute, but if a user has a Pro account, they should be able to perform a 20-requests burst in one second and then perform one request for each of the 59 remaining seconds in that minute window, assuming we start from a baseline of zero requests. So, the user should be able to perform 79 requests in a minute if those requests are spread out as previously described. 

The frequency of the polling loop in the connector was set to 30s. This task includes investigating if we can increase that frequency while remaining in the capacity of the basic account tier.

## Definition of Done
* [ ] The Kraken connector is updated to use the decay-based schema according to the Kraken documentation.
* [ ] ~The Kraken connector is updated to request the account tier from the user and then dynamically set the rate-limits according to the tier.~
* [ ] ~The Kraken connector sets the `retry_interval` of the `AsyncThrottler` to the appropriate given the account tier.~
* [ ] Check if the polling loop frequency can be increased while remaining within the capacity of the basic account tier.

Edit: the tier-related points were moved into a separate task (#4254)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran4m6) by [Unito](https://www.unito.io)

**Comment by aarmoa** [comment]
I think we need to make this part of #4163. Without the inclusion of the decaying throttler in Kraken connector QA will not be able to test the changes in the throttler.

**Comment by dennisocana** [comment]
After our recent discussion, we agreed to create both PRs and merge them into an epic branch where QA can test it when both tasks have already been completed.

**Comment by dennisocana** [comment]
Refer to this comment: https://github.com/CoinAlpha/hummingbot/issues/4163#issuecomment-925360622
