### ISSUE TITLE
Fix the Kraken connector's `_user_stream_event_listener` loop

### ISSUE THREAD

**Issue by petioptrv** [hummingbot/hummingbot#4208]
# Description
Currently, the `_user_stream_event_listener` loop does not listen for `"openOrders"`, although the `KrakenAPIUserStreamDataSource` requests that update from the websocket connection. This means that the exchange only updates order status in the `_status_polling_loop`.

In addition, because the `KrakenInFlightOrder.update_with_trade_update` does not update the order's status, the only event we can emit in the `_user_stream_event_listener` function is a `OrderFilledEvent` because the line 

```Python
455    async def _user_stream_event_listener(self):
[...]
483                        tracked_order.update_with_trade_update(trade)
[...]
496                        if tracked_order.is_done:  # always false
```

will always return `False`.

~PR #4180 sets `last_state` to `"new"` in order to avoid the scenario where the order is created and cancelled in between polling loop runs, in which case the order will be considered as "local". This "new" state should be removed here and we should only rely on ws status updates.~

# Definition of Done
* [ ] The `_user_stream_event_listener` now processes `"openOrders"` events.
* [ ] The `_user_stream_event_listener` emits events on order filled and cancelled.
* [ ] ~The reliance on `last_state="new"` is removed in `KrakenInFlightOrder`.~
* [ ] All executions paths of the `_user_stream_event_listener` are covered by test cases.

Edit: The "new" state will remain for the reasons outlined in @aarmoa's comment below.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran59e) by [Unito](https://www.unito.io)

**Comment by aarmoa** [comment]
According to the code in kraken_exchange.pyx this exchange processes requests synchronously. As soon as they process the "create order" request they include the exchange request id as part of the response. That means that all in flight orders, that are created with an initial state of "NEW" as @petioptrv mentions in the description, should be updated to the proper state before the logic of `execute_buy` or `execute_sell` finish running. What I am trying to say is that the idea of correctly updating order status based on events received by websocket is great, but marking the orders as "no longer only local" should not depend on the updates coming from the websocket.
