### ISSUE TITLE
Prototype Avalanche/Pangolin connector

### ISSUE THREAD

**Issue by mifeng** [hummingbot/hummingbot#4232]
# Why
Gateway V2 is designed to let external devs add connectors to 1) other EVM compatible protocols and 2) other Uniswap-style AMM exchanges relatively easily by inheriting from the Ethereum and Uniswap base classes.

Before we finalize the design of Gateway V2, we should prototype adding another EVM-compatible chain + DEX in order to confirm that the design works. Since Ava Labs has commissioned us to build a connector to Avalanche/Pangolin, we should use that for the prototype.

# What
Build a prototype connector to Avalanche/Pangolin with the same API structure as ETH/Uniswap:

* Create Avalanche service
* Create Avalanche routes
* Create Pangolin service
* Create Pangolin routes
* Add Pangolin to client Gateway connector

Since the goal is to confirm that Gateway V2 architecture is suitable for multiple chains, focus on getting the basic functionality supported and highlighting any design changes needed. Tests, documentation, etc can come later.

Avalanche reference:
https://www.notion.so/hummingbot/Avalanche-research-d2b5523a2e1a46f48ea942d9e5ab89a1

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran64v) by [Unito](https://www.unito.io)

**Comment by HariSeldon23** [comment]
Hi @mifeng,

Thanks for creating this issue. I'm from the Pangolin team and would love to help however we can.

**Comment by phbrgnomo** [comment]
Hey there @HariSeldon23. can you reach me out on our Discord to talk about the singularities of the Pangolin Porotocol?
@phgnomo#1429 is my discord handle
