### ISSUE TITLE
Hanging orders disappear intermittently on KuCoin

### ISSUE THREAD

**Issue by mbadran** [hummingbot/hummingbot#4307]
When Hummingbot attempts to recreate hanging orders on the KuCoin connector/exchange, this operation sometimes fails. This causes hanging orders to intermittently disappear, which results in unbalanced trading pairs, and ultimately, trading losses.

There is no obvious reason for these failures to happen, and there are no helpful clues in the logs. The hanging orders can technically be filled, so it does not seem like the root cause is an exchange error.

**Steps To Reproduce**

1. Set up the KuCoin connector
1. Set up a pure market making bot on any current campaign.
1. Enable the `hanging_orders_enabled` setting
1. Execute one or more buy orders (for a quick fill, use a low `bid_spread` from the `best_ask` `price_type`)
1. Wait for the corresponding hanging sell order(s) to be created
1. Watch the strategy logs as the hanging sell order is regularly cancelled and recreated
1.  Wait/search for this error: `hummingbot.connector.exchange.kucoin.kucoin_exchange - NETWORK - Error submitting sell limit_maker order to Kucoin`

In my case, when the error occurs, I have repeatedly checked that I have enough of the `order_amount` to sell on the exchange, and I can manually enter the trade in the KuCoin trading console.

(As an aside, it's unfortunate that the KuCoin connector doesn't reveal the failure reason, only an `OrderCancelledEvent` and `MarketOrderFailureEvent`. The code assumes that an order will be successfully created and performs a dictionary lookup for the order ID. When that fails with a `KeyError` exception, the root cause is masked. If you can improve the error handling for order creation, that would be a very welcome enhancement to the connector.)

Thanks for investigating!

**Screenshots**

![missing!UNITO-UNDERSCORE!ho!UNITO-UNDERSCORE!bot!UNITO-UNDERSCORE!view](https://user-images.githubusercontent.com/13339/135030245-ecc38f28-0bd7-48a3-b1b9-c62b8d4d63c9.png)
![missing!UNITO-UNDERSCORE!ho!UNITO-UNDERSCORE!log](https://user-images.githubusercontent.com/13339/135030253-4cda61c2-a8d5-4154-91a7-ea28552e2774.png)

**Release version**

0.43.0 (on Raspberry Pi, Docker image `version-0.42.0-arm_beta`)

**Attachments**

[dyp-eth-2.yml.txt](https://github.com/CoinAlpha/hummingbot/files/7241402/dyp-eth-2.yml.txt)
[logs_dyp-eth-2.log](https://github.com/CoinAlpha/hummingbot/files/7241379/logs_dyp-eth-2.log)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran7j1) by [Unito](https://www.unito.io)

**Comment by gerald-hb** [comment]
I have run some test on my end and I was not able to encounter the same issue/error.
![image](https://user-images.githubusercontent.com/84826167/135038226-1d0d22a6-5b7c-4726-bafe-a20bb84802ac.png)
[configpuremm5.txt](https://github.com/CoinAlpha/hummingbot/files/7241846/configpuremm5.txt)
[logs_conf_pure_mm_5.log](https://github.com/CoinAlpha/hummingbot/files/7241847/logs_conf_pure_mm_5.log)

I'll check with other support if they will be able to replicate this issue.

**Comment by mbadran** [comment]
@gerald-hb Thanks for jumping on this so quickly.

The failure is intermittent in my testing. I've been watching the logs for a couple of days and it definitely doesn't happen right away for me. If you trawl through the log I attached, you'll see that the hanging sell order is successfully recreated several times (with different IDs) earlier on / higher up in the file, and then the error eventually occurs on line 4987.

Any chance we can add some verbose logging and improve error handling for this connector? Or does the KuCoin API not provide enough detail in the error responses?

**Comment by gerald-hb** [comment]
I think I was able to replicate this on my end (I re-run another test using rpi docker build 0.43)
[rpiconfmm.txt](https://github.com/CoinAlpha/hummingbot/files/7243450/rpiconfmm.txt)
[rpilogs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/7243452/rpilogs_conf_pure_mm_1.log)
![image](https://user-images.githubusercontent.com/84826167/135077451-c0a5be16-ab6f-4264-a065-b35a2542e255.png)
I got some info from my colleague that this Keyerror:Data is related to your `balance`. By any chance, do you have any other bots that are running on the same Market and token?

**Comment by mbadran** [comment]
In this particular case (DYP-ETH), I don’t have other bots using the same quote or base currency.

I highly doubt that this error is related to the balance. As I mentioned, I had enough DYP to cover the sale. And if you check the log and the bot’s screenshot, you’ll see that after the hanging order disappeared, another (regular, not hanging) sell order for the same DYP amount was successfully created.

I know this error also appears on buy orders when there’s a low balance, but from looking at the code, this error is produced by a dictionary lookup on a non-existent order ID, which is the result of failing to place an order, but the root cause for that failure may or may not be the low balance — there could be other reasons for the failure (eg. a bad request of some form).
