### ISSUE TITLE
Dexalot

### ISSUE THREAD

**Issue by dennisocana** [hummingbot/hummingbot#4334]
Dexalot is built on Avalanche platform’s C-Chain technology for its implementation as it offers the following advantages:

* 100% compatibility with the mature Ethereum Virtual Machine technology
* Transactional speeds with 1-2 second finality
* Transactional throughput that can withstand thousands of transactions per second
* Low cost of deployment and operation

Source: https://www.reddit.com/r/BlockChain/comments/p1bj2r/dexalot_decentralized_exchange_powered_by/

Exchange URL : https://app.dexalot-test.com/ (testnet)
API Documentation : 
Type of Exchange : DEX

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran84m) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment]
Added in 1.14.0
https://hummingbot.org/release-notes/1.14.0/#new-clob-dex-connector-dexalot
