### ISSUE TITLE
Bybit Spot Exchange

### ISSUE THREAD

**Issue by dennisocana** [hummingbot/hummingbot#4338]
Established in March 2018, Bybit is one of the fastest growing cryptocurrency derivatives exchanges, with more than 1.6 million registered users. Built on customer-centric values, we endeavor to provide a professional, smart, intuitive and innovative trading experience for retail and professional clients around the world. Bybit is committed to creating a fair, transparent and efficient trading environment, and offer 24/7 multi-language customer support to provide assistance in a timely manner.

Derivatives products currently offered on the Bybit platform are inverse perpetual contracts (BTCUSD, ETHUSD, XRPUSD, EOSUSD), linear perpetual contracts (BTCUSDT, ETHUSDT, BCHLINK, LINKUSDT, LTCUSDT, XTZUSDT, ADAUSDT, DOTUSDT, UNIUSDT) and inverse futures contracts (BTCUSD quarterly).

Source: https://coinmarketcap.com/exchanges/bybit/

Exchange URL : https://www.bybit.com/en-US/trade/spot/
API Documentation : https://bybit-exchange.github.io/docs/spot/#t-introduction
Type of Exchange : Spot

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran865) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Not doing for now since it's a new exchange limited to only five pairs.

**Comment by rapcmia** [comment]
Bybit spot connector has been added
