### ISSUE TITLE
Status - Unable to display status output on Windows source and binary build

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#4339]
**Describe the bug**
While testing TWAP on the staging branch (dev-0.44.0), the bot was able to create/cancel orders according to config however when checking the `status` it returns an error of `Unhandled error in background task: Python int too large to convert to C long`

```
2021-09-30 15:54:09,423 - 15660 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Python int too large to convert to C long
Traceback (most recent call last):
  File "C:\Users\Ralph\github\staging\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\staging\hummingbot\client\command\status_command.py", line 137, in status_check_all
    self._notify(await self.strategy_status())
  File "C:\Users\Ralph\github\staging\hummingbot\client\command\status_command.py", line 81, in strategy_status
    st_status = self.strategy.format_status()
  File "C:\Users\Ralph\github\staging\hummingbot\strategy\twap\twap.py", line 168, in format_status
    df = LimitOrder.to_pandas(active_orders)
  File "hummingbot\\core\\data_type\\limit_order.pyx", line 43, in hummingbot.core.data_type.limit_order.LimitOrder.to_pandas
    long now_timestamp = int(time.time() * 1e6) if end_time_order_age == 0 else end_time_order_age
OverflowError: Python int too large to convert to C long
```

Tried to reinstall and change the rate_oracle_source and global_token (from USD to USDT) but still getting the same error. The issue does not happen on Windows docker and Mac's src/docker build. 

**Steps To Reproduce**

1. Create TWAP strategy
1. Disable `is_time_span_execution` (optional if you want to enable it)
1. Wait for the bot to create orders and crosscheck them on the connector
1. Once you are sure that orders match, run the status command

**Screenshots**

Windows binary
![status not working](https://user-images.githubusercontent.com/73840223/135417155-def0bdf5-24a6-4a21-bff4-8139da3888e2.PNG)

Windows source build
![status not working](https://user-images.githubusercontent.com/73840223/135417300-1bc28878-7ddf-493c-9a66-bb95d11334bb.PNG)

**Release version**
dev-0.44.0

**Attachments**
[twap.zip](https://github.com/CoinAlpha/hummingbot/files/7258018/twap.zip)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran86w) by [Unito](https://www.unito.io)

**Comment by cali-tomas** [comment]
I am getting the same error when trying to check the `status` this is on XEMM strategy
![image](https://user-images.githubusercontent.com/85161223/135741557-3e9e99fd-1dee-4a21-887e-4307a28cc881.png)

**Comment by nikspz** [comment]
Still unable to check `status` and `status --live` for XEMM (cross exchange market making) strategy
0.46.0 dev Windows gitbash source.

![image](https://user-images.githubusercontent.com/83953535/143185720-faa6d5e8-497e-447d-9c2d-08e556ac39ab.png)
![image](https://user-images.githubusercontent.com/83953535/143185771-76e619c1-48e9-47ac-8e47-14613021ba80.png)

**Comment by rapcmia** [comment]
Fixed has been applied on the upcoming Hummingbot v1.3
