### ISSUE TITLE
Pure MM - Values shown on Amount (Orig) not showing

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#4380]
**Describe the bug**
When running a pure market making strategy, the values shown on Amount (Orig) is not appearing and only shows blank. Tested on most connectors with the same result and can confirm that this doesn't happen on other strategies (eg. avellaneda_mm, perpetual_mm)

The values shown is observed to be properly working under commit `bf5d62c9fd816ba70425fb2ccca015edaf5f403f`

![](https://user-images.githubusercontent.com/64377055/136141798-629ecfe0-1e5a-4e1d-af27-10c5f294f91e.png)

**Steps To Reproduce**

1. Run a pure_mm strategy on any supported connector

**Release version**
development-0.45.0

**Attachments**
Logs and config: [logs_conf.zip](https://github.com/CoinAlpha/hummingbot/files/7290853/logs_conf.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0gmf) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to a component

**Comment by leastchaos** [comment]
Can I apply for this bounty?

**Comment by JeremyKono** [comment]
Hi, closing this issue as it has been marked as paid. Thank you for your contribution!
