### ISSUE TITLE
Replace websockets library with aiohttp library - FTX

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#4406]
See epic https://github.com/CoinAlpha/hummingbot/issues/3941 for the rationale of this task.

## Definition of Done
* [ ] Replace `websockets` library with `aiohttp` in `FTX` connector
* [ ] Connector should be working without issues after the change

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0g1b) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment]
Closed that issue as FTX going to be removed as connector in 1.10.0 Release
