### ISSUE TITLE
Replace websockets library with aiohttp library - Hitbtc

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#4407]
See epic https://github.com/CoinAlpha/hummingbot/issues/3941 for the rationale of this task.

## Definition of Done
* [ ] Replace `websockets` library with `aiohttp` in `Hitbtc` connector
* [ ] Connector should be working without issues after the change

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0g0r) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment]
closing since connector was removed https://github.com/hummingbot/hummingbot/pull/7197
