### ISSUE TITLE
Replace websockets library with aiohttp library - k2

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#4409]
See epic https://github.com/CoinAlpha/hummingbot/issues/3941 for the rationale of this task.

## Definition of Done
* [ ] Replace `websockets` library with `aiohttp` in `k2` connector
* [ ] Connector should be working without issues after the change

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0fzy) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment]
since connector was removed
