### ISSUE TITLE
Replace websockets library with aiohttp library - Okex

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#4413]
See epic https://github.com/CoinAlpha/hummingbot/issues/3941 for the rationale of this task.

## Definition of Done
* [ ] Replace `websockets` library with `aiohttp` in `Okex` connector
* [ ] Connector should be working without issues after the change

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0fxd) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment]
Closing this one since okx connector was updated here:

https://github.com/hummingbot/hummingbot/pull/5368

and original issue is not available on [https://github.com/CoinAlpha/hummingbot/issues](https://github.com/CoinAlpha/hummingbot/issues/3941)
