### ISSUE TITLE
Deprecate minimum order amount feature

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#4421]
## Why
This is a legacy feature which doesn't serve well anymore, users often have to manually set the config parameter to 0 to get around the validation requirement. 

## What
Define or outline the task(s) that needs to be done.
- Remove the minimum order amount feature
- Remove `min_quote_order_amount` config from global config
- Remove `minimum_order_amount`, `default_min_quote` from config_helpers
- Update strategy config files to no longer validate minimum order amount

## Definition of Done
- The feature is removed
- Upon config a strategy, minimum order amount is no longer enforced.

**Comment by aarmoa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/4421?planning-poker) with ZenHub @CrimsonJacket @mhrvth @Nullably @petioptrv
