### ISSUE TITLE
Perpetual MM + DyDx Closing Order Renew Spin

### ISSUE THREAD

**Issue by petioptrv** [hummingbot/hummingbot#4426]
**Describe the bug**
// A clear and concise description of what the bug is.
Occasionally, the Perpetual MM strategy would attempt to cancel a closing order which apparently would fail. The strategy then goes into about a minute long sequence of re-attempts, one every second, until the order is finally cancelled and the new one is submitted (see screenshot).

This has been observed on the DyDx perpetual connector and it seems to happen only when closing long positions.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Create a perpetual MM config with a tight bid spread so as to trigger long positions.

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![pmm-dydx-bug.png](https://images.zenhubusercontent.com/60b2470e7aa82c4d096f7e09/27d629dd-030b-42d8-a45b-e1f1d5cc976d)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
dev-0.43.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[config file](https://app.zenhub.com/files/179163124/cdec4ebd-25ac-4d33-b2e0-0fff1c649c6f/download)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0ftx) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Setup a long term bot to reproduce but no go, seems it is now resolved. However there was one instance of spam of `creating stop loss bu order to close short position` still the client was able to recover. We have decided to close this ticket for now, else we can reopen if a fix is needed.
