### ISSUE TITLE
DYDX Perpetual - No module named `dydx3`

### ISSUE THREAD

**Issue by sirEven** [hummingbot/hummingbot#4447]
**Describe the bug**
Hummingbot is not able to setup connection details to dydx_perpetual connector. Upon calling the connect command, the module "dydx3" can't be found.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. install hummingbot (version 044.0) from source on macOS according to https://docs.hummingbot.io/installation/source/#macos (or equivalent on raspberry pi)
1. Start bot and run connect command to connect to dydx_perpetual derivatives connector and follow the pormpts

**Screenshots**
![no-module-named-dydx3](https://user-images.githubusercontent.com/36056348/136780984-2e89a60f-ec96-4e9e-9f40-084e97f71e1e.JPG)

**Release version**
0.44.0 (bug happens on both an old macbook pro (macOS High Sierra) and a raspberry pi 4b (raspbian))

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/7322564/logs_hummingbot.log)

**Optional: your discord username:**
everSin

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0f3g) by [Unito](https://www.unito.io)

**Comment by sirEven** [comment]
Currently I am trying to install the newest version on raspberry pi and agreed with sid from support to post the errors I find in here. 
(still following the raspberry pi guide from source). It results in this pip error:
<img width="660" alt="Screenshot 2021-11-06 at 11 05 47" src="https://user-images.githubusercontent.com/36056348/140605939-80338259-e6b8-47e3-ad03-e60f401c068b.png">

**Comment by sirEven** [comment]
Today I tried the current version (master) on raspberry pi 4 again. After running into the same old dydx error (and some failed pip message during installation, as mentioned above) I went through the workaround as posted before, to install dydx3 manually. 
Trying to connect to dydx perpetual afterwards ended in "Error: 'Response' object is not subscriptable" ->
<img width="1024" alt="Screenshot 2021-11-29 at 17 03 37" src="https://user-images.githubusercontent.com/36056348/143902488-708f4d46-5647-4273-944a-d37ae0bbcb13.png">

**Comment by sparksun** [comment]
> 

I got same issue as you, do you have any solution for it ?  the error about "Response object is not subscriptable"

**Comment by sirEven** [comment]
> I got same issue as you, do you have any solution for it ? the error about "Response object is not subscriptable"

I am currently not testing the raspberry pi version. Have you encountered this error with the newest release of hummingbot? As for this report here, it was way back with version 0.45.0

**Comment by sparksun** [comment]
> > I got same issue as you, do you have any solution for it ? the error about "Response object is not subscriptable"
> 
> I am currently not testing the raspberry pi version. Have you encountered this error with the newest release of hummingbot? As for this report here, it was way back with version 0.45.0

Yes, I encountered this problem with connect dydx on the latest tag1.1.0. I am running the source  on AWS ubuntu 20.04
