### ISSUE TITLE
Remove hummingbot.wallet

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#4460]
## Why
We don't need them anymore (functionality replaced by Gateway)

## What
* Delete hummingbot/wallet folder
* Remove references to hummingbot.wallet (in setup.py)

## Definition of Done
* `hummingbot.wallet` is no longer present

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0eg9) by [Unito](https://www.unito.io)

**Comment by petioptrv** [comment]
Blocked on https://app.shortcut.com/coinalpha/story/19931/move-hummingbot-wallet-to-hummingsim
