### ISSUE TITLE
Terra - Luna sell and buy market prices far from mid-price

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#4470]
**Describe the bug**
Luna sell and buy market prices far from mid-price when you start amm_arb strategy for terra

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

1. Create amm_arb strategy with terra as connector_1
1. Set up low order_amount
1. Start the bot to see Sell and buy market prices too far from mid-price

**Screenshots**
![image](https://user-images.githubusercontent.com/83953535/137443698-f669584d-3c56-4927-b240-7f00741caa7f.png)
**Release version**
Linux, Docker, 0.44.0

**Attachments**

![4 order amount 1000](https://user-images.githubusercontent.com/83953535/137443593-e6ed51d2-fae0-4284-a441-a26bad27b2d9.png)
![4 1 order amount 1000](https://user-images.githubusercontent.com/83953535/137443602-58641273-4c97-41a0-8732-814d5c80ce67.png)
![1 order amount 0 49](https://user-images.githubusercontent.com/83953535/137443606-c21abe88-0d72-4470-9454-6d978cdcece5.JPG)
![1 1  - order amount 0 49](https://user-images.githubusercontent.com/83953535/137443610-60789688-a662-4727-9f85-ece41993293d.png)
![2 - order!UNITO-UNDERSCORE!amount 2](https://user-images.githubusercontent.com/83953535/137443612-dee097ee-929f-4a5e-88cf-f04e02cc8397.JPG)
![3 order amount 0 49 min profitability 100](https://user-images.githubusercontent.com/83953535/137443614-6b1e59ea-2c6a-4f1b-87d6-9f0eb9dc76bc.JPG)

[terratest.txt](https://github.com/CoinAlpha/hummingbot/files/7351406/terratest.txt)
[logs_terratest.log](https://github.com/CoinAlpha/hummingbot/files/7351404/logs_terratest.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0e2d) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Adding a note here, despite wrong price shown in the client. The execution price in the terra chain is correct,
example:
![image](https://user-images.githubusercontent.com/57189990/140668205-037869dc-2ea3-4331-b09a-3847d48ace6f.png)
![image](https://user-images.githubusercontent.com/57189990/140668209-31e5a3e6-3f2a-46f1-85c5-12eb85e964c2.png)
![image](https://user-images.githubusercontent.com/57189990/140668250-23bc9eed-65ff-498d-8249-477b45038224.png)

tx: https://finder.terra.money/columbus-5/tx/606A10EBAE27D416B2741029750ABAFE427BFEE3A4D5F8A1482B559592A4429B

**Comment by johnnyappleust** [comment]
Hey @dennisocana is there any update here? The spread is still 60+ points wide.

Moreover, is this Terraswap pricing? Where is this Terra API feed coming from? 

Thanks for all the great work you and the team do! Discord has been invaluable!

**Comment by johnnyappleust** [comment]
Hi there @dennisocana is there any update here?

Thx!

**Comment by nikspz** [comment]
closed this ticket since currently Terra is not available on gatewayv2
