### ISSUE TITLE
Binance Perpetual - Delay starting strategy

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#4481]
**Describe the bug**
When running perpetual_mm strategy using binance_perpetual the strategy takes more than 30+ seconds before it starts placing orders.

**Steps To Reproduce**

1. Create and run a perpetual_mm strategy using binance_perpetual.
1. Start the bot. Notice that it takes around 30s before it starts placing orders.

**Screenshots**
![](https://user-images.githubusercontent.com/64377055/137616187-ca44a5eb-9d7f-44f5-baf2-a920fafdea22.png)

**Release version**
development-0.45.0

**Attachments**
Logs and config: [binance_perp.zip](https://github.com/CoinAlpha/hummingbot/files/7359004/binance_perp.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0dnv) by [Unito](https://www.unito.io)

**Comment by leastchaos** [comment]
![image](https://user-images.githubusercontent.com/64965782/140262629-c13f6fd1-38e7-4620-b821-e6e217e2720b.png)
hello, can i check is this fixed? seems to be having this issue with the hedge strat too after i upgraded to the latest version.

**Comment by rapcmia** [comment]
Fix has been merged to staging branch `v1.2-staging` for Hummingbot 1.2.0
