### ISSUE TITLE
Terra:  unhandled rejection when connecting to testnet

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4485]
**Describe the bug**
Terra wallet fail to connect when connecting using testnet mode. 

```python
2021-10-17 04:17:46 | error | 	/terra/balances Error: getaddrinfo ENOTFOUND tequila-lcd.terra.dev
2021-10-17 04:17:46 | error | 	unhandledRejection: Cannot read properties of undefined (reading 'status')
TypeError: Cannot read properties of undefined (reading 'status')
    at C:\Users\Ralph\github\gw\src\routes\terra.ts:76:29
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Ralph\github\gw\dist\routes\terra.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):

1. Generate client certificate
1. Create a gateway instance using master or development branch
1. Configure gateway configuration file
1. Use testnet mode
1. Start gateway
1. Connect terra wallet

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/137670662-048ec6ee-bc5b-469c-a905-49e499ce67a8.png)

**Release version**
0.44.0
Gateway-v1 : 0.10.0
**Attachments**
[logs_gateway_app.2021-10-17.log](https://github.com/CoinAlpha/hummingbot/files/7361888/logs_gateway_app.2021-10-17.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0dk1) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
A workaround to test terra connector on testnet is to use the latest testnet network ( bombay-12)
```
TERRA_LCD_URL: https://bombay-lcd.terra.dev
TERRA_CHAIN: bombay-12
```
confirmed working on my side:
![image](https://user-images.githubusercontent.com/57189990/140667012-ada31cbe-a562-4064-b675-486221802e9d.png)

**Comment by cali-tomas** [comment]
A user had an issue with connecting with Terra testnet

![image](https://user-images.githubusercontent.com/85161223/140668580-6106ae8c-df66-4c88-b492-cc821dcdbca2.png)
![image](https://user-images.githubusercontent.com/85161223/140668592-3962561e-4917-451d-aac4-419af9dea8f5.png)

After suggesting the workaround Terra connected 
![image](https://user-images.githubusercontent.com/85161223/140668634-734e1a68-a741-4881-819c-412bb75977f9.png)

**Comment by rapcmia** [comment]
Resolved by changing the testnet and testnet chain to:
```
TERRA_LCD_URL:  https://bombay-lcd.terra.dev
TERRA_CHAIN: bombay-12
```
