### ISSUE TITLE
Perpetual MM - Use `take_if_crossed` as default behavior and remove from config

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#4499]
## Why

As part of the efforts of simplifying perpetual market making, we will remove certain parameters derived from pure market making such as `take_if_crossed`. It's an advanced parameter from pure-MM which is optional and does not affect the main behavior of the strategy.

Orders should always be created as limit (not Post-only/maker limit). That way, `take_if_crossed` is the default state of the strategy, and the execution would happen at a better price than first intended by the trader when the initial orders are created.

## What / Definition of Done

* [ ] Remove `take_if_crossed` from the strategy configuration
* [ ] The `take_if_crossed` functionality is the strategy's default behavior
* [ ] Ensure no issues with the strategy after completing this task

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0cz5) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Initially, we discussed about removing some other parameters from pure market making such as `hanging_orders_enabled`, and `ping_pong_enabled`. If so, should we include that task in this same story?
