### ISSUE TITLE
Refactor Perpetual MM strategy to pure Python + create unit tests

### ISSUE THREAD

**Issue by phbrgnomo** [hummingbot/hummingbot#4503]
## Why
While fixing some bugs related to Perpetual Market Making, the strategy was difficult to debug in its current Cython implementation. It would also be easier for future developers to contribute on top of this strategy and for maintainability.

## What
Once all the other tasks to rework / improve the strategy is complete, convert it from Cython to just Python code. Also add the necessary unit tests.

## Definition of Done
* [ ] Files related to strategy in [perpetual_market_making](https://github.com/CoinAlpha/hummingbot/tree/master/hummingbot/strategy/perpetual_market_making) are in `.py` format
* [ ] At least 75% diff-coverage for unit tests

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0crz) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
This task will include adding unit tests to the strategy. Will update the description of the story.
