### ISSUE TITLE
avellaneda vol_to_spread_multiplier

### ISSUE THREAD

**Issue by drumer979** [hummingbot/hummingbot#4518]
Can you please change max value of setting vol_to_spread_multiplier (avellaneda_market_making) to 50.

Im testing new strategy, and I found out that I would need at least 30.

thx

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0cah) by [Unito](https://www.unito.io)

**Comment by drumer979** [comment]
In 0.45 there is no update about avellaneda

**Comment by dennisocana** [comment]
@drumer979 the pull request @phbrgnomo mentioned is still open. When it gets merged, it will be available in 0.46 release after 4 weeks.

**Comment by drumer979** [comment]
I can test it before it goes "live" in 0.46

**Comment by phbrgnomo** [comment]
> I can test it before it goes "live" in 0.46

@drumer979 our team is still working on it, but once you see the task #4584 as closed, this means that the update is on the development branch.

You will be able to run if from the source code, or creating a docker instance using the `development` version
