### ISSUE TITLE
Update K2 connector to use production endpoints

### ISSUE THREAD

**Issue by dennisocana** [hummingbot/hummingbot#4535]
The exchange will go on soft launch this coming November 1st. We will update the connector to use their production endpoints so they can run internal testing and so does our QA team for a month.

Will update the task description once we have the endpoints.

**What**
- [ ] Update REST and WebSocket URL in `k2_constants.py`
- [ ] Build Windows Binary for their internal Team
- [ ] Test connector on Production endpoints.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rg70ad) by [Unito](https://www.unito.io)

**Comment by CrimsonJacket** [comment]
We have not been provided any production endpoints. Only the "pre-production" endpoints.

**Comment by nikspz** [comment]
closing Since connector was removed
