### ISSUE TITLE
PancakeSwap

### ISSUE THREAD

**Issue by dennisocana** [hummingbot/hummingbot#4537]
PancakeSwap is a decentralized exchange for swapping BEP20 tokens on Binance Smart Chain. PancakeSwap uses an automated market maker (AMM) model where users trade against a liquidity pool. Such pools are filled with users’ funds. They deposit them into the pool, receiving liquidity provider (or LP) tokens in return. They can use those tokens to reclaim their share, plus a portion of the trading fees.

The LP tokens are called FLIP tokens. PancakeSwap also allows users to farm additional tokens – CAKE and SYRUP. On the farm, users can deposit LP tokens, locking them up in a process that rewards users with CAKE. Users can stake CAKE tokens to receive SYRUP, which will have further functionality as governance tokens (and as tickets in a lotteries).

Source: https://coinmarketcap.com/exchanges/pancakeswap/

Exchange URL : https://pancakeswap.finance/
API Documentation : https://github.com/pancakeswap/pancake-info-api/blob/develop/v1-documentation.md
Type of Exchange : DEX

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rg726e) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment]
connector added in Version 1.10.0 and available in latest development  / version 1.24.0
https://hummingbot.org/release-notes/1.10.0
