### ISSUE TITLE
Using spreads command then skipping one of the spread midway (ctrl + x) will set the strategy spread to None 

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#4637]
**Describe the bug**
When using the `spreads` command then accidentally input negative value and skip the new spread parameter will cause None value on one of the spread.

**Steps To Reproduce**

* use spreads command while using pure_mm strategy
* input `spreads 0.01 -0.01` bot will throw `Value must be between 0 and 100 (exclusive).` and ask for new spread do ctrl + x
* type `config` see that ask_spread is set to None

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/139778487-97f1130b-c04a-4043-bf13-a82c36152169.png)
![image](https://user-images.githubusercontent.com/54516858/139778537-a94f9732-c0a2-407c-a726-16c1504615c1.png)

**Release version**
dev-0.45.0

Similar https://github.com/CoinAlpha/hummingbot/issues/2900

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1u9d72k) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Tested on Hummingbot version 1.2.0 and issue does not occur anymore. Closing ticket
