### ISSUE TITLE
Binance Perpetual not getting execution type from right attribute

### ISSUE THREAD

**Issue by HenryByte** [hummingbot/hummingbot#4643]
In the following code it tries to get the `execution_type` from the `execution_report` but should instead get it from the `order_report`. Then afterwards it should set the `exchange_id` from the `order_report` as well.

https://github.com/CoinAlpha/hummingbot/blob/0e58a625884abdc1a0da43f9c91df62b26425fa0/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_in_flight_order.py#L70

This isn't a major issue as the `exchange_id` is also set upon the response from the exchange when the order is created.
I think this code would only be called when there is an issue with that code and the reconciliation happens later on during the polling.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1u9hcfc) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Closing ticket, the file  `binance_perpetual_in_flight_order.py` mentioned on this ticket is not available on the latest master and development branch.
![image](https://user-images.githubusercontent.com/73840223/211463342-fa5972f0-246d-4065-a8f0-dc9f944ffdd4.png)
