### ISSUE TITLE
Upgrade to Python 3.10

### ISSUE THREAD

**Issue by MHHukiewitz** [hummingbot/hummingbot#4722]
**Feature Suggestion**
Name says it all. Would need to check all used pip modules and see, whether they all have 3.10 compatible versions. As this distribution exists for some time already, I hope this should be the case.

**Impact**
Some of the newer exchanges and DeFi protocols have python modules to interact with them. Only that they often require python 3.10.

EDIT: Change 3.9 to 3.10, as it is officially released: https://docs.python.org/3/whatsnew/3.10.html

**Comment by rapcmia** [comment]
Hummingbot now supports python 3.10
