### ISSUE TITLE
[Hummingbot] Strategy start validation and confirmation on Gateway exchanges

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#4733]
## Why
To make sure the user has configured Gateway exchange correctly and selected the right network for their trading.

## What
Upon `start` command on any strategy that has Gateway exchange(s) configured:

### 1. Configuration validation
Validate Gateway connector configs, notify user for all invalid configuration e.g.:
```
The following configs are invalid/missing for [exchange]: 
    network
    wallet_address
Please use `gateway config-[exchange]` to list and update the configuration.
```

If all configurations are valid, proceed to the second step below

### 2. Network Selection Confirmation
Confirm if the network of the exchange is what user intends, for each of configured Gateway exchange, display
```
[exchange] configuration:
  chain: ethereum
  network: mainnet
  wallet_address: 0xWallet1
  0xWallet1 balances:
  Token             Amount
  ETH                2.1
  DAI                 3000 
  [limit balances display to top five tokens]
 
```

And prompt ` Do you want to continue? (Yes/No)  >>>  `
Yes - continue on with the start procedure. 
No - exit the start procedure.

Noe: You can see start confirmation example on a strategy where `rate oracle` is configured.

## Definition of Done
The validation and confirmation work on any strategy with Gateway exchanges configured.

**Comment by aarmoa** [comment]
During estimation discussion we decided that the second confirmation after requesting `start` should not be included.

**Comment by Nullably** [comment]
> During estimation discussion we decided that the second confirmation after requesting `start` should not be included.

There is no second confirmation, just one. Validation and confirmation are 2 different things here, validation is to make sure all connector configurations are valid, confirmation is to make sure the network of the connector (valid configuration) is what user intends. Since likely there are multiple chains (e.g. Ethereum, Arbitrum) and networks (e.g. testnet, mainnet) for a Gateway connector, we want to make sure the user selects the right one before the strategy starts trading.
