### ISSUE TITLE
AscendEx: NoOpenForCancel error causes untracked fills

### ISSUE THREAD

**Issue by zappra** [hummingbot/hummingbot#4738]
**Describe the bug**
When running a liquidity mining strategy with low spread and low refresh time, orders are failing with "NoOpenForCancel" errors. According to the API docs this means "Order is not in active status: order does not exist or has been filled/canceled"

I have some custom script code that tracks expected base inventory amount based on received order fill events and compares it to the reported amount from the exchange balance. Some time after the "NoOpenForCancel" error there is a balance discrepancy equal to the amount of the order that failed.

I suspect what is happening here is that the connector is attempting to cancel an order that has been filled, but before the order fill has been received. When the error is received, the connector stops tracking the order. Any future messages (eg. order fill) would then be ignored, as the order is no longer tracked by the connector

See attached logs

[cns.txt](https://github.com/CoinAlpha/hummingbot/files/7548420/cns.txt)
[dafi.txt](https://github.com/CoinAlpha/hummingbot/files/7548423/dafi.txt)

Untracked fills will obviously mean any PnL calculations will be wrong.

**Steps To Reproduce**

Run pure_market_making on AscendEx with low spread and order refresh time. Examples from logs above use spread 0.1% and 3 seconds respectively. Single order mode, no hanging orders.

**Optional: your discord username:**
zappra

**Comment by zappra** [comment]
I've confirmed this by running with a workaround that doesn't remove the order from tracking if the error code is "NoOpenForCancel" See attached log snippet that shows the order fill event being generated right after the error.

[lime.txt](https://github.com/CoinAlpha/hummingbot/files/7568475/lime.txt)

This is obvs not a viable long term fix since it wouldn't do the right thing if the order didn't actually exist (eg. the connector was trying to cancel an order that had already been manually cancelled on the exchange)

**Comment by CrimsonJacket** [comment]
@zappra this seems to happen on the rare occasion when an order gets filled on the exchange and a cancellation request is sent before the filled event message is received and processed. As you've mentioned, I do not believe theres a viable long term fix considering this is entirely circumstantial, and as such I have opted to include a failure limit before we call `stop_tracking_order`.
