### ISSUE TITLE
Kraken-Order_book data is not synchronized with the exchange order_book

### ISSUE THREAD

**Issue by bluecammut** [hummingbot/hummingbot#4741]
**Describe the bug**
// When running the PMM strategy on differents connectors, I notice that some of them are not showing accurate data.

**Steps To Reproduce**
// 1. Create a PMM strategy
2. Start the strategy
3. Run the "order_book --live" command 
4. compare the HBOT order book info vs exchange info
Note: try to select a market which is not too busy so you can compare easily.

Connector with wrong data:
-Krake

**Screenshots**
<img width="1440" alt="krarken" src="https://user-images.githubusercontent.com/79382440/142128672-a250cd98-7094-4cfc-b13d-1a64e7d407c1.png">

**Release version**
Branch Master - MAC source build 0.46

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by bluecammut** [comment]
as a result of the order book desynchronization, the output in order_book, ticker and the best bid/ask in status also are incorrect or do not match with the exchange

**Comment by rapcmia** [comment]
While monitoring live `order_book` and `ticker` parameters using DOGE-BTC it seems to be its working as expected and did not found order book desync. Tagging this ticket as closed for now and to reopen if persist/reported again.

Screen recording:

https://user-images.githubusercontent.com/73840223/155663145-f1fe4a74-fdad-412a-b842-28b43a871bd0.mp4
