### ISSUE TITLE
Bybit Perpetual - not showing Position in the bot status after cancel manually and restart the strategy

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#4778]
**Describe the bug**
After you cancel another position manually, stop and start strategy again bot hide Position and not showing it in the bot status

**Steps To Reproduce**

1. Create perpetual MM strategy with derivative bybit_perpetual, tight spreads, high filled_order_delay (600)
2. Set up some long_profit_taking_spread, short_profit_taking_spread, high stop_loss_spread
3. Start a strategy till buy/sell order get filled
4. Stop the bot
5. Manually Close position created on 3rd step (by market order)
6. Start the same strategy again
7. Wait till the order filled
8. Check status, bot not showing Position in the bot status

**Release version**
Win10, Source, gitbash, ver. dev 0.46.0

**Screenshots**

![2 2 - order on exchange status](https://user-images.githubusercontent.com/83953535/142584114-a036090a-5fcf-4383-b6d3-1ee387f79f56.JPG)

**Attachments**

Screenshots, logs and config
[19 11.zip](https://github.com/CoinAlpha/hummingbot/files/7568592/19.11.zip)

**Comment by RC-13** [comment]
@nikspz Can you please re-test this, I was trying replicate the issue using our test bot however the test bot is able to recover the position.

**Comment by nikspz** [comment]
I was able to replicate this on cloud (Docker, ubuntu) dev 0.46.0

with `filled order delay 600` **bot cant see opened position**. Let's wait till bot refreshing orders.

![image](https://user-images.githubusercontent.com/83953535/142978891-6632c9b9-a3b0-489e-a6e6-25048c9e3330.png)

![image](https://user-images.githubusercontent.com/83953535/142978916-67b22d65-e2e9-49f8-9ede-f75bfa716bb6.png)

Then when bot's refreshing orders, can't see opened position still 
![image](https://user-images.githubusercontent.com/83953535/142979049-6586ddbd-e93c-4dfa-b2d1-7098baed0cf4.png)
![image](https://user-images.githubusercontent.com/83953535/142979067-f9f6deaa-59bb-47d0-abef-d41766530599.png)

When fresh order is filled bot can see the position again.
Then for some reason, the position disappears and is not shown by the bot again.

![image](https://user-images.githubusercontent.com/83953535/142979234-cbdcb248-72f7-42d6-b88e-feb7e7cbd918.png)

**Comment by rapcmia** [comment]
The fix for this issue has been applied on the Hummingbot version 1.4
