### ISSUE TITLE
WazirX - Could not fetch new trading rules

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4870]
**Describe the bug**
When starting any strategy using the WazirX connector, you immediately get the following message `Could not fetch new trading rules from WazirX. Check network connection` and after running for a while, the bot will start receiving HTTP status is 429 (too many API requests). Despite getting this message, orders are created and cancelled according to the parameter specified on the strategy.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create any market making strategy using WazirX connector
2. Start the strategy
3.  Monitor the log pane
...

**Screenshots**
![wazirx-failed-to-fetch-start-up](https://user-images.githubusercontent.com/57189990/144798631-5283b083-f6ea-4e44-b863-9b23092d4ff5.png)
![wazirx-too-many-request](https://user-images.githubusercontent.com/57189990/144798644-80685a94-38b4-49c7-ab9b-a4e2a0866001.png)

**Release version**
0.46.0

**Attachments**
[logs_pmm-trx-usdt-wazirx.log](https://github.com/CoinAlpha/hummingbot/files/7658518/logs_pmm-trx-usdt-wazirx.log)
*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Connector has been removed
