### ISSUE TITLE
Replace aiohttp and signalr_aio library with WebAssistant library - Bittrex

### ISSUE THREAD

**Issue by petioptrv** [hummingbot/hummingbot#4890]
See epic https://github.com/CoinAlpha/hummingbot/issues/3941 for the rationale of this task.

## Details
- The REST part of the connector, using `aiohttp`, is straight-forward
- The WS part, using `signalr_aio`, can be tackled by
    - Writing a child class of `ConnectionsFactory` that will deliver the existing `RESTConnection` and a new `WSConnection` alternative that will use `signalr_aio` instead of `aiohttp`.
- Allowing `WebAssistantsFactory` to receive a `ConnectionsFactory` injection (an `__init__` parameter) and injecting the new connections factory at the composition site.
- Base on a quick scan, the data sources classes have some opportunities to use the pre- and post-processors
    - E.g. `_transform_raw_message` is a great candidate for a post-processor

## Definition of Done
* [ ] Replace the use of `aiohttp` and `signalr_aio` libraries with `WebAssitant` in `Hitbtc` connector
* [ ] Connector should be working without issues after the change

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0g0r) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment]
Closing since connector was removed https://github.com/hummingbot/hummingbot/pull/6617
