### ISSUE TITLE
MEXC - Unsupported order type: OrderType.MARKET

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4892]
**Describe the bug**
When running a cross-exchange market-making strategy and MEXC connector is used as the `taker` exchange, the order fails to get executed with the following error. 
```python
2021-12-10 03:30:39,335 - 14776 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Unsupported order type: OrderType.MARKET
Traceback (most recent call last):
  File "/home/ubuntu/mexc/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/mexc/hummingbot/connector/exchange/mexc/mexc_exchange.py", line 731, in execute_sell
    raise Exception(f"Unsupported order type: {order_type}")
Exception: Unsupported order type: OrderType.MARKET
```
Tried using the exchange in an arbitrage strategy however, there was no error in the bot however there was no executed arbitrage order on the mexc side.
**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a cross-exchange market making strategy
2. Set MEXC connector as the taker exchange
3. Set low minimum profitability for a higher chance of executing a trade
4. Start the strategy
5. Check the history and observe the logs when there is a filled event.

**Screenshots**
**Release version**
0.46.0

**Attachments**
[logs_conf_xemm_1.log](https://github.com/CoinAlpha/hummingbot/files/7690053/logs_conf_xemm_1.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by physioshane** [comment]
same issue now, had no trades at all on mexc side, despite the logs saying the strategy completed

**Comment by jubalo93** [comment]
Hi
I'm also facing this issue on an arb strategy

`ingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659577171.0, "order_id": "sell-ABC-USDT-16016", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "mexc"}
2022-08-04 01:39:31,037 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Unsupported order type: OrderType.MARKET`

**Comment by Extractthedata** [comment]
Any idea in how to resolve this? I'm also getting this error

**Comment by nikspz** [comment]
Severity: P3
Bounty: 10 000 HBOT (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to MEXC exchange (or component)

**Comment by cardosofede** [comment]
@nikspz I will take it

**Comment by nikspz** [comment]
Removing this bounty, since PR to refactor MEXC is ongoing. This one is achieved.
