### ISSUE TITLE
Beaxy - Bot not updating the current price for trades

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#4893]
The bot is not updating `the current price` for BTC-USDC pair. For some reason, it uses `56107` as BTC price value for every trade.
That's the reason of `incorrect amount of trade PnL and Return %` and could trigger killswitch incorrectly.

**Steps To Reproduce**
1. Create and run pure MM strategy with `Beaxy` as an exchange and BTC-USDC as market
2. Set up a tight spread
3. Get order filled
4. Check `history --verbose`

You can see `incorrect current price` and `incorrect amount of trade PnL and Return %`

![image](https://user-images.githubusercontent.com/83953535/145518058-cb27f4c4-cd63-48c8-a9fc-d5f8a20d6c73.png)
![image](https://user-images.githubusercontent.com/83953535/145518066-e542ebb3-3232-43f9-81e1-6f0104934f0d.png)
![image](https://user-images.githubusercontent.com/83953535/145517987-4b465a9d-5358-45b7-a254-c2c12222a7ff.png)
![image](https://user-images.githubusercontent.com/83953535/145518019-39284d00-3657-4c0a-9cf0-2373d6dd9240.png)
![image](https://user-images.githubusercontent.com/83953535/145518133-051700da-2867-4170-aa30-64715d907ed3.png)

**Release version**
dev - 1.0.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_beaxy.log](https://github.com/CoinAlpha/hummingbot/files/7690158/logs_beaxy.log)
[beaxy.txt](https://github.com/CoinAlpha/hummingbot/files/7690159/beaxy.txt)

**Comment by RC-13** [comment]
Looks like the issue self-healed. The current price is now close enough with the current price in the exchange.  
![image](https://user-images.githubusercontent.com/57189990/147040218-d55d77ca-d4ea-442c-9e38-2cc163bfe0d6.png)

**Comment by rapcmia** [comment]
Ran Pure-MM on Beaxy connector to test and was not able to reproduce the issue, initially started with the current price at `41661` and waited for the next trades:
![image](https://user-images.githubusercontent.com/73840223/148936849-1db15b97-6cd9-409c-9c99-8f5dd2bf9a95.png)

You would notice that the current price has been updated to `41931`
![image](https://user-images.githubusercontent.com/73840223/148937066-a6aaec0f-7ecd-49b8-9e35-c52bf93d8062.png)

The connector seems to be working as normal atm and this issue has been monitored for a month with the same results. Tagging this ticket as solved for now. Thank you
