### ISSUE TITLE
Hedge improvement

### ISSUE THREAD

**Issue by jellebuth** [hummingbot/hummingbot#4901]
THIS ISSUE IS CREATED TO PARTICIPATE IN THE COMMUNITY VOTING FOR THE STRATEGY IMPROVEMENTS✅

Please note that part of this improvement is not relevant when the Cross-exchange market-making Spot to perpetual improvement gets accepted.

**Feature Suggestion**
 I suggest that within one instance of the hedging strategy, traders are able to select multiple exchanges and tokens to hedge. The bot will read the total funds of these coins on the selected exchanges and hedge those funds within one instance instead of multiple instances. ✅

In the current situation, traders run multiple bots, with funds on multiple exchanges. If they want to hedge their position with the new hedge strategy, they need to run multiple instances to hedge every single coin on every single exchange ❌.  This is hard to manage and is sometimes impossible if a trader has funds constantly moving from one exchange to another (AMM arbitrage, cross-exchange arbitrage).❌

Traders using the cross-exchange strategy are not able to use this feature at the moment as one exchange might say that they have no funds on exchange x and the other exchange might say that they have funds of coin x, while this might change the next second. The same problem for the arbitrage strategies (arbitrage & AMM arbitrage)❌. Running two instances of the hedging strategy (one for every exchange of coin x) will result in a constant opening of hedging orders as funds change every x minutes from exchange 1 to exchange 2. 

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
This allows traders to easier manage the hiding within one instance and allows traders to easily hedge coins that are located on multiple exchanges. ✅

**Comment by leastchaos** [comment]
@jellebuth @rapcmia This issue can be closed as this is implemented in the latest hedge version
