### ISSUE TITLE
Update Fee Estimation Capabilities

### ISSUE THREAD

**Issue by petioptrv** [hummingbot/hummingbot#4903]
# Why
The reasoning behind this task is outlined in [this document](https://www.notion.so/hummingbot/WIP-Trade-Fee-Investigation-eaaf11b6428e46f0b10890681ffec3b4).

# What
- `TradeFee` has a field for the fee token for percentage-based fees, and there are maker and taker percentage fee fields.
- Refactor `TradeFee.fee_amount_in_quote` to a method that calculates the fee amount in the fee token.
- `TradeFee` has a new field that indicates if the (buy) order fee should be added on top of the order size or deducted from the order cost
- Refactor `hummingbot`'s `AllConnectorSettings` to include the new fields needed to populate the `TradeFee` (should be backwards compatible)
- The `BudgetChecker` is refactored to use the `TradeFee` changes, and to output multiple collateral pairs (i.e. amount-token pairs; e.g. in the case where the fee is charged in a third token, we would need two pairs)
- Ensure that Binance, Bittrex, CoinBasePro, Huobi, and Kucoin have sensible defaults as those are the exchanges currently supported by `hummingsim`

As mentioned by @aarmoa, two additional things to consider:
- Keep a single percentage and asset pair as the `TradeFee` object keeps the information for a single order, which is either a taker or a maker but not both simultaneously.
- Double-check where and how currency conversion happens when the fee is in a third token, and consider adding a conversion source to the `TradeFee` object.

# Definition of Done
For Binance, Bittrex, CoinBasePro, Huobi, and Kucoin,
- [ ] `TradeFee` contains all relevant information (except for user tier) necessary to model the trading fees.
- [ ] `BudgetChecker` can accurately size orders given the particular fee structure.

**Comment by aarmoa** [comment]
I think we will also need a new functionality that can calculate the amount in a particular asset. Currently the TradeFee is only capable of doing such calculation in the order quote asset.

**Comment by petioptrv** [comment]
> I think we will also need a new functionality that can calculate the amount in a particular asset. Currently the TradeFee is only capable of doing such calculation in the order quote asset.

Good point, I've added that to the list
