### ISSUE TITLE
Update the login screen to use the new colour defaults

### ISSUE THREAD

**Issue by petioptrv** [hummingbot/hummingbot#4905]
# Why
Currently, the login screen uses the previous colour defaults (before the newly introduced UI changes). It would be a nice extra-touch to update those to match our new lighter-green default.

![Screen Shot 2021-12-14 at 3.34.17 PM.png](https://images.zenhubusercontent.com/60b2470e7aa82c4d096f7e09/0d0a62b1-fdf0-4863-9617-b30505ba0a9c)
![Screen Shot 2021-12-14 at 3.33.26 PM.png](https://images.zenhubusercontent.com/60b2470e7aa82c4d096f7e09/65ac761e-1b44-4e4e-abd4-7b8dc27a4f7d)

# What
Update the login screen colour defaults.

# Definition of Done
- [ ] The login screen uses the same shade of green as the default colour of the rest of the client GUI.

**Comment by sisco0** [comment]
The color config map for the terminal is specified in `hummingbot/client/config/global_config_map.py` as `#00FFE5`

```python
    "terminal-primary":
        ConfigVar(key="terminal-primary",
                  prompt="What is the terminal primary color? ",
                  type_str="str",
                  required_if=lambda: False,
                  validator=validate_color,
                  default="#00FFE5"),
```

This is dynamically got for custom widgets in the file `hummingbot/client/ui/custom_widgets.py` by importing `color_config_map`. We could do the same with the `dialog_style` in `hummingbot/client/ui/__init__.py`.

**Comment by petioptrv** [comment]
Closing due to the issue being migrated [here](https://github.com/hummingbot/hummingbot/pull/4944).
