### ISSUE TITLE
Update Binance perpetual connector

### ISSUE THREAD

**Issue by aarmoa** [hummingbot/hummingbot#4911]
## Why
Aligned with the effort to make it easier for community developers to work on new connectors, we want to apply all latest improvements to one spot connectors, for it to be used as an example, or a golden connector. The Binance perpetual connector was the chosen one for perpetual connectors.

## What
- Adapt all REST API interactions to use the recently developed web assistant.
- Adapt all websocket API interactions to use the recently developed web assistant.
- Change implementation of all data source classes to use only one websocket connection in each of them. If it is possible to use only one shared websocket connection in all places we should make that change.
- Ensure all consumptions of the API are regulated by the use of the throttler (both REST and websocket API)
- Refactor the connector to use the newly developed orders tracker to manage in flight orders.
- Refactor the connector to stop using ad hoc logic to translate from exchange token-pair notation to client token-pair notation and the other way round. Instead keep track of the mapping base on the information provided by the exchange and the tokens composing each pair (as done in Ndax and Beaxy connectors)
- Dosctrings for the "interface" methods that users of the class will use in preparation of the documentation simplification (can use the documentation that already exists in the `.md` files; [original proposal](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/4875))

**Comment by petioptrv** [comment]
To this, I propose we add the following points:
- Re-arrange the methods to have the "interface" methods that are directly used by clients of the connector class on top (and maybe make all other methods private?)
    - I propose the following arrangement: class methods and static methods, `__init__`, properties, interface methods, the rest (with private being last)
    - Overall, I propose a method arrangement in descending order of implementation detail (i.e. higher-level methods go first and the lower-level methods that the former use go next)
- Dosctrings for the "interface" methods that users of the class will use in preparation of the documentation simplification (can use the documentation that already exists in the `.md` files; [original proposal](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/4875))
