### ISSUE TITLE
[Gateway] Refactor trading routes

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#4921]
## What 

Create trading path and endpoints as below:
```
/trading/nonce
/trading/allowances
/trading/balances
/trading/approve
/trading/poll
/trading/cancel
/trading/price
/trading/trade
```

Model these new routes from existing ethereum and uniswap request and response interfaces with:
- Rename the interfaces to be more generic (e.g. remove Ethereum from EthereumBalanceRequest)
- Every request must have 3 new fields:
  connector: string //the target connector (e.g. uniswap or pangolin)
  chain: string //the target chain (e.g. ethereum or avalanche)
  network: string  // the target network of the chain (e.g. mainnet)

Remove existing ethereum, avalanche, uniswap and pangolin routes

Move Uniswap and Pangolin to `src/connectors/` folder. 

## DoD
- New routes created and work with our existing uniswap and pangolin on their available chains/networks
- Existing ethereum, avalanche, uniswap and pangolin routes removed.

**Comment by phbrgnomo** [comment]
> /src/connectors contains all existing connectors

I suggest separate inside the `connectors` folder DEXes and CEXes to make it easier to visualize which is which.

**Comment by Nullably** [comment]
> > /src/connectors contains all existing connectors
> 
> I suggest separate inside the `connectors` folder DEXes and CEXes, or have them on a `/src/dexes`, to make it easier to visualize which is which

There are no CEXes on Gateway.

**Comment by phbrgnomo** [comment]
> There are no CEXes on Gateway.

Yeah, but isnt the idea to have both exchanges types on the same `connectors` folder, so the Client would treat them the same way?

Or would all gateway connectors be inside `/gateway/src/connectors` separated from the other connectors?
