### ISSUE TITLE
Major improvement proposal

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#4931]
To improve user (and dev) experience using Gateway.

* Connector centric approach
* Introduce trading interface to categorise connectors
* Generic client connector approach

In term of API design, we want to achieve something like this

![image](https://user-images.githubusercontent.com/37262506/147923411-427e5aad-dee2-4d94-b372-d7b5cbd2b47e.png)

**Comment by mifeng** [comment]
Issues in this epic:
#4920 
#4921 
#4924 
#4928 
#4929
#4930 
$4937

**Comment by MHHukiewitz** [comment]
Maybe I'll leave this here: https://github.com/yourtrading-ai/hummingbot/tree/feat/gateway-v2_solana

I Disentangled common functionality between SolanaBase and EthereumBase (which was GatewayBase prior to refactoring) into GatewayBase. I hope this looks about right. A lot of code which has to do with the connection to Gateway API (_api_request(), _http_connection(), etc.) was able to remain largely in GatewayBase, so any Blockchain/DEX can build on it.
