### ISSUE TITLE
Order optimization best bid is off

### ISSUE THREAD

**Issue by Perream2** [hummingbot/hummingbot#4934]
**Describe the bug**
Best bid is off while using order optimization on loopring exchange on trading pair USDC-USDT. For example, best bid in order book before bot is started, .9981

When bot is started, status shows best bid order is .9980 and bot submit order on top of actual best bid of .9981 when it should be .9982

**Steps To Reproduce**
start bot on loopring exchange trading pair USDC-USDT with order optimization enabled and bid spread 0.01% with bid depth 0

Here are the steps to reproduce the issue (see attachments in the section below):

...

**Screenshots**
See attached

**Release version**
Dev-1.0.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*
config
![config](https://user-images.githubusercontent.com/95724407/146456469-e3a7ba31-4e05-4f03-99ba-e897e629a7c2.PNG)

best bid before bot start .9981
![beforebotstart](https://user-images.githubusercontent.com/95724407/146456487-2331409d-5f84-4faf-9c5d-16243c4c5b59.PNG)

best bid after bot start .9981 + my order on top
![afterbotstart](https://user-images.githubusercontent.com/95724407/146456495-5087795e-5f15-4cee-ad23-c0a56ee619b4.PNG)

order submitted by bot on top of best bid
![ordersubmittedbybot](https://user-images.githubusercontent.com/95724407/146456502-beaf3454-0e58-472e-acc9-c4a092eebdab.PNG)

status best bid
![bestbidstatus](https://user-images.githubusercontent.com/95724407/146456507-22faff4c-7abc-46fe-8281-715b05b5231c.PNG)

**Optional: your discord username:**
Karma#5173

**Comment by rapcmia** [comment]
Hi @Perream2, I tried to replicate this by testing different markets on loopring, and seems to be in line with the ongoing issue on bid_spread calculation found on ticket #3016. This will be linked to the ticket and you may also add a comment about it.

**Comment by rapcmia** [comment]
There is still an ongoing issue with Loopring's incorrect bid spread calculation, please refer to ticket #3016, and will tag this ticket as a duplicate/close for now. Thank you
