### ISSUE TITLE
PnL : Performance in the UI displays N/A status

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4957]
**Describe the bug**
When running a liquidity mining strategy with multiple markets, after getting multiple fills, the PnL in the UI is unable to display the correct information. Turns out that this happens because each market uses different symbols in the History performance.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a liquidity mining strategy
2. Add multiple markets with the same base but different quotes.
3. Set the base as the token to be used to provide liquidity.
4. Start the strategy and wait for filled orders.
5. Observe the PnL in the UI (bottom section), on the first trade, it will display the right information but as soon as the other markets get a fill, PnL will show N/A

**Screenshots**
First screenshot prior to other markets getting a fill:
![pnl1](https://user-images.githubusercontent.com/57189990/147181132-c31c7ca8-59f6-425f-96c5-e94a4749d0bf.png)

After other markets get a fill:
![image](https://user-images.githubusercontent.com/57189990/147181330-3d8933e3-50a4-4486-8c74-e6bd9d608527.png)

History Performance for each markets:
![image](https://user-images.githubusercontent.com/57189990/147181576-04aff31f-311f-4228-a8f5-15bfb1f60bea.png)
![image](https://user-images.githubusercontent.com/57189990/147181631-8e78da65-85cb-4f72-afbf-029dce654ff9.png)
![image](https://user-images.githubusercontent.com/57189990/147181683-1138ecb0-cfbf-473b-9cbb-6f166eeb64ee.png)

**Release version**
0.46.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by sisco0** [comment]
The referred source code is attached below:

https://github.com/hummingbot/hummingbot/blob/cb3ee5a30a2feb0a55ceca9d200c59662d7e3057/hummingbot/client/ui/interface_utils.py#L64-L79

**Comment by nikspz** [comment]
Still facing that issue on development (dev-1.6.0)
![image](https://user-images.githubusercontent.com/83953535/174108837-81afabde-c488-4b73-9ca2-f60e2b98659e.png)

**Comment by rapcmia** [comment]
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to component on Liquidity Mining strategy

**Comment by sisco0** [comment]
What would be the desired output that you would like to see in this field taking into account the shared data?
Would it be a quantity expressed in AVAX or in USD?

**Comment by rapcmia** [comment]
The current design of the `Liquidity Mining strategy` supports multiple markets with the same quote tokens. There are plans to improve this strategy in our future releases. The HBF team will be working on improving the docs and adding the limitation of each strategy as well
