### ISSUE TITLE
AscendEx: cannot run due to web socket connection errors

### ISSUE THREAD

**Issue by zappra** [hummingbot/hummingbot#4959]
**Describe the bug**
AscendEx web socket connections are being rate limited. A variety of HTTP error codes are being generated: 502, 524, 429, 403

A bot that is running will mostly work ok in the presence of these errors as the REST API seems to be unaffected. However, you cannot then restart the bot as the connector will not initialise properly

This effectively renders AscendEx unusable

**Steps To Reproduce**
This is is IP specific and AscendEx support has confirmed that web socket connections are being rate limited (see attached chat)

Have also attached example log showing the escalation of HTTP errors

[ascendex_support_chat.txt](https://github.com/hummingbot/hummingbot/files/7769575/ascendex_support_chat.txt)
[logs_conf_pure_mm_x1.log](https://github.com/hummingbot/hummingbot/files/7769577/logs_conf_pure_mm_x1.log)

**Comment by trupa** [comment]
Note that this happens a when running several bots from the same IP. When the errors start to occur, the connector tries to open another socket after 5 seconds, when a lot of bots start doing that, the IP gets flagged for too many requests (error 429 from Ascendex firewall)

**Comment by jacurutu1984** [comment]
i have the same issue 
Describe the bug
My bot don't work anymore. the bot is unable to connect to ascendex orderbook.

Steps To Reproduce
// A concise description of the steps to reproduce the buggy behavior:
start the bot and you get the error message

Here are the steps to reproduce the issue (see attachments in the section below):

    Set up your configuration file with these parameters: connect to my config
    Start the bot using this command: start
    ...

Screenshots

![hummingbot_issue_23_12](https://user-images.githubusercontent.com/48470964/147542917-76037b2c-c9b1-4a99-98f6-530a8fd65868.png)


Release version
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.46.0

Attachments
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those!
[logs_and_config.zip](https://github.com/hummingbot/hummingbot/files/7783534/logs_and_config.zip)


WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!

Optional: your discord username:

**Comment by Baehn** [comment]
I'm running one bot on ascendex and I get 524 errors all the time. I attached one part of my log file
[logs_conf_pure_mm.log](https://github.com/hummingbot/hummingbot/files/7789068/logs_conf_pure_mm.log)
.

**Comment by zappra** [comment]
According to the AscendEx API telegram support:

"currently we allow 4 websocket connection requests per minute, if violated, the IP will be banned for 15 minutes."

They also say:

"we've seen huge number of websocket connections recently, so we are adjusting the rate limit rules from time to time. A separate rate limit manager is been developed and will be roll out over the next one or two weeks. We will have more information on rate limit by then"

Is this issue being looked at, and is anyone on the HB team working with AscendEx to figure out what the rate limits are and that the HB client adheres to them?
