### ISSUE TITLE
Bitmart order book data source keeps losing connection but the failure is hidden 

### ISSUE THREAD

**Issue by mhrvth** [hummingbot/hummingbot#4961]
**Describe the bug**

The order book websocket keeps being disconnected but the failure is hidden. The exception is caught, but not reported anywhere. The connector silently reconnects.

**Steps To Reproduce**

1. Enable ConnectionError logging
2. Run pure MM with the Bitmart connector
3. Examine logs

**Release version**

0.46

**Screenshots**

![image](https://user-images.githubusercontent.com/7762229/147267033-ff772370-49c7-4665-a9bb-b442dcad5cc9.png)

**Comment by mhrvth** [comment]
It's possible that the pings we send are being ignored by Bitmart, because they're being sent frequently enough. 
Try sending the ping as a text to see if it will solve the issue.
https://developer-pro.bitmart.com/en/ws/spot_ws/limit.html

**Comment by rapcmia** [comment]
The fix has been applied on the upcoming hummingbot version 1.5
