### ISSUE TITLE
Exception thrown in liquidity mining strategy when no orders are available on either side of the order book

### ISSUE THREAD

**Issue by klpanagi** [hummingbot/hummingbot#4962]
**Describe the bug**
An exception is thrown in liquidity mining strategy while trying to create budget allocation calculate volatility (`update_volatility`), when either side of the order book is empty.
The error is raised within the `update_volatility()` and `create_budget_allocation()` methods of the `LiquidityMiningStrategy` class. You can cross-check this from the attached log file.

Furthermore, I did try with the `pure_market_making` strategy, where the error is also reported in logs, though an exception is not raised. 

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
This can be reproduced on any market. The only dependency is that at least one side of the order book (bid/ask) has to be empty
...

**Screenshots**
![Screenshot from 2021-12-23 17-37-06](https://user-images.githubusercontent.com/4770702/147280257-325c9613-4a3b-48c4-a912-6ea05137819d.png)
![Screenshot from 2021-12-23 19-34-56](https://user-images.githubusercontent.com/4770702/147280261-bdc926b7-8347-44ed-b05d-055d6e14a797.png)

**Release version**
0.4.6

**Attachments**
Log file attached.
[hummingbot.log](https://github.com/hummingbot/hummingbot/files/7770956/hummingbot.log)

**Discord: klpanagi#2483**

**Comment by rapcmia** [comment]
Severity: P2
Bounty: 50000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to a component in Liquidity mining strategy

**Comment by MementoRC** [comment]
This is reproducible with adding a case to the testsuite. This should not be too difficult to correct

**Comment by JeremyKono** [comment]
Assigning this issue to @MementoRC. Thank you for your contribution!

**Comment by rapcmia** [comment]
The fix has been added to the upcoming version 1.9.0 release.
