### ISSUE TITLE
Binance: Best prices under ticker and status are unsynchronized with the order book

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#4964]
**Describe the bug**
- Best prices are unsynchronized on status and ticker command vs exchange.

**Steps To Reproduce**
1. create a strategy - pure_mm 
2. select exchange (my case binance) then select pair (best on mid/high liquid markets)
3. start strategy and observe `ticker --live` or `status --live` command
...

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/147303057-2f3c31ee-bc2c-445c-8ee5-1aacb732bf68.png)
- using `status --live` command

![image](https://user-images.githubusercontent.com/54516858/147303121-dc9b73e5-4942-4e0c-b84a-83f2c08b6598.png)
- using `ticker --live` command

https://user-images.githubusercontent.com/54516858/147303224-4af39e9f-648c-491d-8a1e-518e619cc4da.mov

https://user-images.githubusercontent.com/54516858/147303240-aefb39c8-1e64-4566-b330-1ec40658174f.mov

**Release version**
0.46.0

**Attachments**
[delay.zip](https://github.com/hummingbot/hummingbot/files/7772004/delay.zip)

**Comment by rapcmia** [comment]
This has been tested on the latest version, delay is expected when markets are too volatile
