### ISSUE TITLE
WazirX not tracking all filled orders

### ISSUE THREAD

**Issue by jellebuth** [hummingbot/hummingbot#4966]
**Describe the bug**
WazirX exchange is not recording all traded made. I use cross-exchange market making on wazirx, for multiple pairs, I start with 5 of coin x (could be any coin). Overnight I trade and I end up with 8 coins x. XEMM is designed to be delta neutral, so this should not be the case. After running the history command for the past night, it shows that the traded volume of coin x is on wazirx is the same as for binance, implying that there should be no change in the inventory of coin x.

I also downloaded the trade history from Wazirx, this shows trades of coin x that are not recorded by hummingbot. This means that filled orders are not correctly. 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behaviour**:
Run cross-exchange market making on wazirx (coins could be ICP-USDT, ONE-USDT(happens most on ICP). Min profitability to 0.5, slippage buffer to 0.2. Rest of parameters at default settings. Min order amount is at least 30 dollars worth of coin x.

let the bot run for at least a day or two.
**Screenshots**
Starting balance
![image](https://user-images.githubusercontent.com/83583507/147343874-e4d40935-d36e-41db-8715-d1e795742945.png)

Ending balance
![image](https://user-images.githubusercontent.com/83583507/147343940-b22a181c-cd62-4607-92a6-c159e1413544.png)

Trading history in the time inbetween 
![image](https://user-images.githubusercontent.com/83583507/147343976-bdb4ce86-de88-441e-ad2b-b1fb17d40ba2.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.46

**Optional: your discord username:**
Jelle {Cryptobot}#3627

**Comment by rapcmia** [comment]
Connector has been removed.
