### ISSUE TITLE
DEX Connector for Terra in Gateway v1

### ISSUE THREAD

**Issue by bctoh** [hummingbot/hummingbot#4971]
**Bug Description**
There is an issue in connecting to the Terra ecosystem. After inputting the terra wallet address and seeds, the error message raised is `Error: [Errno 2] No such file or directory`. The bug persists when installing it via source or docker.

**Steps To Reproduce**
- Install hummingbot either through source or docker (macOS Big Sur v11.6.1)
- Use `connect terra` command and input address as well as seed phrase
- Error `Error: [Errno 2] No such file or directory` would be raised
- Test the connection by entering command `connect` and note that under Terra, hummingbot marked `Yes` for `Keys Added` but `No` for `Keys Confirmed`

**Screenshots**
_Error message_
<img width="449" alt="Screenshot_2021-12-24_at_5 51 07_PM" src="https://user-images.githubusercontent.com/9085849/147478056-10b7fb52-73da-4b25-a884-752ca44767ce.png">

_No Keys added_
![Screenshot 2021-12-27 at 9 52 17 PM](https://user-images.githubusercontent.com/9085849/147478077-6faac899-0ac2-42b6-bf93-bea1925069bc.png)

**Release version**
Version: 0.46.0

**Attachments**

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/7780458/logs_hummingbot.log)

**Comment by aNicePlayer** [comment]
Same thing. 
Any way around it yet?

**Comment by babluco** [comment]
You need to run the gateway server see https://hummingbot.org/protocols/terra/#connection

**Comment by bctoh** [comment]
> Same thing. Any way around it yet?

Yes @babluco is right. Had to run the gateway server.

> You need to run the gateway server see https://hummingbot.org/protocols/terra/#connection

Thanks @babluco! I've managed to run the gateway server but am currently faced with an error when connecting to terra - `Error: Cannot connect to host localhost:5000 ssl:default [Connect call failed ('127.0.0.1', 5000)]` Screenshot attached below. Would you know how to troubleshoot this error?

<img width="465" alt="Screenshot 2022-01-04 at 7 10 10 PM" src="https://user-images.githubusercontent.com/9085849/148050556-67e9419c-6c4e-4f0e-8ff6-ab9825185e14.png">

**Comment by rapcmia** [comment]
Hi @bctoh,
It seems your client or gateway is not properly synced that's why the error occurs as `cannot connector host localhost:5000`. This normally occurs if you have an incorrect configuration, you may want to check this youtube video about setting up Terra and gateway [here](https://www.youtube.com/watch?v=JsSNi9PUdVQ). 

You might want to look into our docs also about setting up the gateway, there is a guide on how you can for docker and source build, https://hummingbot.org/protocols/gateway/#install-gateway-via-docker

**Comment by bctoh** [comment]
> Hi @bctoh, It seems your client or gateway is not properly synced that's why the error occurs as `cannot connector host localhost:5000`. This normally occurs if you have an incorrect configuration, you may want to check this youtube video about setting up Terra and gateway [here](https://www.youtube.com/watch?v=JsSNi9PUdVQ).
> 
> You might want to look into our docs also about setting up the gateway, there is a guide on how you can for docker and source build, https://hummingbot.org/protocols/gateway/#install-gateway-via-docker

Hi @rapcmia, thanks for taking a look! I've reinstalled it following the youtube video and the docs but still to no avail. Could it be because the terra connector is currently being refactored? I just noticed this message on the docs - screenshot below

<img width="1023" alt="Screenshot 2022-01-04 at 10 31 36 PM" src="https://user-images.githubusercontent.com/9085849/148074353-dfb4941c-b641-48d9-a1b2-b52015842455.png">

**Comment by rapcmia** [comment]
Hi @bctoh 
That's correct, our dev team is currently working on the Gateway V2 redesign, we don't have any update yet but this will be posted when available. I don't have the assets to run it on the mainnet so I set up a testnet client (source build) and seems to be working ok for me 

![image](https://user-images.githubusercontent.com/73840223/148081462-adda1ad0-61f0-46f6-aaa7-e52a2eb9c832.png)

I have attached my config files so you can check, you can visit our discord and our support should be able to assist you.
[arb-terra-kovan.zip](https://github.com/hummingbot/hummingbot/files/7808582/arb-terra-kovan.zip)

**Comment by bctoh** [comment]
> Hi @bctoh That's correct, our dev team is currently working on the Gateway V2 redesign, we don't have any update yet but this will be posted when available. I don't have the assets to run it on the mainnet so I set up a testnet client (source build) and seems to be working ok for me
> 
> ![image](https://user-images.githubusercontent.com/73840223/148081462-adda1ad0-61f0-46f6-aaa7-e52a2eb9c832.png)
> 
> I have attached my config files so you can check, you can visit our discord and our support should be able to assist you. [arb-terra-kovan.zip](https://github.com/hummingbot/hummingbot/files/7808582/arb-terra-kovan.zip)

Appreciate the help! Thanks for looking into it. I'm attaching my global config file here too. If you have time, could you help me take a look to check if anything flags up? 
[global_conf.yml.zip](https://github.com/hummingbot/hummingbot/files/7820013/global_conf.yml.zip)

**Comment by rapcmia** [comment]
Hi @bctoh 
No problem, The best place to assist you with your config is with help of our support team. You may visit our discord [here](https://discord.com/invite/hummingbot). I'll be closing this ticket for now since this is regarding an incorrect config, Thank you
