### ISSUE TITLE
Bybit Perpetual - Filled trades are not getting recorded

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#4975]
**Describe the bug**
Filled trades are not getting recorded on history, bottom nav, csv and sqlite files when running a perpetual market making strategy using Bybit Perpetual.

**Steps To Reproduce**
1. Create and run a perpetual_market_making strategy using Bybit Perpetual
2. Set spreads to a low value and wait for trades to get filled

**Screenshots**
<img width="1424" alt="Screen Shot 2022-01-03 at 1 42 43 PM" src="https://user-images.githubusercontent.com/64377055/148007120-9efd61ed-dc8c-4213-b2bb-5489a609cbb3.png">

**Release version**
development-1.0.0

**Attachments**
Logs and config: [bybit.zip](https://github.com/hummingbot/hummingbot/files/7805242/bybit.zip)

**Comment by rapcmia** [comment]
The fix for this issue has been applied on the Hummingbot version 1.4
