### ISSUE TITLE
bybit Oneway position mode issue

### ISSUE THREAD

**Issue by bazickoff** [hummingbot/hummingbot#4976]
**Describe the bug**

I'm running spot_perpetual_arbitrage strategy between kucoin and Bybit Perpetual  BTC-USDT
I get the error "This strategy supports only Oneway position mode. Please update your position mode before starting this strategy"
I'm sure that I'm using Oneway position mode on bybit

please note that on bybit each trading pairs has it own  position mode setting

**Release version**

0.46.0

**Attachments**
 
[conf_spot_perpetual_arbitrage_1.txt](https://github.com/hummingbot/hummingbot/files/7806586/conf_spot_perpetual_arbitrage_1.txt)

[logs_conf_spot_perpetual_arbitrage_1.log](https://github.com/hummingbot/hummingbot/files/7806672/logs_conf_spot_perpetual_arbitrage_1.log)

**Comment by RC-13** [comment]
Same issue #4316

**Comment by rapcmia** [comment]
Hi @bazickoff 
Please be advised that Spot Perpetual Arbitrage strategy works only for one-way positions at the moment while the Bybit perpetual connector only works for hedge mode on their USDT perpetuals. As per previous comment, we have created the github issue for tracking in case it will be refactor. I'll be tagging this ticket as close for now. Thank you
