### ISSUE TITLE
Connection error with Ascendex

### ISSUE THREAD

**Issue by sepa85** [hummingbot/hummingbot#4980]
**Describe the bug**
I get connection errors when I try to run the bot with aroon oscillator with Ascendex pair AKT/USDT. Same strategy with other spot (like kucoin) works well. Balance cannot retrive AKT price, so I just see the amount but not its price the USD value.

**Steps To Reproduce**
Try to run the bot with Ascendex on AKT/PAIR. Aroon oscillator strategy.

**Screenshots**
![Screenshot from 2022-01-07 04-24-06 - 1](https://user-images.githubusercontent.com/19758187/148487151-21c973d4-0624-473d-93c7-e74e3843a805.png)
![Screenshot from 2022-01-07 04-37-14](https://user-images.githubusercontent.com/19758187/148487742-f6a29884-e322-4610-b7f0-e1790f3d7936.png)

**Release version**
version 0.46.0 arm_beta, running on raspberry pi

**Attachments**
[logs_conf_aroon_oscillator_1.log.tar.gz](https://github.com/hummingbot/hummingbot/files/7826154/logs_conf_aroon_oscillator_1.log.tar.gz)
[conf_aroon_oscillator_1.yml.tar.gz](https://github.com/hummingbot/hummingbot/files/7826156/conf_aroon_oscillator_1.yml.tar.gz)

**Comment by sepa85** [comment]
The connection error is fixed. Maybe there were some problem in ascendex side.

The problem with the balance is still there. I have the same problem also with DAO in kucoin.

**Comment by JeremyKono** [comment]
With regards to the balance, you have to change the rate_oracle_source to AscendEX and change the global_token to USDT so the correct balance will show. See more info here: https://hummingbot.org/strategy-configs/rate-oracle/#rate_oracle_source

**Comment by sepa85** [comment]
Confirm it is working. Thank you
