### ISSUE TITLE
Binance: duplicate trade record in the history and sqlite file

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4990]
**Describe the bug**
Whenever the strategy is restarted as soon as a filled event takes place and the bot receives a completion event, it creates a duplicate trade record which will result in incorrect performance and aggregation.
The history and SQLite file show an incorrect trade count when compared with exchange record.
**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market-making strategy using Binance connector.
2. Start the strategy
3. Wait for an order to get filled.
4. Stop the strategy immediately after a fill happens and then restart.
5. Observe the log pane, if the message ` The market order_side order_ID has completed according to order status API.`

**Screenshots**
In the client, there are 3 trade record:
![image](https://user-images.githubusercontent.com/57189990/148886600-ee2717c4-d048-4828-9b5c-002aa615332a.png)
While in the exchange, it only shows two trade records:
![image](https://user-images.githubusercontent.com/57189990/148886648-445988c6-6920-4c74-97a7-b442d8973341.png)

**Release version**
0.46.0

**Attachments**
[logs_test-order-fill-issue-dev-binance.zip](https://github.com/hummingbot/hummingbot/files/7843957/logs_test-order-fill-issue-dev-binance.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by sisco0** [comment]
There seems to be an issue where both, the _order status API_ and _user stream_ actions are recorded.
Should we only store the _order status API_ or just to double check if the order name is already contained at our database?

**Comment by rapcmia** [comment]
The fix has been merged to Hummingbot version 1.1.0
