### ISSUE TITLE
Gate_io: duplicate trade record in the history and sqlite file with incremented order size

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4991]
**Describe the bug**
Whenever the strategy is restarted as soon as a filled event takes place, it creates a duplicate trade record and this duplicate trade will have double the size of the original trade. This behavior will result in incorrect performance and aggregation.
The history, CSV, and SQLite files show an incorrect trade count while the CSV and exchange match the information.

**Steps To Reproduce**
1. Create a pure market-making strategy using Gate_io connector.
2. Start the strategy
3. Wait for an order to get filled.
4. Stop the strategy immediately after a fill happens and then restart.
5. Observe the log pane, if the message The market order_side order_ID has completed according to order status API.

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/148888103-3dffe9b2-807b-412f-8658-68194bb260d2.png)
![image](https://user-images.githubusercontent.com/57189990/148888412-2aacfd50-4d13-4eee-ad94-cffcd045405f.png)

**Release version**
0.46.0

**Attachments**

[gate_pure_mm_btc-usdt.zip](https://github.com/hummingbot/hummingbot/files/7844028/gate_pure_mm_btc-usdt.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by fabien-benoit-1984** [comment]
@RC-13 I don't understand the issue.
This is the gate-io inteterface, for order status update. https://github.com/hummingbot/hummingbot/blob/cb3ee5a30a2feb0a55ceca9d200c59662d7e3057/hummingbot/connector/exchange/gate_io/gate_io_exchange.py#L650
Does it close the order incorrectly? Or it stops tracking an order created before suspension of the strategy?

@RC-13 may i contact you via email? I have some information regarding arbitrage and gate.io. Thanks.

**Comment by RC-13** [comment]
@fabien-benoit-1984 The order recorded in the SQLite file are being duplicated if we stop the client immediately then start after. The duplicated order also increments its filled order amount however this order is never submitted in the exchange. Note, the first fill is submitted successfully in the exchange but in the clients' history performance it will give you two trade records instead of just one.

**Comment by fabien-benoit-1984** [comment]
Can you try to cancel all of the orders first, before suspending the strategy. and then try to resume it. Does it display removed orders?

**Comment by RC-13** [comment]
For active orders that are suspended, they get canceled when the strategy is resumed or re-run. This issue on the gate_io connector is the same case for the Binance connector (#4990), with just the addition of the incrementing order size.

**Comment by rapcmia** [comment]
Tested and the issue seems to be fixed already.
