### ISSUE TITLE
MEXC - Intermittent update order status IndexError 

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#4992]
**Describe the bug**
After resuming the long term test bot that was stopped due to [MEXC system maintenance](https://support.mexc.com/hc/en-001/articles/4414108363161-MEXC-Extends-System-Maintenance) I noticed that it's now intermittently getting an `update_order_status IndexError` while the bot is running. Though the error appears frequently on the log pane I don't see any impact on the bot's behavior. Creating a ticket for tracking.

**Steps To Reproduce**
1. Create and run a pure_mm bot using MEXC

**Screenshots**
<img width="1423" alt="Screen Shot 2022-01-11 at 2 41 23 PM" src="https://user-images.githubusercontent.com/64377055/148897983-72f8d724-d7fc-4f86-b1bd-808647651844.png">

**Release version**
0.46.0

**Attachments**
Logs and config: [mexc.zip](https://github.com/hummingbot/hummingbot/files/7844437/mexc.zip)

**Comment by fabien-benoit-1984** [comment]
![image](https://user-images.githubusercontent.com/74528656/149339997-d7696b76-2db0-4d54-b0df-2f377707c69d.png)
it seems like there's a stale order, that doesn't get removed from a tracking list.

**Comment by rxlxrxsx** [comment]
The issue seems to self resolve and is no longer being encountered by the long term running test bot, will re-open if ever the bot encounters this issue again. Closing this ticket for now.

<img width="1422" alt="Screen Shot 2022-01-18 at 10 26 15 AM" src="https://user-images.githubusercontent.com/64377055/149860473-7942dfc5-1937-4a84-b3b2-e142c82df6d6.png">
