### ISSUE TITLE
Invalid trades getting recorded in the client

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4995]
**Describe the bug**
Opening ticket for tracking.
While testing on the refactors of the Binance connector, our test bot was able to capture an invalid trade wherein this order doesn't match the specified amount set in the strategy.  As per discussion with the dev, the problem is related to how the system currently handles the database session and the issue is happening in the latest branch but somehow difficult to replicate or shows a different behavior (could be related to #4990 and #4991)

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create any market-making strategy using Binance
2. Start the strategy and wait for multiple trades to get recorded.
3.  Run history --verbose and inspect if there are trades with unusual trade size
4. Check the SQLite file and verify if there  are trades with unusual trade size

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/149028471-69f6229b-867c-48f7-ad84-87fa74a95f81.png)

**Release version**
0.46.0

**Attachments**

[binance-order-amount-issue.zip](https://github.com/hummingbot/hummingbot/files/7850147/binance-order-amount-issue.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
The fix has been merged to Hummingbot version 1.1.0
