### ISSUE TITLE
Using export trades command then skipping on filename (ctrl + x) will create blank filename

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#4996]
**Describe the bug**
- When using the `export trades` [command](https://hummingbot.org/operation/export/#export-trades) then [exit from the question](https://hummingbot.org/operation/user-interface/#keyboard-shortcuts) using CTRL + X, bot will continue to save the trades using a blank filename with extension csv.

**Steps To Reproduce**
1. create any strategy
2. wait for filled trades
3. then use command `export trades`
4. when asked for filename simply press CTRL + X

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/149276243-3e1974b2-75c2-450b-b5ef-77aee21c4fb9.png)

![image](https://user-images.githubusercontent.com/54516858/149276231-0ec2bcad-4ce4-491c-8ce4-881f46c6e360.png)

![image](https://user-images.githubusercontent.com/54516858/149276250-2accdc9f-88d3-4e75-9e0d-38f91fdb90bf.png)

**Release version**
`0.46.0` / `dev-1.0.0` (docker / source build)

**Attachments**
[blank.zip](https://github.com/hummingbot/hummingbot/files/7860416/blank.zip)

**Comment by fabien-benoit-1984** [comment]
@PtrckM did you try to use upstream, and compile from source code?

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to a component

**Comment by leastchaos** [comment]
I would like to apply for this bounty.

**Comment by leastchaos** [comment]
I would like to apply for this bounty.

**Comment by JeremyKono** [comment]
Assigning this issue to @leastchaos. Thank you for applying!

**Comment by nikspz** [comment]
Fixed on development 1.8.0 with https://github.com/hummingbot/hummingbot/pull/5616
