### ISSUE TITLE
Bitmart - Filled order price on the logs does not matched history, CSV and trade history

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5000]
While checking order-filled events on Bitmart connector, filled order prices do not match the data of `history --verbose`. 
![Screenshot 2022-01-14 185603](https://user-images.githubusercontent.com/73840223/149319486-448050aa-bd7e-414d-b110-953c36536343.png)

However, looking into the data of `history`, CSV file, and connector's trade history have the same order prices.
![Screenshot 2022-01-14 190221](https://user-images.githubusercontent.com/73840223/149320172-8b79bfda-193a-4a3e-bf66-1b2b1024f55f.png)

**Steps To Reproduce**
1. Create a Pure market-making strategy and use Bitmart as a connector
2. Set spreads enough to make a trade 
3. Once you have good amount of trades, run `history --verbose` command
4. Compare the order prices of your CSV fille and Bitmart's trade history 

**Release version**
dev-1.0.0

**Attachments**
[pmm-bitmart.zip](https://github.com/hummingbot/hummingbot/files/7862309/pmm-bitmart.zip)

**Comment by fabien-benoit-1984** [comment]
@rapcmia what version do you use?
