### ISSUE TITLE
Acendex API ERROR: 100004 : Invalid value for argument orderId: orderId length must be between 0 and 1000

### ISSUE THREAD

**Issue by globeone** [hummingbot/hummingbot#5002]
**Describe the bug**
// A clear and concise description of what the bug is.
When running Hummingbot using the Ascendex API in the liquidity mining strategy getting screens full of API Error 10004 

100004 | INVALID_REQUEST_DATA | The HTTP request contains invalid field or argument

**traceback**
`2022-01-13 20:00:10,751 - 1 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - https://ascendex.com/4/api/pro/v1/cash/order/status API call failed, response: {'code': 100004, 'message': 'Invalid value for argument orderId: orderId length must be between 0 and 1000', 'reason': 'INVALID_REQUEST_DATA'}
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 655, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 704, in _update_order_status
    resp = await self._api_request(
  File "/home/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 419, in _api_request
    raise IOError(f"{url} API call failed, response: {parsed_response}")
OSError: https://ascendex.com/4/api/pro/v1/cash/order/status API call failed, response: {'code': 100004, 'message': 'Invalid value for argument orderId: orderId length must be between 0 and 1000', 'reason': 'INVALID_REQUEST_DATA'}`

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: see attached config file
2. Start the bot using this command: start
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/10052587/149401546-b332cf47-9531-4845-bf4f-964f3fa3421a.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.46.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[bug_b_logs_conf_liquid_a_usdt.log.txt](https://github.com/hummingbot/hummingbot/files/7865675/bug_b_logs_conf_liquid_a_usdt.log.txt)

[bug_b_conf_liquid_a_usdt.yml.txt](https://github.com/hummingbot/hummingbot/files/7865683/bug_b_conf_liquid_a_usdt.yml.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
Bhagavate bilala#6332

**Comment by globeone** [comment]
So I performed some experiments with a fresh bot and fresh user account.
At 17 markets and higher Ascendex starts to throw this error. If the number of markets is kept less than 16 per bot then the error doesn't occur. So, there is something in the way large numbers of markets are being handled.

**Comment by rapcmia** [comment]
Hi @globeone, we looked into this issue and test 17 to 20 markets and did not get the error however other issues took place such as markets going offline and failing to cancel orders. Upon checking the [Ascendex API docs
](https://ascendex.github.io/ascendex-pro-api/#how-to-subscribe),  batch orders allowed by Ascendex is 10 orders at a time
