### ISSUE TITLE
OKEx - Change the name of the okex connector to the new (OKX)

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5016]
Major cryptocurrency exchange OKEx has changed its name to OKX

**Impact**
1. Change the name of the OKEx connector to the new name
2. Recheck if there are other changes aside from the rebranding.

**Additional context**

https://www.okex.com/
https://www.okx.com/

**Comment by rapcmia** [comment]
Okx has been updated on version 1.5
