### ISSUE TITLE
Remove unwanted tables in the history verbose mode for XEMM and Arb strategies

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#5018]
**Describe the bug**
Unable to display all tables when running `history --verbose` for Arbitrage strategies and cross-exchange market-making strategy due to having multiple tables (13 tables).

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create any of the following strategies: Arbitrage strategies and cross-exchange market-making strategy
2. Start the strategy and wait for an order fill.
3. Run `history --verbose`
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/150244946-75dc9971-7b75-40fa-a260-49e2ed9eb82f.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/57189990/150245054-7e12b29a-630e-4d7b-b13e-e31b5a7dd05d.png)

**Release version**
Hummingbot 1.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Fixed on Hummingbot version 1.0.0
