### ISSUE TITLE
Avellaneda MM - orders not canceled after end_time and order_refresh_time

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5022]
**Describe the bug**
Avellaneda MM - orders not canceled after `order_refresh_time` and after `end_time` with  `order_refresh_tolerance disabled`

**Steps To Reproduce**
1. Create Avellaneda MM strategy with `execution_timeframe: from_date_to_date` or  `execution_timeframe: daily_between_times`
2. Set up `start_time` and `end_time` 
3. Set up `order_refresh_tolerance -1` 
4. Set up `order_refresh_time` with the condition that orders remain in the order book according to order_refresh_time when end_time arrives (i.e. from start_time to end_time = 1 min and order_refresh_time 11)
5. Wait till end_time

Actual behavior:
Orders stay in order book after end_time for a long time

Expected behavior:
Orders canceled after end_time

**Screenshots**
![image](https://user-images.githubusercontent.com/83953535/150336902-7c6a8c35-a0e4-4598-8839-deb438a86bb8.png)
![image](https://user-images.githubusercontent.com/83953535/150336921-d7b5ece2-e957-41f1-8b19-1b0d210da7b3.png)

**Release version**
Dev 1.0.0, windows gitbash, linux ubuntu

**Attachments**
[conf_avellaneda_market_making_3.txt](https://github.com/hummingbot/hummingbot/files/7905026/conf_avellaneda_market_making_3.txt)
[logs_conf_avellaneda_market_making_3.log](https://github.com/hummingbot/hummingbot/files/7905027/logs_conf_avellaneda_market_making_3.log)

**Comment by rapcmia** [comment]
Fixed on Hummingbot version 1.0.0
