### ISSUE TITLE
setup.py broken

### ISSUE THREAD

**Issue by oberstet** [hummingbot/hummingbot#5029]
**Describe the bug**
The change in https://github.com/hummingbot/hummingbot/commit/7399baed67dfe7b6648ff2f6360327478b065c12 modifies `install_requires` in [setup.py](https://github.com/hummingbot/hummingbot/blob/master/setup.py), but misses two commas, and adds a spurious package "sync-timeout" which doesn't exist.

**Steps To Reproduce**
`pip install -e .` from the top folder.

**Release version**
Current master branch.

**Comment by rapcmia** [comment]
the `sync_timeout` has been removed from `setup.py` on latest version
