### ISSUE TITLE
Failing docker build using staging branch

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#5043]
**Describe the bug**
- Unable to build docker image of [staging branch](https://github.com/hummingbot/hummingbot/tree/staging)

**Steps To Reproduce**

```bash
# assuming you already installed docker

git clone -b staging https://github.com/hummingbot/hummingbot staging
cd staging
docker build -t coinalpha/hummingbot:staging -f Dockerfile .
```

**Screenshots**
- aws linux (ubuntu 20.04)
- Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
![image](https://user-images.githubusercontent.com/54516858/150890256-fed6a799-ece2-4361-9677-7c0165367def.png)
![image](https://user-images.githubusercontent.com/54516858/150890285-e1f40c63-3dc3-431f-98e2-1d30ff69441d.png)

**Comment by rapcmia** [comment]
Tried to build docker images for the following:
Windows Ubuntu18LTS: passed
![image](https://user-images.githubusercontent.com/73840223/150897882-ae0eccd0-d6fb-4c80-bdef-72309c8b0d09.png)

Macbook (m1, ARM image): passed
![image](https://user-images.githubusercontent.com/73840223/150898078-c92e900c-28ef-465d-a2bc-649178d59f74.png)

Test server AWS: failed on 3/3 attempts
![image](https://user-images.githubusercontent.com/73840223/150898798-150695e8-5fc6-4370-9c79-8ff0d9583d27.png)

**Comment by rapcmia** [comment]
Fixed on the latest release.
