### ISSUE TITLE
Pure MM / Avellaneda MM - Cancelled order turns to a hanging order after restarting the strategy

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#5044]
**Describe the bug**
When running pure_mm or avellaneda_mm strategy with hanging order enabled it creates a ghost hanging order (based on the order that was cancelled after stopping the bot) every time you restart the bot. So far this has been observed to be happening on Binance, Bitfinex and OKEx. Tested on Ascendex, Gate.io and Kucoin as well but didn't get the same issue.

<img width="1423" alt="Screen Shot 2022-01-25 at 10 37 01 AM" src="https://user-images.githubusercontent.com/64377055/150921188-b5dfa716-c18c-48a1-967b-4675811b43db.png">

**Steps To Reproduce**
1. Create and run a pure_mm or ave_mm strategy
2. Enable hanging orders (The issue only persists if hanging orders is enabled)
3. Start the strategy, once there are orders already placed you can now stop the running strategy
4. Restart the strategy and notice that hanging orders are created based on the order that was cancelled after stopping the bot

NOTE: For Bitfinex and OKEx I noticed that only the most recent cancelled order turns into a hanging order after restart

**Release version**
dev-1.0.0

**Attachments**
Logs/config: [hanging_order.zip](https://github.com/hummingbot/hummingbot/files/7931040/hanging_order.zip)

**Comment by rapcmia** [comment]
Fixed on the Hummingbot version 1.0.0
