### ISSUE TITLE
Binance: Conflicting trade order information

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#5056]
**Describe the bug**
When running multiple pure market-making bots using the binance connector and one Binance account (same API key or different API key per bot/instance). If a fill event happens on each bot and `history --verbose` is run, there are instances wherein a fill trade record from one bot will be displayed in the other, or trades of each both are reported in each test bot. This will result in an incorrect performance.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Setup two or three pure market-making bots using Binance as the connector
2. Set a tight spread for each bot for faster fill
3.  Start the strategies.
4. Run `history --verbose` on each instance after they get a fill
5. Check each filled trade recorded and look for a price or order size that doesn't correspond to the amount and price of the market specified in the strategy of that bot being checked.

**Screenshots**
Bot 1 running in a cloud server:
![btc-usdt-market](https://user-images.githubusercontent.com/57189990/151279653-14846e70-b41c-4a17-b3ca-9bc71b6b62ef.png)
Affected order_ID:`x-XEKWYICX-BBCUT42f51643246975001220`  --> From DOGE-USDT market
client_order_id=`x-XEKWYICX-BDEUT61441643246969006935'`
trade_id=`396314113`
exchange_order_id=`2309226043`
Bot 2 running from local device:
![doge-usdt-market](https://user-images.githubusercontent.com/57189990/151279690-2730f9b6-51a2-461d-a0f0-86a6a2b999fe.png)

**Release version**
dev 1.0

**Attachments**
[binance-conflict-order.zip](https://github.com/hummingbot/hummingbot/files/7947000/binance-conflict-order.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by leastchaos** [comment]
binance fill trade event seems to be broken. I think strategy using filled trade events like XEMM are having weird issues due to this.  Can this fix be prioritized, please?
