### ISSUE TITLE
History: CSV randomly getting split to multiple files

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#5057]
**Describe the bug**
Opening ticket for tracking:
When running a test for a couple of days or even less, there are scenarios that the CSV file is suddenly split into multiple files which sometimes causes an issue displaying the history performance when run in verbose mode. So far I've seen this occur on Binance, and Gate_io

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create any market making strategy using Binance or Gate_io connector
2. Start the strategy and leave it running for a long duration
3. Regularly check your test bot by running history --verbose
4. Check the data file folder if an error occurs when the history --verbose command is run.

Note: replicating the behavior is difficult to do so, I tried several steps such as:
- Interrupt the bot after a fill event, was able to create another CSV file but happened once only and unable to do it again even if I repeat the same method.
- Interrupting the network when a filled event happen
- Change configuration such as changing the markets after getting a fill
I will update add more details if in case I get to capture the issue again.
**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/151260006-d56e1e34-c01b-4403-b343-6c1fa2a0a263.png)
![image](https://user-images.githubusercontent.com/57189990/151260137-c0c23875-928c-4372-a172-d97d886c874a.png)

**Release version**
0.46.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Fix has been merged to staging branch `v1.2-staging` for Hummingbot 1.2.0
