### ISSUE TITLE
History command shows Trade PnL of zero even after few trades

### ISSUE THREAD

**Issue by akim-tor** [hummingbot/hummingbot#5069]
**Describe the bug**
The history command shows a zero Trade P&L even after a few trades.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Compile from source on Linux (in this case on Amazon EC2 instance)
2. Run any strategy
3. After a few trades, run the 'history' command.
...

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/68867545/151622356-463418e5-27a3-4a5d-a679-607f89d67f5e.jpg)

**Release version**
Version 1.0.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by leastchaos** [comment]
same issue here

**Comment by toniohc** [comment]
Same here on docker container with 1.0.0. 
Only fee are displayed

**Comment by rolandgem** [comment]
same with me. My bot has already completed several round trip trades and I can only see the fees. It shows 0 Trade PnL

**Comment by Seroleashed** [comment]
Some on my end, too, running 1.0.0 on a paper trading account with the Avellaneda Strategy on binance as well as ascendex (to give some more cues as to what's going on). On Binance 194 buy and 178 sell orders were filled so far.

**Comment by rolandgem** [comment]
How can we get the Hummingbot team to prioritize this?

**Comment by ReneP78** [comment]
+1  //P&L showing always 0 regardless of exchange and market

**Comment by BGTCapital** [comment]
Same issue here. Some bots are winding down due to kill_switch_rate

**Comment by presidentemattia** [comment]
Is it possibile to give high priority to this bug? I think this is a very big issue. We need a fix to continue using 1.0.0 version. Thanks.

**Comment by ReneP78** [comment]
I absolutely agree with the others that this is the most major bug currently known. At the same time it cannot be that big effort to fix since trade P&L is simply calculated as the difference of assets-hold value and assets-current value. And these two values are shown up correctly in the history,

**Comment by lattech1** [comment]
Same bug. This important issue seems to be open now for the last 6 days here. Would be great if it gets fixed soon. Thanks

**Comment by Corran57** [comment]
Same here, with 1.0.0

**Comment by akim-tor** [comment]
I started getting annoyed with the trade PnL and took some time to see if I can debug it. I warn that I am not the greatest coder in the world.

I found that the zero trade pnl was due to the _are_derivatives() function not working properly. "NILL" should actually be "NIL".

I forked and created a branch called "fix/history pnl". So far it looks like it's working. I haven't tested it against derivatives pnl since I haven't gotten to market making derivatives.

**Comment by toniohc** [comment]
Will try this. Thanks 👍

**Comment by toniohc** [comment]
For those who want to edit, it's the file hummingbot/client/performance.py
And it's line 170 
![image](https://user-images.githubusercontent.com/2438572/152637201-ea409901-e05e-4e15-b1df-f7f346aa73c6.png)

**Comment by presidentemattia** [comment]
It worked for me the edit for the docker install.
I'm wondering if is there any news about the real fix of this issue.
It sounds strange to me that is not considered like a real big issue.

**Comment by rapcmia** [comment]
Fixed on the latest Hummingbot version 1.0.1
