### ISSUE TITLE
XEMM Taker Filled trade info is incorrect

### ISSUE THREAD

**Issue by leastchaos** [hummingbot/hummingbot#5070]
**Describe the bug**
// A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/64965782/151642323-91cc02ad-a636-4ec8-b396-5d965e5ca28c.png)
filled trade info incorrect
run history --verbose

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
run xemm and wait for fill on any market.
check fill trade info of taker exchange with exchange and bot.
I checked binance seems to be working fine.
should be a kucoin issue.
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
v1.0.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Hi @leastchaos can you share your logs or config file so we can have a look? Just checking if you happen to encounter errors while executing trades on the client. Thank you

**Comment by leastchaos** [comment]
Hi @rapcmia, I don't have the logs now but there was no issue in trade execution for these trades. Just history --verbose doesn't match actual trades executed. I think the trade history issue should just be for kucoin only
