### ISSUE TITLE
Binance perpetual get position not working correctly

### ISSUE THREAD

**Issue by leastchaos** [hummingbot/hummingbot#5074]
**Describe the bug**
// A clear and concise description of what the bug is.
trading pair format is BASE**-**QUOTE in strategy.

Binance account_positions return
![image](https://user-images.githubusercontent.com/64965782/151691077-4246cdb7-f89b-4237-bc77-07ceda94c8fe.png)
Bybit account_position return
![image](https://user-images.githubusercontent.com/64965782/151691092-03000258-3ebb-48ec-8791-a92c37d67cd6.png)
I think standardizing the key format for account positions should be handled by the connector side rather than perpetual trading class

get position under class PepertualTrading does not account for this difference.

```
    def position_key(self, trading_pair: str, side: PositionSide = None) -> str:
        """
        Returns a key to a position in account_positions. On OneWay position mode this is the trading pair.
        On Hedge position mode this is a combination of trading pair and position side
        :param trading_pair: The market trading pair
        :param side: The position side (long or short)
        :return: A key to the position in account_positions dictionary
        """
        if self._position_mode == PositionMode.ONEWAY:
            return trading_pair
        elif self._position_mode == PositionMode.HEDGE:
            return f"{trading_pair}{side.name}"

    def get_position(self, trading_pair: str, side: PositionSide = None) -> Optional[Position]:
        """
        Returns an active position if exists, otherwise returns None
        :param trading_pair: The market trading pair
        :param side: The position side (long or short)
        :return: A position from account_positions or None
        """
        return self.account_positions.get(self.position_key(trading_pair, side), None)
```
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
v1.0.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by cardosofede** [comment]
I had the same issue last week, I forgot to create the issue. Nice one @leastchaos

**Comment by cardosofede** [comment]
I think that we need to use the Hummingbot convention to name the positions BASE-QUOTE.

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related on certified connector, Binance perpetuals

**Comment by MementoRC** [comment]
@rapcmia @cardosofede @leastchaos Proposed PR: https://github.com/hummingbot/hummingbot/pull/5867
This does seem to be an intrusive change (for the cosmetic aspect of the issue), so the proposal above can be considered a quick workaround as it attempts to only solve the issue with a limited amount of changes.
More complete solution could perhaps update the PerpetualExchange to make the behavior systematic and thus propagate the changes to all perpetual connectors

**Comment by JeremyKono** [comment]
Assigning this issue to @MementoRC. Please next time comment first if you want this assigned to you so we can do the steps accordingly. Thanks

**Comment by JeremyKono** [comment]
This bounty has been paid. Thanks!
