### ISSUE TITLE
Bybit spot perpetual arbitrage one-way mode

### ISSUE THREAD

**Issue by bazickoff** [hummingbot/hummingbot#5093]
Bybit perpetual connector only works for hedge mode
now Bybit perpetual api support Position Mode Switch to one way mode , it will be really helpful to include that feature
https://bybit-exchange.github.io/docs/linear/#t-switchpositionmode

**Comment by ReneP78** [comment]
+1
would be an important fix since strategies like spot-perpetual-arbitrage do not work without this setting

**Comment by filipmacek** [comment]
just add new param `position_idx` ,and set it to 0 when making create order api request

**Comment by bazickoff** [comment]
@filipmacek 
Hi thanks for the info, can you help me to add this param position_idx to the code ,I have little programming skill !

**Comment by filipmacek** [comment]
> @filipmacek Hi thanks for the info, can you help me to add this param position_idx to the code ,I have little programming skill ! should i edit _create_order() on bybit_perpetual_derivative.py file ?

Yes, you are correct edit `params` object

**Comment by nikspz** [comment]
Should be fixed with https://github.com/hummingbot/hummingbot/pull/5233

**Comment by nikspz** [comment]
Bybit perpetual works for One-way now on development 1.9.0, closing that issue
![image](https://user-images.githubusercontent.com/83953535/196650438-10f703c5-aa95-4fb1-bb23-29ac59bf108f.png)
![image](https://user-images.githubusercontent.com/83953535/196650474-12686e45-726f-4d50-8f4c-90287b9baf35.png)
