### ISSUE TITLE
Bybit not connecting 

### ISSUE THREAD

**Issue by ReneP78** [hummingbot/hummingbot#5096]
**Describe the bug**
when trying to connect to bybit_perp by adding the API keys I always get the error  " 'NoneType'  object has no attribute 'itmes' "  Connect status shows 'keys added - yes' and ' keys confirmed - no'. All other exchanges connect without any problems. 

**Steps To Reproduce**
Start a new Hummingbot instance, connect bybit_perpetual, enter API keys

**Release version**
Release v1.0.0. Win10, Subsystem Ubuntu 18.04.2, Docker Desktop.

**Attachments**
[logs_my_perp-test.log](https://github.com/hummingbot/hummingbot/files/8009463/logs_my_perp-test.log)

**Comment by rapcmia** [comment]
Hi @ReneP78 the error seems to be corresponding to an invalid API key. I tried mine seems to be working ok on Win11 docker build ubuntu18lts
![image](https://user-images.githubusercontent.com/73840223/152900172-b28df258-aade-40b1-8a75-65bf995800fe.png)

Please try again using valid keys or generate a new one. Tagging this as resolved for now, thank you

**Comment by bazickoff** [comment]
@rapcmia @ReneP78 
I have the same exact issue with bybit ,
 Install Hummingbot from Source  on Win10, Subsystem Ubuntu 18.04
Install Hummingbot from Source  on Win10 without Subsystem Ubuntu works fine

**Comment by cengovski** [comment]
> @rapcmia @ReneP78 I have the same issue with bybit :,
> 
> * Install Hummingbot from Source  on Win10, Subsystem Ubuntu 18.04, bybit api not connecting
> * Install Hummingbot from Source  on Win10 without Subsystem Ubuntu works fine

Hi. How can i create hummingbot without subsystem

**Comment by cengovski** [comment]
İm using windows 10 - ubuntu 18.04

**Comment by rapcmia** [comment]
The fix for this issue has been applied on the Hummingbot version 1.4
