### ISSUE TITLE
error when Install Hummingbot from Source 

### ISSUE THREAD

**Issue by bazickoff** [hummingbot/hummingbot#5112]
**Describe the bug**
I got this error when Install Hummingbot from Source on ubuntu 18.04.6

`(hummingbot) root@vultr:~/hummingbot# bin/hummingbot.py
00:09:52 - root - Error loading configs. Your config file may be corrupt. unacceptable character #x0082: special characters are not allowed
  in "conf/conf_global.yml", position 5109 (See log file for stack trace dump)
00:09:52 - root - Error writing configs: unacceptable character #x0082: special characters are not allowed
  in "conf/conf_global.yml", position 5109 (See log file for stack trace dump)
Traceback (most recent call last):
  File "bin/hummingbot.py", line 79, in <module>
    ev_loop.run_until_complete(main())
  File "/root/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bin/hummingbot.py", line 52, in main
    AllConnectorSettings.initialize_paper_trade_settings(global_config_map.get("paper_trade_exchanges").value)
  File "/root/hummingbot/hummingbot/client/settings.py", line 173, in initialize_paper_trade_settings
    for e in paper_trade_exchanges:
TypeError: 'NoneType' object is not iterable
`

**Steps To Reproduce**

1. setup fresh ubuntu 18.04.6 server
2. install hummingbot 

- Download install script
    wget https://raw.githubusercontent.com/hummingbot/hummingbot/development/installation/install-from-source/install-source-ubuntu.sh

- Enable script permissions
    chmod a+x install-source-ubuntu.sh

- Run installation
    ./install-source-ubuntu.sh

3- run bin/hummingbot.py then enter the password and press ok
...

**Release version**
v1.0.1

**Comment by JeremyKono** [comment]
Hi, I just tested this issue and it seems to work on my ubuntu AWS server without issues. On what step did you encounter the issue?

**Comment by jojoharu** [comment]
I have the same problem when I install from source.
Platform: Windows 10 Business
Command: winpty python bin/hummingbot.py
I can set the password. and after that it has error.

15:40:31 - root - Error loading configs. Your config file may be corrupt. 'charmap' codec can't decode byte 0x82 in position 5288: char
acter maps to <undefined> (See log file for stack trace dump)
15:40:31 - root - Error writing configs: 'charmap' codec can't decode byte 0x82 in position 5288: character maps to <undefined> (See lo
g file for stack trace dump)
Traceback (most recent call last):
  File "bin/hummingbot.py", line 79, in <module>
    ev_loop.run_until_complete(main())
  File "C:\Users\asawin.w\Anaconda3\envs\hummingbot\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "bin/hummingbot.py", line 52, in main
    AllConnectorSettings.initialize_paper_trade_settings(global_config_map.get("paper_trade_exchanges").value)
  File "C:\python\hummingbot\hummingbot\client\settings.py", line 173, in initialize_paper_trade_settings
    for e in paper_trade_exchanges:
TypeError: 'NoneType' object is not iterable

**Error**
1. Undefined on charmap 0x82 in file envs\hummingbot\Lib\encodings\cp874.py
2. global_config_map.get("paper_trade_exchanges").value return 'NoneType' that cannot be iterated on function "initialize_paper_trade_settings" in file hummingbot\hummingbot\client\settings.py line 173

**Comment by rapcmia** [comment]
Hi @bazickoff Good day to you. I tried to use the script installation for Ubuntu18LTS for both local and AWS instance and working ok for me. Can you please try it again this time and let us know if this is still an issue? Thank you

**Comment by rapcmia** [comment]
Run installation script on fresh Ubuntu18 and Ubuntu20.04 server and seems to be working ok. Closing ticket for now
