### ISSUE TITLE
Hedge strategy rate limit

### ISSUE THREAD

**Issue by Sladoeg** [hummingbot/hummingbot#5114]
When the hedge strategy starts the API rate limit is reached instantly.

v. 1.0.1
hedge strategy
binance perpetual connector
kucoin spot connector

![image](https://user-images.githubusercontent.com/17851813/153840230-50f21e99-bce6-438f-a155-f4067c1b1d05.png)
![image](https://user-images.githubusercontent.com/17851813/153840296-a2466e12-2c51-4e08-934b-931b79043813.png)
![image](https://user-images.githubusercontent.com/17851813/153840550-29ba5a04-fdbd-486b-8202-c88a7775e658.png)

**Comment by rapcmia** [comment]
Hi @Sladoeg good day
We would like you to check out our version 1.12.0 which has the revamped Hedge strategy. Closing ticket for now, else please reopen with attach config and log files for investigation. Thank you!
