### ISSUE TITLE
staging - information error version no. and codebase url

### ISSUE THREAD

**Issue by leastchaos** [hummingbot/hummingbot#5121]
**Describe the bug**
// A clear and concise description of what the bug is.
staging version still showing v1.0.0
codebase information should be hummingbot/hummingbot

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/64965782/154423916-458bb3f9-55c6-4ea6-8490-0c22ea317e74.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
staging: 1.0.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
This has been fixed
