### ISSUE TITLE
ascendex cannot recover from fail to cancel order errors

### ISSUE THREAD

**Issue by leastchaos** [hummingbot/hummingbot#5122]
**Describe the bug**
// A clear and concise description of what the bug is.
This bug is present in both v1.0.0 and v1.1.0
For ascendex exchange, the bot cannot recover from fail to cancel order if the orders does not exists in the market.
bot have to be restarted to continue.
This is likely resulting from failed to create orders on the exchange as the bot detects there is a created order but the connector does not still has the order.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Run any strategy on ascendex until market starts to fail. This may require some simulation by disconnecting and connecting.
If the order is treated as created on the bot while the exchange does not have, the bot will be stucked in fail to cancel order.

**Screenshots**
// If applicable, add screenshots to help explain your problem.
```
2022-02-13 14:45:05,007 - 1138414 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Failed to cancel order HMBot-BBOLUSD1644763433006692: Failed to cancel order - HMBot-BBOLUSD1644763433006692. Order not found.
Traceback (most recent call last):
  File "/root/mm6/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 640, in _execute_cancel
    raise ValueError(f"Failed to cancel order - {order_id}. Order not found.")
ValueError: Failed to cancel order - HMBot-BBOLUSD1644763433006692. Order not found.
```
**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
1.0.0 and staging 1.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by kitos9112** [comment]
This is indeed quite annoying. I think there needs to be some sort of internal mechanism to trust the exchange after X attempts to cancel an order, otherwise, HB will get stuck and does not continue creating limit orders.

**Comment by rapcmia** [comment]
Hi @leastchaos I think this is also related to a reported issue [4987](https://github.com/hummingbot/hummingbot/issues/4987), you may want to add comment to the ticket. Tagging this ticket now as duplicate/close
