### ISSUE TITLE
perpetual_market_making hangs when started 1 hour later.

### ISSUE THREAD

**Issue by leochan007** [hummingbot/hummingbot#5149]
**Describe the bug**
// A clear and concise description of what the bug is.
when it hangs, it shows 
**Steps To Reproduce**

i test this strategy on binance futures testnet.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by leochan007** [comment]
conf:

########################################################
###       Perpetual market making strategy config         ###
########################################################

template_version: 6
strategy: perpetual_market_making

# derivative and token parameters.
derivative: binance_perpetual_testnet

# Token trading pair for the exchange, e.g. BTC-USDT
market: ATOM-USDT

# What leverage to used
leverage: 10

# Position mode to use, hedge mode or one-way position mode.
position_mode: Hedge

# How far away from mid price to place the bid order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_spread is 1.
# Your bid is placed at 99.
bid_spread: 0.05

# How far away from mid price to place the ask order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_spread is 1.
# Your bid is placed at 101.
ask_spread: 0.05

# Minimum Spread
# How far away from the mid price to cancel active orders
minimum_spread: -100.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 18.0

# The spread (from mid price) to defer order refresh process to the next cycle.
# (Enter 1 to indicate 1%), value below 0, e.g. -1, is to disable this feature - not recommended.
order_refresh_tolerance_pct: 0.0

# Size of your bid and ask order.
order_amount: 20.0

# long position take profit spread
long_profit_taking_spread: 0.1

# short position take profit spread
short_profit_taking_spread: 0.1

# Spread from position entry price to place a stop-loss order to close position
stop_loss_spread: 0.2

# Time to wait before refreshing a stop loss order that has not been executed
time_between_stop_loss_orders: 30.0

# Spread to include in stop loss orders covering possible price slippages in the market
stop_loss_slippage_buffer: 0.3

# Price band ceiling.
price_ceiling: -1.0

# Price band floor.
price_floor: -1.0

# Number of levels of orders to place on each side of the order book.
order_levels: 1

# Increase or decrease size of consecutive orders after the first order (if order_levels > 1).
order_level_amount: 0.0

# Order price space between orders (if order_levels > 1).
order_level_spread: 1.0

# How long to wait before placing the next order in case your order gets filled.
filled_order_delay: 60.0

# Whether to enable order optimization mode (true/false).
order_optimization_enabled: false

# The depth in base asset amount to be used for finding top ask (for order optimization mode).
ask_order_optimization_depth: 0.0

# The depth in base asset amount to be used for finding top bid (for order optimization mode).
bid_order_optimization_depth: 0.0

# The price source (current_market/external_market/custom_api).
price_source: current_market

# The price type (mid_price/last_price/last_own_trade_price/best_bid/best_ask).
price_type: mid_price

# An external exchange name (for external exchange pricing source).
price_source_derivative:

# A trading pair for the external exchange, e.g. BTC-USDT (for external exchange pricing source).
price_source_market:

# An external api that returns price (for custom_api pricing source).
price_source_custom_api:

# An interval time in second to update the price from custom api (for custom_api pricing source).
custom_api_update_interval: 5.0

# Use user provided orders to directly override the orders placed by order_amount and order_level_parameter
# This is an advanced feature and user is expected to directly edit this field in config file
# Below is an sample input, the format is a dictionary, the key is user-defined order name, the value is a list which includes buy/sell, order spread, and order amount
# order_override:
#   order_1: [buy, 0.5, 100]
#   order_2: [buy, 0.75, 200]
#   order_3: [sell, 0.1, 500]
# Please make sure there is a space between : and [
order_override:

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters

**Comment by leochan007** [comment]
![WechatIMG258](https://user-images.githubusercontent.com/1071537/155851284-12ed9fc1-0a20-499d-b6aa-0ae4242a4e12.jpeg)

**Comment by rapcmia** [comment]
Hi @leochan007 
We tested and able to replicate the reported issue however this has been address on [issue/5076](https://github.com/hummingbot/hummingbot/issues/5076), you may want to add some comments on it and we will tag this issue ticket as duplicate/resolved.


I have attached the logs I have when testing using MKR-USDT, thank you
Attached: [perp-test.zip](https://github.com/hummingbot/hummingbot/files/8152457/perp-test.zip)

**Comment by leochan007** [comment]
@rapcmia  thx. 
btw. i find when it hangs, it shows that strategy still has some orders but which is actually not existed.( already cancelled)
