### ISSUE TITLE
Binance Perpetual InFlightOrder returns wrong executed amount for partial fills

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5170]
When filling an order with Binance perpetual connector, partial fills are summed but last partial fill execution_amount in InFlightOrder is equal to the total original amount. This leads to incorrect total executed amount in client order tracker. Hedge Strategy relies in order_filled_event.amount which is wrong because of InflightOrder bug.

<img width="1498" alt="Screen Shot 2022-03-08 at 18 09 22" src="https://user-images.githubusercontent.com/36869960/157326917-abc2aa91-0208-400f-bf29-36cbb5599503.png">

[analisis_hedge.txt](https://github.com/hummingbot/hummingbot/files/8209728/analisis_hedge.txt)

**Comment by dennisocana** [comment]
Our team will start working on a fix for this bug today.

**Comment by rapcmia** [comment]
Fix has been applied version 1.3.0
