### ISSUE TITLE
Avellaneda bot takes exceptionally long time to start trading

### ISSUE THREAD

**Issue by WinstonPrivacy** [hummingbot/hummingbot#5171]
**Describe the bug**
When starting the Avellaneda bot, the log shows that the volatility and order book liquidity buffers are filling. These steadily count down 5 ticks at a time. It frequently takes 5-15 minutes or longer before the bot starts trading after this point (sometimes it doesn't begin at all).

**Steps To Reproduce**
* Start bot with kucoin connection to LUNA_USDT.
* Exact parameters don't matter but the volatility and trading intensity buffer size parameters exhibit this behavior with values 150-200. It seems to improve somewhat if they are reduced to 60.

**Screenshots**
Here's an example - the buffers filled at 4:03pm but as of 4:16pm, the bot still hasn't started trading.
![image](https://user-images.githubusercontent.com/36650369/157335170-72d02e70-93ed-4b63-856c-678a2a80db11.png)

**Release version**
1.1.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Hi @WinstonPrivacy we hope all is well,
We recently release version 1.6 and would like to know this is still an ongoing issue? We tried to running it on different markets and seem to be working ok. Thank you

**Comment by nacr** [comment]
@rapcmia  Hey I'm using 1.6.0 and avellaneda_market_making simply does not place any order.

So I have the same problem that @WinstonPrivacy

**Comment by guiguid** [comment]
Hi, same issue 1.7.0 latest : 
after count down to 0, it takes 5 at 15 minutes to start, filling logs with : 
09:38:38 - avellaneda_market_making - Calculating volatility, estimating order book liquidity ... no trades tick

**Comment by rapcmia** [comment]
Hi @nacr @guiguid thanks for your comments. I tried again and still managed to run the strategy and start creating/canceling orders. Would it be possible if you can attach your config files here so I can use them as a reference to investigate further? Thank you!

**Comment by nikspz** [comment]
Close that ticket since that's expected behavior for bot not start trading for a long time, since bot is need to calculate `Asset price volatility`. Usually it takes a long time if there's no big changes in price.

there's a result for Kucoin, bot was able to calculate and start:

![image](https://user-images.githubusercontent.com/83953535/204356978-0436daab-db1a-420b-b27d-4a435808c615.png)
