### ISSUE TITLE
Issues with Hedge Strategy

### ISSUE THREAD

**Issue by BGTCapital** [hummingbot/hummingbot#5184]
**Describe the bug**
Due to the outstanding issues with this strategy: https://github.com/hummingbot/hummingbot/issues/5093
and what is mentioned in this thread: https://discord.com/channels/530578568154054663/563462222878212098/934402846634426428
We found that Hedge Strat has some issues with Binance Perpetual that is not creating orders, and that is consuming 90% of available CPU due to a increase (in multiple orders of magnitudes) of the traffic.

**Steps To Reproduce**
See test config
<img width="710" alt="Screenshot_2022-03-12_at_10 30 19" src="https://user-images.githubusercontent.com/94967120/158202416-6ef54430-58ec-4c94-8899-8ab4c157885f.png">

We've switched from Bybit to Binance Perpetual, but we see now that orders are not created on binance. Please check this screenshot and you will see that at this moment, we had >$10 in AVAX in Kucoin but the strategy is not opening the short trade in Binance

<img width="1440" alt="Screenshot_2022-03-12_at_10 28 39" src="https://user-images.githubusercontent.com/94967120/158202294-b91561bd-6bb5-459d-90df-f91b9a4d3cc9.png">

Additionally we found that the strategy starts reporting reaching to API rate limit immediately after starting. After some analysis we found that indeed it is generating TONS of traffic, that within seconds eats 100% of all resources available.

<img width="562" alt="Screenshot_2022-03-12_at_10 57 20" src="https://user-images.githubusercontent.com/94967120/158203103-d91a77ce-fa82-4cac-befc-4cfba08cb6e9.png">

<img width="1134" alt="Screenshot_2022-03-12_at_10 44 52" src="https://user-images.githubusercontent.com/94967120/158203153-a950bc70-93ae-4432-950d-6948a8c1210e.png">

<img width="1440" alt="Screenshot_2022-03-12_at_10 49 30" src="https://user-images.githubusercontent.com/94967120/158203183-b86246ce-b4b3-4e6e-8d6e-9114100acba2.png">

We tried switching to Bybit but the issue with the traffic seems to be not related to the taker exchange selection

Do you know why is this happening? 

...
**Release version**
v 1.1.0

**Comment by BGTCapital** [comment]
Update: we tried using the last development version of HB but the problem persist

**Comment by Badkkube** [comment]
Hey 
Got the same issues with Binance/Bybit_perp
![image](https://user-images.githubusercontent.com/95508370/166448223-16c9a68f-3a29-407a-93f5-46d06a030377.png)

**Comment by rapcmia** [comment]
Hi @BGTCapital good day to you,
Please be advised that the Hedge strategy has been revamp and would like to check if this is still an ongoing issue as of version 1.11.0? Thank you 🙇
