### ISSUE TITLE
Avellaneda - Hanging order amount's orig and adj does not matched on status

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5190]
**Describe the bug**
While testing Avellaneda strategy on staging branch, we noticed that for hanging order amount the `orig` and `adj` does not match on `status`. Initially the orders are created with an order amount of 20 XRP but after one side getting filled and the other gets hanged you would noticed that the `org` changed. This seems to be affecting whole numbers ending in 0

![Screen Shot 2022-03-17 at 3 42 09 PM](https://user-images.githubusercontent.com/73840223/158761125-233d0d45-26a5-401f-9b95-5b2bbeccc63f.png)

**Steps To Reproduce**
1. Create Avellaneda strategy with hanging orders enabled
2. Select a market with order amount of whole number ending with 0 (Tested on XRP and DOGE-USDT pairs)
3. Start the bot and wait for trades, best to run with `status --live`
4. Check hanging orders after few trades

**Release version**
Staging 1.2 and dev-1.3

**Attachments**
[ave-binance.zip](https://github.com/hummingbot/hummingbot/files/8283058/ave-binance.zip)

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to component on Avellaneda strategy

**Comment by MementoRC** [comment]
Is this still relevant? Based on the latest source, it does not seem possible:
```
            amount_orig = self._config_map.order_amount
            if is_hanging_order:
                amount_orig = float(order.quantity)
                level = "hang"
            data.append([
                level,
                "buy" if order.is_buy else "sell",
                float(order.price),
                f"{spread:.2%}",
                amount_orig,
                float(order.quantity),
                age
            ])
```

**Comment by rapcmia** [comment]
Hi @MementoRC good day and thanks for your response. 
I setup a testbot on paper to reproduce this quickly and confirm its still a ongoing issue. Also I can confirm that when the hanging order was created the log file shows the client stores the correct amount . The issue is that if the order amount is a whole number that ends on `0` and a hanging order is created, we noticed that it removes the zeros from the `status` command resulting to cosmetic bug

Sample:
![Screenshot 2022-11-03 155737](https://user-images.githubusercontent.com/73840223/199675166-b6ab94d9-0dbe-4c7a-8b43-8aff302483e8.png)

**Comment by MementoRC** [comment]
Hi @rapcmia , got it, I confirmed t the issue with a testcase, it's a cython module, so a tidbit annoying to debug - Any chances the bounty scales with the debugging difficulty ;P (just kidding!)

**Comment by MementoRC** [comment]
@rapcmia PR: https://github.com/hummingbot/hummingbot/pull/5862

**Comment by JeremyKono** [comment]
Assigning this issue to @MementoRC. Also, next time please comment first so we can see your comment before creating a PR. Thanks!

**Comment by carlitogetaladajr** [comment]
@MementoRC, please fill up & submit the AML Policy Form via this link: https://forms.gle/MULD7qfm2g2Nhqbr5
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by JeremyKono** [comment]
This bounty has been paid. Thanks!
