### ISSUE TITLE
DYDX orders keep failing on Perpetual Orders with the error message about low balance

### ISSUE THREAD

**Issue by balamurugan678** [hummingbot/hummingbot#5198]
**Describe the bug**
- DYDX orders keep failing on Perpetual Orders with error message on low balance.

**Steps To Reproduce**

- We get the following "warning" on DYDX - The bot executed one leg of the trade on Binance (The Spot market) but it did not execute it on DYDX (The PERP market) even though there is enough margin on DYDX
- Had to manually place the Perpetual order on DYDX

**Screenshots**
![image](https://user-images.githubusercontent.com/8293893/160295048-8757d20e-c8a6-4fbe-99cf-138b2d79c32f.png)
![image](https://user-images.githubusercontent.com/8293893/160295071-83d493a2-aba4-46db-8824-59d0a6194a50.png)

**Release version**
Hummingbot 1.1.0

**Attachments**

[DYDX-ENJ-PERP-LOG.txt](https://github.com/hummingbot/hummingbot/files/8358218/DYDX-ENJ-PERP-LOG.txt)

Discord username: NROB007, Dead Donkey, Dr.Guru

**Comment by SC4RECOIN** [comment]
Also been having issues with margin on dYdX for perpetual market making
`Insufficient balance: SELL order ... is omitted`
This happens after an order is placed and filled. Hummingbot is maybe not aware of the fills?

**Comment by rapcmia** [comment]
Hi @balamurugan678 
Please be advised that Dydx perpetual has been recently updated and improved by one of our community devs. This will be available on the upcoming Hummingbot 1.10 release and also on development branch. As per testing this update we had not observed this issue happened and already fixed.

Closing this ticket for now, else you can reopen if issue persist. Thank you
