### ISSUE TITLE
Client - Getting "cannot convert float NaN to integer" error when stopping multiple orders

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5217]
**Describe the bug**
No printing in the output pane after stop the bot with `Multiple order levels` enabled after `status --live` is terminated

**Steps To Reproduce**
1. set up multiple order levels
2. start the bot
3. run status --live
4. stop the bot

Actual:
Bot showing error `ValueError: cannot convert float NaN to integer` and have to push Esc to see the commands

Expected Result:
Could execute commands and see the result in the output pane after `status --live` is terminated with `stop` command, 

```
2022-04-04 07:05:09,193 - 3950 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: cannot convert float NaN to integer
Traceback (most recent call last):
  File "/home/ubuntu/5197/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/5197/hummingbot/client/command/status_command.py", line 134, in status_check_all
    await self.strategy_status(live=True) + script_status + "\n\n Press escape key to stop update.", 1
  File "/home/ubuntu/5197/hummingbot/client/command/status_command.py", line 82, in strategy_status
    st_status = self.strategy.format_status()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 639, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.format_status
    df = map_df_to_str(self.active_orders_df())
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 559, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.active_orders_df
    age = pd.Timestamp(order_age(order, self._current_timestamp), unit='s').strftime('%H:%M:%S')
  File "/home/ubuntu/5197/hummingbot/strategy/utils.py", line 15, in order_age
    return int(now - (order.creation_timestamp / 1e6))
ValueError: cannot convert float NaN to integer
```

**Screenshots**
![dev 1 3 0 multiple order levels status --live](https://user-images.githubusercontent.com/83953535/161504037-d3987b5a-ca21-4fc9-9d6b-724e11003b4e.gif)

**Release version**
dev 1.3.0

**Attachments**
[logs_conf_pure_mm_1.log](https://github.com/hummingbot/hummingbot/files/8408008/logs_conf_pure_mm_1.log)
[conf_pure_mm_1.txt](https://github.com/hummingbot/hummingbot/files/8408033/conf_pure_mm_1.txt)

**Comment by Deepali6997** [comment]
Issue description : When hanging order is interrupted, we can see error in the log pane as 

" **14:48:17 - async_utils - Unhandled error in background task: cannot convert float NaN to integer (See log file for stack trace dump)** "

<img width="1615" alt="Screenshot 2022-05-16 at 3 25 01 PM" src="https://user-images.githubusercontent.com/100112937/168567471-6097fae1-7a11-48dc-ba0c-be7fef382b80.png">

steps to reproduce

1. Connect Kucoin API keys
2. Create PureMarketMaking strategy and make sure you've enough balance
3. Start the strategy 
4. Run status --live to keep an eye on order creations

Expected
When hanging order is created and right after that "stop" command is given, the hanging order should get cancelled and there should be no error in the log-pane

Actual:
Whe hanging order is created and right after that "stop" command is given;
1. We can see that error log is generated on log pane
2. Although, order gets cancelled successfully

**Comment by cmichaeltimmons** [comment]
Hi,  I would like to be assigned this issue if it is available?   I am looking for a good first issue and to participate in the bug bounty.  Thanks

**Comment by nikspz** [comment]
@cmichaeltimmons There's current available bugs (bug bounties board)
https://github.com/orgs/hummingbot/projects/7/views/2

**Comment by JeremyKono** [comment]
Assigning this issue to @cmichaeltimmons . Thank you for your contribution!

**Comment by nikspz** [comment]
Couldn't reproduce on master branch (ver 1.7.0)

![status --live gate io no issue](https://user-images.githubusercontent.com/83953535/188067618-7e012b03-0cb7-4176-b550-c44a426d13ae.gif)
![status --live ascendx no issue](https://user-images.githubusercontent.com/83953535/188067629-10f6e9cd-0aa1-4995-bfc8-8245fe1e270a.gif)

**Comment by cmichaeltimmons** [comment]
Do we still want to investigate this if you are not able to reproduce it any more?

**Comment by nikspz** [comment]
Close this issue as `can't reproduce`
