### ISSUE TITLE
`cimport bool` should be renamed to `cimport bool as cppbool` to avoid confusion

### ISSUE THREAD

**Issue by martinkou** [hummingbot/hummingbot#5232]
**Describe the bug**

We have a few places in Hummingbot source where somebody is doing a `cimport bool` - which is confusing for Python because Python also has a bool type. Improper use of it can lead to compilation issues like #5140.

Let's do a grep for it in the current source code...

```
(base) martin_kou@DESKTOP-VN1G646:~/hummingbot$ git grep "cimport bool"
hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pxd:from libcpp cimport bool
hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx:from libcpp cimport bool
hummingbot/connector/exchange/paper_trade/paper_trade_exchange.pyx:from libcpp cimport bool as cppbool
hummingbot/core/data_type/LimitOrder.pxd:from libcpp cimport bool
```

1. It's unnecessary in the bitfinex_exchange connector - since all the bool types are really just used in regular Python classes. Those should be eliminated.
2. The usage in `paper_trade_exchange.pyx` is the only proper one here, it's used in C++ STL data types, and it's aliased to "cppbool" to indicate it's not Python's bool.
3. The usage in `LimitOrder.pxd` should use the `cppbool` to explicitly say it's a C++ bool, since the file is describing a C++ class. Simply saying "bool" is confusing since a casual reader may mistaken it as a Python bool.

**Comment by rapcmia** [comment]
The fix has been applied on development branch
