### ISSUE TITLE
`gateway create` should not ask for Infura key again if it already exists in gateway config

### ISSUE THREAD

**Issue by martinkou** [hummingbot/hummingbot#5238]
**Feature Suggestion**

When `gateway create` is called to update a gateway v2 installation (i.e. an existing gateway is already running) - the command would ask for the user's Infura key again as if it's a fresh new installation.

Since `gateway create` does not wipe the old gateway config in general, there's really no need to ask for the user's Infura API key again if it already exists. It's also pretty easy to implement - `gateway create` can just detect whether there's an existing Infra API key config with the current gateway, and skip the API key question if it's already been set.

**Impact**

This simplifies the UX flow for the case when the user wants to update a gateway v2 installation via `gateway create`.

**Comment by rapcmia** [comment]
Gateway has been refactored and `gateway create` command has been removed
