### ISSUE TITLE
FTX spot avellaneda instantly cancels sell orders after placing when out of quote

### ISSUE THREAD

**Issue by JohnnyVicious** [hummingbot/hummingbot#5244]
**Describe the bug**
FTX spot avellaneda strategy instantly cancels sell orders after placing when out of quote.
You'd have to get lucky to hit a sell order within that second to get another buy order opportunity.
Trading activity goes 'inactive' for long periods this way.

Restarting the container does not help.
I think a temporary workaround for this bug could be to set a balance limit on the quote, will try this next.

**Steps To Reproduce**
Default connect to FTX spot
Create avellaneda strategy with default settings on BTC-USD
Config hanging orders enabled (only custom thing I enabled)

Note: if you sell a chunk of your asset, everything works again as expected until it runs out of quote.

**Release version**
Tested on 'latest' stable 1.2.0 & 'development' 1.3.0 docker builds

**Attachments**
(https://github.com/hummingbot/hummingbot/files/8529668/logs_conf_avellaneda_market_making_1.log)
[conf_avellaneda_market_making_1.zip](https://github.com/hummingbot/hummingbot/files/8529680/conf_avellaneda_market_making_1.zip)

**Optional: your discord username:**
JV66

**Comment by NisoKTNU** [comment]
also having an issue where orders are automatically cancelled(within 1 second) no config settings appear to make a difference.
[conf_avellaneda_market_making_1.zip](https://github.com/hummingbot/hummingbot/files/9890939/conf_avellaneda_market_making_1.zip)

[logs_conf_avellaneda_market_making_1.log](https://github.com/hummingbot/hummingbot/files/9890978/logs_conf_avellaneda_market_making_1.log)
