### ISSUE TITLE
upgrading dydx client

### ISSUE THREAD

**Issue by JulesText** [hummingbot/hummingbot#5275]
**Describe the bug**

There are a few related issues here. 
1. The dydx-v3-python version called in the setup files is version 1.0.10
2. The most recent version of this client available on pypi is version 1.5.1 (see [link](https://pypi.org/project/dydx-v3-python/#history))
3. There are markets that are currently available on dydx that are not included in v1.0.10. For instance in v1.4.4 and 1.4.6, new markets were added to include NEAR-USD, RUNE-USD, ETC-USD, ENJ-USD, XLM-USD, LUNA-USD, 1INCH-USD, CELO-USD (see [link](https://github.com/dydxprotocol/dydx-v3-python/commits/dfa3c4ea7d88d6d12e1220296a2f80d44c0a0547/dydx3/constants.py))
4. This issue of markets that cannot be used has occurred before and was previously resolved in PR #3734 . The error logs you will see are explained in issue #3450 . You can reproduce these by trying to trade on a market pair such as NEAR-USD.
5. I have attempted to upgrade to the latest client v1.5.1 by updating the environment.yml file, however this version of the client does not seem to work with hummingbot. I have tested various versions and found that the client up to v1.3.1 seems to work, but from v1.4.0 onwards there are errors. These errors include:
6. When querying the account balance $0 is always shown despite funding in the account
7. When importing a strategy, the preliminary check for the exchange check fails. Message:
`Invalid connections:
dydx_perpetual: 'Response' object is not subscriptable` 

Not sure if this should be considered a bug or a script request, though anyone trying to trade on one of the newer market pairs will encounter the error explained in issue #3450 . 

Also not sure if the error is in the dydx client script and needs to be fixed by them, or if an upgraded integration is needed in hummingbot.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Change line in environment.yml for installing dydx-v3-python from version 1.0.10 to version 1.4.0
2. Install script, activate anaconda, compile, and run hummingbot
3. Connect to dydx_perpetual
4. Check balance is incorrectly shown as $0
5. Import strategy file for instance perpetual_market_making
6. Check error displayed for invalid connection

![Screen Shot](https://user-images.githubusercontent.com/32991504/166145104-acfe6a19-eec0-4f36-b6e5-d759166ec157.png)

**Release version**
development 1.2.0

**Comment by rapcmia** [comment]
Hi @JulesText good day to you,
Please be advised that dydx perpetual has been updated and improved by one of our community devs and will be available on the upcoming release of Hummingbot 1.10. In the event that you would want to check this out please feel free to use our development branch.

Closing this PR now as we have not observed this issue happened. You may reopen if needed. Thank you! 👍
