### ISSUE TITLE
Update the Hedge strategy to switch the account position mode for derivatives connectors

### ISSUE THREAD

**Issue by mhrvth** [hummingbot/hummingbot#5298]
**Describe the bug**

The Hedge strategy currently doesn't set the account position mode for derivatives, and this results in an error when trying to submit an order with a different position mode than what is set in the account.

The strategy should detect the current position mode and use the method `set_position_mode()` to set the appropriate mode just like the Perpetual MM strategy.

**Steps To Reproduce**

Run the hedge strategy with Bybit while the account is set to a single side position mode.

**Comment by leastchaos** [comment]
@rapcmia @mhrvth this can be closed as this is already enabled in the latest hedge
