### ISSUE TITLE
Client - Unable to start due to TypeError on docker build

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5346]
**Describe the bug**
While checking development branch using docker build, we are getting an error when trying to open the client via helper script `./create.sh and ./start.sh` or `docker start xxxx`

```
Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 143, in <module>
    fork_and_start(main)
  File "/home/hummingbot/bin/docker_connection.py", line 137, in fork_and_start
    main_function()
  File "bin/hummingbot_quickstart.py", line 136, in main
    if not login_prompt():
TypeError: login_prompt() missing 1 required positional argument: 'style'
```
![image](https://user-images.githubusercontent.com/73840223/170688010-071780f0-fd96-480d-8ef6-c354bc9d207f.png)

![image](https://user-images.githubusercontent.com/73840223/170688069-38201cff-09e7-404a-a9bd-921a4b7a4d13.png)

The last working docker build is under commit `2cd11d7c50d31267dfece6cdce22289214e562d0`

**Steps To Reproduce**
1. Clone latest development branch
2. Create docker image
3. Run the helper scripts available on `/installation/docker-commands/` folder
4. Notice the error when the client is about to launch

**Release version**
development branch dev-1.5

**Comment by xiandong79** [comment]
I face the some error case

**Comment by xiandong79** [comment]
However when I try the same step in Linux 18.04server, it is gone.

**Comment by meyer-net** [comment]
the same，but i try it on centos 7.6

**Comment by rxlxrxsx** [comment]
Getting the same issue on source build when running the client and entering an incorrect password

https://user-images.githubusercontent.com/64377055/171343741-607a675e-4752-4ea1-b351-4e58b5ab81c4.mov

**Comment by rapcmia** [comment]
Fixed
