### ISSUE TITLE
Client - Error: unable to communicate with docker socket notification showing on instance start

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5359]
Error - unable to communicate with docker socket notification showing on instance start using `windows docker`

**Steps To Reproduce**
1. clone latest master branch
2. ./create.sh and start docker image
3. Set up a password
4. Pay attention to the output pane

Actual:
Bot showing Error - unable to communicate with docker socket notification showing on instance start using `windows docker`

Expected:
no error showing

**Screenshots**
![image](https://user-images.githubusercontent.com/83953535/171320116-159f519a-fc1f-4e57-aaf0-f9ea8d606cba.png)

**Release version**
Win10 Docker master branch

**Comment by nikspz** [comment]
confirmed the issue showing when 1.docker desktop isn't running or 2.using old help scripts (./create.sh etc...) for docker (in this case needed to reinstall from scratch with the new ones)

Win10:
https://user-images.githubusercontent.com/83953535/171330638-24c69ea4-ab54-4d7d-89a9-a024140ead13.mp4
https://user-images.githubusercontent.com/83953535/171330669-0bccbe18-f799-4086-b0de-360971ac48fb.mp4

**Comment by OokamiKB** [comment]
i am working on MacOS source code built (not docker mode), also got same error msg
