### ISSUE TITLE
Client - Unable to create docker image for MacOS and Ubuntu20.04 using development branch

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5363]
**Describe the bug**
While testing we noticed that we could not create a docker image for macOS running on M1 and got the error `conda clean: error: argument -p/--packages: ignored explicit argument 'sy'`. Crosschecked on the development branch and tested on AWS running on Ubuntu20.04 and getting the same error

macOS (M1)
<img width="1393" alt="Screen Shot 2022-06-01 at 6 25 45 PM" src="https://user-images.githubusercontent.com/73840223/171385651-080ff02d-aa74-4e92-b240-ae09580e5923.png">

AWS ubuntu 20.04
![image](https://user-images.githubusercontent.com/73840223/171386323-28549b0d-4afb-4f1d-8d4f-9fdd27738295.png)

Tried to run using Windows Ubuntu18LTS terminal with docker desktop not getting the reported error
![image](https://user-images.githubusercontent.com/73840223/171386953-f9d246f4-58a2-48ed-bb0a-604e0fb1fdea.png)

**Steps To Reproduce**
1. Install client using development branch via source 
2. Build docker image using `docker build -t coinalpha/hummingbot:dev -f Dockerfile .`
3. Monitor the process and notice the error 

**Release version**
development dev-1.5

**Comment by nikspz** [comment]
That issue also showing for Windows 10 WSL
![image](https://user-images.githubusercontent.com/83953535/171527589-14133187-9d00-4768-b44c-0056d86ca0e0.png)

**Comment by rapcmia** [comment]
Fixed
