### ISSUE TITLE
Installation from source. Could not find conda environment: hummingbot

### ISSUE THREAD

**Issue by GSequist** [hummingbot/hummingbot#5370]
**Update tried to run the installation also with miniconda. Failed to build the environment and attaching additional screenshot.
![Screen Shot 2022-06-05 at 9 08 26 PM](https://user-images.githubusercontent.com/75031938/172066634-e38eabe8-31a5-4285-958d-27c6b8b18331.png)

**Describe the bug**
// Trying to install from source on mac m1. Followed all steps in https://hummingbot.org/installation/source/#contributing-to-hummingbot and after cd hummingbot added also 
git checkout development
Anaconda is installed on my mac. 
I keep getting this error all the time and cannot finish installation:
Could not find conda environment: hummingbot

**Steps To Reproduce**
// Just following steps for installation from source on mac m1 as per your documentation https://hummingbot.org/installation/source/#contributing-to-hummingbot. 
In step 3. I get stuck.
Please also note (not sure this is relevant that I have another bot running from docker while I am installing from source.

**Screenshots**
// Please see attached.
![Screen Shot 2022-06-02 at 6 08 35 PM](https://user-images.githubusercontent.com/75031938/171677032-b49d675a-3a9a-4cc6-b526-3189f5b6d98c.png)

**Release version**
// 1.4

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by cardosofede** [comment]
hi @GSequist, do you solve the issue? I have M1 too and I think that is a problem with your anaconda.

**Comment by rapcmia** [comment]
Hi @GSequist I remember this happened not only on m1 but on the new AWS server as well and was able to fix it by running `conda install conda-build`. Im able to install the source using m1 build atm, please kindly check if you installed anaconda correctly. Will close this ticket for now. Thank you
