### ISSUE TITLE
Gateway v2 - Failed to create a docker image of gateway

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5376]
**Describe the bug**
Gateway v2 - Failed to create a docker image of gateway

got an 
```
src/chains/polygon/polygon.ts(18,5): error TS2554: Expected 9 arguments, but got 7.
error Command failed with exit code 2.
```

**Steps To Reproduce**

1. Clone and install the development branch
2. Change directory to ./gateway
3. - Run `docker build -t coinalpha/gateway-v2-dev:INSERTNAME -f Dockerfile .`

**Screenshots**
![image](https://user-images.githubusercontent.com/83953535/172093362-e83140d5-e21f-45c2-98e1-33326b741532.png)

**Release version**
1.5-development

**Comment by rapcmia** [comment]
This has been fixed.
