### ISSUE TITLE
Gate.io - Error: `GateIOExchange` object has no attribute `name_cap`

### ISSUE THREAD

**Issue by gerald-hb** [hummingbot/hummingbot#5393]
**Describe the bug**
Getting this error during the connect command, due to this we're unable to connect gate.io API keys.

**Steps To Reproduce**
1. Clone and install latest hummingbot (source build)
2. git checkout development
3. run `connect` you will see the error below
4. run `connect gateio` and enter your api and secret
5. You will see the 2nd error below

note: no error on logs_hummingbot.logs, its blank
...

**Screenshots**
![image](https://user-images.githubusercontent.com/84826167/173093916-fe70d11d-7151-43be-8206-0dafc129717c.png)
![image](https://user-images.githubusercontent.com/84826167/173094812-07e6d6e7-81e5-40df-b95e-dcf1a3d7277d.png)

**Release version**
dev 1.5.0 (foundation

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Jake1Support** [comment]
Getting the same error as well on Source build (dev1.5.0) when connecting Gate.io API keys.
![image](https://user-images.githubusercontent.com/92734086/173104807-fe4fcfd3-9a2c-48ec-8772-68de6af98663.png)
![image](https://user-images.githubusercontent.com/92734086/173104837-1b326ceb-df67-4e02-80b4-cc2e8ec10e20.png)

**Comment by RC-13** [comment]
No issue in the latest development 
![image](https://user-images.githubusercontent.com/57189990/174502745-53f34a96-c30b-4523-8398-91d549cfe0a5.png)

**Comment by rapcmia** [comment]
Fixed
