### ISSUE TITLE
Gate_io : Unable to find exchange rate for market pair. PNL value will be inconsistent

### ISSUE THREAD

**Issue by gerald-hb** [hummingbot/hummingbot#5394]
**Describe the bug**
After sometime of running bots on gate.io, the said error will keep on flooding. It still places order (getting canceled and filled) though.

**Steps To Reproduce**
1. Clone and install latest hummingbot (source build)
2. Connect gate.io api keys
3. Create a simple PMM strategy
4. Observe the logs, it may take minutes or sometimes an hour for the error/flooding to appear
5. Tried to switch rate oracle to coingecko, kucoin and binance but same result.

logs and config attached

**Screenshots**
![image](https://user-images.githubusercontent.com/84826167/173097472-8e71865d-9a9d-441a-967f-505f72a8780a.png)

**Release version**
v1.4.0 (master branch foundation)

**Attachments**

[gatelogs.txt](https://github.com/hummingbot/hummingbot/files/8880156/gatelogs.txt)
[gatetest.txt](https://github.com/hummingbot/hummingbot/files/8880157/gatetest.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by MementoRC** [comment]
LIME-USDT is effectively not one of the 1500 or prices that can be fetched from Binance. The pair does not exist on Kucoin. Using the PR gate.io oracle resolved the issue. Note that the PnL is still acceptably reliable, it uses the last traded price instead of the oracle price

**Comment by rxlxrxsx** [comment]
This has been observed to be happening on Bitmart connector as well.

<img width="1423" alt="Screen Shot 2022-07-12 at 4 21 55 PM" src="https://user-images.githubusercontent.com/64377055/178447286-a98e9d12-aab8-4c72-89f8-83371726e971.png">

Logs and config: [bitmart.zip](https://github.com/hummingbot/hummingbot/files/9091135/bitmart.zip)

**Comment by rapcmia** [comment]
Hi @rxlxrxsx @gerald-hb good day,
It seems to be the set "source" on your `rate_oracle_source` parameter does not have prices nor support the markets you are using thats why the error occurred. 

Tested LIME-USDT on gate_io and setting up my rate_oracle_source to ascendex then wait for an order to be filled, I dont noticed the issue happened. In line with the results, We would suggest to make sure to check the `rate_oracle_source` by running `rate --pair XX-XXX` to check if it supports the market you want to use. 

Closing this ticket for now

**Comment by 0xferit** [comment]
In my experience, this "rate oracle" errors causes maximum CPU utilization.

How to disable the rate oracle if you don't want to use one?
