### ISSUE TITLE
Decimal.ConversionSyntax error while connecting OKEX

### ISSUE THREAD

**Issue by buckydroid** [hummingbot/hummingbot#5432]
I'm getting decimal conversion syntax error when connecting okex exchange after entering api, security and pass keys,

Here's the screenshot,
![Screenshot_558](https://user-images.githubusercontent.com/17883122/175643074-d79ddfa9-2088-4d81-a743-26a41046e585.png)

They keys are completely fine, already using em to run another bot using ccxt python. Dunno what I'm doing wrong with hummingbot.

**Comment by nikspz** [comment]
Hey @buckydroid could you please tell what's version you use?
I'd advise to update your bot version to the latest version.
https://hummingbot.org/installation/
Looks like on your screenshot that's old one. Thanks

Actual on latest dev:
![image](https://user-images.githubusercontent.com/83953535/175859144-8ef09e38-92ac-48e5-8b38-9e7e22bb0f38.png)
