### ISSUE TITLE
Bitmart connector not working

### ISSUE THREAD

**Issue by thetaproject** [hummingbot/hummingbot#5435]
i created arbitrage strategy.. and getting this error/ see attached photo
![1231](https://user-images.githubusercontent.com/64147266/176272846-1478c8e1-a561-4307-862e-064eefec4bd8.PNG)

**Comment by rapcmia** [comment]
The fix for this issue has been applied on the release of Hummingbot version 1.5

**Comment by thetaproject** [comment]
when 1.5 version will be released?
