### ISSUE TITLE
Order Optimization doesn't work right on Cross-Exchange Market Making strategy

### ISSUE THREAD

**Issue by Sailboats** [hummingbot/hummingbot#5437]
**Describe the bug**

Order Optimization doesn't work right on Cross-Exchange Market Making strategy,for example,after order adjusting,the price of bid limit order doesn't adjust my prices right next to the next best orders.

**Steps To Reproduce**

Create a Cross-Exchange Market Making strategy with below config:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/7370037/176341952-03ae7f30-f454-45ba-8fcb-6bf69c4ba583.png">

**Screenshots**

<img width="312" alt="image" src="https://user-images.githubusercontent.com/7370037/176342071-562e8020-a937-47f1-beea-e7dccfceb4fa.png">

**Release version**

dev-1.6.0

**Attachments**

[config and logs.zip](https://github.com/hummingbot/hummingbot/files/9006929/config.and.logs.zip)

**Optional: your discord username:**

moon8823#4914

**Comment by rapcmia** [comment]
hi @Sailboats our team does not have any plans to update v1 XEMM strategy for now however you may want to look on our v2 strategy XEMM on our latest version 1.27.0 https://hummingbot.org/release-notes/1.27.0/#new-strategy-cross-exchange-market-making-xemm
