### ISSUE TITLE
Universal Docker image

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5444]
**Feature Suggestion**
Create a Dockerfile that lets you build the Hummingbot image with BUILDX and make it available to all platforms.

**Impact**
The desired behavior will allow me to create a custom Docker image of the client in my Mac with M1 and deploy that image in a free instance of AWS EC2.

**Additional context**
If you build the image in a computer with ARM then you can't deploy that image in x86.

**Comment by rapcmia** [comment]
This is done with multiarch support https://docs.hummingbot.org/installation/docker/#docker-buildx
