### ISSUE TITLE
Ascendex orders cancelled and no new orders

### ISSUE THREAD

**Issue by ThomasArcher1** [hummingbot/hummingbot#5470]
**Describe the bug**
// Ascendex pair FINE-USDT orders are cancelled but no new orders are created. 

The problem started 2 days ago after I updated the HB version to 1.5.0. The Ascendex bot started failing and not placing orders after a while. 

**Steps To Reproduce**
Find it hard to answer this Q. Nothing was changed to configs of bot. 

Things I tried but did not help:
1. Paused bot for 2hrs
2. I changed order refresh / max order age from 30 --> 60
3. Created a new API
4. Created a new EC2 instance

**Screenshots**
The start-up of the bot all seems fine. Bot placed a limit BUY order (No SELL due to no held inventory). Then after cancelling the initial order, no new orders are placed.
<img width="645" alt="Cancelling order after order refresh and failing to produce new order" src="https://user-images.githubusercontent.com/104364178/177547886-edba6e8c-22a7-420b-94ad-e5db0c6633dd.png">

**Release version**
// Version 1.5.0

**Attachments**
// Zip file contains Configs + latest log file
[Ascendex issue 6 July HB.zip](https://github.com/hummingbot/hummingbot/files/9054594/Ascendex.issue.6.July.HB.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
ThomasA - Discord
Thommar - Miner

**Comment by rapcmia** [comment]
Duplicate ticket, please refer to #4987
