### ISSUE TITLE
[Connector Issue] Cannot place orders via the Loopring Connector 

### ISSUE THREAD

**Issue by limark96** [hummingbot/hummingbot#5481]
Hello devs, I encountered the following situation while trying to use the loopring connector:

I was able to connect to looping by providng the api keys, and using the `balance` command does return the correct balances on loopring. However, when I tried to run a strategy, the log panel throws the following errors: 

![image](https://user-images.githubusercontent.com/30963021/178154352-a437f833-2fde-4cb4-bde6-1e9b4cc24efb.png)

I also checked that I did have enough balance in my account for running my strategy (i.e. I have both LRC and USDC, and the amounts are greater than the order sizes), so I think it's unlikely that the issue was due to insufficient balances. 

Please look into the possible causes of the `ERR_REST_INVALID_SIGNATURE` errors. Meanwhile, let me know if there's anything that you think that I should try to get the loopring connect working correctly. Thank you!

**Comment by rapcmia** [comment]
@limark96 Please be advised that this is a known issue reported from [#3453] regarding the `Issue with Loopring API GET to /api/v3/order, response:` (https://github.com/hummingbot/hummingbot/issues/3453), We will have to close this ticket and please add a comment instead. Thank you
