### ISSUE TITLE
Binance rate limits are incorrect

### ISSUE THREAD

**Issue by abduramann** [hummingbot/hummingbot#5491]
binance_constants.py contains obsolete rate limits. Especially `orders per second` raises issues. It should be 50 orders per 10 seconds instead of 10 orders per 1 second. As a suggestion, could you make the limits dynamic(i.e. reading from exchangeInfo API instead of using constants) or assignable by the users via config settings?

Here are the related part in exchangeInfo API:

`"rateLimits":[{"rateLimitType":"REQUEST_WEIGHT","interval":"MINUTE","intervalNum":1,"limit":1200},{"rateLimitType":"ORDERS","interval":"SECOND","intervalNum":10,"limit":50},{"rateLimitType":"ORDERS","interval":"DAY","intervalNum":1,"limit":160000},{"rateLimitType":"RAW_REQUESTS","interval":"MINUTE","intervalNum":5,"limit":6100}]`

See also: https://github.com/hummingbot/hummingbot/issues/5473

**Comment by nikspz** [comment]
Should be fixed in https://github.com/hummingbot/hummingbot/pull/5600

**Comment by rapcmia** [comment]
Hi @abduramann inline with the previous comment, our community devs have added a fix for this issue. Would it be possible for you to confirm if this is still an ongoing issue? Thank you

**Comment by rapcmia** [comment]
Fix has been deployed on Hummingbot version 1.8.0

**Comment by abduramann** [comment]
Confirmed. They are the same as the ones in my fork. Thanks.
