### ISSUE TITLE
Running Duration of the Hummingbot gets messed up after 1 day

### ISSUE THREAD

**Issue by theomaniac** [hummingbot/hummingbot#5497]
**Describe the bug**
When the Hummingbot runs for more than 1 day, the bottom status on the left, displaying the running time, gets messed up

**Steps To Reproduce**
Hummingbot needs to be run for more than 1 day(s)

Here are the steps to reproduce the issue (see attachments in the section below):
1. Start the bot ...
2. Wait 1 or more days

**Screenshots**
Before:
![2022-07-14-20-08-44](https://user-images.githubusercontent.com/109097532/179042810-891e3d1f-3698-4a8f-8480-b14312fdd5f2.png)

After:
![2022-07-14-20-22-43](https://user-images.githubusercontent.com/109097532/179046449-41a99e29-3d93-414c-97fe-fe67ab07adaa.png)

**Release version**
Dev1.6.0

Solved in https://github.com/hummingbot/hummingbot/pull/5499

**Optional: your discord username:**
TTC

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: An issue related to client UI where duration is reset when reaching 24hours

Assigned bounty to @theomaniac since he has already a PR to fix the issue. Thank you

**Comment by theomaniac** [comment]
fixed and tested

**Comment by carlitogetaladajr** [comment]
@theomaniac , please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by theomaniac** [comment]
done it

**Comment by nikspz** [comment]
Closing this ticket as Paid. [The PR](https://github.com/hummingbot/hummingbot/pull/5499) has been deployed to development branch and will be available on the next release version 1.12.0.
