### ISSUE TITLE
Low value of ORDER_NOT_FOUND_COUNT_LIMIT causes untracked orders for long-running bots.

### ISSUE THREAD

**Issue by abduramann** [hummingbot/hummingbot#5502]
Currently, `ORDER_NOT_FOUND_COUNT_LIMIT` is 10. Since Binance returns `{"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}` error frequently for especially the bots which running for a long time and/or which have a high number of orders, the value 10 causes untracked orders in a few hours. I suggest either making this setting configurable by the user or making it a consequent value, i.e. if an order cannot be found X times "consequently", let the order be untracked.

In fact, a more effective solution to the root cause would be better. The user shouldn't face `{"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}` error unless a synch error exists. In my fixed-grid bots, I use more than 99 orders. Due to the rate limits, humming bot might create some orders with incorrect timestamp. This possibility can be examined.

**Comment by rapcmia** [comment]
Hi @abduramann good day,
Just want to follow up if this is still an ongoing issue on your fix grid issue? There were updates for fix grid and binance on previous versions and possibly fixed this issue.
