### ISSUE TITLE
take_if_crossed = false causes #levels to decrease in fixed-grid strategy.

### ISSUE THREAD

**Issue by abduramann** [hummingbot/hummingbot#5503]
When `take_if_crossed = false` , the bot uses LIMIT-MAKER orders. In a volatile market, this type of order causes Binance to return `{"code":-2010,"msg":"Order would immediately match and take."}` error. This is normal. The problem is that the bot does not try to create this order, which cannot be created previously when the market is suitable to create this order. So, for example, let's assume that I create a fixed-grid bot with 99 levels. As time goes on, since the number of levels decreases significantly, the fixed grid loses its benefit.

**Comment by rapcmia** [comment]
Hi @abduramann good day,
Just want to follow up if this is still an ongoing issue on your fix grid issue? There were updates for fix grid and binance on previous versions and possibly fixed this issue.
