### ISSUE TITLE
Frequent "API rate limit has almost reached" message.

### ISSUE THREAD

**Issue by abduramann** [hummingbot/hummingbot#5505]
I'm not sure whether this can be counted as bug but "API rate limit has almost reached" messages shouldn't be shown frequently. From the previous bugs I reported, you know that I use the bots with fixed grid strategy with more than 99 levels :) This situation creates many UI responsivity, connection drop, rate limit etc. issues. I didn't report some of them yet but you may face those issue easily after you create a fixed grid bot in Binance with +99 levels and run that bot 7-8 (maybe less) hours. 

Anyway, this issue is one of them. Since there are a lot of orders, ORDERS endpoint are used at its limits. That's why this message appears but I want to prevent it from appearing since it creates a crowded log/screen and make seeing important messages difficult. To me, the user should be able to use the rate limits with some safety margin. `rate_limits_share_pct` setting does not help on this issue. When you set it to a value less than 100, the bot takes `exchange_rate_limit * rate_limits_share_pct` as the new rate limit and goes on showing "API rate limit has almost reached" according to this new limit. Another multiplier parameter and some easy code change is required, so the throttler will use `exchange_rate_limit * rate_limits_share_pct * new_parameter` as the new limit when sending API messages but it will use  `exchange_rate_limit * rate_limits_share_pct` while checking whether API rate limits has reached.

**Comment by nikspz** [comment]
Should be fixed with https://github.com/hummingbot/hummingbot/pull/5600 (already merged to the latest development branch (dev-1.8.0)

**Comment by rapcmia** [comment]
hi @abduramann good day to you, a fix has been deployed on development branch and upcoming version 1.8.0 We would want to know if you could have a look with it on the development branch and see if this is working ok now? Thank you
