### ISSUE TITLE
Config migration - Failed to migrate config using latest staging

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5517]
Upon crosschecking with the team
`Failed to migrate configs`
Getting this error `on Staging 1.6.0` branch fresh installation (`Source`)

**Steps To Reproduce**
1. Clone and install latest branch
2. Put the old configs and connector files in `..instance_name/conf/` folder
3. Start the bot and setup the password
4. Check if the conf files migrated (using `import` and `connect` commands)

Actual:
Bot didn't migrate any files

Expected:
after the automatic migration, that should be:
- conf
    - strategies
        - old_strategy_file.yml
    - connectors
        - old_connector_file.yml
(https://github.com/hummingbot/hummingbot/pull/5428#issuecomment-1168751344)

**Screenshots**
![image](https://user-images.githubusercontent.com/83953535/179884989-1933671d-686f-4cb9-a1dc-b9aea5bae2c3.png)
![sta16 config migration faild1](https://user-images.githubusercontent.com/83953535/179885005-07466ada-9a63-4dbb-a8b8-851303af52fc.gif)
![sta16 config migration faild2](https://user-images.githubusercontent.com/83953535/179885013-e3a8c7c5-7766-45a6-a80a-90844a2075ea.gif)

**Release version**
Staging 1.6.0 source

**Comment by rapcmia** [comment]
Crosschecking with Development branch latest commit `3ea43929dc822189a07a73f176f12bbf45288cf0` and we did not experience migration failed issue. Screen recording available below:

https://user-images.githubusercontent.com/73840223/179887493-ae7397e9-b069-43ba-903f-31ef72e73b03.mov

**Comment by petioptrv** [comment]
@nikspz, is it possible to upload a zip file with the configs you're using to reproduce the issue?

**Comment by nikspz** [comment]
Checked with Petio, should be fixed with #5523
