### ISSUE TITLE
spot_perpetual_arbitrage - bot showing low balance for base asset on derivative exchange

### ISSUE THREAD

**Issue by Crypto369** [hummingbot/hummingbot#5533]
**Describe the bug**
// I have the problem. Bot keep saying the coin balance is too low on perp exchange, but I shouldn't require a coin to open an perp short position, which is weird.

**Steps To Reproduce**
// When I run the bot in the status, I get an error: Binance_perpetual market SOL balance too low. Cannot place order. Why?
And I am worried that when creating the strategy, I did not have a request to create: "Would you like to take advantage of the funding rate on the derivative exchange, even if min convergence is reached during funding time?"  Why?

Here are the steps to reproduce the issue (see attachments in the section below):
1. 
2. Start the bot using this command: start...
...

**Screenshots**
// 
<img width="1552" alt="Знімок екрана 2022-07-24 о 14 08 24" src="https://user-images.githubusercontent.com/79196068/180644844-7234f209-d7a6-497f-ad0a-a4ea9fceb74a.png">
<img width="1552" alt="Знімок екрана 2022-07-24 о 14 28 29" src="https://user-images.githubusercontent.com/79196068/180644862-8b6c52b4-d443-41aa-b289-2d51123b54da.png">

**Release version**
// version 1.5.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Ivan [ArgenTerra]#3941

**Comment by Crypto369** [comment]
> **Describe the bug** // A clear and concise description of what the bug is.
> 
> **Steps To Reproduce** // A concise description of the **steps to reproduce the buggy behavior**:
> 
> Here are the steps to reproduce the issue (see attachments in the section below):
> 
> 1. Set up your configuration file with these parameters: ...
> 2. Start the bot using this command: ...
>    ...
> 
> **Screenshots** // If applicable, add screenshots to help explain your problem.
> 
> **Release version** // version 1.5.0
> 
> **Attachments** // Please attach your config file and log file to help us debug. It would be difficult for us to help you without those!
> 
> _WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_
> 
> **Optional: your discord username:** Ivan [ArgenTerra]#3941

**Comment by Crypto369** [comment]
I was also recommended to write to you in Discord.
<img width="1552" alt="Знімок екрана 2022-07-24 о 14 29 35" src="https://user-images.githubusercontent.com/79196068/180644907-8e24cee9-1829-4916-9167-251a7c858a2e.png">

**Comment by lbhein** [comment]
i have the same problem!

**Comment by rapcmia** [comment]
Hi @Crypto369 @lbhein please be advised that the `warning on low balance` does not affect the arbitrage on perpetual connectors. At the moment this is expected `warnings` for the spot-perpetual-arbitrage strategy and are plans of improvements on future releases.
