### ISSUE TITLE
error when Install Hummingbot from Source :No module named 'zero_ex'

### ISSUE THREAD

**Issue by sinsign** [hummingbot/hummingbot#5536]
Describe the bug
I got this error when Install Hummingbot from Source on ubuntu 18.04.6

(base) root@ip-172-31-28-133:/home/ubuntu/hummingbot# ./bin/hummingbot.py 
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/./bin/hummingbot.py", line 9, in <module>
    from bin.docker_connection import fork_and_start
  File "/home/ubuntu/hummingbot/bin/docker_connection.py", line 9, in <module>
    from hummingbot.core.gateway import (
  File "/home/ubuntu/hummingbot/hummingbot/core/gateway/__init__.py", line 10, in <module>
    from hummingbot.core.event.events import TradeType
  File "/home/ubuntu/hummingbot/hummingbot/core/event/events.py", line 8, in <module>
    from hummingbot.core.data_type.trade_fee import AddedToCostTradeFee, TokenAmount, TradeFeeBase
  File "/home/ubuntu/hummingbot/hummingbot/core/data_type/trade_fee.py", line 13, in <module>
    from hummingbot.connector.utils import combine_to_hb_trading_pair, split_hb_trading_pair
  File "/home/ubuntu/hummingbot/hummingbot/connector/utils.py", line 8, in <module>
    from zero_ex.order_utils import Order as ZeroExOrder
ModuleNotFoundError: No module named 'zero_ex'

Steps To Reproduce

setup fresh ubuntu 18.04.6 server
install hummingbot
Download install script
wget https://raw.githubusercontent.com/hummingbot/hummingbot/development/installation/install-from-source/install-source-ubuntu.sh

Enable script permissions
chmod a+x install-source-ubuntu.sh

Run installation
./install-source-ubuntu.sh

3- run bin/hummingbot.py then enter the password and press ok
...

Release version
v1.6.0

**Comment by rapcmia** [comment]
Hi @sinsign it seems related to your AWS instance. Im able to install the source build on a` t2.medium with 8gb storage` and not getting these errors. For more info you can check our docs about cloud instances: https://hummingbot.org/installation/cloud-servers/#linuxubuntu

**Comment by sinsign** [comment]
I tried to compile the source code on the AWS ECS t2.small instance, but the same error still occurred
