### ISSUE TITLE
Gateway v2 - gateway connector-token parameter does not return the set tokens for balance command.

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5577]
**Describe the bug**
When checking `gateway connector-token`  and set preferred tokens to return when `balance` command is executed it does not return the available balance.

![image](https://user-images.githubusercontent.com/73840223/183364400-87ba656b-e0e1-4108-8605-f22144017e90.png)

It is also noticeable that the `balance` command would only display also the markets used on the gateway connector.
![image](https://user-images.githubusercontent.com/73840223/183364979-2282d23b-a1e6-490b-b872-105597cadad4.png)

**Steps To Reproduce**
1. Setup your preferred gateway connector wallet
2. Setup `gateway connector-tokens connector tokens`, on my example its `gateway connector uniswap-ethereum-kovan WETH,USDC,DAI`
3. Run balance command 

**Release version**
Development version dev-1.7

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to Gateway-v2 UI

**Comment by vic-en** [comment]
I'll like to fix this issue. I'll create a pr soon.

**Comment by JeremyKono** [comment]
Assigning this PR to @vic-en. Thank you for your contribution!

**Comment by carlitogetaladajr** [comment]
Hi @vic-en, please fill up & submit the AML Policy Form via this link: https://forms.gle/3wCGykiQtjEAY2J17
This is a one-time process for each ETH Address used to received HBOT bounty.

**Comment by vic-en** [comment]
@carlitogetaladajr 
Done!

**Comment by nikspz** [comment]
Closing this issue as it has been marked as paid. Thank you for your contribution!
