### ISSUE TITLE
Gateway v2 - returns incorrect gateway certs,conf and log file directory on docker client build

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5578]
**Describe the bug**
While testing docker client and gateway, we noticed that the directory where the ` gateway certs,logs and conf` file for users to access is incorrect on the output panel

It seems that the `gateway generate-certs` and `gateway create` commands created the required folders inside the client docker instance folder (on this example its under `dev3_files`)

![image](https://user-images.githubusercontent.com/73840223/183370420-72ef8da7-5987-4e1c-8733-9eaf7a5f2576.png)

gateway_conf
![image](https://user-images.githubusercontent.com/73840223/183371081-d9a5ea93-e1e1-411e-a665-f489d99e534e.png)

gateway_logs
![image](https://user-images.githubusercontent.com/73840223/183371232-5e588571-f06f-4f9b-b4c1-e18737735686.png)

hummingbot_certs
![image](https://user-images.githubusercontent.com/73840223/183371322-2a0cb16c-6ba3-4450-8da8-c9bd19bf7a41.png)

**Steps To Reproduce**
1. Create docker client image manually
2. Create docker gateway image manually from /gateway folder for testing 
3. Run `create.sh` from `/installation/docker-commands`
4. Run `start.sh` from `/installation/docker-commands`
5. Run `gateway generate-certs` and `gateway create`, notice where the `gateway ssl certification` is created
6. Check docker client instance folder 

**Release version**
master and development branch

**Comment by han-qiu** [comment]
What's the expected behavior here?

**Comment by rapcmia** [comment]
Hi @han-qiu apologies on the late response and hope you are doing well!
The directory should be based on the which the docker instance folder is placed. On the client UI it displayed ` /home/hummingbot/.hummingbot-gateway/certs` which seems related if you are using the hummingbot client on source build. However when checking my docker build, it should be within the directory where my docker container is stored.

Example below:
![Image](https://user-images.githubusercontent.com/73840223/189258462-438871de-1e8e-4dce-a878-e9dc7fb5a8e2.png)

We are also in discussion to improve this part of the gateway with the team.

**Comment by MementoRC** [comment]
This does not seem to be a bug (unless already fixed). See the steps below:
Start docker GW
Start docker HB with the binding of user's defined instance directory to `/home/hummingbot/.hummingbot-gateway/certs/`
`    --mount "type=bind,source=$CERTS_FOLDER,destination=/home/hummingbot/.hummingbot-gateway/certs/" \`
Wrote a file in that directory from inside the docker HB
Observed the file created in the user's local directory and on the GW docker certs directory

**Comment by MementoRC** [comment]
@rapcmia @han-qiu Any update on the answer above?

**Comment by rapcmia** [comment]
Hi @MementoRC thanks for your comment and apologies on the late reply, 
Normally if there is a assigned community-dev to work on the issue and confirm its `not a bug or expected behavior` based on his investigation it would be tagged as `wontfix` and still be granted the bounty. 

Based on your comment, looks like you did put time to look into it thats why I'd like to discuss it with our team. Please give me some time check with it and get back to you. Thank you again for your time

**Comment by rapcmia** [comment]
Closing ticket as the foundation team decided that this issue is a expected behavior on the current version of Gateway-v2. Hbot granted to @MementoRC for his investigation.
