### ISSUE TITLE
Binance - order_book, status and ticker --live not updating

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5585]
order_book --live and ticker -- live not updating using binance

Upon checking issue replicated on latest dev 1.7.0

Not showing on master branch 1.6.0

**Steps To Reproduce**
1. create/start a pureMM using binance exchange
2. check `order_book --live`

Actual:
order_book --live and ticker -- live not updating using binance

Expected:
order_book --live and ticker -- live updating live

![order_book --live and ticker not updating using binance](https://user-images.githubusercontent.com/83953535/184052229-9dcb52fc-85d4-4044-b3b6-c6af1538dbe6.gif)

**Release version**
development 1.7.0 AWS ubuntu source

**Comment by rapcmia** [comment]
While checking our test bot on Binance, this results to orders recreated on the same price every order cycle.
![WindowsTerminal_Pg94rH5Bkp](https://user-images.githubusercontent.com/73840223/184094031-512dc954-70a9-4743-99ea-b5ef02490294.gif)

**Comment by RC-13** [comment]
On mac m1, running from source, I don't see the issue.
Ticker - order book:

https://user-images.githubusercontent.com/57189990/184758154-0df9c46a-0110-43c6-a323-9964ed1cc5fc.mov

Status - order book:

https://user-images.githubusercontent.com/57189990/184758135-7f41fcd8-1cb5-4d96-9e53-419c6f9ceb4b.mov

**Comment by nikspz** [comment]
Yeah, this issue should be fixed with https://github.com/hummingbot/hummingbot/pull/5587
