### ISSUE TITLE
Gateway v2 - token pairs on avalanche chain are doubled on when checking on autocomplete lists

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5590]
**Describe the bug**
When checking autocomplete list feature on gateway connectors, we noticed that when setting up two connectors under avalanche chain the markets displayed are getting doubled

![image](https://user-images.githubusercontent.com/73840223/184311093-e010d03b-1689-49a3-89aa-b9ac5b3d6a2f.png)

Tried to add another connector (third) under avalanche chain but it seems the issue only display it twice.

**Steps To Reproduce**
1. Setup Pangolin, TraderJoe and OpenOcean connector using `gateway connect xxx`
2. Relaunch the client 
3. Setup simple amm-arbitrage
4. On `Enter your first connector...` prompt, enter `WAVAX- ,wWAGMI- ,WETH.e`

**Release version**
v1.6.0 and development branch

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to Gateway-v2 UI

**Comment by han-qiu** [comment]
I'd like to take this.

**Comment by rapcmia** [comment]
hi @han-qiu thanks for participating to the bounty program. This will be assigned to you

**Comment by JeremyKono** [comment]
> 
Hi, closing this issue as it has been marked as paid. Thank you for your contribution!
