### ISSUE TITLE
Autostart of Avellaneda Marketing Strategy Returns Error at Command line

### ISSUE THREAD

**Issue by akim-tor** [hummingbot/hummingbot#5593]
**Describe the bug**
When trying to autostart an avellaneda market making strategy using the command "bin/hummingbot_quickstart.py -f avellaneda-test.yml -p password" returns an error

**Steps To Reproduce**
1. Compile and run from source.
2. Run hummingbot and create an avellaneda market making strategy. Save the strategy as avellaneda-test.yml
3. Exit
4. From the command line run the command "bin/hummingbot_quickstart.py -f avellaneda-test.yml -p password"

I am running this on Amazon AWS

**Screenshots**
Here is the error that it returns.
![Screenshot 2022-08-14 151230](https://user-images.githubusercontent.com/68867545/184683816-7450f922-957f-4377-900f-868741fc52d2.jpg)

**Release version**
ver 1.6.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by akim-tor** [comment]
Taking a deeper look at the code, I fixed it the problem.

In the hummingbot_quickstart.py file, one line needs to be corrected. Starting at line 104
from:
`
hb.strategy_name = (
    strategy_config.strategy
    if isinstance(strategy_config, BaseStrategyConfigMap)
    else strategy_config.get("strategy").value
)
`

To:
`
hb.strategy_name = (
    strategy_config.strategy
    if isinstance(strategy_config, ClientConfigAdapter)
    else strategy_config.get("strategy").value
)
`

**Comment by MementoRC** [comment]
Great, will you be making a PR for this fix?
