### ISSUE TITLE
Client - allows you to change name of strategy while the bot is active

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5617]
**Describe the bug**
We noticed that even if a strategy is actively running, we can execute the `config strategy` and the client is still modify/save the strategy parameter even a invalid input. Running stop and start command seems to be working ok and still recognizes the initial strategy before it was changed. Example on the screenshot:

`config strategy xxx`
![Screen Shot 2022-08-25 at 7 29 10 PM](https://user-images.githubusercontent.com/73840223/186655729-fa789bd8-06a4-487f-8bf4-35d1e3a5535d.png)

`config strategy`
![Screen Shot 2022-08-25 at 7 40 48 PM](https://user-images.githubusercontent.com/73840223/186656097-8a1949f1-976d-4b53-8124-11cf2810eae4.png)

Tried to relaunch the hummingbot client and import the strategy file and we got an error of `invalid strategy specified in the file`
![Screen Shot 2022-08-25 at 7 33 50 PM](https://user-images.githubusercontent.com/73840223/186656403-9b220227-4ebe-48b9-a7c4-57ba23165fa8.png)

This issue can normally be found on the following strategies:
- liquidity_mining
- spot_perpetual_arbitrage
- uniswap_v3_lp
- amm_arb

The workaround to fix this issue is by manually updating the `strategy` on the your_strategy.yml file found in `conf/strategies` folder

**Steps To Reproduce**
1. Select and create a simple strategy from the affected list above
2. Start the strategy
3. Run `config strategy` or `config strategy xxx` then check the updates by using `config` command
4. Stop and Start the client, notice the client would still recognize the initial strategy that was used
5. Relaunch the client and import the strategy file, notice you would get `invalid strategy specified in the file`

**Release version**
1.6.0 and development branch 1.7

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to component

**Comment by MementoRC** [comment]
@rapcmia This does no longer seem to be the case:


![Image](https://user-images.githubusercontent.com/93164135/195202313-0815a7c1-39f8-4716-b2b9-efcbda6758e0.png)

**Comment by rapcmia** [comment]
Hi @MementoRC yes correct it was observed not happening for other strategies which I assume on the screenshot is Pure market-making. 

> This issue can normally be found on the following strategies:
> - liquidity_mining
>- spot_perpetual_arbitrage
>- uniswap_v3_lp
>- amm_arb

**Comment by MementoRC** [comment]
@rapcmia got it, it's for the non-`ConfigMap` strategies, i should have guessed it when observing the non-issue. I can continue to look into it then

**Comment by rapcmia** [comment]
Hi @MementoRC, good day
Thanks for your time, yes that's correct it would be better if the expected behavior is the same as for the other strategies therefore the 2nd option is ok :grin:

> or rather remove the 'strategy' from the list of configurable fields:
> 
> ![Image](https://user-images.githubusercontent.com/93164135/195905164-c21c4d0c-9e3f-46a3-9ac6-2c029016e861.png)

**Comment by MementoRC** [comment]
This proposed PR has both included, but ofc the removal from the auto-complete takes precedence

**Comment by JeremyKono** [comment]
assigned to @MementoRC. thank you for your contribution!

**Comment by nikspz** [comment]
Fixed with https://github.com/hummingbot/hummingbot/pull/5809

**Comment by JeremyKono** [comment]
Bounty has been paid. Thank you for your contribution!

**Comment by nikspz** [comment]
fix has been deployed and available on the Hummingbot version 1.9.0 release
