### ISSUE TITLE
Gateway creates multiple certs folders

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#5623]
**Describe the bug**

Gateway creates multiple dummy copies of the `.hummingbot-gateway` directory used to house certs. This prevents developers from connecting the right certs path to their local Gateway server

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

1. start Hummingbot from a fresh install
2. run `gateway generate_certs`
3. exit Hummingbot and restart
4. run `gateway generate_certs`

**Expected behavior:** Gateway should not create a new certs folder because one already exists

**Actual behavior:** Gateway creates a duplicate version of certs in the `.hummingbot-gateway` folder. If you are running Gateway from source, you have to add those new certs to `ssl.yml`. However, when you restart Gateway, it will create another duplicate version and say that Gateway is offline.

**Screenshots**

*If certs have already been generated, Gateway shouldn't let user generate again, like below. However, if you exit Hummingbot and generate again, it lets you generate them.*

<img width="850" alt="Screen Shot 2022-08-25 at 2 19 16 PM" src="https://user-images.githubusercontent.com/1795030/186771685-9d8a2866-5e27-4a00-8f68-99db4a86ebcb.png">

**Release version**
`dev-1.7`, `staging`

**Comment by mifeng** [comment]
Did some testing and it looks like the workaround is to keep the Hummingbot client running while you set up Gateway in another Terminal window. After it establishes connection, then you have to connect to at least one DEX and add a wallet. Then, if you quit the client and start it again, it will remember your prior Gateway cert path and use it.

However, if you simply connect to Gateway and don't connect a DEX/wallet, then the client will create another `.hummingbot-gateway` folder when it restarts.

**Comment by rapcmia** [comment]
gateway has been refactored and this issue is does not occur anymore
