### ISSUE TITLE
Gateway - Uniswap_ethereum_mainnet stuck on waiting for allowances

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5625]
**Describe the bug**
While testing gateway-v2 on the staging branch and another PR, we noticed that Uniswap-Ethereum-mainnet does not proceed with token approval and is stuck waiting for allowances.  Tried different tokens (WETH, CRO, etc) and wallets but to no avail

![Screenshot 2022-08-26 180045](https://user-images.githubusercontent.com/73840223/186880514-9ef3c0cf-7205-43d4-aca6-a3db016b4794.png)

Tried to change the node URL and use either ankr or infura but still waiting for allowances

```
https://mainnet.infura.io/v3/...
https://rpc.ankr.com/eth
```

We also tried to test endpoint and it seems it doesn't recognize the tokens we used for testing as well. On the screenshot below we tried to run `evm/approve` but getting `token not supported` which was working on previous tests

![Screenshot 2022-08-26 175643](https://user-images.githubusercontent.com/73840223/186881283-fcda4291-78aa-4ca0-95b3-505ffc733ea5.png)

```

# cat requests/eth_approve.json from ../gateway/manual-tests
{
  "chain": "ethereum",
  "network": "mainnet",
  "address": "$ETH_ADDRESS",
  "spender": "uniswap",
  "token": "WETH"
}

curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "Content-Type: application/json" -d "$(envsubst < ./requests/eth_approve.json)" https://localhost:$PORT/evm/approve | jq
```

This has been tested locally and AWS instance. Other Uniswap-Ethereum networks Mumbai, Optimism and chains such as Pangolin and TradeJoe for Avalanche, Harmony, etc.. are not affected.

**Steps To Reproduce**
1. Setup gateway-v2 on staging or development branch
2. Create simple AMM arbitrage on `Uniswap-Ethereum-mainnet `
3. Start the strategy and notice that the client is stuck on waiting for the allowance 

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
staging 1.7 and development branch

**Attachments**
[amm-uniswap-mainnet.zip](https://github.com/hummingbot/hummingbot/files/9432268/amm-uniswap-mainnet.zip)

**Comment by rapcmia** [comment]
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to Gateway-v2 `Uniswap -> ethereum -> mainnet` component

**Comment by han-qiu** [comment]
Is this already fixed by @Faouzijedidi1 ?

**Comment by rapcmia** [comment]
Fixed
