### ISSUE TITLE
DYDX problems with "good til" cap to 10 min 

### ISSUE THREAD

**Issue by Willstar44** [hummingbot/hummingbot#5659]
**Describe the bug**
All order place on dydx are cap to 10 min expiry , if you use a order refresh time of  longer then 10 min dydx will cancel order from dydx side and the bot will not re-place a new order 

**Steps To Reproduce**
upgrade the order limit max time , dydx has a limit order max time of 28 days

**Comment by nikspz** [comment]
Reproduced using dev-1.12.0

![image](https://user-images.githubusercontent.com/83953535/209126930-91c377a0-26c1-4336-81e0-9bdbb7da6ce9.png)

**Comment by nikspz** [comment]
Severity: P2
Bounty: 50000 HBOT (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to [dYdX perpetual](https://docs.hummingbot.org/exchanges/dydx-perpetual/) exchange (or component)

**Comment by petioptrv** [comment]
CoinAlpha is interested in tackling this issue.

**Comment by fengtality** [comment]
Assigned to @petioptrv from CoinAlpha

**Comment by nikspz** [comment]
hi @petioptrv please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by nikspz** [comment]
Sorry as discussed it will be paid to the CA Wallet

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to CoinAlpha Wallet. The fix has been deployed on development branch and next hummingbot version 1.18.0.
