### ISSUE TITLE
grid exchange,做一个网格交易吧

### ISSUE THREAD

**Issue by phpmac** [hummingbot/hummingbot#5673]
grid exchange,做一个网格交易吧

**Comment by phpmac** [comment]
for dydx

**Comment by phpmac** [comment]
for perpetual_market_making

**Comment by cardosofede** [comment]
Hi @phpmac ! We are not managing the improvements or new strategies. You can create a forum on Discourse: https://hummingbot.discourse.group/t/hip-bot-orchestration/186 (here you have an example), and explain why it's important and then if some of the community wants to implement the strategy, you can create the HIP!
