### ISSUE TITLE
Gateway v2 - Unable to create gateway after using the `update.sh` helper script

### ISSUE THREAD

**Issue by glarkou** [hummingbot/hummingbot#5676]
**Describe the bug**
// A clear and concise description of what the bug is.

Cannot create gateway

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Run the bot and type: `gateway create`

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/25099792/188962971-616daa4b-54d8-4558-a12b-a08520837a97.png)

![image](https://user-images.githubusercontent.com/25099792/188962695-b7c0e127-98b7-45b7-8a51-f608f004d20d.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
v1.7.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Hi @glarkou just to confirm are you using docker build on this ticket? I was able to reproduce it after running `update.sh` helper script. If you can provide us the steps to reproduce so we can further check this bug thanks!

**Comment by glarkou** [comment]
Yes exactly @rapcmia . I faced that issue after running `update.sh` screen. Using `create.sh` everything worked.

**Comment by rapcmia** [comment]
Severity: P2
Bounty: 50000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to a component in gateway

**Comment by MementoRC** [comment]
Proposed a PR:https://github.com/hummingbot/hummingbot/pull/5729

**Comment by JeremyKono** [comment]
Assigning this PR to @MementoRC. Thank you for the contribution!

**Comment by rapcmia** [comment]
The fix has been added to the upcoming version 1.9.0 release.
