### ISSUE TITLE
Call Hummingbot commands externally

### ISSUE THREAD

**Issue by julianmukaj** [hummingbot/hummingbot#5691]
Not sure if this is possible yet or not, been reading through documentation and haven't seen it.

Is there a way to call hummingbot commands outside the instance? For example if I want to update the config hourly via some automated process, just changing the .yml does not update hummingbot, so would be good to have a way to get to pick up the new config without having to kill then start the process.

**Comment by cardosofede** [comment]
Hi @julianmukaj! The community is currently working in the solution, here you can find the details: 
https://hummingbot.discourse.group/t/hip-bot-orchestration/186
