### ISSUE TITLE
Gateway v2 cannot show balance except from Eth

### ISSUE THREAD

**Issue by glarkou** [hummingbot/hummingbot#5694]
**Describe the bug**
// A clear and concise description of what the bug is.
When running the balance command on Gateway v2 it does not show any balance except ETH.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

1. Create a new bot
2. Connect to Gateway v2
3. Add key
4. Run `balance` command
5. Run `gateway connector-tokens uniswap_ethereum_mainnet ETH,USDT`
6. Run `balance` command
7. It does not show your USDT balance

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
8. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
Not sure if this is related to https://github.com/hummingbot/hummingbot/issues/5577

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
1.7.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Hi @glarkou good day to you,
Please be advised a ticket has already been created for this issue and waiting for a fix from one of our community devs. You may want to add your issue as a comment on this ticket https://github.com/hummingbot/hummingbot/issues/5577. Thank you!
