### ISSUE TITLE
XEMM - Incorrect rate oracle conversion

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5695]
**Describe the bug**
When using XEMM and Gateway, we observed that the `rate_oracle_conversion_rate` is inconsistent as it will return an error of `Cant find conversion rate for...` which will set the default conversion to 1. However when we tried to stop/start, it would display the conversion rate again.

This has been tested using `rate_orace_source Binance, Ascendex, Kucoin and Coingecko`, on the screenshot below is a sample we found when using Kucoin and CoinGecko
![Screenshot 2022-09-12 135844](https://user-images.githubusercontent.com/73840223/189584298-1da12efa-c192-4437-a805-769191db7323.png)

![image](https://user-images.githubusercontent.com/73840223/189586133-a255a95f-ee3f-48f8-b5b4-0302bcc1300a.png)

**Steps To Reproduce**
1. Setup XEMM and Gateway
2. Setup CEX and Gateway connector (on this test we used Kucoin and Pangolin-Avalanche)
3. Start the strategy, notice the conversion rate on the log panel 
4. If its showing the default 1, try to stop/start the strategy

**Release version**
Development dev-1.8.0

**Comment by JeremyKono** [comment]
Severity: p3
Bounty: 10000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to a component

**Comment by MementoRC** [comment]
Proposed a PR:https://github.com/hummingbot/hummingbot/pull/5728

**Comment by JeremyKono** [comment]
Assigning this PR to @MementoRC. Thank you for your contribution!

**Comment by kadirc** [comment]
@JeremyKono should have been addressed by #5812 , could you assign to me?

**Comment by MementoRC** [comment]
@JeremyKono This should be not be assigned to me, the PR I proposed is closed and obsoleted by https://github.com/hummingbot/hummingbot/pull/5812

**Comment by JeremyKono** [comment]
Bounty has been paid. Thank you for your contribution!

**Comment by nikspz** [comment]
Closed that issue as fixed with https://github.com/hummingbot/hummingbot/pull/5812
