### ISSUE TITLE
Kucoin - Getting rate limit on api/v1/fills 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5696]
**Describe the bug**
When using `kucoin ` as CEX for testing strategies and monitoring, we observed that the client kept on getting api rate limit on `api/v1/fills`

XEMM:
- We observed this happening when setting up order_refresh_mode to active_order_refresh 
- Set min_profitability to low value, on our testing we used `0.00001`
![image](https://user-images.githubusercontent.com/73840223/189588003-c73bdb73-50ee-44f6-aec2-24c4b0ea8455.png)

Liquidity Mining:
- This can be easily triggered by running 2-3 market pairs 
- It would be also reproduced by setting `order_refresh_tolerance` to -1 to disable it so the client continuously creating orders
![Liquidity mining](https://user-images.githubusercontent.com/73840223/189588034-8b91d4ae-937a-405b-81a0-0f4e92274789.png)

Pure market making:
- Setup a short or long refresh time on a multiple order levels
![image](https://user-images.githubusercontent.com/73840223/189589867-822e10a4-ae31-45c4-b7fd-d541f4e7555d.png)

While this happens, i see that my order creation/cancellation or trades seems to be working fine and no stuck orders on exchange.

**Steps To Reproduce**
1. Setup simple XEMM and LM strategy using Kucoin
2. Setup simple Pure market making strategy with multiple orders on short/long refresh time 
3. Start the strategies and monitor client logs 

**Release version**
Development dev-1.8.0

**Attachments**
[kucoin.zip](https://github.com/hummingbot/hummingbot/files/9545422/kucoin.zip)

**Comment by glarkou** [comment]
@rapcmia we face exactly the same issue as well.

**Comment by MementoRC** [comment]
This is an expected behavior of the Throttler, it actually illustrates that it is working perfectly well, rate limiting a request that is happening above the rate limit. Once a request arise above the rate limit, the throttler will hold it until the sliding window in time adds sufficient number of seconds for the request to be executed.
When the throttler limits a request, it emits this warning. If the request was to go through, the trading activity would be stopped since Kucoin would ban the requester for 5mns.
Now, is the "bug" that it is unexpected that there are that many requests?

**Comment by rapcmia** [comment]
Hi @MementoRC correct, this would be the expected behavior when hitting the rate limit however we posted this ticket since it has been noticeably active compared to previous version of the client `1.6.0`. Same test has been done both previous and current version and observed that it happened more often.

**Comment by MementoRC** [comment]
Understood, I found a potential issue and have a tentative fix for it
Note that while browsing through, I found odd configurations of the Rate limits for this connector, it seems to me that, sooner or later a HFT trader will bump into actual violations of rate limits
I will focus on resolving this issue first

**Comment by JeremyKono** [comment]
Severity: p3
Bounty: 10000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to a component

**Comment by JeremyKono** [comment]
Assigning this issue to @MementoRC. thank you for your contribution!

**Comment by rapcmia** [comment]
Closing ticket since fix has been deployed to version 1.8.0
