### ISSUE TITLE
Prompt for confirmation if a source-installed Hummingbot user runs `gateway create`

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#5706]
**Feature Suggestion**

* Hummingbot Gateway is designed to be installed by running `gateway create` from Hummingbot client (which pulls Gateway Docker image and automatically configures it), or from source by developers.
* The `gateway create` method is designed for instances of Humminbot installed via Docker, while Gateway source is designed to work with instances of Hummingbot installed from source
* However, source-installed Hummingbot instances can still run `gateway create`, and it may be hard for users to switch to the source-installed Gateway afterwards
* Therefore, after user runs `gateway create`, if the user is not running the Docker version of Hummingbot, add the following prompt: `This command will automatically install Gateway as a Docker image, and it is designed to work with Docker versions of Hummingbot only. Are you sure that you want to continue? (Yes/No)?`
* Only continue to pull Docker image if user answers Yes
* Do not show this prompt if users are running Hummingbot from source

**Comment by rapcmia** [comment]
gateway has been refactored and `gateway create` command has been removed
