### ISSUE TITLE
Trading rules logic

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5709]
**Describe the bug**
If one of these trading rules **min order size** or **min notional size** is violated, the bot will return the amount s_decimal_0 and say that it's failing due min order size.
The logic should not truncate the value and also log to the user which is the trading rule that it's failing.

**Steps To Reproduce**
I created a test to show that it's failing https://gist.github.com/cardosofede/e6a28f1f424992049bfd41e7e4998eb8

Here are the steps to reproduce the issue (see attachments in the section below):

**Screenshots**

**Release version**

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Fix for this issue has been added https://github.com/hummingbot/hummingbot/pull/6467 to version 1.18.0
