### ISSUE TITLE
Installation on Windows: PermissionError: [Errno 1] Operation not permitted: '/home/hummingbot/conf/conf_fee_overrides.yml'

### ISSUE THREAD

**Issue by delavegaOpengl** [hummingbot/hummingbot#5714]
I tried installation with docker on windows via script, but i got this error:

diego@MSI:/mnt/d$ ./create.sh

===============  CREATE A NEW HUMMINGBOT INSTANCE ===============

ℹ️  Press [ENTER] for default values:

   Enter Hummingbot version you want to use [latest/development] (default = "latest") >>>
   Enter a name for your new Hummingbot instance (default = "hummingbot-instance") >>>
   Enter a folder name where your Hummingbot files will be saved (default = "hummingbot_files") >>>

ℹ️  Confirm below if the instance and its folders are correct:

                Instance name: hummingbot-instance
                      Version: hummingbot/hummingbot:latest

             Main folder path: /mnt/d/hummingbot_files
                 Config files: ├── /mnt/d/hummingbot_files/hummingbot_conf
                    Log files: ├── /mnt/d/hummingbot_files/hummingbot_logs
         Trade and data files: ├── /mnt/d/hummingbot_files/hummingbot_data
            PMM scripts files: ├── /mnt/d/hummingbot_files/hummingbot_pmm_scripts
                Scripts files: ├── /mnt/d/hummingbot_files/hummingbot_scripts
                   Cert files: ├── /mnt/d/hummingbot_files/hummingbot_certs
         Gateway config files: └── /mnt/d/hummingbot_files/gateway_conf
            Gateway log files: └── /mnt/d/hummingbot_files/gateway_logs

   Do you want to proceed? [Y/N] >>> y

Creating Hummingbot instance ... Admin password may be required to set the required permissions ...

Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 152, in <module>
    fork_and_start(main)
  File "/home/hummingbot/bin/docker_connection.py", line 137, in fork_and_start
    main_function()
  File "bin/hummingbot_quickstart.py", line 148, in main
    asyncio.get_event_loop().run_until_complete(quick_start(args, secrets_manager))
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bin/hummingbot_quickstart.py", line 88, in quick_start
    await create_yml_files_legacy()
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 801, in create_yml_files_legacy
    shutil.copy(template_path, conf_path)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/shutil.py", line 416, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/shutil.py", line 305, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: '/home/hummingbot/conf/conf_fee_overrides.yml'

**Comment by rapcmia** [comment]
Hi @delavegaOpengl Good day to you, I'm unable to reproduce this issue when using our helper scripts for docker installation and I'm also using Win11. I've followed the same steps provided on our [docs ](https://docs.hummingbot.org/installation/docker/)and installed it successfully, perhaps you can try to change the directory and try again? Thank you

![image](https://user-images.githubusercontent.com/73840223/191146386-66ebba03-7b66-4c05-aee2-171273fce6f2.png)
