### ISSUE TITLE
Gateway - XEMM not working on Arbitrum Uniswap

### ISSUE THREAD

**Issue by preze93** [hummingbot/hummingbot#5715]
Hi guys, 
As suggested by @Faouzijedidi1 , I leave here a bug that I found when trying Gateway with XEMM on UNISWAP Arbitrum network

I set up a XEMM strategy having a CEX as my maker (GMX-USDT) and Arbitrum Uniswap (GMX-USDC) as a taker exchange. I load up the tokens on both sides so that the bot is able to trade and also leaving some Eth for gas
![image](https://user-images.githubusercontent.com/16908747/190985003-43a5fde3-9e5c-420c-9202-84d46fae04e8.png)

Nonetheless when, I start my strategy the bot tells that both GMX and USDC balance are low on the gateway side, despite having them in my wallet as you saw above
![image](https://user-images.githubusercontent.com/16908747/190985244-5108de22-89ff-4eaa-a299-47d2fa6df049.png)

With this, the bot is not able to start making orders and the strategy does not work
Hbot log files are also empty
![image](https://user-images.githubusercontent.com/16908747/190985969-63af7f51-e28f-4246-8142-06be1d09caa5.png)

I have not tested this issue in XEMM with avalanche network but will do as soon as possible and paste here the findings

Thanks, preze#3890

**Comment by nikspz** [comment]
Hi @preze93 could you please share your config and log files? this will really help us to triage

**Comment by preze93** [comment]
Hi @nikspz 
Here you go
[logs_XEMM_GMX_MEXC_UNI_ARBITRUM_20220912.log](https://github.com/hummingbot/hummingbot/files/9604912/logs_XEMM_GMX_MEXC_UNI_ARBITRUM_20220912.log)

[XEMM_GMX_MEXC_UNI_ARBITRUM_20220912.txt](https://github.com/hummingbot/hummingbot/files/9604922/XEMM_GMX_MEXC_UNI_ARBITRUM_20220912.txt)

**Comment by nikspz** [comment]
@preze93 
The issue seems to be that this pair do not have enough liquidity in uniswap. 
![image](https://user-images.githubusercontent.com/83953535/191263133-ae54dfca-b102-45bc-8b80-95bb2d615075.png)

**Comment by preze93** [comment]
Hi @nikspz you are using the wrong smart contract. Perhaps it is a scam as I can see 2 GMX tokens on Uniswap Arbitrum
The official contract is 0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a.
![image](https://user-images.githubusercontent.com/16908747/191306664-9fbd9ccf-7605-46b8-9954-5e0604c6d509.png)

GMX-USDC already had more than 1m$ traded in 24h
![image](https://user-images.githubusercontent.com/16908747/191306950-5275f307-d78a-45e4-a192-e4b0f80458f0.png)

**Comment by nikspz** [comment]
> Hi @nikspz you are using the wrong smart contract. Perhaps it is a scam as I can see 2 GMX tokens on Uniswap Arbitrum The official contract is 0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a. 

Yep, could add it now, thanks.
![image](https://user-images.githubusercontent.com/83953535/191343488-74bd22c2-ce68-4919-b63e-cd5074d0d8d1.png)

We're currently working on the fix https://github.com/hummingbot/hummingbot/pull/5664 for arbitrum pairs using less decimals (USDC use 6), that's most likely related to your issue.

**Comment by preze93** [comment]
Hi @nikspz thanks.  I don't think that should be the only issue. Not being able to see the correct balances on the wallet (WETH, GMX, USDC etc.) is also something to pay attention to as it appears that the connector is not pulling all the data from the wallet and then the strategy cannot deliver for lack of tokens as well

**Comment by rapcmia** [comment]
Hi @preze93 good day and apologies for not responding back
Looks like it has something to do with the default tokenlist used on this connector. While this is true, I tried also to create a modified version of the json file and finding some issues with it. Please give us more time to investigate this case and will get back to you 🙇

**Comment by rapcmia** [comment]
Hi @preze93 good day to you
The foundation team updated our tokenListSource on gateway and added a fix for this issue which will be available on the upcoming version 1.11.0 release. The fix is also available on our development branch atm if you want to have a look with it. We will close the ticket for now, else please feel free to reopen for further investigation. Thank you!
