### ISSUE TITLE
Trading pairs property wrong in Paper Trade exchange

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5720]
**Describe the bug**
The property to access the trading pairs of the paper trade exchange is trading_pair and it should be trading_pairs as the rest of the connectors.
This is an issue because if you are writing a script and you want to test it in paper trade and then run live, the method will be different and you should change the property.

**Steps To Reproduce**
Run a script and access the trading pairs of a paper trade connector and then use the same connector without paper trade.

Here are the steps to reproduce the issue (see attachments in the section below):

Run this script:
Change the extension to .py
[paper_trade_issue.txt](https://github.com/hummingbot/hummingbot/files/9609531/paper_trade_issue.txt)

**Screenshots**
Logs showing that the Binance connector shows the trading pairs while the paper trade exchange connector has an issue
<img width="800" alt="image" src="https://user-images.githubusercontent.com/36869960/191311249-4c2b9448-07f5-42d0-ae91-af9e3281daa6.png">

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by nikspz** [comment]
fix has been deployed and available on the Hummingbot version 1.9.0 release
