### ISSUE TITLE
Ordertype.LIMIT_MAKER is creating market order

### ISSUE THREAD

**Issue by KlaSun** [hummingbot/hummingbot#5725]
For self.buy(), if I set order_type to OrderType.LIMIT_MAKER, it will send a market order. This is when trading on binance_perpetual, using the following code:
self.buy(
                    connector_name="binance_perpetual",
                    trading_pair='ETH-USDT',
                    amount=0.04
                    order_type=OrderType.LIMIT_MAKER,
                    price=buy_price,
                    position_action=PositionAction.OPEN
                )

If I use OrderType.LIMIT then everything works fine.

This error can be reproduced by trying to use order_type=OrderType.LIMIT_MAKER on binance_perpetuals (perhaps on other connectors too).

Bug happens on version 1.7.0

Discord: Klakteuh#2368

**Comment by amitds1997** [comment]
`LIMIT_MAKER` orders are not supported by Binance Perpetual connector currently. If you look at the [source code](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py#L1239-L1259), you'll see that the `LIMIT` order type is set only for `OrderType.LIMIT` on [#L1247](https://github.com/hummingbot/hummingbot/blob/f1115b480b306ab62adc39815f89f4c0577d4857/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py#L1247) right now, and all other order types are sent as MARKET orders.

**Comment by cardosofede** [comment]
@amitds1997 is right, you should propose the improvement to add the order type. If you want a quick fix, add OrderType.LIMIT_MAKER to the list on the file binance_perpetual_derivative.py, Line 197. It has to be like this:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/36869960/192643200-943c6c33-af10-4eea-b022-24bef15b2715.png">
