### ISSUE TITLE
MEXC Sub-Account Connection Timeout

### ISSUE THREAD

**Issue by austin-astrid** [hummingbot/hummingbot#5740]
**Describe the bug**
When using MEXC sub-account  api key and secret key to connect to mexc, the websocket connect always timeout.

**Steps To Reproduce**
Use MEXC sub-account api key and secret key to connect to mexc and then start pure-market-making strategy.

**Release version**
commit f1115b480b306ab62adc39815f89f4c0577d4857

**Comment by nikspz** [comment]
Will close this issue as duplicated with https://github.com/hummingbot/hummingbot/issues/5777
