### ISSUE TITLE
Order levels with bollinger bands deviation

### ISSUE THREAD

**Issue by vdud** [hummingbot/hummingbot#5752]
Is there any way we can train the software to adjust the order spread levels accordingly to bollinger bands deviation?

**Comment by vdud** [comment]
Meaning when there's a compression in bollinger bands the spread automatically expand. 
Or simply we can adjust the spread between increments of few orders that would be also perfect

**Comment by vdud** [comment]
Something like this;

- Order
- Order
- Gap
- Gap
- Order
- Order
- Original order
- Mid price
- And so on

**Comment by vdud** [comment]
Or training could be camarilla pivots. To have spread expand and compress.

**Comment by rapcmia** [comment]
Hi @vdud you may want to checkout [strategy_v2](https://github.com/hummingbot/hummingbot/pull/6520) on our latest version 1.20.0
