### ISSUE TITLE
Add Gate.io Perpetuals to the codebase

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5788]
The rationale behind this enhancement was discussed in this forum thread: https://forum.hummingbot.org/t/hip-cex-connectors-revamp/212

**Comment by yancong001** [comment]
I would like to be assigned this ticket

**Comment by JeremyKono** [comment]
Assigning this issue to @yancong001. Thank you for your contribution!

**Comment by nikspz** [comment]
PR for gate io perpetual: https://github.com/hummingbot/hummingbot/pull/5798

**Comment by JeremyKono** [comment]
Hi @yancong001, your PR has been merged. Can you please provide us with your ETH wallet so we can send payment? Thanks.

**Comment by yancong001** [comment]
> Hi @yancong001, your PR has been merged. Can you please provide us with your ETH wallet so we can send payment? Thanks.

hi,it's my account 
0xDb40C5FF1EfC28Af389D99F5f4Ec01E18A6Df771
