### ISSUE TITLE
Upgrade Bybit Spot to v2.1

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5791]
The rationale behind this enhancement was discussed in this forum thread: https://forum.hummingbot.org/t/hip-cex-connectors-revamp/212

**Comment by yancong001** [comment]
I would like to be assigned this ticket

**Comment by cardosofede** [comment]
@JeremyKono this will be assigned to @yancong001

**Comment by yancong001** [comment]
https://github.com/hummingbot/hummingbot/pull/5798

here is my PR;
