### ISSUE TITLE
Upgrade Ascendex Spot to v2.1

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5792]
The rationale behind this enhancement was discussed in this forum thread: https://forum.hummingbot.org/t/hip-cex-connectors-revamp/212

**Comment by cmichaeltimmons** [comment]
Can you assign this one to me and remove me from https://github.com/hummingbot/hummingbot/issues/5794.   I cannot create an api key with Hitbtc without kycing and their sandbox environment is currently down.

**Comment by HODLER-CODING** [comment]
I would like to be assigned this bounty thanks

**Comment by PeterCHK** [comment]
Also would like to get assigned to this bounty.

**Comment by dennisocana** [comment]
We (CoinAlpha) would like to be assigned to this bounty.

**Comment by JeremyKono** [comment]
Will be assigning this bounty to CoinAlpha.

**Comment by MementoRC** [comment]
@JeremyKono Is it assigned to CoinAlpha because of how long it remained unassigned? I am interested in giving it a try if that's the case

**Comment by JeremyKono** [comment]
It is assigned to CoinAlpha since they have it already upgraded and will be easier for them to update @MementoRC

**Comment by JeremyKono** [comment]
This bounty has been paid. Thanks!

**Comment by nikspz** [comment]
Closing this enhancement as it has been marked as paid. Thank you for your contribution!
