### ISSUE TITLE
Upgrade HitBTC to v2.1

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5794]
The rationale behind this enhancement was discussed in this forum thread: https://forum.hummingbot.org/t/hip-cex-connectors-revamp/212

**Comment by JeremyKono** [comment]
Assigning this issue to @cmichaeltimmons. Thank you for your contribution!

**Comment by JeremyKono** [comment]
Hi @cmichaeltimmons, can you please give us an update on this issue? Have you created a PR yet?

**Comment by cmichaeltimmons** [comment]
- [ ] implement update_balances
- [ ] implement api_user_stream_data_source (multiple methods, will break down later)
- [ ] implement user_stream_data_source (multiple methods, will break down later)
- [ ] implement config_map
- [ ] implement rest_authenticate
- [ ] implement ws_authenticate
- [ ] implement initialize_trading_pair_symbols_from_exchange_info
- [ ] implement get_fee
- [ ] implement place_order
- [ ] implement place_cancel
- [ ] implement format_trading_rules
- [ ] implement status_polling_loop_fetch_updates
- [ ] implement update_trading_fees
- [ ] implement user_stream_event_listener
- [ ] implement update_order_fills_from_trades
- [ ] implement all_trade_updates_for_order
- [ ] implement request_order_status
- [ ] implement get_last_traded_price
- [ ] test utils
- [ ] test web_utils
- [ ] test user_stream_data
- [ ] test order_book
- [ ] test exchange
- [ ] test auth
- [ ] test api_order_book

**Comment by cmichaeltimmons** [comment]
I have a meeting with Fede on November 10th to answer some questions I have about this upgrade.

**Comment by cmichaeltimmons** [comment]
I have been blocked.  I need to have a meeting with @cardosofede about some things. I was not able to meet with him on the 10th but I scheduled another for the 22ond.  If someone is ready to work on this and can move faster,  I will not be upset.  I plan on completing it if not though.  It is a good learning experience for me with Python and this codebase

**Comment by yancong001** [comment]
I would like to be assigned this bounty and solve the remaining problems.

**Comment by cmichaeltimmons** [comment]
@JeremyKono feel free to assign this to @yancong001

**Comment by yancong001** [comment]
i see
