### ISSUE TITLE
Upgrade Binance Perpetuals to v2.1

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5795]
The rationale behind this enhancement was discussed in this forum thread: https://forum.hummingbot.org/t/hip-cex-connectors-revamp/212

**Comment by HODLER-CODING** [comment]
Hey can this be assigned to me? 
I'm an engineer who has been working in the industry for 5 years and strong in python coding. 
Can talk more about it on discord if you want.

**Comment by yancong001** [comment]
I would like to be assigned this ticket

**Comment by JeremyKono** [comment]
@HODLER-CODING, you have been assigned to this issue. Thank you for your contribution.

**Comment by HODLER-CODING** [comment]
https://github.com/hummingbot/hummingbot/pull/5814

PR submitted thanks

**Comment by yancong001** [comment]
I would like to be assigned this bounty and solve the remaining problems.

**Comment by JeremyKono** [comment]
Removing the bounty of this issue.

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/5976 Merged

**Comment by nikspz** [comment]
Enhancement has been deployed to development branch and will be available on the next release version 1.12
