### ISSUE TITLE
Add Kucoin Perpetuals to the codebase

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5796]
The rationale behind this enhancement was discussed in this forum thread: https://forum.hummingbot.org/t/hip-cex-connectors-revamp/212

**Comment by ethicrypt** [comment]
I would like to be assigned this ticket, I was previously researching how to do this in Hummingbot and have worked with the KuCoin perpetuals API quite a bit.

**Comment by definevalue** [comment]
Where do I claim this bounty ?

**Comment by cardosofede** [comment]
as @ethicrypt asked first, this connector will be assigned to him

**Comment by JeremyKono** [comment]
hi @ethicrypt, can you please provide us an update on the progress of this?

**Comment by ethicrypt** [comment]
Hi @JeremyKono, progress is coming along well for KuCoin perpetuals. I am expecting to be finished testing and ready to merge in about 1-2 weeks time.

**Comment by ethicrypt** [comment]
FYI I am still working on this, very near to completion. I will absolutely have this fully checked in and submitted by the end of February.

**Comment by nikspz** [comment]
Hey @ethicrypt Do you have news on this enhancement?

**Comment by ethicrypt** [comment]
> Hey @ethicrypt Do you have news on this enhancement?

Yes, I'm happy to report that I have the code completed and will be submitting the PR for it today.

**Comment by ethicrypt** [comment]
@JeremyKono My PR has been merged, you can send the bounty to my usual address:  0x493ADd425Fa94Dd93f69389e996bD847d40729cE
