### ISSUE TITLE
Coin Gecko oracle constantly hits rate limits

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/hummingbot#5805]
**Describe the bug**
The Coin Gecko oracle systematically hits the rate limit for the `markets` API method

**Steps To Reproduce**
Set the rate_oracle_source to coin_gecko
Run a strategy (tested with liquidity_minig)
Observe the API limit warning every 30s

**Screenshots**
![image](https://user-images.githubusercontent.com/93164135/195947000-520d2b4c-f87e-4ea7-a5db-2cc9ce4bb7b8.png)

**Release version**
dev-1.9.0

**Optional: your discord username:**
MementoMori

**Comment by rapcmia** [comment]
Fix has been deployed to Hummingbot version 1.10.0
