### ISSUE TITLE
Coin Gecko API not conforming to API for markets

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/hummingbot#5806]
**Describe the bug**
The Coin Gecko API seems to have an undocumented specification (not found yet) in which when a `category` is specified, the API method only returns 50 entries per page, instead of the 250 advertized

**Steps To Reproduce**
Set the rate_oracle_source to coin_gecko
Run a strategy with debug logging the number of entries per categories
Observe the API response length

**Screenshots**
![image](https://user-images.githubusercontent.com/93164135/195957261-bbdb9eee-1c90-470e-8ef8-5e473d676841.png)

**Release version**
dev-1.9.0

**Optional: your discord username:**
MementoMori

**Comment by cardosofede** [comment]
@MementoRC @rapcmia P3 means Priority 3. If it's in the bounties board means that there is a bounty for it.

**Comment by MementoRC** [comment]
@rapcmia @cardosofede THank you for the clarification, there was a mix-up between P[123] and bounties

**Comment by nikspz** [comment]
Closed with #5821
