### ISSUE TITLE
Binance connector not working with Hummingbird from the Source (Ubuntu)

### ISSUE THREAD

**Issue by luky1984** [hummingbot/hummingbot#5808]
**Describe the bug**
I've installed the Hummingbird from the source, then when i try to use binance_paper_trade trading connector it doesn't work. Hummingbird from the docker works.

Note: source was installed via the "scripts" that means the following commands, although the manual version is same i guess, but i just want to say that it clones the default repository from "https://github.com/hummingbot/hummingbot.git"

```
# 1) Download install script
wget https://raw.githubusercontent.com/hummingbot/hummingbot/development/installation/install-from-source/install-source-ubuntu.sh

# 2) Enable script permissions
chmod a+x install-source-ubuntu.sh

# 3) Run installation
./install-source-ubuntu.sh

```

I even tried to clone the "staging" branch like this: (but the error was still present anyway)
`git clone https://github.com/hummingbot/hummingbot.git --single-branch --branch staging
`

**Steps To Reproduce**
- Install Hummingbird from the source
- Create any strategy, i tried the pure_market_making strategy
- Select binance_paper_trade connector

Error in the log console:

> BinanceAPIOrderBookDataSource - Unexpected error occured when listening to order book streams.

Errors in the log file:

#1

```
2022-10-16 18:51:31,497 - 13538 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: BinanceExchange.exchange_symbol_associated_to_pair() takes>
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/root/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 177, in _init_order_books
    self._order_books[trading_pair] = await self._initial_order_book_for_trading_pair(trading_pair)
  File "/root/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 170, in _initial_order_book_for_trading_pair
    return await self._data_source.get_new_order_book(trading_pair)
  File "/root/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 67, in get_new_order_book
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair=trading_pair)
  File "/root/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 112, in _order_book_snapshot
    snapshot: Dict[str, Any] = await self._request_order_book_snapshot(trading_pair)
  File "/root/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 52, in _request_order_book_snapshot
    "symbol": await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair),
TypeError: BinanceExchange.exchange_symbol_associated_to_pair() takes no keyword arguments

```
#2 repeating still over and over

```
2022-10-16 18:51:32,408 - 13538 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source.BinanceAPIOrderBookDataSource - ERROR - Unexpected error occurred>
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 75, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
TypeError: BinanceExchange.exchange_symbol_associated_to_pair() takes no keyword arguments

```

**Screenshots**
<img width="587" alt="Screenshot 2022-10-16 at 23 32 43" src="https://user-images.githubusercontent.com/10039829/196059344-f3ce53f6-3f82-4750-af68-a9be4b2989cc.png">

**Release version**
1.8.0

Btw the installation from the source is broken and doesn't work until you execute the following commands (Ubuntu 20.04)

- apt-get install pip3
- snap install pre-commit --classic
- conda install conda-build
- pip3 install numpy
- pip3 install aioprocessing pandas 0x-order-utils
- pip3 install --upgrade web3
- pip3 install 0x-contract-wrappers cache-tools ujson pydantic ruamel.yaml bidict aiokafka telegram python-telegram-bot sqlalchemy prompt_toolkit scipy psutil pyperclip

maybe also need:

- pip3 install pyYaml
- pip3 install tabulate
- pip3 install cryptography

If the pip3 install lines with multiple libs doesn't work as group, you have to install one by one.

**Comment by rapcmia** [comment]
Hi @luky1984 good day,
Tried to use the installation script for `Ubuntu 20.04` and not getting the error reported on this ticket and able to install and then run `PMM with binance_paper_trade`. However, we can confirm that there are some packages that are broken and needed to be installed but the Hummingbot client still works as expected.

https://user-images.githubusercontent.com/73840223/196103878-7dafa916-dabe-4043-9042-e4bfc46e1ea9.mp4

**Comment by luky1984** [comment]
Hi, were you able to install it only with commands

```
# 1) Download install script
wget https://raw.githubusercontent.com/hummingbot/hummingbot/development/installation/install-from-source/install-source-ubuntu.sh

# 2) Enable script permissions
chmod a+x install-source-ubuntu.sh

# 3) Run installation
./install-source-ubuntu.sh
```
Or how exactly you have installed it?

**Comment by rapcmia** [comment]
@luky1984 same steps

**Comment by cardosofede** [comment]
@rapcmia should we close this issue?
@luky1984 can you install hummingbot?

**Comment by rapcmia** [comment]
Closing ticket, installation script working as expected.
