### ISSUE TITLE
OKX orderbook datasource get the wrong amount

### ISSUE THREAD

**Issue by awayme** [hummingbot/hummingbot#5813]
There are errors in the okx_api_order_book_data_source.py which makes the amount in the order book not correct.

line 43,44 and 108,109:
            "bids": [(bid[0], bid[3]) for bid in snapshot_data["bids"]],
            "asks": [(ask[0], ask[3]) for ask in snapshot_data["asks"]],
should be:
            "bids": [(bid[0], bid[1]) for bid in snapshot_data["bids"]],
            "asks": [(ask[0], ask[1]) for ask in snapshot_data["asks"]],

Version:
1.8.0 and the latest master branch

**Comment by nikspz** [comment]
same in the latest development 1.9.0 code
![image](https://user-images.githubusercontent.com/83953535/196809219-f4874e49-f36d-4085-9474-73bd5e3e06b3.png)

**Comment by nikspz** [comment]
Upon checking OKX exchange `order_book --live`, bid and ask prices updating is OK, but bid and ask volume is wrong
![OKX prices ok, but ask and bid volume is wrong](https://user-images.githubusercontent.com/83953535/196811348-97ec7ee6-6b42-47a2-9b68-a150f8431840.gif)

**Comment by cardosofede** [comment]
@awayme I reviewed the docs and you are right, do you want to provide a PR for this?

**Comment by huatahhhhh** [comment]
@cardosofede can you assign this to me?

**Comment by JeremyKono** [comment]
Assigning this issue to @huatahhhhh.

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to component

**Comment by JeremyKono** [comment]
Hi @huatahhhhh , can you please provide us with your ETH wallet to send the rewards? Thank you

**Comment by huatahhhhh** [comment]
Thank you @JeremyKono My eth wallet address is
0xFe53737f18CABAE9C48DB8dC57d150757d3E4099

**Comment by JeremyKono** [comment]
Bounty has been paid. Thank you for your contribution!

**Comment by nikspz** [comment]
fix has been deployed https://github.com/hummingbot/hummingbot/pull/5828 and will be available on the upcoming Hummingbot version 1.10.0 release

**Comment by huatahhhhh** [comment]
> Bounty has been paid. Thank you for your contribution!

Confirmed and received thanks!
