### ISSUE TITLE
ByBit updated API - Deprecated parameter

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/hummingbot#5824]
**Describe the bug**
ByBit recently deprecated a set of parameters causing HB to fail:

**Steps To Reproduce**
Use strategies using ByBit connector

**Screenshots**
![image](https://user-images.githubusercontent.com/93164135/197399948-205d1a25-7d95-4b09-bf19-408a54bb9c7b.png)

**Release version**
All

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by nikspz** [comment]
Fixed with #5829
