### ISSUE TITLE
handle different tokens which has same symbol

### ISSUE THREAD

**Issue by gzliudan** [hummingbot/hummingbot#5831]
**Feature Suggestion**
Sometimes different tokens have same symbol. But hummingbot use symbol to stand for token. So one symbol can not stand for two 
tokens at same time, there is a token will be disabled in hummingbot when we use token list URL. Can we add a new token list file to override the symbols of token according to token address manually ?

**Comment by fengtality** [comment]
In the this case, you can override the default tokenList with a new list that defines new symbols for those addresses
