### ISSUE TITLE
Unexpected error occurred when listening to order book streams

### ISSUE THREAD

**Issue by nelyajizi** [hummingbot/hummingbot#5841]
**Describe the bug**
// A clear and concise description of what the bug is.
unexpected disconnection very frequently when using hedge strategy or spot_perp_strategy on 1.8.0
when i catch the error in the exception in ws_connection.py, I got:
RuntimeError: Concurrent call to receive() is not allowed

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
create a hedge strategy with dydx or bybit_perpetual (the one I tested)
1. Set up your configuration file with these parameters:  see screenshot for hedge strategy
2. Start the bot using this command:  start

**Screenshots**
// If applicable, add screenshots to help explain your problem.
see log and config screenshot
**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
1.8

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
![hb_log](https://user-images.githubuserconte
![config](https://user-images.githubusercontent.com/45716874/198382614-395f57ee-c2ed-41f4-9695-a2eeabd96ffe.jpg)
[logs_dydx_hedge.log](https://github.com/hummingbot/hummingbot/files/9882646/logs_dydx_hedge.log)

nt.com/45716874/198382608-9c400e53-0028-4aba-8a27-1302dac4d28a.jpeg)

**Comment by nelyajizi** [comment]
mainly in dydx, I tested on bybit and its working fine

**Comment by nikspz** [comment]
Also happened to bybit spot, not affected the pureMM strategy

**Comment by nikspz** [comment]
Issue was related to dydx connector,
dydx_perpetual was refactored with this PR https://github.com/hummingbot/hummingbot/pull/5849
