### ISSUE TITLE
XEMM bot is stopped due to market connection and never resumed itself when connection is back

### ISSUE THREAD

**Issue by tuvshinbayar-mm** [hummingbot/hummingbot#5865]
**Describe the bug**
XEMM bot is stopped and never resumed when some markets are not connected or are down at the moment.
When I checked what market was not connected, it was FTX. 
I expected when FTX gets connected back, the bot should get resumed and work continuously.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a XEMM strategy and configure the taker market as FTX
2. Start the bot and wait until the FTX connection is down (maybe it takes 4 hours or more)
3. Check the status, the bot will be stuck 
4. When FTX connection is back, the bot would not work automatically
...

**Screenshots**
![image](https://user-images.githubusercontent.com/92418675/200096852-b7375663-7548-4e3a-8ff5-4098a318b324.png)
![image](https://user-images.githubusercontent.com/92418675/200096884-bee7bf4e-6007-4a1f-8770-738c35306804.png)

**Release version**
master - v1.9.0

**Comment by nikspz** [comment]
Will close the issue since Ftx is going to be deleted in 1.10.0 Release
