### ISSUE TITLE
Crypto.com - Hummingbot API is outdated 

### ISSUE THREAD

**Issue by Valodax** [hummingbot/hummingbot#5868]
**Describe the bug**
The Crypto.com connector is no longer working.

**Steps To Reproduce**
Create a new strategy using the arbitrage strategy. 
Then select Crypto.com and another exchange for the trading pairs (it doesn't matter what trading pairs).
Run the start command and you should receive this output in the log:

`Traceback (most recent call last):`
`File "/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper`
`return await c`
`File "/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 177, in _init_order_books`
`self._order_books[trading_pair] = await self._initial_order_book_for_trading_pair(trading_pair)`
`File "/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 170, in _initial_order_book_for_trading_pair`
`return await self._data_source.get_new_order_book(trading_pair)`
`File "/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 127, in get_new_order_book`
`snapshot: Dict[str, Any] = await self.get_order_book_data(trading_pair, self._throttler)`
`File "/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 122, in get_order_book_data`
`orderbook_data = orderbook_data[0]["result"]["data"][0]`
`KeyError: 'result'`
`2022-11-07 10:44:07,559 - 24521 - hummingbot.connector.exchange.crypto_com.crypto_com_api_order_book_data_source - ERROR - Unexpected error with fetching order book snapshot via API Request. Retrying in 5 seconds...`
`Traceback (most recent call last):`
`File "/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 251, in listen_for_order_book_snapshots`
`snapshot: Dict[str, any] = await self.get_order_book_data(trading_pair, self._throttler)`
`File "/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 122, in get_order_book_data`
`orderbook_data = orderbook_data[0]["result"]["data"][0]`
`KeyError: 'result' `
[](url)
**Release version**
1.9

**Attachments**
[logs_conf_arb_9.log](https://github.com/hummingbot/hummingbot/files/9953379/logs_conf_arb_9.log)

**Comment by MementoRC** [comment]
@Valodax The log seem to indicate that you are trying to trade an unsupported pair on Crypto.com:
`https://api.crypto.com/v2/public/get-book?instrument_name=LTC_ETH&depth=10`
Please confirm

**Comment by Valodax** [comment]
I believe that was the trading pair given to Kraken. I gave a different trading pair to Crypto.com.

**Comment by bonez56** [comment]
Crypto.com made some significant changes to their Exchange (and API) on 31/10/22, this will need to be checked and taken into account for Hummingbot to work again properly. I am also able to reproduce the same error as OP. All USDC pairs have moved to USD, eg. BTC/USDC is now BTC/USD. They now have a single USD 'bucket', so with the exception of USDT, when you deposit USDC/BUSD/TUSD etc you end up with a single USD wallet balance.

There is some more information here: https://crypto.com/product-news/introducing-the-gen-3-0-crypto-com-exchange/

**Comment by MementoRC** [comment]
@bonez56 @Valodax @rapcmia @cardosofede Correct, however the correct location for the relevant changes are under: https://exchange-docs.crypto.com/spot/index.html#change-logs scroll-down to:
<p style="margin-right: 498.786px; padding: 0px 28px; box-sizing: border-box; display: block; line-height: 1.6; margin-top: 0px; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(243, 247, 249); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="font-weight: bold;">Effective from 2022-06-04 (UAT), 2022-11-01 (PROD)</strong></p>

HB may want to notify users that Crypto.com is not available till the connector websocket is fixed. The next chages would need to also be implemented but production date is TBD and the Gen 3.0 does not seem to have a date

Method | Breaking Change
-- | --

**Comment by bonez56** [comment]
Just received this email from Crypto.com, more changes ahead:

Dear Valued Customer,

Following the launch of the GEN 3.0. Crypto‌.com Exchange, please be informed that there will be API breaking changes to the USD Bundle, impacting both the Exchange v1 API and Spot V2.1 API.

The following changes will happen on 1 December 2022, 20:00 UTC:

    USD_Stable_Coin symbol will be renamed to USD
    Users can still input USD_Stable_Coin and USD to represent the USD Bundle
    However, in response, USD will now be used to represent the USD Bundle (instead of USD_Stable_Coin)

Action required:
This is a breaking change to the Exchange v1 API and Spot v2.1 API codes. Please test the change in UAT as soon as possible before the aforementioned date and time.

You can refer to the Breaking Change Schedule in the [API documentation](http://ablink.serviceinfo.crypto.com/ls/click?upn=h3xW1fHX5LrofpDruvFgKmjdGGKiVbQo8Ig7fwBJ1W65peVbf-2FLBEJcUtRQLSydYktITez58eKqRfQPAJ33UgcceXVxb-2BfuvUOx3E5PTOqs-3DFtJ5_7DdTEkYToG-2F844Ri32SWG-2FO-2Bo3wkNA6z-2BMJKU2Wfn4ROTlMEamY7s-2Bi9qhOnomwdKm0cSqNAPurDZaJcVY8L5yuu8eTb3E90J-2ByMuofUM3KiEIcMFcL83I-2Bi6yLF3aPZSzDH3Z76sx-2BN5CsfDv6yVjwXW4HTk71LMbN-2FAwxOEpfCmRopRAhxXyoiBtQS2gKurzna9vNUgXauJhSF8goBaX2HMh3YqSBvpQEAtsJuVscEMiVAffWgFmAKPLLJ5DhE7zysf8cUKgaKBNcoLMKX3ogSh0AQqZLTFZAM3xzV46zWk-2B2rLkWTEImYmtSuVI6vKM4BYWanQoixRxNYNOawgEXVdFZYDKg4EwkAX5QXpMXhnqLx3UPtoocJKm03NsXo9wXa359gL0Eki-2FNJJcykeH1MTi-2B11iznjJCmMNZ-2FEsA9jwES-2BXR1JY31Qf-2B3kv5nJ3cmtl4e07JWYS3svGHoeWy7-2BVpbfY9DEo41sunoDyrbsrWHv-2FNAVtJ9F-2FnUVpTq2l-2BUZnqgjytfuSl-2Fjxg7drHrqtQcVLhMhpVYRGUoTaxfvMtkyleCmPAEk66UbckCsAypp2CfZvnbO1kTqpWWm9KpL20hCb95-2BJrug3zPftHwnjvoXvhjRJxpIaV-2BlJlnjwo3MHZDYEnaOGyXafE-2Fp2-2BORtJacK-2BT2dvehGtYsyQ-3D) for more details.

If you have any additional questions, please reach out to us at [contact‌@crypto‌.com](mailto:contact@crypto.com). We’re here to help.

Best regards,
The Crypto.‌com Team

**Comment by bonez56** [comment]
Just wondering if any progress has been made on getting the crypto_com connector working again? It is the main exchange I run Hummingbot on, so haven't been able to use it for some time.

**Comment by nikspz** [comment]
Duplicated with 
https://github.com/hummingbot/hummingbot/issues/6023

**Comment by rapcmia** [comment]
A bounty has been placed for this connector and being worked on by community devs https://github.com/hummingbot/hummingbot/issues/6023
