### ISSUE TITLE
Orders cancelled after 1 second with no trigger

### ISSUE THREAD

**Issue by NisoKTNU** [hummingbot/hummingbot#5869]
**Describe the bug**
Orders cancel 1 second after being placed no matter what the config is set to. I have been using avellaneda mostly but this also happens on the pure MM strategy and presumably others, this is consistent across both binance and bybit.

**Steps To Reproduce**
Create a new strategy (either Avellaneda or PureMM)
Set config with high/no order refresh tolerance and a high order refresh time (give it no reason to cancel an order)
Orders will be posted after refresh time and then cancelled 1 second later

Running on Windows 10 x64
CPU: AMD Ryzen 7 1800x
more version info in conda screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/116913195/200412326-e846c67c-217b-4b55-a3b6-83ec234936b6.png)

![image](https://user-images.githubusercontent.com/116913195/200408609-9327efec-d66f-48ca-bfa8-a178898a7c53.png)

**Release version**
1.8.0

**Attachments**
(Avellaneda has most data, PureMM test was just to see if it was strategy specific)
[conf_avellaneda_market_making_1.zip](https://github.com/hummingbot/hummingbot/files/9955198/conf_avellaneda_market_making_1.zip)
[logs_conf_avellaneda_market_making_1.zip](https://github.com/hummingbot/hummingbot/files/9955216/logs_conf_avellaneda_market_making_1.zip)
[conf_pure_mm_1canceltest.zip](https://github.com/hummingbot/hummingbot/files/9955204/conf_pure_mm_1canceltest.zip)
[logs_conf_pure_mm_1canceltest.zip](https://github.com/hummingbot/hummingbot/files/9955217/logs_conf_pure_mm_1canceltest.zip)

**Optional: your discord username:NisoKTNU#6124**

**Comment by rapcmia** [comment]
Hi @NisoKTNU good day to you
Just to confirm if this has been tested on other markets as well? I would assume that's the expected behavior if the price of the order changes quickly resulting spreads to move away from the threshold that holds the order not be cancelled.

**Comment by nikspz** [comment]
Can't reproduce on dev-1.10.0 using AvellanedaMM with bybit spot
![bybit not cancelled orders immedeately](https://user-images.githubusercontent.com/83953535/203305856-f97c7808-9f44-40fe-a893-a57299ede954.gif)

**Comment by nikspz** [comment]
@NisoKTNU Please update your version to the latest to see if issue there for you

**Comment by space-agent** [comment]
[2022-11-30 17-40-44-1.webm](https://user-images.githubusercontent.com/118084216/204932683-c3c81f25-4745-4d21-9bfb-fa985f89d420.webm)

I have the same issue

**Comment by nikspz** [comment]
@space-agent On the video you provide you have `order_refresh_time 1` so your orders instantly cancelled. (Could you try to adjust?)
The reason for you bot could stop placing orders also could be API rate limit that not allow you to place it (that's really depends on exchange).

**Comment by space-agent** [comment]
@nikspz yes but given the order refresh tolerance percentage it shouldn't be cancelling the orders every 1 second. It's not an API limit issue.

**Comment by space-agent** [comment]
[2022-12-01 11-29-12-1.webm](https://user-images.githubusercontent.com/118084216/205121938-5acc9568-dc0b-4064-82eb-f6c973a6aeeb.webm)

Here is a video of hummingbot deciding to cancel all orders every refresh cycle, and then deciding to not and act as it's supposed to, and then reverting back to cancelling every cycle. In the video I am spamming status so you can see that the mid price and best bid and ask aren't changing at all on the exchanges, but the bot is still deciding to cancel orders. You can see config at the end, 0.05% refresh tolerance pct. Again, the issue remains no matter what I set there, and also with order optimization off. Is there a way to see a log of what logic is leading to it deciding to cancel? Hanging orders are broken too, they get cancelled no matter the cancel % threshold I set for them.

**Comment by nikspz** [comment]
@space-agent Could you please send your config file/or screenshot of config that you use during this run. 

Could you please also tell the environment you use? (could help to triage the issue). 
(Win10 x64 + Ubuntu on virtual machine on same windows, that's correct?)

**Comment by nikspz** [comment]
Can't reproduce using config from here: https://github.com/hummingbot/hummingbot/issues/5869#issuecomment-1332906045

![image](https://user-images.githubusercontent.com/83953535/205144356-a32ac562-e821-477f-8846-431bb0955642.png)
