### ISSUE TITLE
[binance] OrderType.MARKET is not in the list of supported order types

### ISSUE THREAD

**Issue by NRZelenskiy** [hummingbot/hummingbot#5880]
Look at changelog of 1.9.0 => found a new one script (buy_low_sell_high)

Then I try to use it with default for that script binance_paper_trade connector - it is going well.
After some setting Moving Average timeframes I try to use it at regular binance connector and get error.

hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668247307.0, "order_id": "x-XEKWYxxxxx", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "binance"}
hummingbot.connector.client_order_tracker - INFO - Order x-XEKWYxxxxx has failed. Order Update: OrderUpdate(trading_pair='VITE-USDT', update_timestamp=1668247307.0, new_state=<OrderState.FAILED: 6>, client_order_id='x-XEKWYxxxxx', exchange_order_id=None, misc_updates=None)

Not a sure, but maybe our binance connector have no MARKET order type?

My discord username: NRZelenskiy#3705

**Comment by rapcmia** [comment]
Hi @NRZelenskiy good day to you,
Please be advised our binance connector does not support market order type and only limit orders atm. I tried to check the script and seems to be designed on a paper trade. Our team do have plans to integrate this market order type on supported connectors on future releases.

Tagging this ticket as closed for now

**Comment by NRZelenskiy** [comment]
Greetings, sir! @rapcmia Appreciated for your answer. Will waiting for update with opportunity to use script.
