### ISSUE TITLE
feat / Add VVS Finance & MM Finance on Cronos Chain

### ISSUE THREAD

**Issue by JeremyKono** [hummingbot/hummingbot#5882]
Connector created in accordance to: https://snapshot.org/#/hbot-ip.eth/proposal/0x9e8d1424df8c4fbc8820faef66168d7313b0d6540fffcb3e6905b43cdd3ad6e3

**Comment by JeremyKono** [comment]
Allocated HBOT: 1,000,000 HBOT

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/5816
