### ISSUE TITLE
magicbot

### ISSUE THREAD

**Issue by tomerqueves** [hummingbot/hummingbot#5899]
haciendo unas pruebas.

**Comment by rapcmia** [comment]
Hi @tomerqueves good day to you
Please be advised that if this ticket is something to do with enhancement or an issues is to make sure to add details or supporting files such as logs, strategy config and screenshots so we can help investigate. 

We will close this ticket for now, we suggest to visit our [discord channel ](https://discord.gg/hummingbot?_ga=2.65206254.117362285.1669013543-1267687797.1641860837)for support related concerns. Thanks!
