### ISSUE TITLE
Huobi - Bot returns a prompt / shows non-existing hanging orders after restarting the strategy on status

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5903]
Bot shows non-existing hanging orders after restarting the strategy on status, only new sets of order is on exchange

**Steps To Reproduce**

1. create a pureMM strategy using huobi
2. enable hanging orders
3. get filled orders and wait for hanging orders showed on both sides in status
4. stop the bot and confirm if orders are cancelled on both client and exchange 
5. Start  the bot again

Actual:
notice that the bot returns a prompt that hanging orders are cancelled when there is no hanging order created.
check status and hanging order could still shows

Expected:
Hanging order gets canceled when the strategy is stopped.
After restarting the strategy and checking the status, only new sets of order should be created.
After restart there's No prompt that hanging orders are cancelled 

[huobi.zip](https://github.com/hummingbot/hummingbot/files/10073797/huobi.zip)

![image](https://user-images.githubusercontent.com/83953535/203502760-1361e4df-b07c-4541-afa8-509ffe665fee.png)
![image](https://user-images.githubusercontent.com/83953535/203502773-d6d6da6c-97b4-4dc6-be57-3403b5afb0ea.png)

**Comment by nikspz** [comment]
Should be fixed on https://github.com/hummingbot/hummingbot/pull/5892

**Comment by nikspz** [comment]
Also happened on ascendex (development 1.10.0)
![image](https://user-images.githubusercontent.com/83953535/203654059-c2f46678-b5cd-4d8e-af22-8084a4ce123e.png)

**Comment by aarmoa** [comment]
Order cancellation is not executed synchronously in the server either for Huobi or for AscendEx. I think the description of the expected behavior in this case goes against the bot core implementation.

**Comment by nikspz** [comment]
Can't reproduce using latest development branch, fix has been deployed to development branch and will be available on the next release version 1.11
