### ISSUE TITLE
AMM Arbitrage strategy stuck on "waiting for allowances" on Arbitrum

### ISSUE THREAD

**Issue by Albonida** [hummingbot/hummingbot#5920]
similar issue to https://github.com/hummingbot/hummingbot/issues/5915 on arbitrum gateway

**Comment by rapcmia** [comment]
Hi @Albonida good day
Please be advised to follow the template designed for bug report when opening a github ticket. We will be closing this as this does not have the support/details we need for investigation. Thank you
