### ISSUE TITLE
XEMM issue with decimal invalid operation

### ISSUE THREAD

**Issue by glarkou** [hummingbot/hummingbot#5922]
**Describe the bug**
When doing XEMM and when I have enough balance on both exchanges to start trading on both sides, BUY and SELL FRONT only one side is executed. 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Not sure the issue started after upgrading to 1.10.0

Here are the steps to reproduce the issue (see attachments in the section below):
Not sure.

**Screenshots**
![image](https://user-images.githubusercontent.com/25099792/205480331-c0f611c3-28b5-46d5-8b5a-d827085cb8f1.png)

**Release version**
1.10.0

**Attachments**
![image](https://user-images.githubusercontent.com/25099792/205480392-5b1bf35e-0dd5-46a7-8df0-c153689fba33.png)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by kadirc** [comment]
Should be fixed by #5921

**Comment by nikspz** [comment]
Fixed in the latest development (dev-1.11.0)
