### ISSUE TITLE
AWS ASCENDEX error - Service unavailable from a restricted location

### ISSUE THREAD

**Issue by 9Karma9** [hummingbot/hummingbot#5932]
**Describe the bug**
// A clear and concise description of what the bug is:

Look the picture 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Just run the ascendex api

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

<img width="1501" alt="Captura de pantalla 2022-12-07 a la(s) 10 17 59" src="https://user-images.githubusercontent.com/110263836/206233457-5a24080b-778e-4faa-9d5d-09ec7539b0a7.png">

**Comment by nikspz** [comment]
Hey @9Karma9, 
To solve this You could change the region on your AWS, since binance is no longer support US IPs and could show this error `Service unavailable from a restricted location`
