### ISSUE TITLE
Using amm_arbitrage all funds were transferred to unknown wallet

### ISSUE THREAD

**Issue by SadisticMelodies** [hummingbot/hummingbot#5946]
**Describe the bug**
After setting up gateway between pancakeswap and sushiswap , providing wallet private key I noticed the wallet became empty from all the tokens inside (even those not related to bot config) 

the wallet to which was transferred https://bscscan.com/token/0xc748673057861a797275cd8a068abb95a902e8de?a=0xf5ff35ba3b4f7b681ec39db505e4be3909815a6f

and it keeps sending now even that the bot is stopped !!!

Please advice

**Comment by carlitogetaladajr** [comment]
Hi @SadisticMelodies Please provide some screenshots, and logs. Providing details such as your installation method, where you installed Hummingbot, and other steps you did. These can help us investigate on the issue. 

It is clear by now that your private wallet key has been compromised, and advisable NOT to use the wallet anymore. You need to create a new wallet.
