### ISSUE TITLE
anonymized_metrics_mode.anonymized_metrics_interval_min - Value must be more than 0.

### ISSUE THREAD

**Issue by dec0dOS** [hummingbot/hummingbot#5962]
**Describe the bug**
No option to disable the metrics

**Steps To Reproduce**
Update the config as in the the docs https://docs.hummingbot.org/reporting/#how-do-i-configure-or-turn-off-this-feature

**Screenshots**
![Screenshot 2022-12-19 at 18 29 37](https://user-images.githubusercontent.com/14824142/208494959-c18421e6-63bd-41a2-b395-448267b278fb.png)

**Release version**
v1.10.0

**Comment by rapcmia** [comment]
Hi @dec0dOS good day
We confirmed this is the same behavior when we set to 0 on the `conf_client.yml` file however there are also other ways to disable it. You may want to change the `anonymized_metrics_mode`, please see screenshot below:
![image](https://user-images.githubusercontent.com/73840223/210708744-1d223c34-394d-448d-87b2-0a11496e4c6f.png)

Or with the same that you need to change the `../conf/conf_client.yml` and set `anonymized_metrics_mode: {}`
![image](https://user-images.githubusercontent.com/73840223/210709013-b72b4e97-61e9-48bb-8054-c722f67ceeef.png)

At the same time I have informed our team about updating the docs. We will be closing this ticket for now, thank you 🙇

**Comment by Cacti2333** [comment]
Dear @rapcmia 

Is the current document regarding this setting still valid? [link](https://hummingbot.org/reporting/#how-do-i-configure-or-turn-off-this-feature)

Maybe link it to here or add more description to it.

Appreciate it.

**Comment by rapcmia** [comment]
Yes thats a valid link. I do think thats explains what it does for us to locate the data we need for our fee share partnerships with exchanges. If there's a need to review or change base, your feedback would help our docs team improve it and you can submit a issue ticket here https://github.com/hummingbot/hummingbot-site/issues
