### ISSUE TITLE
`gateway connector-tokens` command only allows you to add one token

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#5965]
**Describe the bug**
The command `gateway connector-tokens` is supposed to let users add new tokens to `balance` command, but it only shows one token. When the user adds a new token, it replaces the previous one.

**Steps To Reproduce**
See screenshot below

**Screenshots**
<img width="609" alt="Screen Shot 2022-12-20 at 12 00 59 PM" src="https://user-images.githubusercontent.com/1795030/208756111-36986f65-5123-4176-852c-af2dbd3bcd91.png">

**Release version**
1.11

**Comment by cardosofede** [comment]
@fengtality I think that you have to add the trading pairs with commas, like WETH.e,WAVAX and so

**Comment by fengtality** [comment]
I think the client should display that message to the user when they run `gateway connector-tokens -h`

**Comment by nikspz** [comment]
Fix of help message has been deployed to development branch and will be available on the next release version 1.12

User could add the tokens, needs to separate multiple tokens with commas (,)
