### ISSUE TITLE
Ascendex issue with 1.11.0

### ISSUE THREAD

**Issue by glarkou** [hummingbot/hummingbot#5975]
**Describe the bug**
Just upgraded to 1.11.0 and it seems that there is a problem with Ascendex connector.

I get the following:

![image](https://user-images.githubusercontent.com/25099792/209085464-cb24fb04-630f-4fcc-9bd7-2874e1e11e8a.png)

**Steps To Reproduce**
Upgrade to 1.11.0

**Comment by rapcmia** [comment]
Hi @glarkou good day to you,
Please be advised as part of the refactored Ascendex connector it requires us to add the account id found on our API settings on the website. May you please try to re-add the Ascendex API keys again and it should work ✌️ 

![image](https://user-images.githubusercontent.com/73840223/209086505-3de0f27b-181c-4817-a66d-414bc048fffe.png)

**Comment by glarkou** [comment]
Thanks let me try it and I will report back.

**Comment by glarkou** [comment]
@rapcmia thanks a lot. It works now. We can close.
