### ISSUE TITLE
web socet integration

### ISSUE THREAD

**Issue by ARGT100** [hummingbot/hummingbot#5980]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to ...

**Additional context**

**Comment by nikspz** [comment]
hey @ARGT100 Could you please provide more details to this enhancement ticket? Thank you
