### ISSUE TITLE
Documentation incorrect - `hummingbot.connector.connector` doesn't exist

### ISSUE THREAD

**Issue by michaelmoreno** [hummingbot/hummingbot#5993]
The official documentation section for [Connectors](https://docs.hummingbot.org/developers/architecture/#connectors) says
> `hummingbot.connector.connector.uniswap.uniswap_connector` is the market connector module for Uniswap. 

![image](https://user-images.githubusercontent.com/72640530/210099623-0d9b0b5e-5bfe-417e-be96-29b4f409bc68.png)

However there does not appear to be a `connector` folder in `hummingbot.connector`, and ctrl-f'ing for `uniswap_connector` does not return anything.

**Comment by fengtality** [comment]
Thanks @david-hummingbot can you fix this in the docs?

The Uniswap connector is in https://github.com/hummingbot/hummingbot/tree/master/gateway/src/connectors/uniswap
