### ISSUE TITLE
SushiSwap exchange should support Polygon network 

### ISSUE THREAD

**Issue by prince-choksi** [hummingbot/hummingbot#5994]
**Feature Suggestion**
polygon network already available for uniswap exchange please also add same polygon network for sushiswap

**Impact**
polygon network has very low gas fees. this will help people to do arbitrage between sushiswap and uniswap on polygon network.

**Additional context**

**Comment by fengtality** [comment]
See https://github.com/hummingbot/hummingbot/pull/5727
