### ISSUE TITLE
strategy_base.pyx sum_flat_fees function is misspelled 

### ISSUE THREAD

**Issue by ahoura** [hummingbot/hummingbot#5998]
**Describe the bug**
It appears that function `sum_flat_fees` in `strategy_base.pyx` is mistakenly named `cum_flat_fees`.

**Steps To Reproduce**
[Line 388 of strategy_base](https://github.com/hummingbot/hummingbot/blob/master/hummingbot/strategy/strategy_base.pyx#L388)

**Comment by rapcmia** [comment]
hi @ahoura 
We appreciate your time opening this ticket however the current build is working as expected even with the reported misspelled method. The foundation team decided that we tag this issue as `wontfix` for now and be reviewed / tested on future releases.
