### ISSUE TITLE
Kraken - Using the same spot exchange in the arbitrage strategy results in a loop that crashes the Docker instance

### ISSUE THREAD

**Issue by varkmiti** [hummingbot/hummingbot#6003]
**Describe the bug**
Using the same spot exchange in the arbitrage strategy results in a loop that crashes the Docker instance: 
**there is no validation to ensure that two different exchanges were entered!!** 

**Steps To Reproduce**
Start an arbitrage strategy and use the same exchange for both the primary and secondary markets (I used Kraken twice).

**Release version**
Version 1.11.0

**Optional: your discord username:**
markviti

**Comment by nikspz** [comment]
Can't reproduce using latest development and binance/ascendex exchange, could you share your config or config screenshot @varkmiti?
![image](https://user-images.githubusercontent.com/83953535/211720380-95b7e5cb-6bc4-496a-9801-cefaee68178e.png)
