### ISSUE TITLE
Systematic order cancelation failure with API Binance connector

### ISSUE THREAD

**Issue by Sladoeg** [hummingbot/hummingbot#6006]
**Description:**
The script cannot cancel orders systematicaly and update the orders IDs in the current record of saved state in DB on cumulative basis.

**Impact:**
Trying to cancel to many not existed orders leads to Binance API connection block  with the to many requests error.
CPU goes to full overload state. 
   
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 523, in _execute_order_cancel
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_exchange.py", line 202, in _place_cancel
    cancel_result = await self._api_delete(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 857, in _api_delete
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 887, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request DELETE https://api.binance.com/api/v3/order. HTTP status is 400. Error: {"code":-2011,"msg":"Unknown order sent."}

**How to reproduce:**
When placing orders with tick size 1 second or less on BestBid and BestAsk or even inside the spread on high liquid spot pair BTC-USDT.

**Script log attached:**
[logs_script.zip](https://github.com/hummingbot/hummingbot/files/10395383/logs_script.zip)

**Logs from the HBot**
When sending the stop command to the script:
![image](https://user-images.githubusercontent.com/17851813/211897383-86c6c385-9653-42f4-9229-7986c2b5f6fb.png)
![image](https://user-images.githubusercontent.com/17851813/211897479-b120ea33-a279-48fd-86e0-b735861045af.png)

**Comment by rapcmia** [comment]
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: An issue related to lost order management for Binance connector. The HBF team discussed that this will be assigned to CoinAlpha to create a fix.

**Comment by dennisocana** [comment]
We will submit a PR when the patch is ready.

**Comment by dennisocana** [comment]
@rapcmia could you please assign this ticket to me? Thanks in advance.

**Comment by rapcmia** [comment]
Hi @Sladoeg I tried to reproduce this issue using PMM but no avail specially on the lost orders part, would it be possible if you can share the script used when this issue occurred?

**Comment by Sladoeg** [comment]
Hi, @rapcmia need to find and check that version of the script, will do it tommorrow.

**Comment by Sladoeg** [comment]
Hi, @rapcmia have sent the Discord.

**Comment by nikspz** [comment]
Fixed with #6107

**Comment by nikspz** [comment]
Closing issue as paid
