### ISSUE TITLE
Coinbase Advanced Trade - Upgrade Coinbase spot connector to the latest exchange API and connector standard

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/hummingbot#6024]
**Feature Suggestion**
Update Coinbase connector. Coinbase closed its 'CoinbasePro' API and relies on the 'Advanced Trading API'.

**Impact**
This is likely to break the current Coinbase Pro connector

**Comment by theWebKeyGuy** [comment]
Would really like to see this done soon myself.

**Comment by InitialSupport** [comment]
We'd be happy to look into this for you.
Kindly file a support ticket here
https://forms.gle/xABEcR5MwDBJAm1c6

**Comment by MementoRC** [comment]
I could give it a try, I had started looking into it with the template. The Advanced Trading AP is completely new, with many methods changed/replaced. Some devs have complained on their dev forum, so I was letting the dust settle

**Comment by nikspz** [comment]
hi @MementoRC Could you please add any updates here?

**Comment by MementoRC** [comment]
Hi @nikspz , I have started the pre-work. I am progressing a bit slowly due to concurrent items on my plate.

**Comment by nikspz** [comment]
Okay got it, thanks

**Comment by nikspz** [comment]
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Community bounty related to bronze connector (connector needs API update)

**Comment by srirambandi** [comment]
We'd like to take up this development bounty - Coinbase connector. Me and @manibandi. I have previously contributed BitMart to Hummingbot, and have a lot of experience developing connectors and strategies in private.

**Comment by nikspz** [comment]
This issue was assigned to @MementoRC . Thank you for your contribution!

**Comment by nikspz** [comment]
Hey @MementoRC could you please update us with your progress on this Bounty?

**Comment by MementoRC** [comment]
@nikspz Most of the implementation is completed. A few details are still investigated due to gaps in their documentation and unavailability of sandbox. Currently going through the tests as pipe-cleaning.
Should I make a PR (which will fail) for early review?

**Comment by nikspz** [comment]
Yea you could create a draft @MementoRC

**Comment by MementoRC** [comment]
Oh right, gonna start on it

**Comment by nikspz** [comment]
This bounty will be increased to `250K HBOT` since the connector need huge refactor to advanced trade v2 API

https://snapshot.org/#/hbot-ip.eth/proposal/0x62d8feacfd0b69ab37576b9dd2304f648a23216d6e48eb8d9d50ff06fe86e90c

**Comment by MementoRC** [comment]
Very nice.
Note that Coinbase is actively adding features to their API, as it's being developed (like a REST method for order book snapshot, heartbeats for websocket, new channels). This may trigger modifications to this PR
Thank you

**Comment by nikspz** [comment]
This bounty increased to  `250K HBOT` according to https://snapshot.org/#/hbot-ip.eth/proposal/0x62d8feacfd0b69ab37576b9dd2304f648a23216d6e48eb8d9d50ff06fe86e90c 
and since the connector need huge refactor.

**Comment by fengtality** [comment]
## Description

* Proposal: HGP-30 (https://snapshot.org/#/hbot-ip.eth/proposal/0x62d8feacfd0b69ab37576b9dd2304f648a23216d6e48eb8d9d50ff06fe86e90c)
* Description: Upgrade Coinbase spot connector to the latest exchange API and connector standard
* Acceptance criteria: Upgrade connector to latest connector standards: https://docs.hummingbot.org/developers/connectors/#what-are-exchange-connectors

## Bounty

* Sponsor: Hummingbot Foundation
* Budget: Epoch 5 Budget
* Bounty amount: 250,000 HBOT or USDC equivalnet
* Developer portion: 100%
* Status: Assigned to MementoRC who has done prior work in https://github.com/hummingbot/hummingbot/issues/6024

**Comment by fengtality** [comment]
I think we only need support for Advanced Trade

**Comment by nikspz** [comment]
#6458

**Comment by nikspz** [comment]
- Closed the https://github.com/hummingbot/hummingbot/pull/6458
- unassigned Memento from bounty since connector since pr doesn't met our [connector v2.1 standart ](https://hummingbot.org/developers/connectors/spot-connector-checklist/#directory-setup)
    - could read comment related there https://github.com/hummingbot/hummingbot/pull/6458

**Comment by MementoRC** [comment]
I'd submit that the primary deviation is in the websocket proposal. This
part is mostly reverted in my workspace.

Would it be helpful to update with that correction?

**Comment by MementoRC** [comment]
Persona non grata?

**Comment by nikspz** [comment]
Hello @MementoRC the reason was based on the PR changes 99 files and using (new) redundant changes that not met [connector standart](https://hummingbot.org/developers/connectors/spot-connector-checklist/#directory-setup) as mentioned above. 
From this solution, unfortunately it can't be merged into HB codebase to not create a case when it's hard to maintain connector (that built not with our latest standarts).

**Comment by nikspz** [comment]
Description
Proposal: HGP-30 (https://snapshot.org/#/hbot-ip.eth/proposal/0x62d8feacfd0b69ab37576b9dd2304f648a23216d6e48eb8d9d50ff06fe86e90c)
Description: Upgrade Coinbase spot connector to the latest exchange API and connector standard
Acceptance criteria: Upgrade connector to latest connector standards: https://docs.hummingbot.org/developers/connectors/#what-are-exchange-connectors
Bounty
Sponsor: Hummingbot Foundation
Budget: Epoch 5 Budget
Bounty amount: 450,000 HBOT or 3000 USDC equivalent
Developer portion: 100%
Status: Assigned to MementoRC

@MementoRC Please answer you want bounty in USDC or HBOT?

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/6887

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @MementoRC. The connector has been deployed on development branch and hummingbot version 1.27.0.
https://hummingbot.org/exchanges/coinbase-advanced-trade/

**Comment by MementoRC** [comment]
Thank you
