### ISSUE TITLE
Ability to auto start a script by passing the script file name

### ISSUE THREAD

**Issue by LeonDowling** [hummingbot/hummingbot#6031]
**Feature Suggestion**
Add the ability to pass a script file name to HBOT on startup.  Also would be nice to be able to add it to a docker-compose file as an environment variable.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
This would allow the use of script files to be automated instead of the current solution that can only use strategy files.

**Comment by rapcmia** [comment]
Hi @LeonDowling good day
We have partially added a feature for supporting script file on quickstart/autostart available on development branch. Our team will discuss for the approach for docker-compose and will update this ticket. Thank you

**Comment by fengtality** [comment]
Fixed in https://github.com/hummingbot/hummingbot/releases/tag/v1.13.0
