### ISSUE TITLE
Binance Perpetual error not handled properly when creating orders

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#6033]
**Describe the bug**
When running a directional strategy on Binance Perpetuals Testnet, I noticed that I was receiving an error with status code 503 when submitting orders and Hummingbot was triggering the MarketOrderFailureEvent, and after some seconds the same order id was filled.
I reviewed the Binance Docs and the status 503 shouldn't be treated as an error.
![image](https://user-images.githubusercontent.com/36869960/214610115-756de6e2-9517-4dfc-a1db-3f152c3f109d.png)

**Steps To Reproduce**

Run any strategy with Binance Perpetuals Testnet for a long time. Is something that happens only when the servers are overloaded so you will need to wait until it happens/

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
1.12

**Attachments**
[message.txt](https://github.com/hummingbot/hummingbot/files/10501081/message.txt)

**Comment by ech761** [comment]
Message https://t.me/boydtech on telegram he can guide you on this issue

**Comment by nikspz** [comment]
Fixed with #6123
