### ISSUE TITLE
Help configuring and using `BinanceOrderBook`

### ISSUE THREAD

**Issue by harpone** [hummingbot/hummingbot#6048]
**Feature Suggestion**
Docs LOL

I'm trying to use the `BinanceOrderBook`. Managed to instantiate it just barely, but the LOB just stays empty...

I have no idea whatsoever how to use it (actually goes with most of the code). Are there some hidden/secret docs? Hummingbot website is not very helpful in that regard...

Anyway, thanks for the reply & help in advance. Seems like awesome softeware!

**Comment by harpone** [comment]
... or using `BinanceAPIOrderBookDataSource`, whatever is the intended way.

**Comment by cardosofede** [comment]
Hi! if you need help you can ask on the developer-chat on Discord. I don't know exactly what you want to do but probably you can use just the exchange class in a script and the order book of the exchanges that you want is going to be updated via web socket and you are going to have a local copy of the order book in Cython with methods to query them in an efficient way. There is a cheat sheet also with all the most common methods that you can use to get what you want from the OB.
For example: get_volume_for_price | get_price_for_volume and so. Good luck and see you on Discord!

**Comment by cardosofede** [comment]
@harpone btw, I saw that you have a background in AI so probably you are interested in one of the scripts that I'm working on.
The idea of the script is to normalize the order book and get the volume of the order book within a x% from the mid price, so for example, if the normalization_step is 0.5% and the n_levels is 4 the resulting csv will have the following structure:
timestamp | price | -2 | -1.5 | -1 | -0.5 | 0 | 0.5 | 1 | 1.5 | 2

And the value will be the volume in each price
