### ISSUE TITLE
Is it possible to run scripts straight from CLI?

### ISSUE THREAD

**Issue by harpone** [hummingbot/hummingbot#6049]
Something like `python hummingbot.py --script=my_script.py --params=...`.

That would help a lot with debugging IMO... I know it's possible to debug with breakpoints etc by starting the app and running the script from there, but the error handling seems a bit buggy when interrupting the script etc.

**Comment by fengtality** [comment]
This is now possible in the v1.13.0 release! https://github.com/hummingbot/hummingbot/releases/tag/v1.13.0
