### ISSUE TITLE
XEMM crashs when a small amount maker trades happens

### ISSUE THREAD

**Issue by mfavareto-vitra** [hummingbot/hummingbot#6055]
Describe the bug
// A clear and concise description of what the bug is.

For XEMM, you need to check if the tickSize is the same for both exchanges.
if tickSize not same and the smaller value is the Maker side -> you probably will slam into this bug.

I've made an fix, changing maker_order_ids variable to a List.

Before that, I think is a good idea if someone can write a test case for this particular case, looks like a good idea, using as start point is the existent test_cross_exchange_market_making.
I've tryed, but with no much success until now...

Let me explain the whole TC
a) start the strategy, it places two maker orders
b) receive a partial execution small enough that it cannot be executed by taker
c) receive a second partial execution that, added to the first, has enough quantity to be executed by taker
d) receive a last partial execution, this time, with an amount that can be executed by taker
e) finally, the order is fully executed
f) two new maker orders are placed

There are still other issues that we will need to address, for example:

in the flow above, step b) happened and the offer is no longer economically interesting, the strategy will cancel the offer, without doing the hedge -> how to trat?
at what price step c) will be performed?
in item e) the remaining amount is so small that it cannot be executed by taker side -> how to treat?

I know if we move toward with this, trader need to know the profit couldn't be expected one, but has no hedge sounds much worst...

Steps To Reproduce
// A concise description of the steps to reproduce the buggy behavior:

For example, you select Foxbit and Binance (as maker and taker), configure your strategy like this:
![image](https://user-images.githubusercontent.com/108166719/216428008-04d35962-728b-48ce-a831-194e8b4a116b.png)

You need to know as Foxbit accept orders granter than BRL 1.00, but Binance only accept orders grater than BRL 10.00.

You start the strategy and one order is bited with BRL 1.00, when XEMM try to hedge this operation at Binance, you'll see a message, informing you the order is too small and it'll be accumulated.

When next trade happens at same order, XEMM checks if has any accomulated value to send a Taker order, but, nothing happens, because it has a if blocking this...
![image](https://user-images.githubusercontent.com/108166719/216429862-25217695-ba40-4baf-b119-06f89ae587c0.png)
And returns, without send hedge order!

Strategy only became operational when current order is full filed or canceled... until there, you're open to be executed - WITH NO HEDGE.

Here are the steps to reproduce the issue (see attachments in the section below):

You need to use XEMM strategy
Select two exchanges when tickSize are different to same trading pair
Configure XEMM, selecing maker exchange as has smaller tickerSize
Start strategy
Now, you need a small trader happens at maker side to trigger this bug
Current maker sell fill amount of 0.0001 USDT is less than the minimum order amount allowed on the taker market. No hedging possible yet.
Another execution to same maker order
You will see that error message
ERROR - Multiple buy maker orders fills
or
ERROR - Multiple sell maker orders fills
Screenshots
// If applicable, add screenshots to help explain your problem.

Release version
// Include your bot's version number (Can be found at the upper left corner of your CLI).
We are using version: 1.12.0

Attachments
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those!
I'm not attaching any config or log files because it is very ease to reproduce... but, if you need it, I can add it latter.
But, I'm attaching my fix suggestion (in fact, I'm using it right now with good results)...
[cross_exchange_market_making.zip](https://github.com/hummingbot/hummingbot/files/10572818/cross_exchange_market_making.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
I'm Favareto 

Discord user #8697

**Comment by rapcmia** [comment]
Hi @mfavareto-vitra good day,
Thanks for submitting the ticket, please give me time to reproduce this issue 🙇‍♂️

**Comment by preze93** [comment]
@mfavareto-vitra thanks for bringing this over, This is something I've been struggling myself as well. Happens a lot in MEXC where I get filled order of 1 USDT but then on Binance it can only hedge above 10USDT minimum

**Comment by nikspz** [comment]
Severity: P3
Bounty: 10000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to XEMM, Core strategy

**Comment by nikspz** [comment]
hi @mfavareto-vitra would you like to be assigned for this bounty?

**Comment by mfavareto-vitra** [comment]
> Severity: P3 Bounty: 10000 (https://hummingbot.org/maintenance/bugs/) Rationale: Bug related to XEMM, Core strategy

Hi @nikspz,
I believe this bug is a P2 as it is a bug into XEMM (Functionality of strategies).
Can you reclassified it?

After that, Yes I'll love it, you can assing it to me, please.

**Comment by nikspz** [comment]
@mfavareto-vitra we have discussed that this bounty is good for P3 based on our contribution guidelines. Once your PR is up for review, we can check with the team again for your request

**Comment by mfavareto-vitra** [comment]
Ok, it's fair enough.
You can assign it to me.

**Comment by nikspz** [comment]
This issue is assigned to @mfavareto-vitra . Thank you for your contribution!

**Comment by nikspz** [comment]
Hi @mfavareto-vitra, any updates on this issue?

**Comment by Joram3** [comment]
P3 work will be done,

**Comment by nikspz** [comment]
hi @mfavareto-vitra Could you please submit PR for this? thanks

**Comment by nikspz** [comment]
hi @mfavareto-vitra Could please add any updates? if no answer we will have to close the bounty.

**Comment by mfavareto-vitra** [comment]
Sorry for this long delayI’ve made a fix for this, but when I try to create a PR I received an error from GitHubI asked for help and as soon I fix it, I‘lol upload it.  ---- On Wed, 10 May 2023 14:26:34 -0300  ***@***.******@***.***> wrote ----  
hi @mfavareto-vitra Could please add any updates? if no answer we will have to close the bounty.

**Comment by nikspz** [comment]
@mfavareto-vitra please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.
