### ISSUE TITLE
Mistake in avellaneda strategy

### ISSUE THREAD

**Issue by surGeonGG** [hummingbot/hummingbot#6059]
In the function c_calculate_reservation_price_and_optimal_spread it calculates the optimal spread like so:

```
self._reservation_price = price - (q * self.gamma * vol * time_left_fraction)

self._optimal_spread = self.gamma * vol * time_left_fraction
self._optimal_spread += 2 * Decimal(1 + self.gamma / self._kappa).ln() / self.gamma

min_spread = price / 100 * Decimal(str(self._config_map.min_spread))

max_limit_bid = price - min_spread / 2 
min_limit_ask = price + min_spread / 2

self._optimal_ask = max(self._reservation_price + self._optimal_spread / 2, min_limit_ask)
self._optimal_bid = min(self._reservation_price - self._optimal_spread / 2, max_limit_bid)

```

But surely the left side of the plus sign should also be multiplied by 2 because we divide by 2 to get the optimal ask/bid. This is why the right side is multiplied by 2.

So it should be like this:

```
self._optimal_spread = 2 * self.gamma * vol * time_left_fraction
self._optimal_spread += 2 * Decimal(1 + self.gamma / self._kappa).ln() / self.gamma
```

This makes the minimum optimal_ask and optimal_bid 0 if {-1 < q < 1}. 

Graphed it in desmos. You can remove the leftmost 2* from x_spread and adjust q and see the difference:
https://www.desmos.com/calculator/yt3upegesf

**Comment by nikspz** [comment]
This issue is assigned to HB Foundation team

**Comment by fengtality** [comment]
This isn't really a mistake since the bid and ask spread calculations divide `self._optimal_spread` by 2, but I do agree that it's confusing:

```
            self._reservation_price = price - (q * self.gamma * vol * time_left_fraction)

            self._optimal_spread = self.gamma * vol * time_left_fraction
            self._optimal_spread += 2 * Decimal(1 + self.gamma / self._kappa).ln() / self.gamma

            min_spread = price / 100 * Decimal(str(self._config_map.min_spread))

            max_limit_bid = price - min_spread / 2
            min_limit_ask = price + min_spread / 2

            self._optimal_ask = max(self._reservation_price + self._optimal_spread / 2, min_limit_ask)
            self._optimal_bid = min(self._reservation_price - self._optimal_spread / 2, max_limit_bid)
```

However, I don't think we should change this as it may have been intended to align variables with the original Avellaneda paper.

**Comment by fengtality** [comment]
To further clarify, this

**Comment by MementoRC** [comment]
The factor `1` also defines the optimal spread to be equal to the `minimum spread = |price - price_reservation|` in the extreme situation of the large sigma for gamma=0.5. A consideration could be to add an adjusting parameter a >=1 so that the optimal spread becomes `a * |price - price_reservation|` - CE: Just pretending to understand something, ;P
