### ISSUE TITLE
Client - quickstart for docker does not support scripts

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6077]
**Describe the bug**
In line with the recent updates for quickstart for scripts strategy, the docker build still does not support the feature and returning the error on the screenshot:

![image](https://user-images.githubusercontent.com/73840223/218388989-63fc4850-d56b-4ce6-86a7-289dcd5edda2.png)

```
2023-02-13 05:54:26,492 - 1 - root - ERROR - No module named 'hummingbot.strategy.ralph'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 526, in get_strategy_starter_file
    strategy_module = __import__(f"hummingbot.strategy.{strategy}.start",
ModuleNotFoundError: No module named 'hummingbot.strategy.ralph'
2023-02-13 05:54:26,498 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 117, in start_check
    self._initialize_strategy(self.strategy_name)
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 250, in _initialize_strategy
    raise NotImplementedError
NotImplementedError
```

**Steps To Reproduce**
- Make sure to create a hummingbot client for docker (on this example the name is `humminbot_files`)
```
# 1) Create folder for your new instance
 mkdir autobot

# 2) Create folders for logs, config files and database file 
mkdir autobot/certs autobot/logs autobot/data autobot/conf autobot/pmm-scripts autobot/script

# 3) Copy config files from pre-existing config folder 
cp -a \
hummingbot_files/conf/* \
hummingbot_files/conf/.password_verification \
autobot/conf

# 4) Set environment variables specifying the strategy config file to use, and the decryption password
export CONFIG_FILE_NAME=<strategy config file name> 
export CONFIG_PASSWORD=<config password>
export TAG=<development, latest or local_image>

# 5) Launch unattended instance of Hummingbot 
docker run -itd \
--name autobot --network host \
--mount "type=bind,source=$(pwd)/autobot/conf,destination=/conf/" \
--mount "type=bind,source=$(pwd)/autobot/logs,destination=/logs/"  \
--mount "type=bind,source=$(pwd)/autobot/data,destination=/data/" \
--mount "type=bind,source=$(pwd)/autobot/scripts,destination=/script/" \
--mount "type=bind,source=$(pwd)/autobot/certs,destination=/certs/" -e STRATEGY -e CONFIG_FILE_NAME -e CONFIG_PASSWORD \
hummingbot/hummingbot:$TAG && docker start autobot && docker attach autobot
``` 

**Release version**
v1.12.0 and development branch

**Attachments**
[logs_ralph.log](https://github.com/hummingbot/hummingbot/files/10719385/logs_ralph.log)

**Comment by MementoRC** [comment]
@rapcmia Is this not more of a feature request? Is this docker not running `hummingbot` instead of `hummingbot_quickstart`? How was `hummingbot/hummingbot:$TAG` created? (Note: I am kind of a noob on docker)

**Comment by rapcmia** [comment]
Hi @MementoRC good day to you
When testing docker build, you have to create a docker image for the hummingbot client {development,master,staging} and there two ways either you run the create.sh or create a local docker image. 

For creating local docker image:
1. Go to hummingbot client source folder
2. Run `docker build -t hummingbot/hummingbot:insert_here -f Dockerfile .` where `insert_here` can be any name you prefer.

Our dev team propose to use docker-compose instead and will close this ticket. Here's a link for more info https://github.com/hummingbot/deploy-examples
