### ISSUE TITLE
Source installation  - conda COMMAND: invalid choice: 'develop' during `./install` script

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6082]
**Describe the bug**
We observed that for initial attempt of source installation with miniconda or miniforge, we are getting the error of `CommandNotFoundError: To use 'conda develop', install conda-build`

![image](https://user-images.githubusercontent.com/73840223/218756172-ef396053-b681-4a41-89ab-a783a9f6e487.png)

Note: This can be fixed using `conda install conda-build`

**Steps To Reproduce**
1. Setup a fresh AWS ubuntu server or uninstall all packages of hummingbot client
    `./clean && ./uninstall && conda clean -a -y`
2. Clone and install hummingbot client using source
3. Observe the installation process 

**Release version**
v1.12.0 and development branch

**Comment by MementoRC** [comment]
@rapcmia It seems to me that it may be best to simple not call `conda develop .` in the `install` script. Nobody has apparently used it the way it is supposed to and many developers do not even know what it is supposed to do 0.) (see https://github.com/conda/conda-build/issues/4251 and other searches)

**Comment by MementoRC** [comment]
@rapcmia any feedback on the comments above? Close?

**Comment by nikspz** [comment]
seems Related to the conda develop command that we have in current ./install script
![image](https://github.com/hummingbot/hummingbot/assets/83953535/de160df1-b1a2-428b-8f39-07db6c04fe25)


conda: error: argument COMMAND: invalid choice: 'develop'

![image](https://github.com/hummingbot/hummingbot/assets/83953535/5cfd1d26-ad95-470d-89bc-bc4503c95a1e)
