### ISSUE TITLE
Amm_Arb sells one side but does not buy on the other - no error in the logs

### ISSUE THREAD

**Issue by toxicehc** [hummingbot/hummingbot#6112]
I woke up this morning and found my hummingbot instance spotted an arb opportunity and proceeded to sell in the quantities I specified tokens on the DEX side, but failed to buy back on the CEX side. No indication in the logs of why.

Install Hummingbot latest release.
Connect to HUOBI CEX.
Install Gateway - Connect to uniswap polygon.
Create AMM_Arb strategy.
Config:
![image](https://user-images.githubusercontent.com/4660657/221395555-18917957-af05-4e46-b46d-4f505b53b475.png)

The bot was just started and waiting for an arbitrage opportunity.
![image](https://user-images.githubusercontent.com/4660657/221395609-e480bb80-1de1-4068-9408-7da108c3f528.png)
![image](https://user-images.githubusercontent.com/4660657/221395855-62480cd6-4f58-4a45-9e69-88a36e814609.png)

History view:
![image](https://user-images.githubusercontent.com/4660657/221395772-71fddd05-d790-49e6-a606-a960b6caa2dd.png)

**Release version**
V1.12
Logs
[logs_conf_amm_arb_1.log](https://github.com/hummingbot/hummingbot/files/10833146/logs_conf_amm_arb_1.log)
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/10833147/logs_hummingbot.log)
[conf_amm_arb_1.yml.log](https://github.com/hummingbot/hummingbot/files/10833151/conf_amm_arb_1.yml.log)

**Optional: your discord username:**
toxicehc#5599

**Comment by fengtality** [comment]
Closing as this issue seems related to a custom node provider: https://github.com/hummingbot/gateway/issues/61

We can only triage issues related to Gateway connectors if users are running using default node providers and trading tokens in the default token lists.
