### ISSUE TITLE
Could not fetch account updates from Binance. Check API key and network connection.

### ISSUE THREAD

**Issue by kaanguven** [hummingbot/hummingbot#6120]
I used my API and Secret key for other stuff it works well. But when i start bot it gives these errors that i provided in screenshot.

![42](https://user-images.githubusercontent.com/83061705/221868729-3cd77aaf-73f1-4f65-a0e7-65d088e413e1.PNG)

**Comment by MementoRC** [comment]
@kaanguven Can you please add the logs (`logs/conf_xxx.log` or hummingbot_logs/conf_xxx.log`) or double-check that you are not calling the API from a restricted location. Binance recently applied strict rules with respect to restricted locations

**Comment by kaanguven** [comment]
I always use my api with other bot stuff
