### ISSUE TITLE
Client - Failed to import strategies/connectors after ./update.sh

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6138]
The structure of folders in 1.13.0 version was updated from hummingbot_files/hummingbot_conf to `hummingbot_files/conf`, so when you trying to update from 1.12.0 and older versions there's a bug related to new folder structure.

Steps to reproduce:
1. Clone and install hummingbot with tag 1.12.0 or older
2. Manually create docker image with `latest` tag (docker build -t hummingbot/hummingbot:latest  -f Dockerfile .)
3. create the docker instance with old ./create.sh script (from 1.12.0 version or older)
4. connect connectors, create and ran strategy.yml
5. download new master branch update.sh script
6. update the docker instance to latest
7. start the docker instance with new ./start.sh script
8. try to check `balance` and try to `import the strategy.yml`

Actual:
Bot not showing balance for previously connected connectors.
Failed to import strategy.yml that created earlier in 1.12.0

Expected:
config and connectors files able to migrated successfully into new version.
User able to import/check balance for earlier added strategies/connectors

Loom video:
https://www.loom.com/share/7e211bf2c1f04a328e93aded5891aea6

Old folder structure:
![image](https://user-images.githubusercontent.com/83953535/223879721-8b1496b4-f81e-4d4f-b339-c0ac9c73b560.png)

New folder structure:
![image](https://user-images.githubusercontent.com/83953535/223879905-03eb1b52-aa4b-422e-829c-f60b4146264d.png)

Failed to use connector that earlier was added:

![image](https://user-images.githubusercontent.com/83953535/223879991-306cb348-d914-4c7b-91b1-237cb6cc19ef.png)
![image](https://user-images.githubusercontent.com/83953535/223880000-ced9d8f2-582c-414e-afee-ea1ebb70e85f.png)

**Comment by rapcmia** [comment]
The fix has been applied https://github.com/hummingbot/hummingbot/pull/6145 to the development branch and will be available on the next Hummingbot version 1.14.0
