### ISSUE TITLE
Kucoin perpetuals - history displays incorrect fees paid 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6163]
**Describe the bug**
While checking `kucoin_perpetual` trade data we notice that the fees paid does not match between client and kucoin's exchange trade history. Based on [kucoin future trading fees](https://www.kucoin.com/vip/level) default 0.02%/0.06%  (maker/taker) which is correct on `kucoin_perpetual_utils.py` however this is not the case for the client when tested on different markets {XRP-USDT, LINK-USDT} For calculating the fees we assume this calculation `(price * order_amount) * fees rate`

![image](https://user-images.githubusercontent.com/73840223/227113407-43a91c03-bb37-4515-9f44-6120dfd74ec8.png)

Sample scenario on the attached CSV
The price is 0.419 with order_amount of 20XRP and fee is 0.02% on trade history in which we expect should be around `0.001676` however on the CSV file its returning value is 0.20

```
{'fee_type': 'DeductedFromReturns', 'percent': '0', 'percent_token': 'USDT', 'flat_fees': [{'token': 'USDT', 'amount': '0.20'}]}
```

**Steps To Reproduce**
1. Setup simple perpetual market making strategy
2. Setup spreads enough for trade 
3. Check history, CSV and kucoin trade history 

**Release version**
Development branch

[trades_perp-kucoin1.csv](https://github.com/hummingbot/hummingbot/files/11047384/trades_perp-kucoin1.csv)

**Comment by cardosofede** [comment]
@yancong001 do you want to work in this issue?

**Comment by yancong001** [comment]
> @yancong001 do you want to work in this issue?

OK, you can give it to me

**Comment by nikspz** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to Kucoin perpetual connector

**Comment by nikspz** [comment]
Closing issue as paid, thank you @yancong001 for contribution
