### ISSUE TITLE
cross_exchange_market_making - Markets are not ready. No market making trades are permitted.

### ISSUE THREAD

**Issue by ME-nandita** [hummingbot/hummingbot#6171]
We are implement a cross market making strategy with ascendex and quickswap_polygon_mainnet  and when we run the strategy  this shows  "cross_exchange_market_making - Markets are not ready. No market making trades are permitted." and the  quickswap_polygon_mainnet prices are not fetched such as ask, bid prices etc.  Please refer to the screenshot for more info... And let me know your suggestions

cross_exchange_market_making
maker_market: ascend_ex
taker_market: quickswap_polygon_mainnet
maker_market_trading_pair: PRXY-USDT
taker_market_trading_pair: PRXY-USDC

(https://user-images.githubusercontent.com/106417745/227904339-9120e3cc-5375-4df0-9b1e-30b3aa239d71.png)
(https://user-images.githubusercontent.com/106417745/227902825-d8349e27-33e9-47c8-a3fa-c76f90439beb.png)

**Comment by rapcmia** [comment]
Hi @ME-nandita thanks for submitting the ticket however this is not the correct template for submitting bug reports. Please [submit a ticket](https://github.com/hummingbot/hummingbot/issues/new/choose) using our bug template. Thank you 

![image](https://user-images.githubusercontent.com/73840223/227916884-da451138-38db-48e5-97b1-bb42af66fd63.png)
