### ISSUE TITLE
XEMM- Markets are not ready. No market making trades are permitted.

### ISSUE THREAD

**Issue by ME-nandita** [hummingbot/hummingbot#6172]
Describe the bug
Implement a cross market making strategy with ascendex and quickswap_polygon_mainnet.  When we run the strategy this shows "cross_exchange_market_making - Markets are not ready. No market making trades are permitted."
The quickswap_polygon_mainnet prices are not fetched such as ask, bid prices etc. Please refer to the screenshot for more info... And let me know your suggestions

Steps To Reproduce
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create cross_exchange_market_making strategy.
2.  Start strategy and check status
3. Observe log pane

Screenshots
![Screenshot 2023-03-27 150946](https://user-images.githubusercontent.com/106417745/227924906-3ffac28a-7766-438c-9f50-39267543ef56.png)
![Screenshot 2023-03-27 145517](https://user-images.githubusercontent.com/106417745/227924966-e8797a25-f0f8-4389-9afe-82e5f2490a1f.png)

Release version
1.13.0

Attachments
[cross_exchange_conf_logs.zip](https://github.com/hummingbot/hummingbot/files/11077909/cross_exchange_conf_logs.zip)

**Comment by ME-nandita** [comment]
Hi @cardosofede  we don't know any specific reason but we didn't use any allowance specifically.

**Comment by rapcmia** [comment]
Hi @ME-nandita good day
As per checking the issue looks like you need to approve the PRXY from your wallet. I'm able to reproduce this by using AMM-arb instead:
![image](https://github.com/hummingbot/hummingbot/assets/73840223/06f5b6c2-0542-4960-8abe-c7727ef05489)

Then ran `gateway approve-token quickswap PRXY` to fix. 
![image](https://github.com/hummingbot/hummingbot/assets/73840223/70016f75-e68e-4cc6-bf66-aa4e31b9d4dd)

Run `start` again and all ok
![image](https://github.com/hummingbot/hummingbot/assets/73840223/b0a70b31-cb0d-405f-ad3d-6c69e01e8b25)
