### ISSUE TITLE
Script - always shows 'No active maker orders'

### ISSUE THREAD

**Issue by beyondev** [hummingbot/hummingbot#6173]
**Describe the bug**
status --live always shows 'No active maker orders'

**Steps To Reproduce**
1. Start a script with active_order_df() invoked in format_status()
2. Use status --live 
3. Manually put a new buy order on okx exchange
4. The status panel always show 'No active maker orders' and the balances are correctly updated

**Screenshots**
<img width="687" alt="image" src="https://user-images.githubusercontent.com/18281374/227949036-315eb214-54aa-494c-a7f1-51ac31aba43c.png">

**Release version**
1.13.0

**Attachments**
` strategy = {
        "test_volume": 50,  # the amount in base currancy to make the hypothetical market buy and market sell.
        "bid_spread": .5,   # how far away from the mid price do you want to place the first bid order (1 indicated 1%)
        "ask_spread": .5,   # how far away from the mid price do you want to place the first bid order (1 indicated 1%)
        "amount": 0.0001,       # the amount in base currancy you want to buy or sell
        "order_refresh_time": 60,
        "market": "okx",
        "pair": "BTC-USDT"
    }`

**Comment by rapcmia** [comment]
hi @beyondev good day. Please be advise the Hummingbot client does not take manually created orders from supported exchanges. It should only affect those orders created within the app.
