### ISSUE TITLE
Can it be used without installing?

### ISSUE THREAD

**Issue by Mihaug** [hummingbot/hummingbot#6203]
Good day hummingbot developers, I wanted asking if it is possible to download the github repo and run scripts without going through the hassle of installation (as I am particularly interested in the py scripts examples) If so, please where does one apply the api keys and passphrase and also switch live/paper trade and other necessary config parameters. Thank you. Looking forward to a response

**Comment by nikspz** [comment]
hi @Mihaug Currently `you need to install` hummingbot to use `start --script` command

docs are here:

https://docs.hummingbot.org/installation/
https://docs.hummingbot.org/scripts/
https://docs.hummingbot.org/scripts/examples/
