### ISSUE TITLE
Integrate fixed_rate_conversion into amm_arb strategy

### ISSUE THREAD

**Issue by hui121315** [hummingbot/hummingbot#6209]
## Problem Definition

Currently, the amm_arb strategy calculates arbitrage opportunities using real-time exchange rates. In some cases, it may be desirable to use a fixed exchange rate instead of a real-time one to provide a more stable price difference when calculating arbitrage opportunities.

## Feature Request

I would like to request the integration of the fixed_rate_conversion feature from the cross_exchange_market_making strategy into the amm_arb strategy. This feature would allow users to set a constant exchange rate between the two assets they are trading, instead of using the real-time exchange rate.

## Implementation Steps

1. Add a new variable `fixed_conversion_rate` to the amm_arb strategy with a default value.
2. Modify the `AmmArbStrategy` class's `__init__` method to include the new 
3. Update the strategy configuration file to include the new `fixed_conversion_rate` parameter.
4. Update the documentation to describe the new functionality.

Please let me know if you need any additional information or clarification on this feature request. Thank you!

**Comment by fengtality** [comment]
## Bounty

**Sponsor**: Hummingbot Foundation
**Rationale**: AMM ARB is a Core Strategy for Epoch 2, which means that the Foundation will be the official maintainer for these strategies, prioritize updates and fixes to them, and maintain their documentation pages.
**Assessment**: P2: General / Fixable in 1-2 days
**Bounty Amount**: 50,000 HBOT or 250 USDT
**Developer Share**: 100% - Paid upon merge to `development`
**Status**: Open

**Comment by fengtality** [comment]
I think this is a well-defined enhancement request to the AMM-ARB strategy: https://docs.hummingbot.org/strategies/amm-arbitrage/. If devs interested in taking this bounty have questions about implementation, please ask below.

**Comment by srirambandi** [comment]
Hi @fengtality, I'd like to take up this bounty.

**Comment by srirambandi** [comment]
Thanks Mike. Will start my work on this from tomorrow. Will update everything in this thread and a draft PR I'll submit for this bounty.

**Comment by fengtality** [comment]
@srirambandi any update on this?

**Comment by srirambandi** [comment]
Hey Mike! Will do a draft PR with the commits tonight 🙌 Need yours or someone’s review to check the logic of that later. I was working in crypto_com connector and logic, and it has come to a good stage, pending just 2 more unit test files.

Anyway will update here with the draft PR tonight, thanks.

**Comment by nikspz** [comment]
As discussed changes on fix requested was too hard to implement, will sent funds after #6472 will be merged, as it used dev fix code.
@srirambandi please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by srirambandi** [comment]
Hi @nikspz, I filled in the AML Policy Form just now. Let me know if there's anything needed with the form or this issue. Thanks!

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @srirambandi . The PR has been deployed on development branch and hummingbot version 1.18.0
