### ISSUE TITLE
Cross-Exchange Market Making on `same exchange` only uses the Maker pair

### ISSUE THREAD

**Issue by cryptojorge** [hummingbot/hummingbot#6223]
**Describe the bug**
// A clear and concise description of what the bug is.
Cross-Exchange Market Making strategy configuration.  The maker pair SOL-USDC, taker pair SOL-USD, maker and taker exchanges were same Kraken. All trades (at least 50 of them) were ALL made on SOL-USDC pair and NONE (ZERO) on SOL-USD. 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

1. Setup configuration for Cross-Market Making on same exchange (e.g., Kraken) for both Maker & Taker
2. Find configuration that will result in orders (below is my exact configuration that included over 50 trades)
3. Start the bot
4. After trades made, analyze them and you'll see all trades made only with the Maker pair.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...

+----------------------------------------+------------------------------+
      | Key                                    | Value                        |
      |----------------------------------------+------------------------------|
      | strategy                               | cross_exchange_market_making |
      | maker_market                           | kraken                       |
      | taker_market                           | kraken                       |
      | maker_market_trading_pair              | SOL-USDT                     |
      | taker_market_trading_pair              | SOL-USD                      |
      | min_profitability                      | 0.5                          |
      | order_amount                           | 2                            |
      | adjust_order_enabled                   | True                         |
      | order_refresh_mode                     | active_order_refresh         |
      | top_depth_tolerance                    | 0.0                          |
      | anti_hysteresis_duration               | 60.0                         |
      | order_size_taker_volume_factor         | 25.0                         |
      | order_size_taker_balance_factor        | 99.5                         |
      | order_size_portfolio_ratio_limit       | 16.67                        |
      | conversion_rate_mode                   | fixed_conversion_rate        |
      | ∟ taker_to_maker_base_conversion_rate  | 1.0                          |
      | ∟ taker_to_maker_quote_conversion_rate | 1.0                          |
      | ∟ gas_to_maker_base_conversion_rate    | 1.0                          |
      | slippage_buffer                        | 0.1                          |
      | debug_price_shim                       | False                        |
      | gateway_transaction_cancel_interval    | 600                          |
      +----------------------------------------+------------------------------+ 

5. Start the bot using this command: ...
...start

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
Version: 1.14.0 

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

[logs_kraken_cm_sol-usdtusc.log](https://github.com/hummingbot/hummingbot/files/11217075/logs_kraken_cm_sol-usdtusc.log)

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Hi @cryptojorge our team does not have any plans to update v1 XEMM strategy for now however you may want to look on our v2 strategy XEMM on our latest version 1.27.0 https://hummingbot.org/release-notes/1.27.0/#new-strategy-cross-exchange-market-making-xemm
