### ISSUE TITLE
Installation in ubuntu not working: 404 not found 

### ISSUE THREAD

**Issue by cryptod6969** [hummingbot/hummingbot#6225]
When i try to install hummingbot within ubuntu i get the following error: 404 not found

wget https://raw.githubusercontent.com/hummingbot/hummingbot/master/installation/docker-commands/create.sh
--2023-04-13 02:26:43--  https://raw.githubusercontent.com/hummingbot/hummingbot/master/installation/docker-commands/create.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-13 02:26:43 ERROR 404: Not Found.

**Comment by nikspz** [comment]
Hey @cryptod6969 docker scripts deprecated in this PR https://github.com/hummingbot/hummingbot/pull/6160
You could use https://github.com/hummingbot/deploy-examples repo as reference for docker installation
