### ISSUE TITLE
ImportError: cannot import name 'ContractFunction' from 'web3.contract

### ISSUE THREAD

**Issue by Amirghrb** [hummingbot/hummingbot#6233]
Hi everyone 
Iam just start work with hummingbot and I want to develop a connector for an exchange . 
I did what [installation](https://docs.hummingbot.org/installation/linux/#install-from-source) guide said But when i want to run `python ./bin/hummingbot.py`
i get some sort of import Error that says :
```
     from web3.contract import ContractFunction
ImportError: cannot import name 'ContractFunction' from 'web3.contract' (/home/amir/anaconda3/envs/hummingbot/lib/python3.11/site-packages/web3/contract/__init__.py)
```
and i should mention that I installing it on Window WSL2 ubuntu 20.04

full error message :
``` 
hummingbot) amir@amir:~/secondins/hummingbot$ bin/hummingbot.py
Traceback (most recent call last):
  File "/home/amir/secondins/hummingbot/bin/hummingbot.py", line 9, in <module>
    from bin.docker_connection import fork_and_start
  File "/home/amir/secondins/hummingbot/bin/docker_connection.py", line 10, in <module>
    from hummingbot.core.gateway import set_hummingbot_pipe
  File "/home/amir/secondins/hummingbot/hummingbot/core/gateway/__init__.py", line 12, in <module>
    from hummingbot.core.event.events import TradeType
  File "/home/amir/secondins/hummingbot/hummingbot/core/event/events.py", line 8, in <module>
    from hummingbot.core.data_type.trade_fee import AddedToCostTradeFee, TokenAmount, TradeFeeBase
  File "/home/amir/secondins/hummingbot/hummingbot/core/data_type/trade_fee.py", line 7, in <module>
    from hummingbot.connector.utils import combine_to_hb_trading_pair, split_hb_trading_pair
  File "/home/amir/secondins/hummingbot/hummingbot/connector/utils.py", line 10, in <module>
    from zero_ex.order_utils import Order as ZeroExOrder
  File "/home/amir/anaconda3/envs/hummingbot/lib/python3.11/site-packages/zero_ex/order_utils/__init__.py", line 36, in <module>
    from zero_ex.contract_wrappers.exchange import Exchange
  File "/home/amir/anaconda3/envs/hummingbot/lib/python3.11/site-packages/zero_ex/contract_wrappers/exchange/__init__.py", line 18, in <module>
    from web3.contract import ContractFunction
ImportError: cannot import name 'ContractFunction' from 'web3.contract' (/home/amir/anaconda3/envs/hummingbot/lib/python3.11/site-packages/web3/contract/__init__.py)```

**Comment by ej-gsu** [comment]
I have just encountered the same problem, so on what basis was this closed?

**Comment by ej-gsu** [comment]
I was directed to this page, which shows that for now Hummingbot doesn't support Python versions higher than 3.8.22: 
https://github.com/hummingbot/hummingbot/blob/master/setup/environment.yml#L22

By downgrading my python installation from 3.10 I got rid of the error and has been able to compile and run the Hummingbot client :o)

**Comment by Amirghrb** [comment]
hi  i close the issue because  it was not a bug its just simple bad installation , you should let ./install file do the installation and in my case it was closed by OS because I've not allocate  enough  ram to WSL windows.
   installing from source need 4 GB of ram . if you don't want to develop the project recommend that use docker for installations

**Comment by Amirghrb** [comment]
hi  I close the issue because  it was not a bug its just simple bad installation , you should let ./install file do the installation and in my case it was closed by OS because I've not allocate  enough  ram to WSL windows   installing from source need 4 GB of ram . if you don't want to develop the project recommend that use docker to install the file
