### ISSUE TITLE
Is there a guide on how to start an amm_arb strategy on two dexes? Or a single dex + cex. I'm trying to do so but it won't work. 

### ISSUE THREAD

**Issue by xmichael446** [hummingbot/hummingbot#6234]
Hi there? The thing I'm trying to do is that I created a bot with an amm__arb strategy with both connectors on the same network (uniswap mumbai), and in the log pane I'm getting "network not ready: waiting for allowances: use trading interface to do manual approval".

**Comment by fengtality** [comment]
Not yet - note we are in the midst of refactoring how the amm-arb strategy works
https://github.com/hummingbot/hummingbot/pull/6242
