### ISSUE TITLE
Hedge Position

### ISSUE THREAD

**Issue by HESSEBO** [hummingbot/hummingbot#6237]
Does any body has any Idea if I can keep Hedge position from the both sides (long & short) running rather than humminbot keeping only of the sides running after one of the sides is closed. Currently when HBOT places orders on each side, and one side is  closed with profit it keeps the other side running and not placing any orders from closed orders position running. I want to keep each side running no matter what the market direction is.

**Comment by fengtality** [comment]
Handing custom requests like this is why we created the Community Bounties process. See this post for more info: https://blog.hummingbot.org/introducing-community-bounties/
