### ISSUE TITLE
Error connecting to Loopring order book stream

### ISSUE THREAD

**Issue by yclai** [hummingbot/hummingbot#6243]
**Describe the bug**
I am receiving an unexpected error when listening to order book streams of Loopring. Appreciate if anyone could help, thanks!!

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up loopring and binance connection
2. Create a cross exchange market making strategy
3. Start the bot using this command: start
...

**Screenshots**
![ss](https://user-images.githubusercontent.com/14324903/233549061-d9a30bcb-5c25-41ee-9df3-922ca80bd33d.png)

**Release version**
1.14.0

**Attachments**
<img width="427" alt="ss" src="https://user-images.githubusercontent.com/14324903/233548894-e43a9804-8146-497b-ae5f-e9246aaed3bd.png">

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by parthvnp** [comment]
Happy to take this issue and work on it!

**Comment by vpmartin** [comment]
Hey, do you have any update on this issue? Encountering the same problem when running basic PMM on Loopring. No previous Hummingbot experience.

**Comment by RobJah** [comment]
Got the same problem now that i switched my bots from binance to loopring.

**Comment by Harspel** [comment]
Having same issue, please fix.

**Comment by Sander1981** [comment]
same issue.  1.16.0

**Comment by Draakjuh** [comment]
Same issue here. Need it for a loopring bot

**Comment by ValkenRSE** [comment]
Would love a fix for this issue, if you would take the time to work on this issue it would be very appreciated.

**Comment by yclai** [comment]
Any update on this issue?

**Comment by rapcmia** [comment]
Loopring has been removed from connector list
