### ISSUE TITLE
Configuring scripts parameters

### ISSUE THREAD

**Issue by Mihaug** [hummingbot/hummingbot#6245]
Please is there a way to configure scripts parameters from the hummingbot console? Am using ubuntu 20.04LTS and i am not familiar with how to setup VScode and find the scripts to edit them on ubuntu

**Comment by MementoRC** [comment]
No, hummingbot client does not have this capability. However, you may only need a simple editor (nano, nedit, etc...) to create a script in the scripts/ directory and load it with `start --script ...` (refer to the docs for accurate syntax)
It would be great if you could join the discord community for a more customized tutorial, if you can do so, please close this Issue.
Thanks

**Comment by Mihaug** [comment]
Thanks 🙏🏽
