### ISSUE TITLE
EnvironmentNameNotFound: Could not find conda environment: hummingbot

### ISSUE THREAD

**Issue by fabioce** [hummingbot/hummingbot#6247]
I'm following this guide
(https://docs.hummingbot.org/installation/source/#install-hummingbot)
When I try to launch:
./install
I receive this output:

(base) ubuntu@ip-172-31-66-5:~/hummingbot$ ./install
Collecting package metadata (repodata.json): | ./install: line 40:  4369 Killed                  ${CONDA_EXE} env create -f $ENV_FILE

EnvironmentNameNotFound: Could not find conda environment: hummingbot
You can list all discoverable environments with `conda info --envs`.

path exists, skipping /home/ubuntu/hummingbot
completed operation for: /home/ubuntu/hummingbot
Requirement already satisfied: objgraph in /home/ubuntu/miniconda3/lib/python3.10/site-packages (3.5.0)
Requirement already satisfied: graphviz in /home/ubuntu/miniconda3/lib/python3.10/site-packages (from objgraph) (0.20.1)
./install: line 51: pre-commit: command not found

**Comment by MementoRC** [comment]
@fabioce It is not clear that this is an issue. Typically, this error occurs when you do not have sufficient RAM for conda to pull and resolve the environment, thus it is not created. You will need >4GB RAM to complete this step - virtual memory would help the process.

**Comment by cryptojorge** [comment]
I can confirm that increasing your memory fixes this problem.

I was using free aws instance and it was sized as a t2.micro which unbelievably only has 1G memory.
With that instance, I was getting stated error of not being able to find conda environment: hummingbot.

I changed the instance to be a t2.large which has 8G memory and the installation worked and I have hummingbot installed from source **_finally_** running now!
