### ISSUE TITLE
Clean up GitHub workflow

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#6267]
**Describe the bug**
The workflow is still trying to build and upload the gateway and client.
A new Dockerfile and conda environment is going to replace the current set up, in order to have multi arch image.

**Screenshots**
<img width="932" alt="image" src="https://user-images.githubusercontent.com/36869960/234616275-572839c3-05a2-4d1d-bde0-2b4715083806.png">

**Comment by rapcmia** [comment]
Fixed has been applied.
