### ISSUE TITLE
Raspberry pi cant install (both docker and from source) 

### ISSUE THREAD

**Issue by RobJah** [hummingbot/hummingbot#6270]
**Describe the bug**
// A clear and concise description of what the bug is.

Because of the parsing error on binance i had to reinstall.
I installed hummingbot from source on my raspberry 4B+ 8GB but got an error in the last step of completing the install (see screenshot).
I have installed and used hummingbot through source code many times before and was now forced to do so again because the docker guide has gone from super easy to super difficult. I dont understand why the previous short and easy docker install isnt available anymore with the latest version :(

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: never got that far
2. Start the bot using this command: bin/hummingbot.py
3. receive error / fail

**Screenshots**
// If applicable, add screenshots to help explain your problem.
Straight away in the first step 'Update the repository and install important dependencies' i get an error:
![image](https://user-images.githubusercontent.com/43188591/235437175-777504c2-39aa-4c0f-a87b-a1b1cc1ddaf8.png)

later on in the final steps of the installation from source i get another error:
![image](https://user-images.githubusercontent.com/43188591/235132051-3c2d7bb6-c88b-4b10-b64b-b32771a29463.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
1.15.0 hummingbot version
the pi is running on the latest 64bit OS (released this februari) 

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Hi @RobJah good day
We moved the helper scripts [here](https://github.com/hummingbot/deploy-examples/tree/main/bash_scripts) if your referring to Hummingbot's `create, start and update` scripts for docker.

**Comment by RobJah** [comment]
Thanks @rapcmia, but besides the clear commands to create start and update there is also the problem of now having to go through many more installation stepts than before to get the docker installed and working.

Besides that i hope you can answer why i am getting the error i shared in the screenshot, its an error i received while installing hummingbot from source so it is not do ker related. This I find even harder to understand because installation from source is now a way easier route to go down than the current docker installation path, because it has a short list of clear stated command in 1 overview. According to the error the Cython module is missing from the installation package. 

Thanks again to everyone for their hard work and speedy intervention after the big parsing error on binance occured.

**Comment by RobJah** [comment]
Also trying to install the docker eventually results in an error saying the software is not a match with the raspberry platform

![image](https://user-images.githubusercontent.com/43188591/235430770-08c66810-3a41-4995-8757-7ffb20fe0407.png)

**Comment by rapcmia** [comment]
Hi @RobJah thanks for the reply and apologies on the delay. We have not changed anything on the installation for source should be working as expected per instruction on docs however this is true that we have not been active for support on raspberryPi. 

For the docker screenshot above, make sure you have modified the `docker-compose.yml` and change to the supported ARM images `latest-arm` or `version-1.14.0-arm`. 
![image](https://user-images.githubusercontent.com/73840223/235596972-5b6fea72-3995-4c81-967b-5d0752b9eb16.png)


If you dont want to use docker-compose then the bash scripts are also on the same repository which should the same as the old helper scripts. To help you please try to download the following and 

```
#Download the bash-scripts
wget https://raw.githubusercontent.com/hummingbot/deploy-examples/main/bash_scripts/hummingbot-create.sh
wget https://raw.githubusercontent.com/hummingbot/deploy-examples/main/bash_scripts/hummingbot-start.sh
wget https://github.com/hummingbot/deploy-examples/blob/main/bash_scripts/hummingbot-update.sh

#Modify permission of the scripts
sudo chmod -R a+rw *.sh

# Create hummingbot docker then choose latest-arm or version-1.15.0-arm
./hummingbot-create.sh 

# Start hummingbot
./hummingbot-start.sh

# Update version hummingbot
./hummingbot-update.sh
```
