### ISSUE TITLE
Phemex Perpetual: Funding payment not received

### ISSUE THREAD

**Issue by mrhzysbl** [hummingbot/hummingbot#6281]
**Describe the bug**
The funding payment is not being received by the bot, waited for at least 10 minutes but no message was seen regarding the funding payment received in the logs.

https://user-images.githubusercontent.com/120451804/236105257-951306a6-9f4a-4c6e-b4fa-289ae64c9786.mov

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Clone and install featured branch
2. Create a perpetual market making strategy using Phemex Perpetual
3. Set tight spreads and wait for an order to get filled
4. With a position currently open, wait for funding period to pass by

**Screenshots**

**Release version**
Latest commit: [9ea3c64](https://github.com/CoinAlpha/hummingbot/pull/342/commits/9ea3c646f5821967cf708671739351220ee55c33)

**Attachments**
[Phemex_funding.zip](https://github.com/hummingbot/hummingbot/files/11392607/Phemex_funding.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Note: This is not a critical bug that affects the functionality of the connector. As per @vic-en, he will create a separate PR.**

**Comment by rapcmia** [comment]
Fix has been applied https://github.com/hummingbot/hummingbot/pull/6285
