### ISSUE TITLE
Injective Perpetual - Creating orphan orders

### ISSUE THREAD

**Issue by mrhzysbl** [hummingbot/hummingbot#6282]
**Describe the bug**
The bot is creating an order that is not showing on both log pane and web app. Also, the said order is not cancelling within the specified refresh time. 

This might be an issue on the Injective Perpetual side since it is also happening on the dev branch and not on a specific PR.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Clone and install dev or feat branch of HB OSS Set up your configuration file with these parameters: ...
2. Generate gateway certs and connect to gateway
3. Connect an Injective Perpetual wallet
4. Create perpetual market making strategy with order_level set as 1.
5. Start the bot using this command: start
6. Observe the status --live screen and web app to verify the orders being created
...

**Screenshots**
https://www.loom.com/share/b292a960bc1443ffaaeaf9dfdd9ef52f

<img width="1206" alt="Screen Shot 2023-05-05 at 12 11 23 PM" src="https://user-images.githubusercontent.com/120451804/236379547-f3906a7f-88da-48d4-85db-83782533414a.png">

**Release version**
PR: https://github.com/CoinAlpha/hummingbot/pull/353 

**Attachments**
[inj_perp.zip](https://github.com/hummingbot/hummingbot/files/11403380/inj_perp.zip)

**Comment by petioptrv** [comment]
This is related to an issue with the Injective JS SDK and the Injective team is currently looking into it. We can keep the ticket open for monitoring.

**Comment by rapcmia** [comment]
Injective Perpetual on gateway will no longer be supported.
