### ISSUE TITLE
Small bug in the position_executor.py

### ISSUE THREAD

**Issue by dimitri19861986** [hummingbot/hummingbot#6286]
**Describe the bug**
Hello, I am not sure but I think I found a bug in the "position_executor.py" file line 127. 
I am using a modified version of the position_executor.py, and so normally there is always a take_profit order, so the original position_executor might works. But the proposition makes the code more efficient for people to modify it. 

I guess the property :
    @property
    def close_price(self):
        if self.status == PositionExecutorStatus.CLOSED_BY_STOP_LOSS and self.stop_loss_order.order:
            return self.stop_loss_order.average_executed_price
        elif self.status == PositionExecutorStatus.CLOSED_BY_TAKE_PROFIT and self.take_profit_order.order:
            return self.take_profit_order.average_executed_price
        elif self.status == PositionExecutorStatus.CLOSED_BY_TIME_LIMIT and self.take_profit_order.order:
            return self.time_limit_order.average_executed_price
        else:
            return None

We should replace the last line by :
        elif self.status == PositionExecutorStatus.CLOSED_BY_TIME_LIMIT **and self.time_limit_order.order:**
            return self.time_limit_order.average_executed_price
        else:
            return None

Otherwise when time limit order is trigger and there is no take_profit order, the function return "none" and I have a bug in the status / Pnl

**Steps To Reproduce**
Configure the Simple Directional Strategy Example with a time limit of 15s to test the time limit
Setup take profit order to make them Market order, or deactivate it
Start the bot
open status to follow the process ![Capture d’écran 2023-05-09 à 11 09 01](https://user-images.githubusercontent.com/92455492/237049751-c81fceeb-006a-455b-a789-3c8b97fdca81.png)

then the status stop and an error occurs in the tick
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
1.15.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username: dimitri2065

**Comment by dimitri19861986** [comment]
Here is also a proposition to modify the position_executor.py. I am trying to modify it because it creates bugs on other exchanges. As I am trying to use it with Bybit I had to change a few things in it.
Not sure if it interrests someone else but here is the code (probably need to be reviewed again)

[position_executor.txt](https://github.com/hummingbot/hummingbot/files/11429363/position_executor.txt)

**Comment by rapcmia** [comment]
Hi @dimitri19861986 thanks for opening this ticket, we'd suggest to open a PR for the workaround for this issue and will have our team to review. Thank you
