### ISSUE TITLE
Add support for Market orders to dYdX

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6292]
## Description
* As described in Hummingbot Roadmap item #6210, we plan to support more order types for the Gold and Silver exchange connectors
* Add support for market orders in the `dydx_perpetual` connector, a Silver DEX connector for Epoch 4
* Modify unit tests to ensure they pass 
* Refer to this PR which add market orders to Binance: https://github.com/hummingbot/hummingbot/pull/6279

## Bounty
* Sponsor: Hummingbot Foundation
* Bounty amount: 10,000 HBOT
* Developer portion: 100%
* Status: OPEN

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by nikspz** [comment]
This Bounty is assigned to @yancong001, thank you for your contribution

**Comment by yancong001** [comment]
here https://github.com/hummingbot/hummingbot/pull/6308

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @yancong001. The fix has been deployed on development branch and hummingbot version 1.16.0
