### ISSUE TITLE
Add support for Market / Limit Maker orders in Gate.io

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6293]
## Description
* As described in Hummingbot Roadmap item #6210, we plan to support more order types for the Gold and Silver exchange connectors
* Add support for market and limit maker orders in the `gate_io` connector, a Silver CEX connector for Epoch 4
* Investigate if support already exists, and add support if it doesn't
* Modify unit tests to ensure they pass 
* Refer to this PR which add market orders to Binance: https://github.com/hummingbot/hummingbot/pull/6279

## Bounty
* Sponsor: Hummingbot Foundation
* Bounty amount: 10,000 HBOT
* Developer portion: 100%
* Status: OPEN

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by dizpers** [comment]
Can I take this one?

**Comment by nikspz** [comment]
This Bounty is assigned to @dizpers, thank you for your contribution

**Comment by rapcmia** [comment]
Hi @dizpers good day to you
We would like to know when can we review the PR for this bounty? Thank you

**Comment by dizpers** [comment]
Hi @rapcmia 
Sorry, I didn't have time to start the work on it. Please unassign it.

**Comment by nikspz** [comment]
Unassign @dizpers from this bounty

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by nikspz** [comment]
Assigned to @yancong001, please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by yancong001** [comment]
here https://github.com/hummingbot/hummingbot/pull/6354

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @yancong001. The fix has been deployed on development branch and next hummingbot version 1.17.0
