### ISSUE TITLE
Add support for Market orders to AscendEx

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6294]
## Description
* As described in Hummingbot Roadmap item #6210, we plan to support more order types for the Gold and Silver exchange connectors
* Add support for market orders in the `ascend_ex` connector, a Silver CEX connector for Epoch 4
* Modify unit tests to ensure they pass 
* Refer to this PR which add market orders to Binance: https://github.com/hummingbot/hummingbot/pull/6279

## Bounty
* Sponsor: Hummingbot Foundation
* Bounty amount: 10,000 HBOT
* Developer portion: 100%
* Status: OPEN

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by spazeba** [comment]
Could I be assigned to this one? @nikspz

**Comment by nikspz** [comment]
This Bounty is assigned to @spazeba , thank you for your contribution

**Comment by rapcmia** [comment]
Hi @spazeba good day to you
We would like to ask when can we review the PR for this bounty? Thank you

**Comment by rapcmia** [comment]
Hi @spazeba good day to you
Can you let us know any update for the bounty? Kindly let us know this week else we would need to open it again. Thank you!

**Comment by nikspz** [comment]
This bounty open.

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by nikspz** [comment]
This Bounty is assigned to @yancong001 now, thank you for your contribution

**Comment by yancong001** [comment]
here https://github.com/hummingbot/hummingbot/pull/6418

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @yancong001 . The fix has been deployed on development branch and next hummingbot version 1.18.0
