### ISSUE TITLE
Add support for Market / Limit Maker orders in Gate.io Perpetual

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6295]
## Description
* As described in Hummingbot Roadmap item #6210, we plan to support more order types for the Gold and Silver exchange connectors
* Add support for market and limit maker orders in the `gate_io_perpetual` connector, a Silver CEX connector for Epoch 4
* Investigate if support already exists, and add support if it doesn't
* Modify unit tests to ensure they pass 
* Refer to this PR which add market orders to Binance: https://github.com/hummingbot/hummingbot/pull/6279, as well as the `binance_perpetual` connector

## Bounty
* Sponsor: Hummingbot Foundation
* Bounty amount: 10,000 HBOT
* Developer portion: 100%
* Status: OPEN

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by nikspz** [comment]
This Bounty is assigned to @yancong001, thank you for your contribution

**Comment by yancong001** [comment]
here https://github.com/hummingbot/hummingbot/pull/6305

**Comment by nikspz** [comment]
Closing this bounty as paid
