### ISSUE TITLE
Config migration appears in first time setup

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6298]
## Description

The configs migration step was added to migrate older configs to the new pydantic standard. It should only run when legacy confs exist.

From https://github.com/hummingbot/hummingbot/blob/master/hummingbot/client/ui/__init__.py#L25:
```
    if Security.new_password_required() and legacy_confs_exist():
        secrets_manager = migrate_configs_prompt(secrets_manager_cls, style)
```

This method checks if there are files that need translation https://github.com/hummingbot/hummingbot/blob/master/hummingbot/client/ui/__init__.py#L80:
```
def legacy_confs_exist() -> bool:
    encrypted_conf_prefix = "encrypted_"
    encrypted_conf_postfix = ".json"
    exist = False
    for f in sorted(os.listdir(CONF_DIR_PATH)):
        f_path = CONF_DIR_PATH / f
        if os.path.isfile(f_path) and f.startswith(encrypted_conf_prefix) and f.endswith(encrypted_conf_postfix):
            exist = True
            break
    return exist
```

However, when you install Hummingbot for the first time, this migration screen still appears:
<img width="1238" alt="Screen Shot 2023-05-12 at 11 06 58 AM" src="https://github.com/hummingbot/hummingbot/assets/1795030/5ebcc37b-c7a3-4d8b-ab28-8da0341f5555">

## Proposed Fix
* Investigate this issue
* If possible, implement a fix so that new users don't go through configs migration
* If not, explain why

## Bounty
* Sponsor: Hummingbot Foundation
* Bounty amount: 10,000 HBOT
* Developer portion: 100%
* Status: OPEN

**Comment by zedquach** [comment]
I'll take this ticket

**Comment by nikspz** [comment]
This bounty assigned to @zedquach , thank you for contribution

**Comment by zedquach** [comment]
> This bounty assigned to @zedquach , thank you for contribution

I know the problem and the fix but I need some confirmation on business logic. Who should I talk to?

**Comment by zedquach** [comment]
@nikspz PR created
https://github.com/hummingbot/hummingbot/pull/6326

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @zedquach . The fix has been deployed on development branch and next hummingbot version 1.17.0
