### ISSUE TITLE
Add Kucoin Spot and Perpetuals Candles Feed

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#6320]
**Description**

A new Candles Feed for Kucoin Spot and Perpetuals
Should implement the CandlesBase class like the Binance candles.
Support web sockets to stream new messages and rest to collect historical data
Contains unit tests and meets % coverage requirements
You can find the candles feed inside hummingbot/data_feed/candles_feed

**Bounty**

Sponsor: Hummingbot Foundation
Bounty Amount: 100,000 HBOT
Developer Payment: 100,000 HBOT (100%)
Status: Open

**Comment by tomasgaudino** [comment]
Hi! I'd like to solve this task please

**Comment by nikspz** [comment]
This bounty assigned to @tomasgaudino, thank you for contribution

**Comment by nikspz** [comment]
@tomasgaudino  please fill up & submit the AML Policy Form via this link: https://forms.gle/ZeSRvWUU3gBeHPbH6
This is a one-time process for each ETH Address used to receive HBOT bounty.

May you please mention your discord handle here if you use different nickname here (github vs discord.)

**Comment by tomasgaudino** [comment]
Hi @nikspz, could you please confirm that the form has been sent correctly? Thanks!

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @tomasgaudino . The feature has been deployed on development branch and next hummingbot version 1.17.0
