### ISSUE TITLE
Add Gate.io Spot and Perpetuals Candles Feed

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#6321]
**Description**

A new Candles Feed for Gate.io Spot and Perpetuals
Should implement the CandlesBase class like the Binance candles.
Support web sockets to stream new messages and rest to collect historical data
Contains unit tests and meets % coverage requirements
You can find the candles feed inside hummingbot/data_feed/candles_feed

**Bounty**

Sponsor: Hummingbot Foundation
Bounty Amount: 100,000 HBOT
Developer Payment: 100,000 HBOT (100%)
Status: Open

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by nikspz** [comment]
This bounty is assigned to @yancong001 , thank you for contribution

**Comment by nikspz** [comment]
hi @yancong001 Are you working on this one? Could you please provide any updates on this bounty? Thanks

**Comment by nikspz** [comment]
Upon discussion with the team. We are increasing the bounty for this task to 100k each connector (Gate.io spot and Gate.io perpetual) so it is 200 000 HBOT now

**Comment by nikspz** [comment]
Sponsor: Hummingbot Foundation
Bounty Amount: 200,000 HBOT (100 000 HBOT for each connector, Gate.io spot and Gate.io perpetual)
Developer Payment: 200,000 HBOT (100%)

**Comment by yancong001** [comment]
here https://github.com/hummingbot/hummingbot/pull/6351

**Comment by nikspz** [comment]
This enhancement was introduced and merged in https://github.com/hummingbot/hummingbot/pull/6351, however gate.io perpetual data from gate.io side is inaccurate, as mentioned in the [PR6351](https://github.com/hummingbot/hummingbot/pull/6351)

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @yancong001 . The feature has been deployed on development branch and next hummingbot version 1.17.0
