### ISSUE TITLE
hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - WARNING - Buy order amount 0 is lower than the minimum order size 0.00001000. The order will not be created.

### ISSUE THREAD

**Issue by debanjanAqb** [hummingbot/hummingbot#6331]
**Hi Team, I have created pure_market_making strategy through docker env. of Hummingbot. I am attaching the screen-shot of it.**
![Screenshot from 2023-05-26 02-48-11](https://github.com/hummingbot/hummingbot/assets/128053922/43e50add-c503-4fe4-9c03-67d6ac219321)

**And Here is the screen-shot of balance.**
![Screenshot from 2023-05-26 02-51-37](https://github.com/hummingbot/hummingbot/assets/128053922/662fb715-f04a-44dc-8078-bbd74ea06cbf)

**But when I run the start command for running the strategy, I am getting below error.**
![Screenshot from 2023-05-26 02-54-08](https://github.com/hummingbot/hummingbot/assets/128053922/832df6af-5df8-4f85-9ecc-c082bc6eeb7e)

**For your reference I am also attaching the screenshot of API configuration of binance.**
![Screenshot from 2023-05-26 02-56-46](https://github.com/hummingbot/hummingbot/assets/128053922/58249302-a64a-4c0f-9435-cca68f0f309d)

**Please help me. Thanks in advance for your support.**

**Comment by nikspz** [comment]
hi, @debanjanAqb, not able to reprlicate. 
You need to add permission to Spot Trading here:


![image](https://github.com/hummingbot/hummingbot/assets/83953535/e36afc9b-a9d9-426e-a24b-e088bcf0ecb7)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/3278f6b7-ff66-47d9-8d31-0b8eef4f595e)

**Comment by debanjanAqb** [comment]
@nikspz Thanks [nikspz](https://github.com/nikspz). Now it works for me.
