### ISSUE TITLE
Uniswap on arbitrum_one does not support ARB token in tokenlist

### ISSUE THREAD

**Issue by designDemon** [hummingbot/hummingbot#6340]
**Describe the bug**
Trying to set up an amm_arb strategy with Uniswap_ethereum_arbitrum_one or sushiswap_ethereum_arbitrum_one is not working
WHenever I try to approve ARB or ETH token for spending, I get the error "Token not supported"

I am guessing its an issue with the tokenlist not being updated. I am not much of a coder, hence would be grateful if some1 could guide me on how to debug this issue or update the tokenlist

**Screenshots**
<img width="1137" alt="Screenshot 2023-05-29 at 9 20 28 PM" src="https://github.com/hummingbot/hummingbot/assets/36794724/e5a2792b-75d6-42dd-b6c7-9024008be700">

**Release version**
1.15

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by nikspz** [comment]
Upon checking, currently there's No pairs contains ARB or ETH or the autocomplete list (no ARB-USDC or ETH-ARB)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/e1faf4c5-d6c8-4d29-b136-67a8dfc714b9)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/a36663c5-864d-426a-adb2-b2231fc01004)

If you're trying to create amm_arb strategy using uniswap_arbitrum ARB-USDC or ETH-ARB after restart of the bot you will receive non active market on arbitrum message:
![image](https://github.com/hummingbot/hummingbot/assets/83953535/5c6e8947-58e2-4294-9d9f-4aaa662c88c6)

**Comment by fengtality** [comment]
This PR should make editing tokens for each network easier: https://github.com/hummingbot/gateway/pull/126. It also updates the Arbitrum token list and others.

**Comment by rapcmia** [comment]
Fix for this issue has been applied on previous version 1.17.0. 
![image](https://github.com/hummingbot/hummingbot/assets/73840223/17aac553-e732-435c-9417-629ae75ca625)
