### ISSUE TITLE
Getting an error when trying to approve token

### ISSUE THREAD

**Issue by debanjanAqb** [hummingbot/hummingbot#6355]
**Hi Team, I run "gateway approve-tokens uniswap_ethereum_mainnet WETH" to approve the token through docker env. of Hummingbot. But I am facing below error after run the above command. I have attached the screenshot.**

![Screenshot from 2023-06-01 20-00-19](https://github.com/hummingbot/hummingbot/assets/128053922/03e044d0-ff3b-45fd-8753-31b11d3ca7cc)
![Screenshot from 2023-06-01 20-00-03](https://github.com/hummingbot/hummingbot/assets/128053922/aac99ece-7b0b-4b7c-aac5-b7de287a8cc9)

**Please help me. Thanks in advance for your support.**

**Comment by rapcmia** [comment]
Hi @debanjanAqb good day,
As per error I would like to check whether I have a working node or ok internet connection. Another is we are missing out the details we need to investigate which is available on our `bug report` template. Please resubmit and make further look into it. Thank you
