### ISSUE TITLE
Integrate THORChain

### ISSUE THREAD

**Issue by AminAzGol** [hummingbot/hummingbot#6360]
**Feature Suggestion**
THORChain DEX is a cross-chain AMM enabling native asset swap. SDKs are available in their site.
There can be found opportunities for arbitraging.

**Comment by rapcmia** [comment]
Hi @AminAzGol good day,
For adding a connector you can:
1. Create a new post on our [proposal-discussion](https://discord.com/channels/530578568154054663/1037719198983532604) on discord
2. Submit a [Pull request proposal](https://docs.hummingbot.org/governance/proposals/#pull-request-proposals)
