### ISSUE TITLE
I want to trade with AITWTZ coin through decentralised (Uniswap) exchange. What would be the best strategy?

### ISSUE THREAD

**Issue by debanjanAqb** [hummingbot/hummingbot#6363]
**Hi Team, I want to trade with AITWTX coin through uniswap exchange. What is the best strategy of hummingbot for that I need to choose. Can you please share the steps of that strategy creation with me. It is too helpful for me.**

**And One more question is that what would be the value of LP connector if I choose uniswap_v3_lp strategy.**
![Screenshot from 2023-06-07 01-45-19](https://github.com/hummingbot/hummingbot/assets/128053922/d7ee4dcb-139b-4135-9179-0d0a2ed9ed4e)
 
**Please help me. Thanks in advance for your support.**

**Comment by rapcmia** [comment]
Hi @debanjanAqb good day to you
Id suggest to checkout first if this `AITWTX` token is supported on uniswap or any of hummingbot's DEX connector. The screenshot means that you have to setup a LP connector, you must connect the `uniswapLP` which is the only connector that supports it. 

Please also be reminded that there have not been much of update for or uniswap_v3_lp strategy and you might encounter such unexpected behaviors 🙇🏼

**Comment by debanjanAqb** [comment]
@rapcmia Thank you for your reply.
