### ISSUE TITLE
How to write a pure market making strategy for decentralized exchange in hummingbot, when I am using docker version 

### ISSUE THREAD

**Issue by debanjanAqb** [hummingbot/hummingbot#6374]
**Hi Team, I am using hummingbot docker environment. I want to write a pure market making strategy for decentralised exchange(Uniswap). Can you please provide me the steps. It will be very helpful. 
Thanks in advance.**

**Comment by rapcmia** [comment]
HI @debanjanAqb there are DEX connectors that support this kind of setup known as `CLOB`. As of the moment we have a number of connectors which you can use with gateway.

- [Injective Spot and Perp ](https://docs.hummingbot.org/exchanges/injective/)
- [Dexalot](https://docs.hummingbot.org/exchanges/dexalot/)
- [dYdX perpetual ](https://docs.hummingbot.org/exchanges/dydx-perpetual/)

For setting up docker client and gateway, you may want to check our [docker-compose guide](https://github.com/hummingbot/deploy-examples/tree/main/hummingbot_gateway_compose).
