### ISSUE TITLE
AscendEx perp connector

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6408]
## Description
* Based on the last quarterly [Poll](https://docs.hummingbot.org/governance/epochs/#cex-connectors_1), Binance, Kucoin, Gate.io and AscendEx are the Gold and Silver connectors for Epoch 4, which means that the Foundation maintains and improves them
* We have created bounties to add perpetual futures support for all connectors except for AscendEx
* This issue creates a bounty to add a perp connector to AscendEx
* Developer should follow the latest standards for perp connectors in the Binance Futures connector

## Bounty
* Sponsor: Hummingbot Foundation
* Bounty amount: 750,000 HBOT
* Developer portion: 100%
* Status: OPEN

**Comment by petioptrv** [comment]
@fengtality, CoinAlpha is interested in tackling this ticket

**Comment by fengtality** [comment]
AscendEx informed us that their perpetual futures API is only open to whitelisted institutional users, so it doesn't make sense for the Foundation to fund a bounty for an open source connector.

We will cancel this bounty as CoinAlpha has not yet started work on it.
