### ISSUE TITLE
Exercise 1 - Hello World got error : script_strategy_base - binance is not ready. Please wait..

### ISSUE THREAD

**Issue by eromoe** [hummingbot/hummingbot#6414]
**Describe the bug**

follow Exercise 1 - Hello World, got error script_strategy_base - binance is not ready. Please wait..

**Steps To Reproduce**

https://docs.hummingbot.org/quickstart/custom-pmm-1/

**Screenshots**
// If applicable, add screenshots to help explain your problem.

<img width="1669" alt="Screenshot 2023-06-27 at 14 59 34" src="https://github.com/hummingbot/hummingbot/assets/3938751/de380fea-3df3-4fd6-bd7e-d9e4b4a7618d">

**Release version**
Version: dev-1.18.0

**Comment by nikspz** [comment]
Hey @eromoe that issue related to your location binance restrictions

Same script on AWS:
![image](https://github.com/hummingbot/hummingbot/assets/83953535/3467983c-457a-4ef2-881f-534ad7f47e5a)
