### ISSUE TITLE
Orders not being placed on binance due to order being below market minimum notional value

### ISSUE THREAD

**Issue by shahmat** [hummingbot/hummingbot#6425]
### Describe the bug

I am running the base liquidity mining strategy.  Occasionally Binance will not open a "Buy" order, I am seeing this as the error message:  "Quantizing order amount to 0 because order notional value is below 10.0000000 market minimum notional value"." 

This was on the RLC/USDT pair, I have 200 RLC tokens (worth $1.30) each and 200 in USDT in the account.  

I updated order_amount value from 100 to 100.00  This seems to have fixed it, but I believe there is some sort of problem in the code section where the quantize order amount code is being done.

### Steps to reproduce

1. Run basic liquidity mining strategy
2. Set order_amount value to a round number (ex. 20 or 100)
3. Occasionally it will stop creating "Buy" orders.
4. Gives the "Quantize order amount error"

### Release version

dev-1.18.0

### Type of installation

Docker

### Attach required files

[logs_conf_liquidity_mining_1.log.zip](https://github.com/hummingbot/hummingbot/files/11909836/logs_conf_liquidity_mining_1.log.zip)

**Comment by cardosofede** [comment]
@shahmat I think that the behavior of the bot is correct but the log message is incorrect since it's showing the same message if your are not compliant with the min notional size or min order amount (they are different)

**Comment by shahmat** [comment]
Sorry I don't understand.  Is there somewhere to set the min notional size instead in the config or what would be causing the error if it's not the min order amount?

**Comment by cardosofede** [comment]
> Sorry I don't understand.  Is there somewhere to set the min notional size instead in the config or what would be causing the error if it's not the min order amount?

I'm currently in the airport to departure in a flight hehe. But yeah the problem is in the value that you selected of the order size, it's very small.
Check in the UI and try to send an order with the first amount that was failing for you, you will see that binance says that the min order amount is ...
If you want to access to this properties in the code, you should look at the trading rules

**Comment by shahmat** [comment]
Ah gotcha, thank you
