### ISSUE TITLE
XEMM - Single side exposure for low liquidity markets

### ISSUE THREAD

**Issue by chenxiemin** [hummingbot/hummingbot#6431]
### Describe the bug

XEMM strategy in low liquidity market may cause the single side exposure.

### Steps to reproduce

1. Create a XEMM strategy with large amount in a low liquidity maker market.
2. The maker side get traded with the amount low than the taker's min trade size.
3. The single side exposure occurs at this time if no maker side's trade anymore.

### Release version

1.3.0

### Type of installation

Source

**Comment by rapcmia** [comment]
hi @chenxiemin you may want to check our latest 1.27.0 that introduces XEMM script and controller for V2 strategy
