### ISSUE TITLE
Add dYdX candles feed

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6447]
### Description

* Add a new Candles Feed for the `dydx_perpetual` connector
* Should implement the CandlesBase class like the Binance Perpetual candles.
* Support web sockets to stream new messages and rest to collect historical data
* Contains unit tests and meets % coverage requirements
* You can find the candles feed inside hummingbot/data_feed/candles_feed
* See https://dydxprotocol.github.io/v3-teacher/#get-candles-for-market for API reference

### Bounty

* Sponsor: Hummingbot Foundation
* Classification: P1
* Bounty Amount: 100,000 HBOT
* Developer Payment: 100,000 HBOT (100%)
* Status: Open

**Comment by nikspz** [comment]
We could close this bounty until candles connection through websocket available
