### ISSUE TITLE
Injective SDK is being upgraded

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/hummingbot#6453]
### Feature Suggestion

The injective SDK has recently been upgraded to v0.7. This upgrade features a refactoring of the methods that Hummingbot uses. Hummingbot is no longer compatible with the latest SDK.
The latest version of the SDK that Hummingbot is compatible with is v0.6.2.7

### Impact

It is foreseeable that users may experience failures in the coming future as the hummingbot implementation becomes more incompatible

**Comment by dyegonery** [comment]
Any update about this? It seems that it's not being possible to run Hummingbot on Injective at this point.

**Comment by nikspz** [comment]
Injective SDK was updated on this PR
https://github.com/hummingbot/hummingbot/pull/6606/files

@dyegonery could you please send here logs/screenshot? thank you
