### ISSUE TITLE
Quantizing error logs are wrong

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#6466]
### Describe the bug

When sending orders to the exchange the bot first checks if the order is compliant with the Trading Rules. If the order amount is lower than the min order amount or if the order x amount is lower than the min notional size, the bot will not send the order and will trigger an order failed event.
Currently, the log message is wrong if the notional value condition is failing and the information shown is inconsistent with the error.

### Steps to reproduce

Run this script (https://gist.github.com/cardosofede/84eb211c2b98f5190742af24ae5c6b63) with the following values:
- Order amount: 0.001 --> notional violated.
<img width="1641" alt="image" src="https://github.com/hummingbot/hummingbot/assets/36869960/37620a3b-bedf-40c9-9522-ecb6d7fdc317">
Check that you have two log messages (one that says that you are violating the min notional size and the other one that you are violating the order amount.

- Order amount: 0.00000001 --> order amount violated
<img width="1642" alt="image" src="https://github.com/hummingbot/hummingbot/assets/36869960/aabc844f-c21c-4c45-9577-ad9211e18b65">
Check that also we have two log messages but they are consistent.

### Release version

dev-1.18

### Type of installation

Source

**Comment by rapcmia** [comment]
Fix has been added to version 1.19.0
