### ISSUE TITLE
HEDGE STRATEGY GATE.IO PERP BUG - HEDGE VALUE ALWAYS 0

### ISSUE THREAD

**Issue by Drtikol22** [hummingbot/hummingbot#6470]
### Describe the bug

There is a bug in the hedge strategy v 1.17 gate.io connector. When in value mode and HEDGE position mode the bot is not seeing the position on gate perp. The trade to do the hedge is calculated and performed correctly, but "status" shows position 0 and hedge value 0 after the trade is made. So the bot is thinking that the position is not hedged and performing the same trade again and again.. 

I also tested it with binance futures testnet and worked with no problems, so it looks its only gate.io specific problem.

<img width="1224" alt="Snímek obrazovky 2023-07-11 v 9 49 27" src="https://github.com/hummingbot/hummingbot/assets/139210818/56c4fa60-d3cb-47e5-bbd9-fa61c31f83c7">

### Steps to reproduce

1. create hedge strategy spot gate.io - gate perp, value mode
2. gate.io spot pair - BUSD-USDT, gate.io perp pair - PENDLE-USDT. 
3. Busd amount on spot 10, PENDLE amount on perp 0
4. when strategy start, it will hedge the amount of BUSD by creating a short postition of 12 PENDLE. So now the position is hedged correctly
5. after hedge_interval the bot performs another sell of 12 PENDLE so now creating a disbalance. Shorted position is bigger than spot position
6. bot continuos shorting 12 PENDLE every hedge_interval until stopped manually

### Release version

1.17.0

### Type of installation

Docker

### Attach required files

For some reason I cant find a log and config file containing this instance :/

**Comment by leastchaos** [comment]
Hi, I am not sure if this is related to the strategy or connector.
From what your screenshot shows, the hedge strategy cannot detect opened position. 
I also tried using another strategy "perpetual market making" and it also cannot detect position in gate_io_perpetual connector.
@cardosofede are you able to help to check if the gate_io_perp account positions is working?
![image](https://github.com/hummingbot/hummingbot/assets/64965782/d2a417a6-0c0b-479a-ace6-ce399c0af4b7)

**Comment by rapcmia** [comment]
The fix on gateio perpetual hedge has been added to development and will be available on `release version 1.20.0`
