### ISSUE TITLE
Upgrade API for Bybit/Mexc

### ISSUE THREAD

**Issue by hlxwell** [hummingbot/hummingbot#6474]
### Feature Suggestion

I am currently using the hummingbot, I realized the bybit API is still v1, as official document said it will be expired in Oct 2023, so that means it won't work after 3 month. also for mexc connector, it is using v2, it will be expired within this year. so do you have any plan to upgrade those API ?

### Impact

Bybit or Mexc won't be able to work anymore.

**Comment by hlxwell** [comment]
any one can help? since this API expiration will come soon.

**Comment by hlxwell** [comment]
@rapcmia could you please help? do you think we could do something like 
https://snapshot.org/#/hbot-ip.eth/proposal/0x3f959c18fcc6936081965e81587a4191b742227454af81aac360e25bbd9062cd

**Comment by hlxwell** [comment]
@fengtality Do you think you could help on this, since we see the bybit connect is still using v1, and the community seems pushing to upgrade API.
below is the message.

![image](https://github.com/hummingbot/hummingbot/assets/39321/30b33802-4190-4d75-a27c-76c9e1799b6c)

**Comment by fengtality** [comment]
I agree that an upgrade would make sense, but the Bybit connector isn't maintained by Hummingbot Foundation. Therefore, either 1) Bybit or a community member would need to fund a bounty or 2) a community member can propose an improvement proposal to allocate an HBOT bounty at https://snapshot.org/#/hbot-ip.eth

**Comment by hlxwell** [comment]
> I agree that an upgrade would make sense, but the Bybit connector isn't maintained by Hummingbot Foundation. Therefore, either 1) Bybit or a community member would need to fund a bounty or 2) a community member can propose an improvement proposal to allocate an HBOT bounty at https://snapshot.org/#/hbot-ip.eth

thanks a lot for the reply, Do you think you could create a proposal on snapshot, or I could create it also?

**Comment by hlxwell** [comment]
@fengtality could you please help to create the proposal on snapshot? thanks a lot.

**Comment by nikspz** [comment]
@hlxwell https://docs.hummingbot.org/governance/proposals/
you need HIP here:
https://docs.hummingbot.org/governance/proposals/#hummingbot-improvement-proposals
Snapshot url:
https://snapshot.org/#/hbot-ip.eth/create

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/issues/6585
Bybit upgrade to the latest API: Added to possible issue bounties , users need to cooperate with developers and fund the bounty / create a proposal to fix
