### ISSUE TITLE
The Bot shuts down due to a memory leak

### ISSUE THREAD

**Issue by ikeda1729** [hummingbot/hummingbot#6479]
### Describe the bug

Every time I run the PMM script on an Azure VM, the bot shuts down after about 3 days due to a memory leak.

Here is the capture of the memory use of Azure VM.
The available memory is going towards 0GB.
![Screenshot from 2023-07-14 11-23-27](https://github.com/hummingbot/hummingbot/assets/88636666/01851945-139a-4625-998a-980bbf8f92e8)

Could any one help me with this memory leak problem.

### Steps to reproduce

1. Install Hummingbot by the deploy-example repo on Azure VM
2. Create a PMM conf and import and start that conf from a Hummingbot CLI
3. The bot trades on MEXC.

### Release version

dev-1.17.0

### Type of installation

Docker

**Comment by fengtality** [comment]
need logs and configs - this could be due to many reasons
