### ISSUE TITLE
Binance rate oracle - default rate oracle for USDT using binanceUS

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6487]
### Describe the bug

BInance rate oracle, incorrect rate for token USDT

![image](https://github.com/hummingbot/hummingbot/assets/83953535/f049cdcb-4d66-45bb-acf5-a712aabf0abe)
https://www.binance.us/spot-trade/usdt_usd
![image](https://github.com/hummingbot/hummingbot/assets/83953535/d7fba551-9213-439d-ba32-a16630bf4ef9)

binance.com:
![image](https://github.com/hummingbot/hummingbot/assets/83953535/c2d2c131-302a-4251-ba3a-1fd3689cc60e)

### Steps to reproduce

1. Clone latest development branch
2. connect binance
3. check balance
4. check rate --token USDT

### Release version

dev-1.18.0

### Type of installation

Source

### Attach required files

P.s. As option could be solved with changing global_token.global_token_name to USDT

![image](https://github.com/hummingbot/hummingbot/assets/83953535/6ced0059-7245-4ad3-a391-3a8aae0d9a9f)

**Comment by fengtality** [comment]
@nikspz I ran the client using `USDT` as global token and didn't see any issues, so if this helps resolve new user issues, we should change global token to USDT.

For users in the US who experience rate limit issues, I would recommend them to use `config rate_oracle` and change source to Kucoin.

**Comment by rapcmia** [comment]
Fix added to version 1.18.0
