### ISSUE TITLE
Upgrade MEXC spot connector

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6507]
## Description

* Proposal: HGP-31 (https://snapshot.org/#/hbot-ip.eth/proposal/0x3f959c18fcc6936081965e81587a4191b742227454af81aac360e25bbd9062cd)
* Description: Upgrade MEXC spot connector to the latest exchange API and connector standard
* Acceptance criteria: Upgrade connector to latest connector standards: https://docs.hummingbot.org/developers/connectors/#what-are-exchange-connectors

## Bounty

* Sponsor: Hummingbot Foundation
* Budget: Epoch 5 Budget
* Bounty amount: 250,000 HBOT or USDC equivalnet
* Developer portion: 100%
* Status: OPEN

**Comment by yancong001** [comment]
i'd like to take this task

**Comment by nikspz** [comment]
Assigned to @yancong001, please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by rapcmia** [comment]
Hi @yancong001 good day to you,
We would like to know any update for the assign bounty? thank you

**Comment by yancong001** [comment]
hi, I am half done, it may take another 1 to 2 weeks.

**Comment by nikspz** [comment]
hi @yancong001 Could you please add  your progress updates / timeframe when PR be available for review? Thanks

**Comment by yancong001** [comment]
this week, or as soon as tomorrow

**Comment by yancong001** [comment]
here https://github.com/hummingbot/hummingbot/pull/6525

**Comment by nikspz** [comment]
Closing this bounty as paid.
The MEXC update has been deployed to development branch and hummingbot version 1.20.0.
