### ISSUE TITLE
Gateio Perpetual account position info missing

### ISSUE THREAD

**Issue by leastchaos** [hummingbot/hummingbot#6510]
### Describe the bug

There may be some issue with getting the position info for gateio perpetual. 
Perpetual Market Making
![image](https://github.com/hummingbot/hummingbot/assets/64965782/5a5149d6-1b27-4266-9a23-bb942e2cdc2f)
Hedge https://github.com/hummingbot/hummingbot/issues/6470

### Steps to reproduce

1. Create position on gateio_perpetual
2. Start strategy
3. Strategy does not receive position information.

### Release version

1.17

### Type of installation

Source

**Comment by rapcmia** [comment]
Current Gateio also does not recognize the position when manually closed from the exchange. 

Steps to reproduce:
1. Create a perp-mm with position mode `hedge` and use gateio 
2. When successfully open a position, manually close it on exchange 
3. Observe on the client by running status (or `status live`) that position is still displayed as active

**Comment by nikspz** [comment]
Adding bounty for this issue.
Bug related to the gate.io perpetual connector

**Bounty**
Sponsor: Hummingbot Foundation
Bounty amount: 10,000 HBOT
Developer portion: 100%
Status: OPEN

**Comment by yancong001** [comment]
fixed https://github.com/hummingbot/hummingbot/pull/6551

**Comment by rapcmia** [comment]
Fix has been added on version 1.20.0

**Comment by nikspz** [comment]
This bounty closed as paid
