### ISSUE TITLE
Change trading pair fetcher so that it only fetches connected exchanges

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6511]
### Rationale

- Trading pair fetcher is used to get the trading pairs for an exchange
- Since Hummingbot fetches pairs from all connectors at startup, errors show in the logs for any exchanges with API issues or geo restrictions
- While this is helpful for QA purposes, it may cause new users to believe Hummingbot is broken

### Description

- Add a new config variable to `conf_client.yml`: `fetch_pairs_from_all_exchanges`. Default: False.
- Change the trading pair fetcher so that if the param above is False, it only fetches pairs from exchanges where the user has added an API key, plus the exchanges included in `paper_trade_exchanges` in the `conf_client.yml`
- If True, the fetcher operates as it does now and fetches pairs from all exchange connectors
- After a user added API key with `connect`, fetch pairs from that new exchange
- Acceptance criteria: When starting a strategy/script on an exchange, the client should have already fetched pairs for any of the connectors loaded (otherwise, the client won't be able to convert pairs and run the strategy)

### Bounty

- Sponsor: Hummingbot Foundation
- Bounty amount: 50K HBOT or USDC equivalent
- Developer portion: 100%
- Status: OPEN

**Comment by isreallee82** [comment]
I will like to work on this

**Comment by fengtality** [comment]
do you have enough context with the trading pair fetcher to perform this
fix? Please note the acceptance criteria, since we will check this
carefully to ensure that the fix doesn't cause bigger problems

**Comment by isreallee82** [comment]
I did a check and I have tried familiarise myself with the trading pair fetcher and fully understand the issue that needs to be addressed. Rest assured, I will approach this fix with utmost care and attention to detail. If there are any additional details or specific requirements I should be aware of, please let me know.

**Comment by isreallee82** [comment]
I should create a pr today undergoing testing @nikspz is there a way to remove an added api

want to test this
- After a user added API key with connect, fetch pairs from that new exchange

**Comment by isreallee82** [comment]
could you give more time @nikspz  maybe by weekend while testing I noticed some behaviour just want to be sure things run fine

**Comment by nikspz** [comment]
#6526

**Comment by nikspz** [comment]
Merged to latest development, feature will be available in 1.21.0 release. 
Thank you for your contribution.

**Comment by carlitogetaladajr** [comment]
@isreallee82 please fill up & submit the AML Policy Form via this link: https://forms.gle/p3zhnSpkP2eZnj9m9
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by isreallee82** [comment]
done @carlitogetaladajr

**Comment by carlitogetaladajr** [comment]
@isreallee82 May I know which discord handle you have registered the wallet address with? Just want to be certain so not to be mixed up with other developer.

**Comment by isreallee82** [comment]
leeteelee#8750

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @isreallee82. The feature has been deployed on development branch and hummingbot version 1.21.
