### ISSUE TITLE
Client - Error parsing 'content-type' causing distorted UI

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6513]
### Describe the bug

Checking the development branch commit `914c71c1b5ed8ff1991e8929db4001d38fbc2575`, observed this error when switching to another window or going idle causing issues on the client's user interface

![image](https://github.com/hummingbot/hummingbot/assets/73840223/58e7c7ab-4f4a-4a8b-8620-0cf23919fed4)

Ran `config` command: 
![image](https://github.com/hummingbot/hummingbot/assets/73840223/347c2088-a11a-4f5b-9800-51c85dc455ee)

Note: Opened ticket for monitoring purpose, the workaround to fix:
- Run `bin/hummingbot.py 2>/dev/null`
- When the issue occurs, refresh client page by `ctrl + l`

### Steps to reproduce

1. Install development branch `914c71c1b5ed8ff1991e8929db4001d38fbc2575`
2. Open client and observe for 3-5mins or
3. Switch to another window or terminal and get back again

### Release version

development 1.19.0

### Type of installation

Source

### Attach required files

Nothing much on log file but still uploaded:
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/12271487/logs_hummingbot.log)

**Comment by nikspz** [comment]
Reviewed issue could happened again after used refresh the Client workaround which could be annoying
![image](https://github.com/hummingbot/hummingbot/assets/83953535/360c6074-8ceb-4228-ad62-29e37a36f5fd)

**Comment by rapcmia** [comment]
Fix has been applied to development and release 1.19.0. 
User can now use `./start` command to start hummingbot. The fix has been integrated as well on docker.
