### ISSUE TITLE
hummingbot.org site - Deadlinks in docs site

### ISSUE THREAD

**Issue by trevorsibanda** [hummingbot/hummingbot#6516]
### Describe the bug

Failing to access docs

<img width="1213" alt="image" src="https://github.com/hummingbot/hummingbot/assets/10484659/417d02b3-1b00-4284-8a12-71bd53b77f4d">

### Steps to reproduce

1.  Follow links on README.md

### Release version

na

### Type of installation

Source

**Comment by nikspz** [comment]
hi @trevorsibanda There's an ongoing issue, we will fix it.
Current workaround is to use https://hummingbot.com/

**Comment by nikspz** [comment]
Docs site seems recovered, hummingbot.org still ongoing

https://docs.hummingbot.org/

![image](https://github.com/hummingbot/hummingbot/assets/83953535/824d4d94-2ed8-451f-a4b4-df68951e26fb)

**Comment by nikspz** [comment]
Closing as fixed, URL:  https://docs.hummingbot.org/docs/
