### ISSUE TITLE
Add Coincap.io as the new rate oracle source

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6517]
Description: 
Rate oracle: https://coincap.io/
We're looking to integrate the coincap.io rate oracle into Hummingbot. 
A lot of Rate oracles do not work very well, not working with some exotic trading pairs or have rate limits too low.
We need rate oracle source that should be more `reliable`, with the good implementation in the Client.
The adding new rate oracle should expand the range of supported cryptocurrencies. 
The rate oracle should provide accurate real-time price data. The successful integration should be documented and compatible with our existing trading bot architecture.

Sponsor: Hummingbot Foundation
Developer share: 100% - paid upon merge to development
Bounty Amount: 100,000 HBOT
Status: Assigned

**Comment by petioptrv** [comment]
@nikspz, here is the PR for this issue: https://github.com/hummingbot/hummingbot/pull/6524

**Comment by petioptrv** [comment]
@nikspz, the code is undergoing internal QA review. Should be submitting it soon.

**Comment by rapcmia** [comment]
`Coincap` has been merged to development and will be available on `release version 1.120.0`

**Comment by nikspz** [comment]
Closing this bounty as paid, feature available on latest development  and release version 1.20.0
