### ISSUE TITLE
Fixed grid script - Client place order at wrong price when rebalance (during the longrun)

### ISSUE THREAD

**Issue by mirono** [hummingbot/hummingbot#6523]
### Describe the bug

fixed_grid.py script issue.
script fail to place orders on initialize to rebalance.
Logs in attached screenshot.

### Steps to reproduce

1. start --script fixed_grid.py
2. 
3. 

### Release version

dev-1.18.0

### Type of installation

Docker

### Attach required files

<img width="1728" alt="Monosnap Microsoft Teams Notification 2023-08-16 11-26-38" src="https://github.com/hummingbot/hummingbot/assets/6016445/a1bbeec0-59e4-4351-a777-793185a7f6c5">

**Comment by nikspz** [comment]
hi @mirono Could you please provide log file and your script file used?

**Comment by mirono** [comment]
Here is the script and logs.
[logs_fixed_grid.log](https://github.com/hummingbot/hummingbot/files/12361115/logs_fixed_grid.log)
[fixed_grid.py.zip](https://github.com/hummingbot/hummingbot/files/12361121/fixed_grid.py.zip)

**Comment by nikspz** [comment]
From what I see from the log that's price for SOL-USDT pair is wrong, also order amount that Client trying to submit are too low for binance exchange. Tried other pair (XRP-USDT, bot used correct price and order amount)

This one SOL-USDT, looks okay, I reduced order levels amount to 5
I guess you could try to reduce order levels and try to restart Client/ fix grid script

![image](https://github.com/hummingbot/hummingbot/assets/83953535/38510e88-6471-47cc-a29d-6db637082104)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/8216444a-834a-422c-8298-449490834700)

**Comment by mirono** [comment]
I made a manual trade to rebalance and be able to use the bot.
But the question is why it send wrong prices to Binance that are not in accordance to their precision, and als owhy the pair rate was wrong.
I guess if it can't be reproduced you can close it.

**Comment by mirono** [comment]
Same thing happen today - the fixed grid need to sell some SOL but the order price is completely wrong (0.22 instead of 21.x).

**Comment by nikspz** [comment]
Okay, seems longrun needed to reproduce this one

**Comment by rkc2000** [comment]
How can I reproduce this? I tried running the same script pasted above but with binance_paper_trade and it appears to work as expected. 
<img width="790" alt="Screenshot 2023-08-18 at 14 31 29" src="https://github.com/hummingbot/hummingbot/assets/6465285/d3bf5a52-18ca-491e-9ccc-7a21c283e6b3">

**Comment by masimo12358** [comment]
In my specific case the grid run out of bounds in SOL-USDT on Binance as the price went below the low limit. As it bought SOL all the way down I was left with not enough USDT. I stopped it and exited Hummingbot. At some point later, I updated the limit and run it again. As there wasn't enough USDT it tried to rebalance by selling some SOL. It is at this point that the bug occurs - the price of SOL in the rebalance order is wrong.

**Comment by rkc2000** [comment]
Got it, the bug is only in sell rebalance orders, not in buy. I've found the solution for it. In line 192, the correct code should be:

price = ref_price * (Decimal("100") + self.rebalance_order_spread) / Decimal("100")

I'll submit a pull request.

**Comment by rkc2000** [comment]
Created pull request here:
https://github.com/hummingbot/hummingbot/pull/6527

**Comment by rapcmia** [comment]
Fixed on version `1.19.0`
