### ISSUE TITLE
Gateio perpetual - displays duplicate position on client when retrieving position from exchange 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6539]
### Describe the bug

When the current gateio retrieve position on an event like stopping the hummingbot (or exit), the client recognize it but displays duplicate position as well resulting client to create two take-profot/stop-loss orders to close position. 

![image](https://github.com/hummingbot/hummingbot/assets/73840223/12d4eede-4b86-4f89-a55f-990f938842b3)

![image](https://github.com/hummingbot/hummingbot/assets/73840223/b732db9f-762f-4ca2-900c-67f679141648)

  - In the event that you need to retrieve a open position, the client recognize it but displays two open position
  - Crosscheck the exchange in the amount is still for single order yet the client displays two
  - When this happens, it also create two take-profit orders to close the position
  - Possibly related to issue https://github.com/hummingbot/hummingbot/issues/6510

### Steps to reproduce

1. Setup perp-mm using` position_mode hedge` on `gate_io_perpetual`
2. When successfully open position, stop (or exit hummingbot) the strategy then start again
3. Observe behavior when retrieving position 

### Release version

dev-1.19.0 / 1.18.0

### Type of installation

Source

### Attach required files

[logs_perp-gateio.log](https://github.com/hummingbot/hummingbot/files/12430402/logs_perp-gateio.log)

**Comment by yancong001** [comment]
fixed https://github.com/hummingbot/hummingbot/pull/6551

**Comment by rapcmia** [comment]
Fixed on version 1.20.0

**Comment by nikspz** [comment]
This bounty closed as paid
