### ISSUE TITLE
Bug Report: error parsing content type

### ISSUE THREAD

**Issue by eMZet0808** [hummingbot/hummingbot#6561]
### Describe the bug

when hummingbot 1.19 is started a parsing content type error appears and hummingbot is not working correctly.

### Steps to reproduce

1. freshly install hummingbot 1.19 from source
2. start hummingbot with bin/hummingbot.py
3. just wait, the error will appear after some time on the screen

### Release version

1.19

### Type of installation

Source

### Attach required files

[meinradZeiler_hummingbot119_bug.zip](https://github.com/hummingbot/hummingbot/files/12514495/meinradZeiler_hummingbot119_bug.zip)

**Comment by nikspz** [comment]
hi @eMZet0808 This is duplicated ticket for https://github.com/hummingbot/hummingbot/issues/6513 Please use new 
```
./start 
```
command to start
