### ISSUE TITLE
Dydx perpetual - add candles feed source bounty request

### ISSUE THREAD

**Issue by JulesText** [hummingbot/hummingbot#6562]
Hello

I am interested in authoring a PR for dydx perpetual candles as mentioned in #6216 

If no one else has started this, would the hummingbot dev team like me to? If so would you offer a hbot token bounty?

Regards.

**Comment by JulesText** [comment]
The candles feed class is based mainly on the websocket end point. The dydx v3 api does not support websocket candle feeds, only Rest end point candle requests, which is possibly why the enhancement has not been implemented yet. Websocket candle feeds appear on the dydx roadmap for v4 but it has not been released yet.

It may be possible to develop a dydx perpetual candles feed that uses only Rest, though I am not sure if the hummingbot dev team would accept the PR.

**Comment by rapcmia** [comment]
Closing ticket, the foundation will discuss if a candles feed is needed for dydx v4
