### ISSUE TITLE
Kucoin perpetual - incorrect position size in connector

### ISSUE THREAD

**Issue by Zzuummzz** [hummingbot/hummingbot#6567]
### Describe the bug

My script was created to work on the futures markets, and has been tested and debugged on the Binance and Bybit test servers, as well as the real Bybit server. 
When connected to the real Kucoin server (kucoin_perpetual connector), the following behavioral change was detected:
When sending an order, of size 0.1 BCH to the exchange, all the necessary order acceptance and execution event (of size 0.1) were received from the connector. But on the exchange, in the order history, these orders are displayed as executed, but the volume in them is 10 "lots". 
The problem is that when the script takes information from the connector about the volume of the current position, it also receives the volume of 10 in the base currency (10 BCH in this case). So, in other words, the volume of the sent order does not match the volume of the position displayed in the Connector, because the exchange counts the volume in lots.
And since the lot size is not included in the market data, it is impossible to recalculate the position size correctly and compare it with the order size.
I attach a part of the bot log, where one order is displayed, and the corresponding screenshot from the exchange, where the same order is indicated.

### Steps to reproduce

The following steps are sufficient for playback:
1. send a market order for opening via kucoin_perpetual
2. See in the logs that the order is executed
3. View the size of the current open position in the connector and compare it with the size of the order
4. To see what size of the executed order is displayed in the Exchange's personal cabinet

### Release version

1.18.0

### Type of installation

Source

### Attach required files

[Kucoin_perpetual errors.log](https://github.com/hummingbot/hummingbot/files/12599795/Kucoin.errors.log)

![Screenshot 2023-09-13 в 13 36 02](https://github.com/hummingbot/hummingbot/assets/129792076/17c321af-b1d3-492a-b23e-7b72c700f8ba)

**Comment by Zzuummzz** [comment]
Addendum to the description of the bug:
When I send a market order to the exchange with a volume of (for example) 0.09, then immediately after its execution the Connector displays the size of the open position equal to 9 (i.e. the number of lots). After a few ticks of the script, the value of the open position size in the Connector suddenly changes to 0.09, and becomes equal to the volume of the order that was used to open the position.

**Comment by rapcmia** [comment]
Severity: P2
Bounty: 50,000 HBOT
Rationale: 
- The volume of sent order does not match the position displayed 
- When a opened a position, it takes couple of second to display the correct amount

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by nikspz** [comment]
@yancong001 You're assigned, please give update us here with a progress

**Comment by yancong001** [comment]
fixed, here https://github.com/hummingbot/hummingbot/pull/6578

**Comment by nikspz** [comment]
hi @Zzuummzz could you please provide your script/ part of the script to test the fix #6578 ?

**Comment by nikspz** [comment]
Reproduced on development:
Steps:
Set up pureMM using BCH-USDT and order amount 0.05 BCH
bot placed order to OPEN 
after order to OPEN get filled

Actual:
Bot placing first order with the amount of 5 BCH instead of 0.05 BCH 
After orders refreshed bot place order to CLOSE using 0.05 BCH and after refresh as well

![image](https://github.com/hummingbot/hummingbot/assets/83953535/cf132333-7552-42c1-a80a-72c800831267)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/967aeac5-bb1c-40d1-9007-775ef6e7d516)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/68afdc47-4ae6-4e27-a45d-15a401ebd81a)

**Comment by nikspz** [comment]
Fix provided to latest development, will be available in 1.20.0 Release

**Comment by nikspz** [comment]
Closing this bounty as paid. Fix available on latest development and 1.20.0 Release
