### ISSUE TITLE
Binance - The Request Weights rate limit needs to be updated

### ISSUE THREAD

**Issue by supervik** [hummingbot/hummingbot#6569]
### Describe the bug

Binance recently made a significant rate limit update for their spot API .

The REQUEST_WEIGHT rate limit for SPOT API has been adjusted to 6,000 every minute.
The RAW_REQUESTS for SPOT API has been adjusted to 61,000 every 5 minutes
The weights to the following requests for the SPOT API have been adjusted.
....
View more on Binance changelog from 2023-08-25
https://binance-docs.github.io/apidocs/spot/en/#change-log

### Steps to reproduce

1. Open Binance API changelog from 2023-08-25
2. Compare previous request weight with the new request weight

### Release version

1.19

### Type of installation

Source

**Comment by nikspz** [comment]
Severity: P3
Bounty: 10,000 HBOT
Rationale:
- Related to the gold tier exchange connector issue
- The Request Weights for Binance needs to be updated
- The RAW_REQUESTS for SPOT API has been adjusted to 61,000 every 5 minutes.
- The weights to the [following requests](https://binance-docs.github.io/apidocs/spot/en/#change-log) for the SPOT API have been adjusted.

**Comment by isreallee82** [comment]
61000 or 6100 @nikspz

**Comment by isreallee82** [comment]
working on this can I create a pr @nikspz

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/6596

**Comment by cardosofede** [comment]
closing this issue since it's solved

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @isreallee82 . The fix has been deployed on development branch and hummingbot version 1.21.
