### ISSUE TITLE
Gateway - amm_trade function do not work correctly with small prices.

### ISSUE THREAD

**Issue by jellebuth** [hummingbot/hummingbot#6646]
### Describe the bug

Whenever the order price on Gateway's "amm_trade" function in "hummingbot/core/gateway/gateway_http_client.py" is too small. e.g. 
![image](https://github.com/hummingbot/hummingbot/assets/83583507/7759e8cf-c1c7-42a8-bf94-f3f68135b7f6)

It was unable to create an order due to the following issue:

Error: {'message': 'The limitPrice param may be null or a string of a float or integer number.', 'httpErrorCode': 404, 'errorCode': -1, 'stack': 'Error: The limitPrice param may be null or a string of a float or integer number.\n    at throwIfErrorsExist (/Users/jellebuth/Downloads/gateway/dist/src/services/validators.js:38:15)\n    at /Users/jellebuth/Downloads/gateway/dist/src/services/validators.js:103:40\n    at /Users/jellebuth/Downloads/gateway/dist/src/amm/amm.routes.js:25:51\n    at Generator.next (<anonymous>)\n    at /Users/jellebuth/Downloads/gateway/dist/src/amm/amm.routes.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/jellebuth/Downloads/gateway/dist/src/amm/amm.routes.js:4:12)\n    at /Users/jellebuth/Downloads/gateway/dist/src/amm/amm.routes.js:24:85\n    at /Users/jellebuth/Downloads/gateway/dist/src/services/error-handler.js:37:28\n    at Layer.handle [as handle_request] (/Users/jellebuth/Downloads/gateway/node_modules/express/lib/router/layer.js:95:5)'} 

I believe it is because of the formatting as when I changed the code to the following:
![image](https://github.com/hummingbot/hummingbot/assets/83583507/92aeccd6-805c-4430-b8dd-8c5ea569122b)

The issue was not present anymore.

### Steps to reproduce

1.  Run AMM Arb on PCS to MEXC on pair ARV-WBNB (PCT) to ARV_USDT (MEXC)
2. Set Min_profitability to -1 to allow for a trade
3. The trade fails as the price input in the "place order" function is formatted as 1.713321E-7 rather than 0.000000017713321

This can be reproduced by:
1.  Run AMM Arb on PCS to MEXC on pair ARV-WBNB (PCT) to ARV_USDT (MEXC)
2. Set Min_profitability to -1 to allow for a trade
3. Logging the AMM_order function's price variable input. This should be formatted as 1.713321E-7. Gateway does not seem to be able to handle the formatting as it is expecting a formatting like: 0.000000017713321.

### Release version

Custom Version

### Type of installation

Source

**Comment by nikspz** [comment]
Description: Fix gateway small order price issue described above
Acceptance criteria: gateway Instance work, QA tests passed, PR including tests, etc
Bounty: P2
Bounty Amount: 50,000 HBOT
Status: OPEN

**Comment by nikspz** [comment]
hi @jellebuth do you want to take this bounty and create the PR for it?

**Comment by nikspz** [comment]
@jellebuth Could you answer if you want to take this bounty?

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/6699

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/6706

**Comment by nikspz** [comment]
@HarjobandeepSingh do you want to be assigned for this bounty?

**Comment by HarjobandeepSingh** [comment]
@nikspz i made a pull request

**Comment by nikspz** [comment]
@HarjobandeepSingh Sure I saw the PR, next time please leave a comment on the bounty that you want to be assigned / work on this bounty (before submitting the PR)

**Comment by isreallee82** [comment]
is this bounty still open @nikspz?

**Comment by nikspz** [comment]
> is this bounty still open @nikspz?

Yes opened now

**Comment by isreallee82** [comment]
alright I will create a pr for it @nikspz

**Comment by nikspz** [comment]
@isreallee82 okay, goal of the bounty is that the function described above should work correctly with small prices.

**Comment by isreallee82** [comment]
okay I see that @nikspz I will try run test if proposed solution works as expected

**Comment by nikspz** [comment]
@jellebuth Is it affects other pairs you re using?

**Comment by isreallee82** [comment]
pr #6719

**Comment by jellebuth** [comment]
@nikspz no, but I believe it is probably applicable to other pairs with a very small price. We have integrated it ourselves already and seems to be working very well, the proposed solution in @isreallee82 PR seems to be correct.

**Comment by HarjobandeepSingh** [comment]
fix/ #6720

**Comment by isreallee82** [comment]
@HarjobandeepSingh I understand you new here but you should try read the guidelines to contributions on hummingbot 
here: https://hummingbot.org/bounties/#bounties-board

**Comment by HarjobandeepSingh** [comment]
> @HarjobandeepSingh I understand you new here but you should try read the guidelines to contributions on hummingbot 
> here: https://hummingbot.org/bounties/#bounties-board

I am sorry again i think i should take time first learn guidelines 
SORRY

**Comment by isreallee82** [comment]
its alright @HarjobandeepSingh
