### ISSUE TITLE
Feature Request : Improvements on funding payment info

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6654]
### Feature Suggestion

- Look for improvements on how to collect funding payment info for perpetual connectors 
- Fix ongoing issues reported related to funding payment in binance perpetuals 

### Impact

the funding payment info for binance perpetuals has been reportedly seeing unexpected errors 

- https://github.com/hummingbot/hummingbot/issues/6653
- https://github.com/hummingbot/hummingbot/issues/6602
- https://github.com/hummingbot/hummingbot/issues/6574

**Comment by nikspz** [comment]
for the mention here
https://github.com/hummingbot/hummingbot/pull/6749

**Comment by nikspz** [comment]
Upon checking on longterm run, issues not reproduced / bot was able to recover
