### ISSUE TITLE
Content - Dexalot-Hummingbot Integration Guide

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6660]
### Description

Create a comprehensive guide on integrating Hummingbot bots with Dexalot, covering every step from initial setup to running a market-making bot that uses Dexalot's DIP Program and the Multiverse Reward Program.

**Guide Outline:**
1. **Setting Up a Wallet on Dexalot:**
   - Provide detailed instructions on creating and setting up a wallet on the Dexalot platform.

2. **Installing Hummingbot and Gateway:**
   - Guide users through the installation process using Docker Compose on Windows WSL2, Linux, Mac, or installing from source.

3. **Connecting to Dexalot via Gateway:**
   - Explain the steps to establish a connection between Hummingbot and Dexalot using the Gateway.

4. **Setting Up a Simple Market Making Bot:**
   - Instruct users on configuring a basic market-making bot within the Hummingbot framework.

5. **Utilizing DIP and Multiverse Programs:**
   - Provide insights on optimizing the market-making bot to benefit from Dexalot's DIP Program and the Multiverse Reward Program.

**References:**
- Dexalot-Hummingbot Stepping Stones Part I: [Link](https://medium.com/dexalot/dexalot-hummingbot-stepping-stones-part-i-a47f60dd6228)
- Dexalot Hummingbot Stepping Stones Part II: [Link](https://medium.com/dexalot/dexalot-hummingbot-stepping-stones-part-ii-623cefd8cca1)
- Dexalot Hummingbot Stepping Stones Part III: [Link](https://medium.com/dexalot/dexalot-hummingbot-stepping-stones-part-iii-740db136c588)
- Dexalot Hummingbot Stepping Stones Part IV: [Link](https://medium.com/dexalot/dexalot-hummingbot-stepping-stones-part-iv-bd907958cc45)
- Dexalot Incentive Program: [Link](https://medium.com/dexalot/dexalot-incentive-program-c9e2844b0b18)
- Dexalot Multiverse: [Link](https://medium.com/dexalot/dexalot-multiverse-c4887aedf301)

**Note:** Ensure the guide is well-structured, beginner-friendly, and includes screenshots for clarity.

### Bounty

- Sponsor: Hummingbot Foundation
- Bounty amount: 100k HBOT
- Developer portion: 100k HBOT

**Comment by cgambit** [comment]
Hi, I want to work on this bounty with following advantages:
1. Using Dexalot for 8-9 months+ since dMiner launch with it
2. Familiar with Incentives and Rewards
3. Can share tips for users to gain more
4. Will include video tutorial

**Comment by nikspz** [comment]
> Hi, I want to work on this bounty with following advantages:
> 
> 1. Using Dexalot for 8-9 months+ since dMiner launch with it
> 2. Familiar with Incentives and Rewards
> 3. Can share tips for users to gain more
> 4. Will include video tutorial

Okay, I think it's reasonable to assign to @cgambit since he mentioned his experience and want to include Incentives and Rewards, tips and video tutorial 

Assigned to @cgambit , please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by cgambit** [comment]
@nikspz Thank you for assigning the bounty. Prefer to get 100k HBOT. Will give update on progress early next week.

**Comment by nikspz** [comment]
> @nikspz Thank you for assigning the bounty. Prefer to get 100k HBOT. Will give update on progress early next week.

Got it, Thank you for the answer

**Comment by cgambit** [comment]
Update: Still on-progress with guide. Encountered some issues and missteps on Gateway setup. Now resolved and continuing...

**Comment by cgambit** [comment]
@nikspz  Here is link of Dexalot-Hummingbot Integration Guide:
https://outstanding-helicona-0c5.notion.site/Dexalot-Hummingbot-Integration-Guide-8aef00808e8b466eaac6d80b1bb36010

Will appreciate your feedback, and suggestions. I don't mind also if content will be edited to make it better.

Will need more time for video as still planning its content such that will not be a duplicate of the written guide.

**Comment by nikspz** [comment]
@cgambit Could you Please submit a PR into hummingbot-site repo?

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot-site/pull/351

**Comment by cgambit** [comment]
Update: Will submit video within 1-2 days. Now, editing/trimming/re-recording some parts to make it more understandable.

**Comment by cgambit** [comment]
Here is link of uploaded video: https://www.youtube.com/watch?v=PC3BPRwjgRI

**Comment by cgambit** [comment]
Submitted.

**Comment by nikspz** [comment]
Available in 
https://hummingbot.org/academy-content/using-dexalot-with-hummingbot/
https://www.youtube.com/watch?v=PC3BPRwjgRI

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @cgambit .
