### ISSUE TITLE
Content - Polkadex-Hummingbot Integration Guide

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6661]
### Description

We are seeking a comprehensive integration guide for using Hummingbot with Polkadex. This guide aims to provide users with clear, step-by-step instructions on integrating Hummingbot with Polkadex, covering essential tasks for seamless interaction. The guide should cover all the steps including the following key components:

1. **How to create a Polkadex wallet:**
   - Installation of the Polkadex extension.
   - Step-by-step guidance on creating a Polkadex wallet.
   - Emphasis on keeping a copy of the mnemonic seed in a secure location.

2. **Register Funding Account:**
   - Explanation of how accounts created on the Polkadot extension serve as funding accounts for the exchange.
   - User selection of the desired account for funding.
   - Guidance on making the selected account usable in the Polkadex Orderbook.

3. **Import Trading Account:**
   - Steps to generate the trading account seed by logging into [https://orderbook-internal.polkadex.trade/](https://orderbook-internal.polkadex.trade/).
   - Creating a new trading account with details on selecting the funding account.
   - Retrieving the mnemonic passphrase for the trading account.
   - Importing the trading account on [https://orderbook.polkadex.trade/](https://orderbook.polkadex.trade/) using the mnemonic phrase.

4. **Add Balances:**
   - Navigating to the 'balances' tab on Polkadex.
   - Instructions on depositing available tokens on the exchange.

   For additional details, users are directed to refer to [https://docs.polkadex.trade/polkadexOrderbookFAQHowToTransferDeposits](https://docs.polkadex.trade/polkadexOrderbookFAQHowToTransferDeposits).

**Reference URL:** [Polkadex Setup Guide](https://www.notion.so/hummingbot-foundation/Polkadex-Setup-wallet-9a641b2632ec45aeb1f99c46b93bb81f)

**Note:** The guide should be beginner-friendly, with clear visuals and explanations at each step.

### Bounty

- Sponsor: Hummingbot Foundation
- Bounty amount: 100k HBOT
- Developer portion: 100k HBOT

**Comment by rapcmia** [comment]
ill take the bounty

**Comment by nikspz** [comment]
Assigned to @rapcmia, please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by nikspz** [comment]
Closing this as paid, available in https://hummingbot.org/docs/ and https://hummingbot.org/academy-content/using-polkadex-with-hummingbot/

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent. The has been deployed on hummingbot docs
