### ISSUE TITLE
Mexc - Failed to cancel order <order id> appears when partial fills happened

### ISSUE THREAD

**Issue by leetjoy** [hummingbot/hummingbot#6667]
### Describe the bug

There is an issue observed with MEXC connector, if the order was partially filled and Humming bot canceled it - then it cannot fetch status update on this order.

`Failed to cancel order <order id>` error appears in log
`Error fetching status update for the lost order ... Partially Cancelled`

I would appreciate if anyone can fix it.
MEXC is growing exchange and connector deserves to be GOLD :)

### Steps to reproduce

1. connect to MEXC
2. using `pure_market_making` create some orders on any paid
3. wait when one of order will be partially filled and bot will attempt to cancel it
4. -> here comes the error

### Release version

1.21.0

### Type of installation

Docker

### Attach required files

[logs_MM_JOY_test.log](https://github.com/hummingbot/hummingbot/files/13417069/logs_MM_JOY_test.log)

**Comment by cardosofede** [comment]
@rapcmia @fengtality @nikspz I talked with @leetjoy and he wants to fund this bounty. I think that has to be considered as P2 and the solution should include:
- cancel order method --> Review how the order is processed when sending the cancelation. (specially when having partial fills)
- evaluate the solution proposed in this PR https://github.com/hummingbot/hummingbot/pull/6584/files for the methods:
_is_order_not_found_during_status_update_error
_is_order_not_found_during_cancelation_error

Once the connector solution is ready we have to validate it by running a bot for > 1 day without issues

**Comment by nikspz** [comment]
https://hummingbot.org/bounties/sponsors/
Okay, then to validate this as P2 Bounty (50k HBOT) it should be funded with 55k HBOT (50k +10%) or 133USDC (111 USDC +20%) using these wallets:
https://hummingbot.org/bounties/sponsors/#foundation-bounty-wallets

**Comment by leetjoy** [comment]
@nikspz can I fund this bounty by sending USDC from CEX?

**Comment by nikspz** [comment]
@leetjoy For `BEP20`, 0xE517b826a26B439eCE92f3220628eC007049d915 can be used for USDC. 
![image](https://github.com/hummingbot/hummingbot/assets/83953535/603d5330-104b-4e8d-8056-8c7e6aa012f3)

**Comment by nikspz** [comment]
hi @leetjoy Are you still willing to fund the bounty?

**Comment by leetjoy** [comment]
> hi @leetjoy Are you still willing to fund the bounty?

bounty funded
tx: [0xf3868f71b20055aadc03a1c136f7f9c670b3b38367fe513091aff1a9b969f14e](https://bscscan.com/tx/0xf3868f71b20055aadc03a1c136f7f9c670b3b38367fe513091aff1a9b969f14e)

**Comment by nikspz** [comment]
Severity: P2
Bounty: 111 USDC (Developer portion)
Rationale:
- Related to the MEXC exchange connector issue
- MEXC connector fails to fetch status updates for partially filled and canceled orders, resulting in log errors
- Please read issue description as the reference

**Comment by nikspz** [comment]
Bounty Opened for developers who want to be assigned

**Comment by cardosofede** [comment]
@yancong001 this might be of your interest

**Comment by yancong001** [comment]
ok, i will fix this bug

**Comment by yancong001** [comment]
here https://github.com/hummingbot/hummingbot/pull/6691

**Comment by rapcmia** [comment]
Fix has been deployed to release version 1.23.0

**Comment by leetjoy** [comment]
thank you guys, will test this out.

**Comment by leetjoy** [comment]
@nikspz 

how to update to version 1.23?

**Comment by nikspz** [comment]
> @nikspz
> 
> how to update to version 1.23?

https://hummingbot.org/installation/post-installation/#updating-hummingbot
