### ISSUE TITLE
Bounty Request: Change name to `amm_v3_lp` strategy

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6710]
## Why
* Now that DEX connectors like PancakeSwapV3 and Osmosis support adding and removing liquidity ranges, the name of the strategy used to test them should be exchange-agnostic. 

## What
* Change the name of the `uniswap_v3_lp` strategy to `amm_v3_lp` everywhere in the Hummingbot client and documentation site 
* Afterwards, users should be able to run the `amm_v3_lp` strategy,
* All unit tests should related to the strategy should be changed
* There should be no references to the UniswapV3 strategy in the codebase

### Bounty

- Sponsor: Hummingbot Foundation
- Bounty amount: 10,000 HBOT
- Developer portion: 100%

**Comment by HarjobandeepSingh** [comment]
refactor/ #6711

**Comment by nikspz** [comment]
changed in latest development and v1.23.0 release, pending payment

**Comment by HarjobandeepSingh** [comment]
> changed in latest development and v1.23.0 release. 
> Thank you for the contribution, will post update about payment here later (first half of January)

Ok

**Comment by carlitogetaladajr** [comment]
@HarjobandeepSingh Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA

**Comment by HarjobandeepSingh** [comment]
> @HarjobandeepSingh Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA
> 

Again ?

**Comment by HarjobandeepSingh** [comment]
> @HarjobandeepSingh Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA

Done

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @HarjobandeepSingh . The fix has been deployed on development branch and hummingbot version 1.23.0.
