### ISSUE TITLE
Fixed Grid - endless loop of unfulfilled order

### ISSUE THREAD

**Issue by masimo12358** [hummingbot/hummingbot#6722]
### Describe the bug

My fixed grid bot closed due to PC upgrade. When I relaunched it - it's trying to send rebalance order that can't be fulfilled by the exchange, thus stuck in an endless loop and not progressing to send the grid orders:

Hummingbot screen attached.
<img width="1244" alt="Monosnap docker attach hummingbot-3 2023-12-17 10-55-10(1)" src="https://github.com/hummingbot/hummingbot/assets/110984416/3883c64f-eae9-45a4-94b3-bb09d2014828">

### Steps to reproduce

1. 
2. 
3. 

### Release version

dev-1.18.0

### Type of installation

Docker

**Comment by nikspz** [comment]
fixed_grid strategy was removed with https://github.com/hummingbot/hummingbot/pull/6065

please check new grid strike strategy using dashboard

https://hummingbot.org/docs/#ways-to-use-hummingbot
https://github.com/hummingbot/dashboard
https://github.com/hummingbot/deploy
