### ISSUE TITLE
Update Kraken connector

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6751]
### Rationale
- Due to restrictions on Binance.US and other exchanges, Kraken is currently one of the only crypto exchanges available to US residents
- Its lower fees compared to Coinbase make it more attractive for US-based Hummingbot users
- The current Kraken connector was built originally in early 2020 and has not been updated
- Updating the Kraken connector and allowing it to be used on Hummingbot V2 strategies should increase adoption and usage among US-based users

### Description of Work
- Update the spot Kraken connector to the latest spot connector standards
- Add support for spot Kraken candles feed using their OHLCV API - see https://docs.kraken.com/rest/#tag/Market-Data/operation/getOHLCData

### Bounty

- Sponsor: Hummingbot foundation
- Bounty amount: 600,000 HBOT tokens
- Snapshot: https://snapshot.org/#/hbot-ip.eth/proposal/0x021b7bd4b433182496c0288d8ed83001ddf0686a1f1e482f4dbf7ea972c0faf5

**Comment by tomasgaudino** [comment]
Hi there! I'd like to take this bounty please

**Comment by yancong001** [comment]
I would like to be assigned this ticket

**Comment by rapcmia** [comment]
Assigned to @yancong001  , please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution! 🙇🏼

**Comment by yancong001** [comment]
got it

**Comment by nikspz** [comment]
hi @yancong001 could you please give update on this bounty here?

**Comment by hidefsooner** [comment]
I would like an update too.

**Comment by yancong001** [comment]
> hi @yancong001 could you please give update on this bounty here?

I'm about a third of the way through, and I'll go ahead and finish and submit a pr

**Comment by AzothZephyr** [comment]
is insuring the kraken docs are up to date in scope for this? wanted to drop this issue i just created if so. i will try to loop back later, but it might be wise to give the docs a look to address any changes between when the connector was last updated and completion of this bounty.

https://github.com/hummingbot/hummingbot-site/issues/277

**Comment by nikspz** [comment]
hi @yancong001 Could you please post updates on this bounty here? Could you please submit a draft PR and give info about status?

**Comment by yancong001** [comment]
No problem, I will submit a pr later

**Comment by yancong001** [comment]
I've just submitted PR https://github.com/hummingbot/hummingbot/pull/6817 for krake candles feed.

Next week I'll give updates about the connector

**Comment by yancong001** [comment]
Update the progress of kraken, the remaining uniitest is still unfinished.
here, https://github.com/hummingbot/hummingbot/pull/6840

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @yancong001 . The fix has been deployed on latest development branch and hummingbot version 1.26.0.
