### ISSUE TITLE
Too many requests when trying to connect ByBit

### ISSUE THREAD

**Issue by markwindsorr** [hummingbot/hummingbot#6756]
### Describe the bug

429 error when trying doing `connect bybit`

### Steps to reproduce

1. `connect bybit`
2. enter api and secret key
3. Error executing request https://api.bybit.com/spot/v1/account. HTTP status is 429

### Release version

1.23.0

### Type of installation

Source

**Comment by rapcmia** [comment]
Bybit connector has not been updated to latest version causing this issues when connecting API keys. Please be advised that a community dev is working on the fix and we are waiting for the PR to be created https://github.com/hummingbot/hummingbot/issues/6585

**Comment by artemkoach** [comment]
Error executing request GET https://api.bybit.com/spot/v1/account. HTTP status is 429. Error:



what are the options for connecting to the baybit?
