### ISSUE TITLE
Bounty: Clean up `gateway balance` command and add allowances

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6769]
### Description (REVISED)

Given the `gateway balance` issue below, I propose the following modifications to this bounty:

1. Change `gateway balance` so that it reports balances for each connector (`exchange_chain_network`), rather than each `chain_network`. It should use the designated wallet for that connector that the `gateway connect` command lists.

2. The output of this command should be a **table of balances and allowances** for each connector. In addition to the native token, it should also show any tokens that the user adds via `gateway connector-tokens`.

```
Connector: uniswap_ethereum_mainnet
Wallet: 0x...

Symbol Balance Allowancce
ETH
HBOT 
WETH
```

3. Accept an optional `connector` parameter in the form of `exchange_chain_network`. In that case, the command only reports balances and allowances for that connector.

This would remove the need for a separate `gateway allowance` command.

### Bounty

- Sponsor: Hummingbot Foundation
- Bounty amount: 50,000 HBOT
- Developer portion: 100%
- Allocation: Chain - Ethereum

**Comment by elijahsnoz** [comment]
I will take this

**Comment by isreallee82** [comment]
I will take this

**Comment by fengtality** [comment]
Hey @isreallee82 - I realized that we should pause and rethink these changes to `gateway balance` and wanted to let you know before you do more work on this PR and the new allowances bounty. The reason is that I didn't consider the case where users add different wallets for different connectors on the same network. 

<img width="531" alt="Screen Shot 2024-01-12 at 5 21 41 AM" src="https://github.com/hummingbot/hummingbot/assets/1795030/bcf1be18-2577-445b-8016-f2eca763307a">

In this case, `gateway balance` would only show balances for the first connected wallet, and there's no way for users to see balances for the second wallet.

I'll think about this a bit more and address what should be done in this bounty.

**Comment by isreallee82** [comment]
Oh true! Okay @fengtality

**Comment by fengtality** [comment]
@isreallee82 I revised the description to describe what I think should be done to clean this up.

**Comment by isreallee82** [comment]
alright noted @fengtality noted

**Comment by isreallee82** [comment]
pr #6786 @nikspz @fengtality

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @isreallee82. The fix has been deployed on development branch and hummingbot version 1.27.0
