### ISSUE TITLE
Add OKX Perpetual Connector

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6775]
### Description

Rationale:
OKX, a prominent crypto exchange, has a fee-sharing agreement with the Hummingbot Foundation. However, the absence of a perpetual connector limits Hummingbot users from fully utilizing strategies and affects the Volumes dashboard.

Description of Work:

1. Implement a perpetual connector for OKX following the 2.1 connector standard.
2. Incorporate support for candles feed utilizing the OKX Historical Data API.
3. Ensure seamless integration with the current Hummingbot architecture.

Requirements:
- In-depth knowledge of Hummingbot architecture and connectors.
- Expertise in developing cryptocurrency exchange connectors, particularly perpetual connectors.
- Familiarity with the OKX Historical Data API.
- Submission of well-documented and clean code.

Deadline:
The developer is expected to complete the task within a reasonable timeframe agreed upon with the Hummingbot Foundation.

Your contribution will enhance the usability of Hummingbot on OKX and contribute to the growth of the Hummingbot ecosystem.

### Bounty

Bounty:
A bounty reward of 700,000 HBOT tokens is allocated for the successful completion of this task.

Developer:
The developer for this task will be assigned by the Hummingbot Foundation.

**Comment by nikspz** [comment]
Assigned to @tomasgaudino, please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by tomasgaudino** [comment]
got it, thank you guys!

**Comment by tomasgaudino** [comment]
I've just submitted PR https://github.com/hummingbot/hummingbot/pull/6791 for okx perpetuals candles feed.

Next week I'll give updates about the connector :muscle:

**Comment by tomasgaudino** [comment]
hi there! sure, here it goes:

- Candles Feed: ready feed and tests, waiting for definitions mentioned in https://github.com/hummingbot/hummingbot/pull/6791
- Connector:
    - Constants: 100%
    - Web Utils: 90% code and tests
    - Utils: 100% code, missing tests
    - Auth: 100% code, missing tests
    - API Order Book Data Source: Current development
    - User Stream Data Source: not started
    - Derivative: not started

The scope for this week is to finish with all code, and if I'm able to do the tests it would be great. Expecting to start testing live performance of connector for next week, and submitting final PR for first march days

**Comment by tomasgaudino** [comment]
Updates:

 - Candles Feed: https://github.com/hummingbot/hummingbot/pull/6791 waiting for new review
 - Connector:
     - Constants: 100%
     - Auth: 100% code | 100% coverage
     - Web Utils: 100% code | 66% coverage
     - Utils: 100% code | missing tests
     - API Order Book Data Source: 100% code | 59% coverage
     - User Stream Data Source: 100% code | missing tests
     - Derivative: Current development

There is no much remaining base code, but still need to run it alive (surely will have several breaks) and improve tests

**Comment by tomasgaudino** [comment]
Updates:

 - Candles Feed: https://github.com/hummingbot/hummingbot/pull/6791 waiting for new review
 - Connector:
     - Constants: 100%
     - Auth: 100% code | 100% coverage
     - Web Utils: 100% code | 66% coverage
     - Utils: 100% code | missing tests
     - API Order Book Data Source: 100% code | 59% coverage
     - User Stream Data Source: 100% code | missing tests
     - Derivative: Current development

There is no much remaining base code, but still need to improve tests and start debugging running different strategies. Deadline keeps to first half of february

**Comment by tomasgaudino** [comment]
Updates:

 - Candles Feed: Already merged on development ✅ 
 - Connector: Base code is ready, started debugging and fixing. 
      - This week the target is to make tests for market connection and verify that every endpoint is fetching the correct data. 
      - Next week I'll finish checking order management/testing and start running strategies to make final adjustments

Deadline keeps to first half of february

**Comment by tomasgaudino** [comment]
Updates:

 - Connector:
     - Constants: 100% :heavy_check_mark: 
     - Auth: 100% code | 93.65% coverage :heavy_check_mark:
     - Web Utils: 100% code | 97.09% coverage :heavy_check_mark:
     - Utils: 100% code | 90.91% coverage :heavy_check_mark:
     - API Order Book Data Source: 100% code | 97.49% coverage :heavy_check_mark:
     - User Stream Data Source: 100% code | 88.46% coverage :heavy_check_mark:
     - Derivative: 100% code | 65.39% coverage :clock1: 

If everything goes as planned, this week I'll finish testing derivative file and pass all of QA steps defined in https://hummingbot-foundation.notion.site/Perp-Connector-v2-1-57d8391eb54c40929f77067355fd551e

So far, I've created a perpetual market making strategy and it worked for > 1 hour without logging any error:
![image](https://github.com/hummingbot/hummingbot/assets/69804854/e664277c-42b4-48d6-ac30-25cd904fdbed)
![image](https://github.com/hummingbot/hummingbot/assets/69804854/99240f38-e077-46d2-8a79-fededc74de7b)

Hopefully, on thursday night / friday morning I'll be opening a PR

**Comment by tomasgaudino** [comment]
Updates:

 - Connector:
     - Constants: 100% :heavy_check_mark: 
     - Auth: 100% code | 93.65% coverage :heavy_check_mark:
     - Web Utils: 100% code | 97.09% coverage :heavy_check_mark:
     - Utils: 100% code | 90.91% coverage :heavy_check_mark:
     - API Order Book Data Source: 100% code | 97.49% coverage :heavy_check_mark:
     - User Stream Data Source: 100% code | 88.46% coverage :heavy_check_mark:
     - Derivative: 100% code | 65.39% coverage :clock1: 

If everything goes as planned, this week I'll finish testing derivative file and pass all of QA steps defined in https://hummingbot-foundation.notion.site/Perp-Connector-v2-1-57d8391eb54c40929f77067355fd551e

So far, I've created a perpetual market making strategy and it worked for > 1 hour without logging any error:

![Screenshot from 2024-02-12 22-04-20](https://github.com/hummingbot/hummingbot/assets/69804854/de042287-f305-43ef-82db-09fbdbb990e4)
![Screenshot from 2024-02-12 22-36-24](https://github.com/hummingbot/hummingbot/assets/69804854/69298190-fef0-4482-9658-c0292ca4ea0e)


Hopefully, on thursday night / friday morning I'll be opening a PR

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @tomasgaudino. The connector has been deployed on development branch and will be available in hummingbot version 1.26.0

**Comment by tomasgaudino** [comment]
I'm feeling really happy about this!

From this point, you can count on me as the connector's mantainer for solving issues if there are.

Thank you guys! See you in the next bounty :rocket:

**Comment by nikspz** [comment]
Congrats Tomas 🎉
