### ISSUE TITLE
Huobi- Change the name of the huobi connector to the new (htx)

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6788]
### Description

Huobi has rebranded to HTX (https://www.htx.com/en-us/). 
The Hummingbot connector for `huobi` needs to be updated to `htx` to reflect this rebranding.

Description:
1. Update the name of the Hummingbot connector from "huobi" to "htx" throughout the codebase.
2. Ensure that the updated connector retains seamless functionality using Hummingbot.

### Bounty

- Sponsor: Hummingbot Foundation
- Bounty amount: 10K HBOT
- Developer portion: 10K HBOT

**Comment by nikspz** [comment]
hey @HarjobandeepSingh I don't think we could assign this to you, based on our previous experience

**Comment by HarjobandeepSingh** [comment]
@nikspz ok

**Comment by nikspz** [comment]
@blagodar1 

Assigned to @blagodar1, please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by nikspz** [comment]
@blagodar1 Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @blagodar1 . The fix has been deployed on development branch and hummingbot version 1.25.0
