### ISSUE TITLE
Continuously place short and long positions

### ISSUE THREAD

**Issue by HESSEBO** [hummingbot/hummingbot#6792]
### Feature Suggestion

From what I'm seeing when running HB perpetual strategy on future markets, hummingbot places Long and short positions and if one of them is filled it just keeps on waiting until one of the directions is closed. Can hummingbot keeps on placing trades on the other directions when it's closed rather than just keeps on waiting for the open position to close.

### Impact

That should reduce loses if the open positions is heading to stoplose while on the other side we are making profit too if the price keeps on dropping.

**Comment by nikspz** [comment]
@HESSEBO Please add short explanation on what script you're using you suggest to modify. Attach logs, script file and additional context https://hummingbot.org/client/log-files/

Also you could try to modify the script yourself / learn the basics on botcamp https://botcamp.hummingbot.org/

**Comment by nikspz** [comment]
Closed since no updates provided
