### ISSUE TITLE
Hyperliquid - Unable to connect to Vault account

### ISSUE THREAD

**Issue by carlitogetaladajr** [hummingbot/hummingbot#6805]
### Describe the bug

Created a Vault in Hyperliquid and deposited 100 USDC. 
Connected Client to hyperliquid_perpetual. 
When using Balance command, it returns the metamask balance instead of the Vault balance.
![Screenshot 2024-01-25_5](https://github.com/hummingbot/hummingbot/assets/97610386/fe305398-1137-4144-93f7-a585abb748e0)

### Steps to reproduce

1. Add `hyperliquid_perpetual`
2. Use `balance ` command and check the balance value vs vault balance

### Release version

dev-1.24.0

### Type of installation

Docker

**Comment by rapcmia** [comment]
To connect Vault account
- Access the vault and copy the address on the link 
- Connect `hyperliquid_perpetual` and use the vault address then wallet pkey
- Run balance command
