### ISSUE TITLE
Hyperliquid - Unable to use Vault for trade

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6815]
### Describe the bug

When setting up vault account on hyperliquid, connecting the vault address on hummingbot client is ok but when you start a strategy (perpetual market making), the connector by default uses hyperliquid main account

Ran tests on testnet and observed this behavior:
![image](https://github.com/hummingbot/hummingbot/assets/73840223/a9353b2d-ddef-4d68-8e4f-818808711096)
- On this screenshot the connector was already created an order but not visible on the exchange
- Changed the account from vault to main account and observed order and position available
   ![image](https://github.com/hummingbot/hummingbot/assets/73840223/65524fce-a4f4-4ee8-91cc-1e52f6a9e101)
   - Observed there are filled events however not recorded on strategy's CSV file nor history command
   

### Steps to reproduce

1.  Create a vault account on testnet
2. Access the vault account and copy the address on the link
3. Connect to hyperliquid_perpetual_testnet and use vault address then wallet pkey
4. Run balance command to confirm if it displays the vault balance
5. Setup simple perpetual market making then start 
6. Go to hyperliquid exchange > `trade` page then select vault or main account
7. Observe behavior 

### Release version

dev-1.24.0

### Type of installation

Source

### Attach required files

[logs_conf_perpetual_market_making_1.log](https://github.com/hummingbot/hummingbot/files/14067015/logs_conf_perpetual_market_making_1.log)

**Comment by yancong001** [comment]
add new feat for hyperliquid
https://github.com/hummingbot/hummingbot/pull/6832
