### ISSUE TITLE
Run scripts on exchanges ..._perpetual_testnet.

### ISSUE THREAD

**Issue by Atonsun** [hummingbot/hummingbot#6819]
### Describe the bug

Hi! Please tell me what could be the reason, maybe need to make additional settings? I can't run any directional strategy script or DManMultiplePairs script on any exchange..._perpetual_testnet. The built-in standard hummingbot strategies work with exchanges ..._perpetual_testnet.

### Steps to reproduce

1. 
2. 
3. 

### Release version

1.23.0

### Type of installation

Docker

### Attach required files

[logs_directional_strategy_macd_bb.log](https://github.com/hummingbot/hummingbot/files/14088500/logs_directional_strategy_macd_bb.log)
[logs_v2_directional-trading_macd_bb_v1.log](https://github.com/hummingbot/hummingbot/files/14088502/logs_v2_directional-trading_macd_bb_v1.log)
[logs_v2_market-making_dman_v3_multiple_pairs.log](https://github.com/hummingbot/hummingbot/files/14088503/logs_v2_market-making_dman_v3_multiple_pairs.log)

**Comment by rapcmia** [comment]
Please resubmit and follow the template for bug ticket. Closing ticket.
