### ISSUE TITLE
Run scripts on exchanges ..._perpetual_testnet

### ISSUE THREAD

**Issue by Atonsun** [hummingbot/hummingbot#6823]
### Describe the bug

Hi! Please tell me what could be the reason, maybe need to make additional settings? I can't run any directional strategy script or DManMultiplePairs script on any exchange ..._perpetual_testnet. The built-in standard hummingbot strategies work with exchanges ..._perpetual_testnet.

### Steps to reproduce

1. In the scripts "v2_directional-trading_macd_bb_v1", "v2_market-making_dman_v3_multiple_pairs" and "directional_strategy_macd_bb" I specify "binance_perpetual_testnet" in the variables exchange and connector and/or candles_exchange:
![Scrinshot1](https://github.com/hummingbot/hummingbot/assets/109980068/a03ec719-3648-4e42-8465-116c1805486b)
2. I launch one of the specified scripts in the program terminal with the command start --script v2_market-making_dman_v3_multiple_pairs.py:
![Scrinshot](https://github.com/hummingbot/hummingbot/assets/109980068/ff435bbf-b652-4682-8943-cc287518528a)
3. And get error:
![Scrinshot2](https://github.com/hummingbot/hummingbot/assets/109980068/848cdf63-4f5a-4bd1-b370-5ed0b90f6270)

### Release version

1.23.0

### Type of installation

Docker

### Attach required files

[logs_directional_strategy_macd_bb.log](https://github.com/hummingbot/hummingbot/files/14101626/logs_directional_strategy_macd_bb.log)
[logs_v2_directional-trading_macd_bb_v1.log](https://github.com/hummingbot/hummingbot/files/14101627/logs_v2_directional-trading_macd_bb_v1.log)
[logs_v2_market-making_dman_v3_multiple_pairs.log](https://github.com/hummingbot/hummingbot/files/14101628/logs_v2_market-making_dman_v3_multiple_pairs.log)

**Comment by nikspz** [comment]
@Atonsun 
The reason is there's no candles available for binance_perpetual_testnet, you could try to change candles_exchange to binance_perpetual
