### ISSUE TITLE
There is a BUG in stop_loss_condition. After completing several orders, it will not be executed.

### ISSUE THREAD

**Issue by phpmac** [hummingbot/hummingbot#6837]
### Describe the bug

There is a BUG in stop_loss_condition. After completing several orders, it will not be executed.

`hummingbot/smart_components/executors/position_executor/position_executor.py`

```


    def stop_loss_condition(self):
        if self.side == TradeType.BUY:
            return self.close_price <= self.stop_loss_price
        else:
            return self.close_price >= self.stop_loss_price

```

### Steps to reproduce

There is a BUG in stop_loss_condition. After completing several orders, it will not be executed.

`hummingbot/smart_components/executors/position_executor/position_executor.py`

```


    def stop_loss_condition(self):
        if self.side == TradeType.BUY:
            return self.close_price <= self.stop_loss_price
        else:
            return self.close_price >= self.stop_loss_price

```

### Release version

latest

### Type of installation

Source

**Comment by nikspz** [comment]
hi @phpmac Could you please add more details, send your logs and script file here?

**Comment by nikspz** [comment]
Closing issue since no details added
