### ISSUE TITLE
Kraken order book message class is assigning messages with incorrect timestamps

### ISSUE THREAD

**Issue by martinkou** [hummingbot/hummingbot#6850]
### Describe the bug

The current Kraken connector's order book parsing logic is incorrectly applying a 1e-3 factor to timestamps when it's not needed. See the code in [`kraken_order_book.pyx`](https://github.com/hummingbot/hummingbot/blob/master/hummingbot/connector/exchange/kraken/kraken_order_book.pyx)

e.g.
```
    @classmethod
    def diff_message_from_exchange(cls,
                                   msg: Dict[str, any],
                                   timestamp: Optional[float] = None,
                                   metadata: Optional[Dict] = None) -> OrderBookMessage:
        if metadata:
            msg.update(metadata)
        return OrderBookMessage(OrderBookMessageType.DIFF, {
            "trading_pair": msg["trading_pair"].replace("/", ""),
            "update_id": msg["update_id"],
            "bids": msg["bids"],
            "asks": msg["asks"]
        }, timestamp=timestamp * 1e-3)
```

The function seems to expect the input timestamps to be in milliseconds since UNIX epoch - but the corresponding order book data source code (https://github.com/hummingbot/hummingbot/blob/master/hummingbot/connector/exchange/kraken/kraken_api_order_book_data_source.py#L228) is giving it seconds since UNIX epoch.

```
    async def listen_for_order_book_diffs(self, ev_loop: asyncio.BaseEventLoop, output: asyncio.Queue):
        ...
                            if "as" in msg[1] and "bs" in msg[1]:
                                order_book_message: OrderBookMessage = (
                                    KrakenOrderBook.snapshot_ws_message_from_exchange(msg_dict, time.time())
                                )
                            else:
                                order_book_message: OrderBookMessage = KrakenOrderBook.diff_message_from_exchange(
                                    msg_dict, time.time())
                            output.put_nowait(order_book_message)
                    ws.disconnect()
            except asyncio.CancelledError
```

This causes all the timestamps coming from order book messages to be too small and incorrect.

### Steps to reproduce

This requires peeking inside the order book tracker, to view the order book messages being processed. The connector itself doesn't display any outward appearance of something being wrong.

1. Enable the debug console.
2. Create a simple pure market making config on Kraken - remember to enable websocket permissions on the API key on Kraken's side.
3. Start the strategy.
4. Go into the debug console.
5. Look into one of the recent order book messages being processed by order book tracker.

```
>>> kraken = hb.markets["kraken"]
>>> kraken.order_book_tracker._past_diffs_windows["BTC-USD"][0]

OrderBookMessage(type=<OrderBookMessageType.DIFF: 2>, content={'trading_pair': 'BTC-USD', 'update_id': 1708078066.683155, 'bids': [['51829.90000', '0.00000000', '1708078066.683155'], ['49976.70000', '0.00014000', '1707944352.792179', 'r']], 'asks': []}, timestamp=1708078.0667860473)
```

6. Take note of the message timestamp - it's off by a factor of 1e-3.

### Release version

v1.24.0

### Type of installation

Source

**Comment by rapcmia** [comment]
Kraken has been updated to latest connector 2.1 standard
