### ISSUE TITLE
Kraken connector is unable to receive public trade events

### ISSUE THREAD

**Issue by martinkou** [hummingbot/hummingbot#6852]
### Describe the bug

The current public trade event subscription code in https://github.com/hummingbot/hummingbot/blob/cdfc1f8b9a8e8ef1feb52567ba9c1b38bd588e7a/hummingbot/connector/exchange/kraken/kraken_api_order_book_data_source.py looks like this...

```
    async def listen_for_trades(self, ev_loop: asyncio.AbstractEventLoop, output: asyncio.Queue):
        while True:
            try:
                ws_message: str = await self.get_ws_subscription_message("trade")
...

    async def get_ws_subscription_message(self, subscription_type: str):
        trading_pairs: List[str] = []
        for tp in self._trading_pairs:
            trading_pairs.append(convert_to_exchange_trading_pair(tp, '/'))

        ws_message: WSJSONRequest = WSJSONRequest({
            "event": "subscribe",
            "pair": trading_pairs,
            "subscription": {"name": subscription_type, "depth": 1000}})
```

What this means is... when the connector tries to subscribe to trade messages, it'll emit a subscription request that looks like this...

```
{
  "event": "subscribe",
  "pair": ["BTC-USD"],
  "subscription": {"name": "trade", "depth": 1000}
}
```

This is a malformed request according to Kraken's websocket API docs (https://docs.kraken.com/websockets/#message-subscribe). Trade subscriptions should NOT carry a "depth" parameter - because that applies only to order book subscriptions. As a result, the subscription is invalid, and the websocket stream would never receive any trade messages.

### Steps to reproduce

This requires a bit of coding in the debug console to verify that no trade messages are being emitted from Kraken order books.
 
1. Enable debug console.
2. Create a pure market making strategy on a Kraken trading pair that sees a lot of trades, e.g. BTC-USD. 
3. Start the strategy.
4. Go the debug console, and hook up an event listener to order book trade events.

```
>>> from hummingbot.core.event.event_forwarder import EventForwarder
>>> from hummingbot.core.event.events import OrderBookEvent
>>> def f(msg):
...    import logging
...    logging.warning(f"trade: {msg}")
>>> ef = EventForwarder(f)
>>> order_book = hb.markets["kraken"].get_order_book("BTC-USD")
>>> order_book.add_listener(OrderBookEvent.TradeEvent, ef)
```

5. Open Kraken Pro's web UI on a browser, and look at the real time stream of public trades there.
6. Compare the public trades vs. the log output in Hummingbot CLI.
7. Notice the Hummingbot CLI never prints any public trades, while public trades are happening on Kraken.

### Release version

v1.24.0

### Type of installation

Source

**Comment by martinkou** [comment]
There is one more bug after fixing the trade message subscription - the trade message parsing logic in Kraken connector is also wrong.

The price and volume fields from Kraken's websocket API are strings. But on the connector side, neither the `KrakenAPIOrderBookDataSource` class nor the `KrakenOrderBook.trade_message_from_exchange()` functions perform any conversion from string to float. This results in trade messages retaining string types for the trade's price and amounts - which are wrong.

A proper fix should add a `float()` conversion to the price and amount of trades in `KrakenOrderBook.trade_message_from_exchange()`

**Comment by rapcmia** [comment]
Compared to v1.24 and reprodued this issue. Ran the same tests on latest branch (v1.26) with updated kraken connector and it is now displaying public trades on exchange
![image](https://github.com/hummingbot/hummingbot/assets/73840223/6f820076-7a91-4520-832a-1e955a122551)
