### ISSUE TITLE
KuCoin Budget Checker Issue on Buy Orders

### ISSUE THREAD

**Issue by usamike25** [hummingbot/hummingbot#6853]
### Describe the bug

I've encountered an error with the kucoin budget checker, specifically related to executing buy orders. Despite utilizing the budget checker for placing limit orders, I have been consistently receiving "failed to submit" error messages. This problem appears to be exclusive to the buy side on kucoin.

To ensure that this issue was not the result of a race condition, because I operate multiple bots concurrently using the same capital, I have taken the following steps to isolate and reproduce the error:
1. created a Subacount on kucoin and funded it with USDT
2. used the provided demo script
Unfortunately, the attempt to reproduce the error was successful.

Thank you for attending to this matter.

### Steps to reproduce

1. create Subaccaount and fund with some USDT
2. use the provided script to reproduce the error
3. 

### Release version

1.24

### Type of installation

Source

### Attach required files

<img width="1284" alt="Bildschirm­foto 2024-02-17 um 09 22 12" src="https://github.com/hummingbot/hummingbot/assets/99398085/dfb5eebf-8f7d-4684-b3c4-761367567dbe">
[kucoin_buy_test.py.zip](https://github.com/hummingbot/hummingbot/files/14318189/kucoin_buy_test.py.zip)

**Comment by rapcmia** [comment]
Hi @usamike25 we tried to follow the steps to reproduce and seems all ok for v1.25. Can you confirm if this is a ongoing issue? thank you
