### ISSUE TITLE
Unable to start hummingbot client on ubuntu machine

### ISSUE THREAD

**Issue by rahulchhabra177** [hummingbot/hummingbot#6854]
### Describe the bug

I followed the documentation on hummingbot docs and getting the following error in ubuntu 22.04

![image](https://github.com/hummingbot/hummingbot/assets/65856206/9f62f1cc-8e75-46ed-a8e5-845a472eb0a3)

### Steps to reproduce

1. ./install
2. conda activate hummingbot
3. ./compile
4. ./start
After the password, it gives the above error

### Release version

1.24.0

### Type of installation

Source

**Comment by nikspz** [comment]
hi @rahulchhabra177 Could you try below (to clean conda packages)?

```
conda deactivate
```
the you see `(base)`

under hummingbot-1.24.0

```
./clean &&  ./uninstall && conda clean -a
```
when conda clean -a choose y or Yes for all

```
./install && conda activate hummingbot && ./compile
```


If didn't help try clean installation.

All confirmed worked on Ubuntu, so should help

**Comment by alexeyneu** [comment]
yeah confirmed. both app and solution offered doesn't work.  

System:
  Kernel: 5.15.0-101-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy


it runs under docker so i'll rather go with that

**Comment by nikspz** [comment]
@FFFFrankCheung Could you provide some additional info about your machine type?
if you have linux (old versions) could be related. 
Also maybe some environment not installed

**Comment by FFFFrankCheung** [comment]
Hi @nikspz 
My machine is Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-88-generic x86_64)
