### ISSUE TITLE
 STOP_LOSS, STOP_LOSS_LIMIT don't support?

### ISSUE THREAD

**Issue by phpmac** [hummingbot/hummingbot#6861]
### Feature Suggestion

比如现在btc价格60000,我需要设置价格达到55000跟随趋势做空，需要用到STOP_LOSS或STOP_LOSS_LIMIT，
需要跟随趋势，而不是等待价格反应迟钝，达到之后才开空，现在是不是没有实现？？

### Impact

For example, the current Bitcoin price is 60,000. I need to set the price to 55,000 to follow the trend and go short. I need to use STOP_LOSS or STOP_LOSS_LIMIT.
You need to follow the trend instead of waiting for the price to react slowly and then open a short position after reaching it. Is it not realized now? ?

**Comment by fengtality** [comment]
You can already implement these features using the V2 Framework. See https://hummingbot.org/v2-strategies/examples/
