### ISSUE TITLE
MEXC - failed to connect exchange

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6867]
### Describe the bug

MEXC - failed to connect exchange. 
![image](https://github.com/hummingbot/hummingbot/assets/83953535/c727ad46-22c4-4a25-9642-ed6a9ae8e3b1)

### Steps to reproduce

1. Clone and install latest development branch (dev-1.25.0) or master branch (1.24.0)
2. start the Client
3. connect mexc

Actual:
failed to connect Mexc exchange 

### Release version

dev-1.25.0

### Type of installation

Source

### Attach required files

![image](https://github.com/hummingbot/hummingbot/assets/83953535/936aeafa-78f5-45c9-8e43-61325d61728d)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/992a6995-4990-4caf-ac23-2ad3ca8d8cd1)

**Comment by nikspz** [comment]
Link Related 
https://www.mexc.com/support/articles/17827791513387

**Comment by dubisoft-solutions** [comment]
i have the same issue

**Comment by nikspz** [comment]
> any ideas when it will be fixed?

no ETA for now, will give you updates later today

**Comment by nikspz** [comment]
Related topic: https://www.mexc.com/support/articles/17827791513387
Acceptance: [Mexc connector's working](https://hummingbot.org/developers/connectors/test/) according to connector standarts

Bounty: Upgrade MEXC exchange in according to [API Interface Optimizations](https://www.mexc.com/support/articles/17827791513387)

Sponsor: Hummingbot Foundation
Bounty amount: 50k HBOT
Developer portion: 50k HBOT

**Comment by mlguys** [comment]
Tests failed, I'm fixing it now, should be done soon 🚧

**Comment by astra-a** [comment]
> i have the same issue, any ideas when it will be fixed?

Patch:

--- a/hummingbot/core/web_assistant/rest_assistant.py
+++ b/hummingbot/core/web_assistant/rest_assistant.py
@@ -73,8 +73,9 @@ class RESTAssistant:
 
         headers = headers or {}
 
-        local_headers = {
-            "Content-Type": ("application/json" if method != RESTMethod.GET else "application/x-www-form-urlencoded")}
+        # local_headers = {
+        #     "Content-Type": ("application/json" if method != RESTMethod.GET else "application/x-www-form-urlencoded")}
+        local_headers = {"Content-Type": "application/json"}
         local_headers.update(headers)

**Comment by eshark9312** [comment]
> > i have the same issue, any ideas when it will be fixed?
> 
> hummingbot/core/web_assistant/rest_assistant.py @@ -73,8 +73,9 @@ class RESTAssistant:
> 
> ```
>     # local_headers = {
>     #     "Content-Type": ("application/json" if method != RESTMethod.GET else "application/x-www-form-urlencoded")}
>     local_headers = {"Content-Type": "application/json"}
> ```

        if "mexc" in url:
            local_headers = {"Content-Type": "application/json"}

**Comment by kaiqiangh** [comment]
if this PR is merged, would it be effect on the case that deploy hummingbot using docker?

**Comment by nikspz** [comment]
@kaiqiangh hotfix submitted to Development source, ETA of next release (master branch) is next monday

@david-hummingbot Could you please push fix to [dockerhub](https://hub.docker.com/r/hummingbot/hummingbot/tags)? 🙏

**Comment by nikspz** [comment]
FYI: fix available on [dockerhub](https://hub.docker.com/r/hummingbot/hummingbot/tags) as well (under `development` tag)

**Comment by kaiqiangh** [comment]
Thanks! It works now.

**Comment by nikspz** [comment]
The fix was merged to the latest development branch and available now on latest 1.25.0 Release (Source and docker)

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @mlguys . The fix has been deployed on development branch and hummingbot version 1.25.0
