### ISSUE TITLE
使用PositionExecutor停止后一直运行 control_task 的BUG

### ISSUE THREAD

**Issue by phpmac** [hummingbot/hummingbot#6885]
### Describe the bug

1. First, you need to print the log in the control_task to know that the control_task continues to exist and run, and then use PositionExecutor to execute the order, or order leves
2. Then stop, you will find that control_task has been running after stopping everything. If "stop->start->stop->start", it will cause countless control_task to run.

### Steps to reproduce

1. 首先需要在 control_task 打印日志，以知道 control_task 持续存在运行，然后使用 PositionExecutor 执行订单，也可以是 order leves
2. 然后停止，就会发现停止一切后 control_task 一直在运行，如果 "停止->启动->停止->启动"  就会导致无数个 control_task 运行
   

目前最新版本解决方案为 修改 executor_status 为 PositionExecutorStatus.COMPLETED
以往的旧版本解决方案为:
```py


        self.terminate_control_loop()
        self.executor_status = PositionExecutorStatus.COMPLETED

```

### Release version

latest

### Type of installation

Source

**Comment by rapcmia** [comment]
Fix has been deployed to version 2.0.1
