### ISSUE TITLE
Binance Connector: use symbol as trading_pair in _all_trade_updates_for_order method

### ISSUE THREAD

**Issue by astra-a** [hummingbot/hummingbot#6895]
### Describe the bug

In _all_trade_updates_for_order of binance_exchange.py, the symbol is assigned in trading_pair field of TradeUpdate class. Btw, the symbol(BTCUSDT) and trading_pair(BTC-USDT) are different in binance. 

![1709630015759](https://github.com/hummingbot/hummingbot/assets/97663984/2c67171d-8793-4d4a-a83f-883bc34f12be)

### Steps to reproduce

1. It works well right now
2. Some errors will occur if using the trading_pair field in TradeUpdate class to implement some logics in the future.

### Release version

v1.25.0

### Type of installation

Source

**Comment by rapcmia** [comment]
![image](https://github.com/user-attachments/assets/5fed70e3-4180-400f-845a-007413d15da0)
