### ISSUE TITLE
Uniswap - add Base chain/network to the current uniswap connector

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6898]
### Description

Objective: Enhance the current `Uniswap connector to support the Base chain` in addition to Ethereum and Polygon. This upgrade will enable users to interact with Uniswap across multiple chains, expanding accessibility and liquidity.

Requirements:
1. Develop and integrate the necessary functionalities to enable interaction with Uniswap on the Base chain.
2. Ensure compatibility and seamless integration with the existing Uniswap connector architecture.
3. Implement appropriate handling for chain-specific differences and features.
4. Test thoroughly to verify functionality, security, and reliability across all supported chains.

Submission: To submit your proposal, please provide details of your experience, approach to the integration, estimated timeline, and any relevant past projects or contributions. 

Selection Criteria: Submissions will be evaluated based on technical expertise, experience with blockchain development, understanding of the Uniswap protocol, proposed timeline.

Note: The successful completion of this bounty will enhance the utility of the Uniswap connector, fostering interoperability and expanding opportunities for users to access liquidity on different chains.

### Bounty

- Sponsor: HB Foundation  (Uniswap connector pots)
- Bounty amount: 50K HBOT
- Developer portion: 50K HBOT

**Comment by alicercedigital** [comment]
This task have to make it work with uniswap v2 and v3? Or just v3?

**Comment by nikspz** [comment]
> This task have to make it work with uniswap v2 and v3? Or just v3?

to add it to current uniswap connector implementation

**Comment by jake-nyquist** [comment]
Hi all, I authored a small PR to accomplish this https://github.com/hummingbot/gateway/pull/308, and @fengtality suggested that I post it here.

**Comment by nikspz** [comment]
unassigned [jake-nyquist](https://github.com/jake-nyquist) since PR308 is closed

**Comment by nikspz** [comment]
https://github.com/hummingbot/gateway/pull/329

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to fengtality . The fix has been deployed on development branch and hummingbot version 2.0.1.
