### ISSUE TITLE
Uniswap - add Avalanche chain/network to the current uniswap connector

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6899]
### Description

Objective: Enhance the current `Uniswap connector to support the Avalanche chain/network` in addition to Ethereum and Polygon. This upgrade will enable users to interact with Uniswap across multiple chains, expanding accessibility and liquidity.

Requirements:
1. Develop and integrate the necessary functionalities to enable interaction with Uniswap on the Avalanche chain/network.
2. Ensure compatibility and seamless integration with the existing Uniswap connector architecture.
3. Implement appropriate handling for chain-specific differences and features.
4. Test thoroughly to verify functionality, security, and reliability across all supported chains.

Submission: To submit your proposal, please provide details of your experience, approach to the integration, estimated timeline, and any relevant past projects or contributions. 

Selection Criteria: Submissions will be evaluated based on technical expertise, experience with blockchain development, understanding of the Uniswap protocol, proposed timeline.

Note: The successful completion of this bounty will enhance the utility of the Uniswap connector, fostering interoperability and expanding opportunities for users to access liquidity on different chains.

### Bounty

- Sponsor: HB Foundation  (Connector pots)
- Bounty amount: 50K HBOT
- Developer portion: 50K HBOT

**Comment by vic-en** [comment]
You can assign this to me.

**Comment by isreallee82** [comment]
I will like to work on this

**Comment by nikspz** [comment]
Assigned to @isreallee82, please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by isreallee82** [comment]
@nikspz Uniswap's SDK and pools still need updating, and Avalanche's integration with the latest uniswap/swap-router-contracts version gives an error. Additionally, it seems that the link to https://info.uniswap.org/#/avax isn't loading.

![Image](https://github.com/hummingbot/hummingbot/assets/70828114/0a23f7d4-d161-4a19-b460-e633519119ed)

**Comment by isreallee82** [comment]
Update:

Building avalanche network on ethereum chain seem to work fine @nikspz 
will run few tests and create a pr

**Comment by isreallee82** [comment]
pr https://github.com/hummingbot/gateway/pull/316

**Comment by isreallee82** [comment]
pr https://github.com/hummingbot/gateway/pull/316

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @isreallee82 . The fix has been deployed on development branch and hummingbot version 2.0.1.

**Comment by isreallee82** [comment]
Thanks ✅💯
