### ISSUE TITLE
Uniswap - add BNB chain/network (BSC) to the current Uniswap connector

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6900]
### Description

Objective: Enhance the current `Uniswap connector to support the BNB chain/network`(BSC) in addition to Ethereum and Polygon. This upgrade will enable users to interact with Uniswap across multiple chains, expanding accessibility and liquidity.

Requirements:
1. Develop and integrate the necessary functionalities to enable interaction with Uniswap on the BNB chain/network.
2. Ensure compatibility and seamless integration with the existing Uniswap connector architecture.
3. Implement appropriate handling for chain-specific differences and features.
4. Test thoroughly to verify functionality, security, and reliability across all supported chains.

Submission: To submit your proposal, please provide details of your experience, approach to the integration, estimated timeline, and any relevant past projects or contributions. 

Selection Criteria: Submissions will be evaluated based on technical expertise, experience with blockchain development, understanding of the Uniswap protocol, proposed timeline.

Note: The successful completion of this bounty will enhance the utility of the Uniswap connector, fostering interoperability and expanding opportunities for users to access liquidity on different chains.

### Bounty

- Sponsor: HB Foundation (Connector pots)
- Bounty amount: 50K HBOT
- Developer portion: 50K HBOT

**Comment by alexeyneu** [comment]
i can make it

**Comment by nikspz** [comment]
Assigned to @alexeyneu, please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by nikspz** [comment]
hi @alexeyneu Could you please add your updates on this bounty here?

**Comment by nikspz** [comment]
@alexeyneu Do you want to continue work on this bounty, we could re-assign the bounty if no answer / updates be provided

**Comment by nikspz** [comment]
Unassigned @alexeyneu 
This bounty is OPEN for other contributors

**Comment by harjas27** [comment]
@nikspz I would like to work on this one

**Comment by harjas27** [comment]
@nikspz please review -> https://github.com/hummingbot/gateway/pull/326

**Comment by nikspz** [comment]
hi @harjas27, Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA

**Comment by harjas27** [comment]
hi @nikspz,
I have submitted the form

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @harjas27  . The fix has been deployed on development branch and hummingbot version 2.0.1.
