### ISSUE TITLE
Pancakeswap - add Ethereum Mainnet, arbitrum and zkSync for current Pancakeswap connector

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6912]
### Description

Objective: Enhance the current [Pancakeswap](https://pancakeswap.finance/) connector to support the Ethereum Chains (Mainnet)  in addition to BSC. 
This upgrade will enable users to interact with Pancakeswap [across multiple chains](https://defillama.com/dexs/pancakeswap), expanding accessibility and liquidity.

Requirements:
- Add functionalities to enable interaction with Pancakeswap on the Ethereum mainnet.
- Ensure compatibility and seamless integration with the existing Pancakeswap connector architecture.
- Implement appropriate handling for chain-specific differences and features.
- Test thoroughly to verify functionality, security, and reliability across Ethereum mainnet.

Submission: To be assigned, please provide details of your experience, approach to the integration, estimated timeline, and any relevant past projects or contributions.

### Bounty

Sponsor: HB Foundation (Connector pots)
Bounty amount: TBA
Developer portion: TBA

**Comment by fengtality** [comment]
Currently there is 86K HBOT in the PancakeSwap connector pot: https://docs.google.com/spreadsheets/d/1UNAumPMnXfsghAAXrfKkPGRH9QlC8k7Cu1FGQVL1t0M/edit?usp=sharing.

**Comment by nikspz** [comment]
Objective: add Ethereum Mainnet for current Pancakeswap connector

Bounty: HB foundation (Pancakeswap connector pots)

Bounty Amount: 50K HBOT
Developer Payment: 50K HBOT

**Comment by isreallee82** [comment]
I will like to work on this

**Comment by nikspz** [comment]
Assigned to @isreallee82 , please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by nikspz** [comment]
Discussed with @isreallee82 to add 35K HBOT from Pancakeswap connector pots (to add arbitrum and zkSync as well)

Objective: add Ethereum Mainnet, arbitrum and zkSync for current Pancakeswap connector

Bounty: HB foundation (Pancakeswap connector pots)

Bounty Amount: 85K HBOT
Developer Payment: 85K HBOT

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @isreallee82 . The fix has been deployed on development branch and hummingbot version 1.27.0
