### ISSUE TITLE
Uniswap - add CELO chain/network to the current Uniswap connector

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6914]
### Description

https://celo.org/

Objective: 
Enhance the current Uniswap connector to support the [CELO ](https://celo.org/) chain/network in addition to Ethereum and Polygon. 
This upgrade will enable users to interact with Uniswap across multiple chains, expanding accessibility and liquidity.

Requirements:
1. Develop and integrate the necessary functionalities to enable interaction with Uniswap on the CELO chain/network.
2. Compatibility and integration CELO with the existing Uniswap connector architecture.
3. Implement appropriate handling for chain-specific differences.
4. Test thoroughly to verify functionality, security, and reliability across CELO.

### Bounty

- Sponsor: HB Foundation (Connector pots)
- Bounty amount: 50K HBOT
- Developer portion: 50K HBOT

**Comment by vic-en** [comment]
You can assign this to me.

**Comment by elijahsnoz** [comment]
i will like to work on this

**Comment by nikspz** [comment]
Assigned to @elijahsnoz , please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by elijahsnoz** [comment]
pr https://github.com/hummingbot/gateway/pull/313

**Comment by nikspz** [comment]
hi @elijahsnoz Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA

**Comment by elijahsnoz** [comment]
It's done 
Thank you

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @elijahsnoz . The fix has been deployed on development branch and hummingbot version 2.0.1
