### ISSUE TITLE
Signal is 1 but no BUY order given

### ISSUE THREAD

**Issue by mirono** [hummingbot/hummingbot#6916]
### Describe the bug

I'm running a simple script for a directional bot.
In the method get_signal() the signal is returned as 1 but the script didn't issue any BUY order.
![image](https://github.com/hummingbot/hummingbot/assets/6016445/d92cd0f7-3740-4fa6-9107-27837e47d71c)
Script file attached.

### Steps to reproduce

1. 
2. 
3. 

### Release version

1.25.0

### Type of installation

Docker

### Attach required files

[directional_strategy_youtube_crypto_intraday.py.zip](https://github.com/hummingbot/hummingbot/files/14615055/directional_strategy_youtube_crypto_intraday.py.zip)

**Comment by rapcmia** [comment]
We recommend to try our latest updates on v2 strategy as of release 1.26.0
