### ISSUE TITLE
Hyperliquid Connector Next Funding Info not updated

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#6933]
### Describe the bug

The method to get the next funding info is correct, I created a script that let's you check funding rates between exchanges for the same trading pair, and for the best combination show the time to the next funding.
In the image you can see that the value for hyperliquid is wrong:
<img width="1616" alt="image" src="https://github.com/hummingbot/hummingbot/assets/36869960/61768720-9a46-4619-8e18-b936ebf6bc76">

### Steps to reproduce

1. Download Script: https://gist.github.com/cardosofede/e4432a9f3cb78954f89bf86f6ee685d5
2. Download Script config: https://gist.github.com/cardosofede/c7fdae95ba30e36b8c3f53f1edcec86f
3. Store the script file under the folder /scripts as funding_rate_arb.py
4. Store the config under the folder /conf/scripts as funding_rate_arb_1.yml
5. Make sure that you have the APIs connected from the connectors that you add in the config or remove some.
6. In the bot run start --script funding_rate_arb.py --conf funding_rate_arb_1.yml
7. Run status --live and you will see that if there is a combination where hyperliquid is a selected exchange the time for the next funding will be -2.84....+07

### Release version

dev-1.27.0

### Type of installation

Source

**Comment by yancong001** [comment]
here, https://github.com/hummingbot/hummingbot/pull/6940
most exchanges use 10-bit integers (seconds), and the unit tests in the picture also use 10 as integers, so change binance and okx to 10-bit integers as well

**Comment by nikspz** [comment]
fixed in dev-1.27.0

![image](https://github.com/hummingbot/hummingbot/assets/83953535/549f9d62-3fc7-44e0-add0-d093336a7ebc)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/2e36c014-132e-4805-b474-7f62608fb51d)
