### ISSUE TITLE
Vertex - Error:Cannot connect to host prod.vertexprotocol-backend.com:443 ssl:default

### ISSUE THREAD

**Issue by AlexeyBoiler** [hummingbot/hummingbot#6934]
### Describe the bug

Writes an error:
```
Error:Cannot connect to host prod.vertexprotocol-backe
nd.com:443 ssl:default [Name or service not known]
```

### Steps to reproduce

According to the API documents, he has a completely different address for working with web sockets:
Mainnet:
Websocket: 
wss://gateway.prod.vertexprotocol.com/v1/ws

REST: 
https://gateway.prod.vertexprotocol.com/v1

Docks https://docs.vertexprotocol.com/developer-resources/api/gateway 

### Release version

1.25

### Type of installation

Source

**Comment by Wandering-Consciousness** [comment]
The old endpoints were deprecated 1st Jan 2024:
https://docs.vertexprotocol.com/developer-resources/api/endpoints#migration
