### ISSUE TITLE
最新版本都是BUG啊 simple_rsi_example.py直接运行都报错

### ISSUE THREAD

**Issue by phpmac** [hummingbot/hummingbot#6935]
### Describe the bug

最新版本都是BUG啊 simple_rsi_example.py直接运行都报错

### Steps to reproduce

最新版本都是BUG啊 simple_rsi_example.py直接运行都报错

### Release version

1

### Type of installation

Source

**Comment by nikspz** [comment]
No steps to reproduced provided, could start the script succesfully
