### ISSUE TITLE
New connector - raindex

### ISSUE THREAD

**Issue by thedavidmeister** [hummingbot/hummingbot#6936]
### Description

I made a dex that is an orderbook where every order is dynamically calculated using an onchain smart contract language that i made (rainlang).

Docs are here https://docs.rainlang.xyz/orderbook/introduction/

I'm looking for a hummingbot connector to be written to make the dex more efficiently and effectively connected to other liquidity sources (e.g. via arbitrage).

I'm not familiar with the process of bounties on HB so i'll work through the docs and form submissions in parallel to this issue until we can move it forward.

### Bounty

- Sponsor: [Rainlang](https://rainlang.xyz/)
- Bounty amount: ?? not sure yet
- Developer portion: ?? not sure yet

**Comment by thedavidmeister** [comment]
@nikspz thanks, form submitted, i'm on discord

**Comment by nikspz** [comment]
@thedavidmeister 
Do you want to sponsor bounty, correct? 

you didn't specified the amount you want to pay (to fund connector creation)

**Comment by thedavidmeister** [comment]
@nikspz right i haven't yet, i've been asking in discord to try to figure out the scope with @mlguys 

raindex works a bit differently to other dex so, i could just put the standard $3750 but i'm not sure if that's right, or if i should perhaps modify the dex itself to make it easier to work with etc.

**Comment by nikspz** [comment]
@thedavidmeister 

- The exchange has an orderbook where each order is a smart contract 
- this bounty needs 4 criteria for a dev (or more):
    - Know how
        - create Hummingbot connector
        - rainlang programming language work
        - rainlang protocol work
        - write rainlang smartcontract order
    - From this statement
        - Since the connector dev will need to learn new rainlang language, change / implement new changes to the existing Hummingbot code standarts and have a lot of experience so estimated price is ~25k USDC, anyway for us it mean for testing dev reviewing it is also complicated so currenly we would advise:
        - would be easier to get someone from Raindex community to learn Hummingbot then go back and build the connector

**Comment by thedavidmeister** [comment]
the way it typically works

- someone places an order on raindex, which is dynamic, they call `addOrder` on the contract
- the logic that defines the order is emitted in an onchain `AddOrder` event
- typically the event is indexed by our subgraph and so all the order logics are available to someone when they query the subgraph, e.g. "get me all the order logics for pair 'buy X for Y'"
- running the order logic is onchain so it's just a smart contract call, e.g. you pass the order logic to the dex smart contract and it tells you what price/amount that order is currently evaluating to, this can be done like any other fork in hardhat/foundry/etc.
- taking the order is basically the same, you pass a list of orders that you want to take, and how much you'd like to spend and it "market buys" that set of orders up to your desired trade size

based on discord discussions, i understand that subgraphs are unusual for HB but then I don't know how HB normally handles onchain events, if that's natively supported then just replace "query subgraph" with "HB listens to the onchain events and tracks them internally"
