### ISSUE TITLE
Update Dexalot to a direct Python connector

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6938]
### Description

Enhance Dexalot by implementing a direct Python connector. This upgrade will streamline trading on Dexalot by eliminating the need for Gateway and providing optimized support for the accounts. (similar to the approach taken with injective_v2). 

Successful completion of this bounty will enhance the efficiency and flexibility of trading on Dexalot, providing users with a smoother experience.

Requirements: This is a complex task and requires understanding of Hummingbot connectors as well as Avalanche subnets, so we will prioritize developers with experience building Hummingbot CEX/DEX connectors

### Bounty

Sponsor: Dexalot
Bounty amount: 4000 USDC
Developer portion: 4000 USDC

**Comment by alexeyneu** [comment]
so you're ready to pay for this? bounty status is unclear

**Comment by webbdays** [comment]
Who ever is going to start this work.
Please add me as collaborator.
Treat me like a junior developer. I will help you.
I have no domain/subject knowledge on this codebase as of now.

**Comment by nikspz** [comment]
> bounty status is unclear

it's not opened (not funded yet)

**Comment by nikspz** [comment]
FYI: This bounty was funded and opened now

**Comment by nikspz** [comment]
as Discussed on the call, and described in Requirements, we will prioritize developers with experience building Hummingbot CEX/DEX connectors

**Comment by webbdays** [comment]
As said before, i will work as a teammate, no need of bounty.
Want to get some idea of the project.

**Comment by nrworld** [comment]
I also want to join as team-member and help. My goal is to gain understanding of codebase. No bounty is required

**Comment by andrewlfc7** [comment]
I would like this take this if possible

**Comment by nikspz** [comment]
Assigned to @yancong001

**Comment by nikspz** [comment]
hi @yancong001, do you have updates on this bounty?

**Comment by KodeSage** [comment]
HI @nikspz , if no one is actively working on this, I can recommend someone who can spin off this task and get it done as soon as possible.

Check out @jaykayudo.

While I was working(still working on it and wraping it up) on the chainflip connector, He helped me out with it.
it will be best he takes up this challenge and tasks, as this one can be done as soon as possible and it's not complex.

**Comment by yancong001** [comment]
here https://github.com/hummingbot/hummingbot/pull/7219

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @yancong001. The fix has been deployed on development branch and hummingbot version 2.1.0
