### ISSUE TITLE
Hyperliquid recreates reversing order on close

### ISSUE THREAD

**Issue by tijsk** [hummingbot/hummingbot#6948]
### Describe the bug

When an order is closed (long or short) a new open is made in the opposite direction.
Occurs in Source and Docker installation, see attached logfile.

For more info send me a message on Discord, I'd like to help.

### Steps to reproduce

1. Tried different scripts, for example; _perpetual_market_making_, but also _v2_generic_with_controllers_
2. 1 or multiple coins active doesn't matter
3. Let the script run and let the script finish a trade
4. See an order appear after a few seconds after close of initial order

### Release version

1.26

### Type of installation

Docker and Source

### Attach required files

[message.txt](https://github.com/hummingbot/hummingbot/files/14854795/message.txt)

### Conf script

markets: {}
candles_config: []
controllers_config:
- conf_directional_trading.dman_v3_SOL.yml
config_update_interval: 20
script_file_name: v2_generic_with_controllers.py

### Conf controller

id: 3tfTznFJZwMPmXj9kCQvdrnChdsjpbsPDif9idf6WheJ
controller_name: dman_v3
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
connector_name: hyperliquid_perpetual
trading_pair: SOL-USD
executor_amount_quote: 3000.0
max_executors_per_side: 1
cooldown_time: 15
leverage: 20
position_mode: ONEWAY
stop_loss: 0.25
take_profit: 0.005
time_limit: null
take_profit_order_type: 2
trailing_stop:
  activation_price: 0.004
  trailing_delta: 0.001
candles_connector: binance_perpetual
candles_trading_pair: SOL-USDT
interval: 5m
bb_length: 100
bb_std: 2.0
bb_long_threshold: 0.2
bb_short_threshold: 0.8
dca_spreads:
- 0.005
- 0.006
- 0.008
- 0.01
- 0.013
dca_amounts_pct:
- 1
- 1.01
- 1.02
- 1.03
- 1.04
- 1.05
dynamic_order_spread: true
dynamic_target: false
activation_bounds: null

**Comment by ak4noir** [comment]
I've ran into something similar. I closed the orders on exchange front-end and then noticed that orders in the opposite direction with the same amounts were created. 

I was also using `dman_v3`

**Comment by nikspz** [comment]
> ### Describe the bug
> When an order is closed (long or short) a new open is made in the opposite direction. Occurs in Source and Docker installation, see attached logfile.

Reproduced on latest development (during the longrun with ~same config)

![image](https://github.com/hummingbot/hummingbot/assets/83953535/cae67ee4-7f84-49b6-8c71-b90efe0cc5e7)

![HPL longrun has issue with wrong position side (CLOSE on bot and OPEN on exchange)  This leads to increasing position amount](https://github.com/hummingbot/hummingbot/assets/83953535/bfdbdfba-d037-496b-8b76-ac181a4ce12c)

After stop command bot failed to close position: 
![HPL after stop command - failed to close](https://github.com/hummingbot/hummingbot/assets/83953535/db012eb0-d38e-4e66-b0c0-d4ae12522a92)

**Comment by nikspz** [comment]
Bounty: fix the issue with inconsistent position side / order creation 
Sponsor: HB Foundation
Bounty amount: 50K HBOT
Developer portion: 50K HBOT

**Comment by yancong001** [comment]
hi,nikspz
This is the fix I submitted
https://github.com/hummingbot/hummingbot/pull/7013

**Comment by yancong001** [comment]
can test whether there is any problem. If there is any problem, I will continue to repair it

**Comment by nikspz** [comment]
fixed, fix merged to latest development (dev-1.28.0)

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @yancong001. The fix has been deployed on development branch and hummingbot version 1.28.0
