### ISSUE TITLE
Add Kucoin HFT connector 

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6955]
### Description

We need to enhance the existing KuCoin connector in Hummingbot to support High-Frequency Trading (HFT) accounts on the KuCoin Pro platform. The objective is to enable Hummingbot users to take advantage of advanced trading features offered by KuCoin's HFT services.

Add kucoin HFT connector, let user choose between default or HFTrading

https://www.kucoin.com/docs/beginners/hftrading
https://www.kucoin.com/news/the-kucoin-spot-api-high-frequency-account-is-now-officially-launched

### Bounty

- Sponsor: HB Foundation (Connector pots) 
- Bounty amount: 50K HBOT
- Developer portion: 50K HBOT

**Comment by supervik** [comment]
I am ready to do this task

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @supervik . The connector has been deployed on development branch and hummingbot version 1.27.0
