### ISSUE TITLE
UnauthorizedException when connecting to Polkadot

### ISSUE THREAD

**Issue by Wandering-Consciousness** [hummingbot/hummingbot#6969]
### Describe the bug

Get the following error when trying to connect to Polkadex:
UnauthorizedException', 'message': 'You are not authorized to make this call.'

### Steps to reproduce

1.  Create Polkadex funding/trade accounts as per [doc](https://hummingbot.org/academy-content/using-polkadex-with-hummingbot/)
2.  Enter the following in Hummingbot:
```
 >>>  connect polkadex 

  Would you like to replace your existing polkadex key (Yes/No)? >>> Yes                                

  Enter your Polkadex seed phrase >>> *************************************************************                                                                                                           
  *****************

  Error: {'errorType': 'UnauthorizedException', 'message': 'You are not authorized to make this call.'}
```
3. Observe said error in left pane soon after. 

### Release version

dev-1.27.0

### Type of installation

Source

**Comment by rapcmia** [comment]
Tried to create a new account and recorded the part generating mnemonic pass. Add the passphrase to the connector setup on hummingbot client and works ok. Please see recording https://www.loom.com/share/750d09f225f74493a3aa770aa6873274?t=48&sid=645385a3-64e1-45ad-9953-c24fc2bbdbd2

**Comment by Wandering-Consciousness** [comment]
Yup, confirmed the latest checked out development branch is now working and no "PolkadexExchange: failed to get market info" error in the top-right console.
Thanks.
