### ISSUE TITLE
Bounty - Refactor and add candles feeds

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#7020]
Description: 

Candles feed support for an exchange is needed to support backtesting and advanced V2 strategies. With the launch of Hummingbot 2.0, adding candles to more exchange will expand support more broadly.

https://snapshot.org/#/hbot-ip.eth/proposal/0x8ef9baacefd56863a6422f118751a577f9b32834a80c653a6997d8e4712afa48

The objective of this bounty is to standardize the current candles feds, improving the current design if needed, and add support to more DEX and CEX exchanges.

Assigning this task to a single developer should streamline it and make it easier to review/test.

Acceptance Criteria
Add new candles for:
- KuCoin (Perp)
- MEXC (Spot and Perp)
- Bybit (Spot & Perp)
- Hyperliquid (Perp)
- Injective V2 (Spot & Perp)

Standardize all the timestamps from milliseconds to seconds. Validate that the download_candles method retrieves the most recent candles at the end of the records for each supported exchange.

Validate that the real-time candles collected are able to fill gaps if there are candles missing or restart the process. Create a simple script that measures the timedelta between the candles and see if it's the same as the interval to use as a validation.

Bounty:

Sponsor: Hummingbot foundation 
Bounty amount: 606612 HBOT
Developer portion: 606612 HBOT

**Comment by nikspz** [comment]
not funded yet

**Comment by dakshbtc** [comment]
Hi, can i pick this please.

**Comment by nikspz** [comment]
hi, @dakshbtc, by checking your profile you do not have enough experience for this task

**Comment by nikspz** [comment]
also not funded yet

**Comment by nikspz** [comment]
Sponsor: Hummingbot foundation connector pots
Bounty amount: 50k HBOT or 150USDC
Developer portion: 50k HBOT or 150USDC

**Comment by tomasgaudino** [comment]
hey, i'd like to take this one please!

**Comment by nikspz** [comment]
Assigned to @tomasgaudino, please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by tomasgaudino** [comment]
Thanks! I'll be giving updates on monday.

Have a nice weekend!

**Comment by nikspz** [comment]
https://snapshot.org/#/hbot-ip.eth/proposal/0x8ef9baacefd56863a6422f118751a577f9b32834a80c653a6997d8e4712afa48

**Comment by tomasgaudino** [comment]
Here's actual PR https://github.com/hummingbot/hummingbot/pull/7086

Two considerations:
- I couldn't find any doc related to rest or websocket feed por candles in injective
- I also added hyperliquid spot candle feed, which wasn't in original scope but i had the opportunity to contribute

**Comment by nikspz** [comment]
Changed this bounty amount as discussed in order to this vote:
https://snapshot.org/#/hbot-ip.eth/proposal/0x8ef9baacefd56863a6422f118751a577f9b32834a80c653a6997d8e4712afa48

Sponsor: Hummingbot foundation 
Bounty amount: 606612 HBOT
Developer portion: 606612 HBOT

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @tomasgaudino . The fix has been deployed on development branch and hummingbot version 2.0.1
