### ISSUE TITLE
OKX- Add OKX Spot Candles Feed

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#7021]
### Description

- Add a new Candles Feed for the OKX spot connector
- Should implement the CandlesBase class like the Binance Perpetual candles.
- Support web sockets to stream new messages and rest to collect historical data
- Contains unit tests and meets % coverage requirements
- You can find the candles feed inside hummingbot/data_feed/candles_feed
- See  https://www.okx.com/docs-v5/en/ for API reference

### Bounty

- Sponsor: HB Foundation connector pots
- Bounty amount: 100k HBOT or 200 USDC
- Developer portion: 100k HBOT or 200 USDC

**Comment by nikspz** [comment]
Assigned to @tomasgaudino , please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by tomasgaudino** [comment]
here's the pr https://github.com/hummingbot/hummingbot/pull/7022, if you have any questions or something feel free to reach me!

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @tomasgaudino . The fix has been deployed on development branch and hummingbot version 1.28.0
