### ISSUE TITLE
New Kraken pair symbols result in "balance is too low" error

### ISSUE THREAD

**Issue by r1979** [hummingbot/hummingbot#7052]
### Describe the bug

Since Kraken allowed users to earn stake rewards on spot balances the symbols for certain coins have changed (ETH => ETH.F, XBT => XBT.F, ALGO => ALGO.F, etc.) and this results in problems when creating orders even if there is a sufficient saldo in the portfolio.

### Steps to reproduce

Suppose a portfolio of:
DASH 4
EUR 100
XBT.F 0.0016
ETH.F 0.03

1. Create and start a v1 "pure market making" strategy with the DASH-EUR pair; it will work.
2. Create and start a v1 "pure market making" strategy with the BTC-EUR; when typing `>>> status` it will return `kraken market BTC balance is too low. Cannot place order.`.
3. Create and start a v1 "pure market making" strategy with the ETH-BTC; when typing `>>> status` it will return `kraken market BTC balance is too low. Cannot place order.` and `kraken market ETH balance is too low. Cannot place order.`.

### Release version

1.27.0

### Type of installation

Source

**Comment by nikspz** [comment]
Sponsor: Hummingbot foundation connector pots
Bounty amount: 30K HBOT or 100 USDC
Developer portion: 30K HBOT or 100 USDC

**Comment by nikspz** [comment]
Steps to reproduce:
1. Add ETH balance, review bot could place orders
2. go to https://www.kraken.com/c/rewards and add ethereum
3. Check balance and review ETH converted to ETH.F

Actual:
There's no pairs for ETH.F trading


![image](https://github.com/hummingbot/hummingbot/assets/83953535/7d63e1b5-6b31-4b7d-a5ad-6d3cb249c04e)

![image](https://github.com/hummingbot/hummingbot/assets/83953535/8d59486d-fcba-494a-8c57-c584c1ec7336)

![image](https://github.com/hummingbot/hummingbot/assets/83953535/c57e7004-a197-4f10-88f9-4a5b9fb92266)

**Comment by yancong001** [comment]
fixed, https://github.com/hummingbot/hummingbot/pull/7069

**Comment by nikspz** [comment]
Sponsor: Hummingbot foundation connector pots
Bounty amount: 30k HBOT or 100 USDC
Developer portion: 30k HBOT or 100 USDC

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/7081

**Comment by nikspz** [comment]
Fix merged to latest development (dev-1.29.0) and will be availble in 1.29.0 release
