### ISSUE TITLE
Hyperliquid - Error while submitting MARKET order to Hyperliquid Perpetual. 

### ISSUE THREAD

**Issue by angelmarine** [hummingbot/hummingbot#7056]
### Describe the bug

1. While experiment the funding_rate_arb script (using Binance and Hyperliquid perp), there was error while submitting order to Hyperliquid perp. 
2. Connection to Binance and Hyperliquid seems okay. I have also double-checked my api key with  hyperliquid-python-sdk library and I could create order without problem.
3. Error is returned like below. 

![image](https://github.com/hummingbot/hummingbot/assets/11015544/f88ea660-713f-4005-8bff-ef10ab727f22)

4. But when I debug the direct response from Hyperliquid. It returns error stating that the 'User or API Wallet OOO does not exist.' And the address return with the error does not match with the address I have entered when I connected to Hyperliquid perp.
![image](https://github.com/hummingbot/hummingbot/assets/11015544/25a00a32-4cd7-4cd8-a860-10ad2c9948fc)

### Steps to reproduce

1. Connect API to Binance and Hyperliquid perp with success.
2. `balance` command should properly show the balance. 
![image](https://github.com/hummingbot/hummingbot/assets/137147853/1b58e805-60a3-4dd9-b45a-6c342adbad6a)

3. Run the `funding_rate_arb` script with the following config.

```
markets: {}
candles_config: []
controllers_config: []
config_update_interval: 60
script_file_name: funding_rate_arb.py
leverage: 5
min_funding_rate_profitability: 0.0012
connectors:
- hyperliquid_perpetual
- binance_perpetual
tokens:
- POLYX
- RNDR
position_size_quote: 30
profitability_to_take_profit: 0.01
funding_rate_diff_stop_loss: -0.001
trade_profitability_condition_to_enter: true
```

### Release version

1.27.0

### Type of installation

Source

### Attach required files

[logs_hummingbot.log.zip](https://github.com/hummingbot/hummingbot/files/15465645/logs_hummingbot.log.zip)

**Comment by ken-wizhodl** [comment]
same thing here

**Comment by nikspz** [comment]
There was API update after 1.27.0 release
![image](https://github.com/hummingbot/hummingbot/assets/83953535/461e78ac-a109-4d79-bd30-9e921ae4999d)


Should be fixed in latest development (dev-1.28.0)



[hyperliquid-30may 2024.zip](https://github.com/hummingbot/hummingbot/files/15495555/hyperliquid-30may.2024.zip)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/11fae2d2-95b2-478e-bfc7-7a4921bf3e13)

**Comment by angelmarine** [comment]
@nikspz 
Thank you for the reply. I will try it again in 1.28.0 release. And close the issue if it works :)

**Comment by ken-wizhodl** [comment]
It worked for me.
