### ISSUE TITLE
Binance spot candles - wrong timestamps at start of candles script

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#7057]
### Describe the bug

Binance spot candles - wrong timestamps at start of candles script

### Steps to reproduce

1. Clone development branch
2. start the script below
3. review first 4 timestamps are wrong

### Release version

dev-1.28.0

### Type of installation

Source

### Attach required files

![image](https://github.com/hummingbot/hummingbot/assets/83953535/eafafbbd-c976-4a34-adc3-4f8cefb401dd)

After a while downloaded some

![image](https://github.com/hummingbot/hummingbot/assets/83953535/c5c2cbe9-a888-46b9-90be-c0947071bd7f)

![image](https://github.com/hummingbot/hummingbot/assets/83953535/5c58d6d5-7272-49ee-9867-47ec131b7ff1)

Same for 1m candles

![image](https://github.com/hummingbot/hummingbot/assets/83953535/545a737a-a4df-4c7e-a19b-8a8faed6558c)

After a while downloaded

![image](https://github.com/hummingbot/hummingbot/assets/83953535/4035e61e-84f3-4a49-8932-6420b761319b)

**Comment by dakshbtc** [comment]
@nikspz can i take this .please.

**Comment by rapcmia** [comment]
Fix has been deployed to development branch
