### ISSUE TITLE
What differnce between parammeter IS_MAKER and LIMIT_MAKER?

### ISSUE THREAD

**Issue by willjay97** [hummingbot/hummingbot#7074]
### Feature Suggestion

Thank you for the excellent work on the HFT architecture.

I have a question regarding two parameters in `OrderCandidate`, `is_maker` and `order_type=OrderType.LIMIT_MAKER`.

1. If I want to ensure that an order is filled as a maker and not as a taker, how should I set these two parameters?
2. I’m also unclear about how `is_maker` works. When I place an order using the buy or sell function, as shown below, the `is_maker` parameter is not included in the sell function:
```python
order = OrderCandidate(
    trading_pair=***,
    is_maker=True,
    order_type=OrderType.LIMIT_MAKER,
    order_side=***,
    amount=***,
    price=***
)
self.buy/self.sell(
    connector_name=***,
    trading_pair=***
    amount=***,
    order_type=order.order_type,
    price=***
)
```
Thank you~~~

### Impact

If I want to ensure that an order is filled as a maker and not as a taker, how should I set these two parameters?

**Comment by Jbekker** [comment]
I believe is_maker is mostly used for fee calculations. The OrderType.LIMIT_MAKER is what you’re looking for. What connector are you using?

**Comment by Jbekker** [comment]
@willjay97, please close this issue if you have enough information.
