### ISSUE TITLE
Improvements in V2 docs

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#7112]
### Description

# Proposal
#proposal 

### Goal
 - Improve the documentation of the v2 strategies since they are becoming mainstream in Hummingbot and the current information provided does not get into much details on how the framework works under the hood.

### Useful links before getting started:
- **Official Docs:** https://hummingbot.org/strategies/
- **Github code:** https://github.com/hummingbot/hummingbot-site/tree/main/docs/v2-strategies

### What is expected:
- **Strategies V2 page:** there are some concepts mixed and can be simplified generating more emphasis on when to use each strategy type (or just present the ones available in v2 to avoid confusion)
- **Content organization:** the current situation starts with 2 walkthroughs, seems like will be better to start with the architecture to provide a general overview of how the framework works (include the flowcharts and the content that Patrick showed me before), and then the walkthrough. The structure can look like similar to this:
	- **Strategy V2**
		- **Architecture**
			- Market Data Provider
			- Executors
			- Controllers
			- Scripts
		- **Getting started**
			- Hummingbot Deploy
			- Running from source
		- **Guides**
			- Coding a controller (directional, mm, custom)
			- Backtesting a controller using notebooks
			- Adding your controller to Hummingbot Deploy and creating a configuration page in the dashboard
- **Blog post:** blog post that we can add to our [Academy](https://hummingbot.org/academy/) explaining a custom strategy defined by the developer (nice to have not required)

### Bounty

- Sponsor: FOUNDATION
- Bounty amount: 100,000 HBOT
- Developer portion: 100,000 HBOT

**Comment by p-meier** [comment]
I'd like to do it please.

**Comment by cardosofede** [comment]
assigned @p-meier for this bounty!

**Comment by p-meier** [comment]
thanks @cardosofede 

I'll started already and see how far I come this week.

**Comment by p-meier** [comment]
I created a PR and am happy to receive feedback. 

One issue I had is that I could not actually build the docs locally to check everything as I lack access to `mkdocs-material-insiders ` repository.

I contacted @cardosofede on Discord already about that.

Have a nice weekend.

**Comment by p-meier** [comment]
Any updates so far? Still didn't get access to `mkdocs-material-insiders`. Otherwise it is considered finished from my side.

**Comment by p-meier** [comment]
Thanks @fengtality. Could build everything and verify it renders correctly. So I consider it done from my side and wait for your comments.

**Comment by fengtality** [comment]
Hey @p-meier good work on fleshing out the V2 docs. I'll do some re-organization, but overall I think your additions fulfill the bulk of the requirements of the bounty. 

The one area I'd like to request more info is a walkthrough for users to create their own custom controllers, perhaps using a simple one based on the generic controller base class. This is what we meant by the Academy post, but I think the one you added is good as well.

```
* Coding a controller (directional, mm, custom)
```

**Comment by p-meier** [comment]
@fengtality I added the missing post in the PR here: https://github.com/hummingbot/hummingbot-site/pull/379

As I wrote in the other one there was things missing and I wanted to deliver a clean state of my work. I assume if you merge the commits from that PR everything should be included.

**Comment by nikspz** [comment]
hi @p-meier 
Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA

**Comment by p-meier** [comment]
@nikspz thanks. Just filled out the form.

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @p-meier . The fix has been deployed on development branch and hummingbot version 2.0.1

**Comment by nikspz** [comment]
Available here:
https://hummingbot.org/academy-content/coding-a-custom-v2-controller-for-future-liquidations-on-binance/
https://hummingbot.org/academy-content/leveraging-ai-for-automated-copy-trading-on-discord/

https://hummingbot.org/academy-content/

**Comment by p-meier** [comment]
@nikspz @fengtality there seems to be an error in the final merge. The content I wrote for the docs is missing in big parts on the live-page and does not reflect on what I submitted here in the bounty. 

I booted up the local version of the site with my PR and this is different on what you have on the live page now: 

![Image](https://github.com/user-attachments/assets/2a5994c8-128c-453c-802f-3986ef9d0287)

Especially the graph with the architecture that @cardosofede wanted there is also missing. Maybe you want to recheck the merge. 

Here are the comparison of the sites between the live-content and my local version. A lot seems to be missing.

[v2_architecture_live.pdf](https://github.com/user-attachments/files/16887884/v2_architecture_live.pdf)
[v2_architecture_bounty.pdf](https://github.com/user-attachments/files/16887885/v2_architecture_bounty.pdf)
[v2_overview_bounty.pdf](https://github.com/user-attachments/files/16887883/v2_overview_bounty.pdf)
[v2_overview_live.pdf](https://github.com/user-attachments/files/16887882/v2_overview_live.pdf)

**Comment by fengtality** [comment]
> @nikspz @fengtality there seems to be an error in the final merge. The content I wrote for the docs is missing in big parts on the live-page and does not reflect on what I submitted here in the bounty.
> 
> I booted up the local version of the site with my PR and this is different on what you have on the live page now:
> 
> ![Image](https://private-user-images.githubusercontent.com/2674097/364733652-2a5994c8-128c-453c-802f-3986ef9d0287.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDUzOTIsIm5iZiI6MTcyNTU0NTA5MiwicGF0aCI6Ii8yNjc0MDk3LzM2NDczMzY1Mi0yYTU5OTRjOC0xMjhjLTQ1M2MtODAyZi0zOTg2ZWY5ZDAyODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMTQwNDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZmZTZjNWZlODU2OTM2NzhlODBhNDdiZWEwZjQyYTUxZmFiODYwMDg1YjhiMTliYjE5Mzg0YTAxZDkxOTJiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bGr72ZywB2i2Rv6t5VkcLWQWLjjPyBtarN7im8Jd4BQ)
> 
> Especially the graph with the architecture that @cardosofede wanted there is also missing. Maybe you want to recheck the merge.
> 
> Here are the comparison of the sites between the live-content and my local version. A lot seems to be missing.
> 
> [v2_architecture_live.pdf](https://github.com/user-attachments/files/16887884/v2_architecture_live.pdf) [v2_architecture_bounty.pdf](https://github.com/user-attachments/files/16887885/v2_architecture_bounty.pdf) [v2_overview_bounty.pdf](https://github.com/user-attachments/files/16887883/v2_overview_bounty.pdf) [v2_overview_live.pdf](https://github.com/user-attachments/files/16887882/v2_overview_live.pdf)

Hey @PatrickLiPM I edited what you submitted and didn't use everything. Note that I added the inheritance diagram to https://hummingbot.org/v2-strategies/. However, I'll take a closer look at these PDFs to see if more that I missed.

**Comment by p-meier** [comment]
@fengtality if that was intentional then all good. Still makes me wonder as most of what I changed in the docs was removed, especially the graphics that @cardosofede wanted which I created during my Hummingbot Cohort and was the initial reason for the bounty. 

But I'm anyway ok with it if that is intentional and the way you want it to be. Just thought it was due to a merge error or conflict.
