### ISSUE TITLE
New Connector Request: Ethereum Classic Network, ETCswap V2

### ISSUE THREAD

**Issue by chris-mercer** [hummingbot/hummingbot#7113]
### Description

1.) Chain Connector: Ethereum Classic, Chain 61. https://chainlist.org/chain/61. Add Chain connector guide
2.) AMM-V2 connector: https://v2.etcswap.org A vanilla fork of Uniswap V2. Add V2 connector guide

The primary goal is connect the ETC/USC markets on ETCswap V2 to the ETC/USD CEX markets via Hummingbot XEMM strategy. This is the foundational DeFi pair for Ethereum Classic.

The secondary goal is to have clear guides that allow novice developers in the Ethereum Classic development community open resources for one of the few decentralized networks in blockchain. This is a perfect open source community that deserves Hummingbot support.

Contact: chris@ethereumclassic.com
Protocol Contract List: https://github.com/etcswap

### Bounty

- Sponsor: EthereumClassic.com
- Bounty amount: 3750 USDC (includes 20% Handling Fee to Hummingbot Foundation)
- Developer portion: 3000 USDC

**Comment by p-meier** [comment]
Sounds interesting, after I completed my current V2 docs bounty I would like to take it.

**Comment by chris-mercer** [comment]
note for the developers. if an RPC endpoint is needed: https://etc.rivet.link is the funded public endpoint. This should be the most stable endpoint for ETC.

**Comment by vic-en** [comment]
I can work on this and get it in asap

**Comment by codebestia** [comment]
I will like to be assigned this bounty. i can get it done as soon as possible

**Comment by vic-en** [comment]
@nikspz I can create a pr for this over this weekend as I have snippets for this v2 as a result of my work on the v3.

**Comment by isreallee82** [comment]
I can work on this @nikspz if still open.

**Comment by chris-mercer** [comment]
NCP Proposal is submitted:
https://snapshot.org/#/hbot-ncp.eth/proposal/0x5face44f80c3c0d3d290da1a6973ec0c030a483023a4647ff91e4339af085770

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @vic-en. The connector has been deployed on development branch and hummingbot version 2.1.0
