### ISSUE TITLE
Connector HashKey Global exchange

### ISSUE THREAD

**Issue by Arisqiu** [hummingbot/hummingbot#7123]
### Description

**Bounty Request 1: Connection Hunter-HashKey Global exchange(Perp)**
**Requirement:** 
1. Integrate to HashKey Global's future market API and push it to Hummingbot.
2. Maintain the code for 2 months after the integration is completed.
**Reward:** 
1. Integration Bonus: **2000 USDT**
2. If the hunter meets the requirements of HashKey Group's Talent Program, he/she will have the opportunity to become an official employee of HashKey Group, mainly responsible for technical support and product operation of the API.
3. If the hunter does not meet the requirements of HashKey Group's Talent Program, he/she will have the opportunity to become a quantitative spokesperson for HashKey Group in the Hummingbot community.

_Note: 
1. The total amount of bounty will be contributed to the Hummingbot official 20%, and the final acceptance will be confirmed by the Hummingbot official.
2. Reward will be distributed officially by Hummingbot._
**3. Based on this request, we will launch an issue hunter after the integration is completed. For details, please refer to https://github.com/hummingbot/hummingbot/issues/7124**
4. The hunter can choose between USDT or the equivalent in HSK(https://global.hashkey.com/) as a reward!

### Bounty

- Sponsor: Hashkey Global exchange
- Bounty Request for connector Hashkey Global exchange(Perp)
- Bounty amount: 2000 USDT 
- Developer portion: 80% (1600 USDT)

**Comment by UkuLoskit** [comment]
hello! I would be interested!

**Comment by yancong001** [comment]
i'd like to accept this ticket

**Comment by Jbekker** [comment]
I would also be interested in this, would be my first perpetual but I’m confident I can deliver a quality connector ☺️

**Comment by dengyh** [comment]
I had finished the hashkey global and hashkey hk connector for the spot trades，can I submit it before I finish the connector for perp trades?

**Comment by akgod** [comment]
i'd like to accept this ticket

**Comment by akgod** [comment]
I have 10 years of experience in quantitative trading of financial derivatives, proficient in CEX-DEX arbitrage, and skilled in statistical arbitrage. I have been conducting quantitative trading on Binance for many years and have considerable experience in quantitative trading and programming.

**Comment by nikspz** [comment]
hi @Arisqiu, are you affiliated with HashKey Global exchange?
we have default prices guide here for perpetual connectors:
https://hummingbot.org/bounties/prices/

**Comment by nikspz** [comment]
> I had finished the hashkey global and hashkey hk connector for the spot trades, and my strategies had ran by it since January this year in Hashkey HK. So I can complete the perp trades connector base on the spot connector.

This bounty is underpriced, from my discussion with sponsor that's a final price. 
if you're okay with 
1. Bounty amount (developer portion is 1600 USDT)
2. Will be paid after 2 month passed after PR merged
3. https://github.com/hummingbot/hummingbot/issues/7124 this could be additional if no bugs reported from what this bounty description said.

**Comment by Jbekker** [comment]
I agree it's underpriced and with the low rate limits it's even quite tricky:
> Unless explicitly stated otherwise, each API Key has a default rate limit of 2 requests per second for query-related endpoints, while order-related endpoints allow 10 requests per second.

I've been having some fun with this the last few days and I do have it mostly working so if @dengyh doesn't want it, I'll be happy to take this on :-)

**Comment by dengyh** [comment]
> > I had finished the hashkey global and hashkey hk connector for the spot trades, and my strategies had ran by it since January this year in Hashkey HK. So I can complete the perp trades connector base on the spot connector.
> 
> This bounty is underpriced, from my discussion with sponsor that's a final price. if you're okay with
> 
> 1. Bounty amount (developer portion is 1600 USDT)
> 2. Will be paid after 2 month passed after PR merged

OK，I accept the price.

**Comment by nikspz** [comment]
The bounty is funded and open now. 
@dengyh do you want to be assigned?

**Comment by dengyh** [comment]
> The bounty is funded and open now. [@dengyh](https://github.com/dengyh) do you want to be assigned?

Yes, I do.

**Comment by nikspz** [comment]
Assigned to @dengyh , please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by nikspz** [comment]
hi @dengyh Please submit the completed AML Policy form so we can process your payout. This is a one-time process for each wallet address. https://forms.gle/RpcA9rAZcMqmPi1TA

**Comment by nikspz** [comment]
Please submit and inform here when ready @dengyh https://forms.gle/RpcA9rAZcMqmPi1TA

**Comment by dengyh** [comment]
> Please submit and inform here when ready [@dengyh](https://github.com/dengyh) https://forms.gle/RpcA9rAZcMqmPi1TA

Done

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @dengyh . The connector has been deployed on development branch and hummingbot version 2.1.0
