### ISSUE TITLE
XRPL - Equilibrium pair

### ISSUE THREAD

**Issue by Ban912** [hummingbot/hummingbot#7136]
### Describe the bug

Equilibrium Balance is always 100% allocated, creating only buy orders on the xrp pair, sell orders are not created

### Steps to reproduce

1. XRPL connector pair Equilibrium/XRP
2. Check balance
3. 

### Release version

2

### Type of installation

Source

### Attach required files

[LOG.txt](https://github.com/user-attachments/files/16343108/LOG.txt)

**Comment by Ban912** [comment]
![photo_2024-07-22_21-05-58](https://github.com/user-attachments/assets/354b686e-207c-4303-92c1-e95ffdc61b13)

**Comment by mlguys** [comment]
Thanks for finding this issue, will work on this soon.

**Comment by Ban912** [comment]
Thanks

**Comment by mlguys** [comment]
@Ban912 @rapcmia should be fixed in #7108

**Comment by rapcmia** [comment]
![image](https://github.com/user-attachments/assets/68d71772-5234-4f7e-a34b-acc8e7774d81)
- The fix has been added to the PR
