### ISSUE TITLE
uniswap_ethereum_mainnet connector not listed when creating pure_market_making strategy

### ISSUE THREAD

**Issue by LautaroNavarro** [hummingbot/hummingbot#7146]
### Describe the bug

I'm trying to create a pure_market_making strategy using uniswap_ethereum_mainnet connector. I created a gateway wallet for mainnet. And when trying to create a strategy, the uniswap_ethereum_mainnet is not listed.
![Screenshot 2024-07-29 at 13 14 01](https://github.com/user-attachments/assets/3df94fa7-e411-47eb-ab47-bb8de9e2742d)
The uniswap_ethereum_mainnet is listed when I'm trying to create a amm_arb strategy
![Screenshot 2024-07-29 at 13 16 01](https://github.com/user-attachments/assets/d2a07af5-f463-4d19-a72e-3ce7a936fc5b)

### Steps to reproduce

1. Connect a mainnet wallet using the gateway
2. Try to create a pure_market_making strategy

### Release version

dev-2.0.1

### Type of installation

Source

**Comment by annemarieshev** [comment]
Hello @LautaroNavarro 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID ETH07638
Please see the link below to our dedicated support line:
[Ethereum Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by fengtality** [comment]
See this PR for ongoing updates: https://github.com/hummingbot/gateway/pull/342

did you run `gateway connect` to add the Uniswap connector first?

Afterwards, the Uniswap connector for the network you connected should appear. See image below

<img width="623" alt="Screenshot 2024-07-29 at 1 52 27 PM" src="https://github.com/user-attachments/assets/d6dc5416-f2a0-4dc7-a3b7-96e49907b4fc">

**Comment by LautaroNavarro** [comment]
> See this PR for ongoing updates: [hummingbot/gateway#342](https://github.com/hummingbot/gateway/pull/342)
> 
> did you run `gateway connect` to add the Uniswap connector first?
> 
> Afterwards, the Uniswap connector for the network you connected should appear. See image below
> 
> <img alt="Screenshot 2024-07-29 at 1 52 27 PM" width="623" src="https://private-user-images.githubusercontent.com/1795030/353233215-d6dc5416-f2a0-4dc7-a3b7-96e49907b4fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDI4ODksIm5iZiI6MTcyMjM0MjU4OSwicGF0aCI6Ii8xNzk1MDMwLzM1MzIzMzIxNS1kNmRjNTQxNi1mMmEwLTRkYzctYTNiNy05NmU0OTkwN2I0ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMTIyOTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ5MzRjNWE3NTU2ZjllNTYxNWE0N2E3NjU4YTQxMTMwNmZmNDMyOTJiNDk5ZGEwYmZiZWE0OGQxZDNlZGI2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YF0l930TGTyvbbQ1fM4VHUbXHkYo5LgDJk4-BzsFb54">

Yes I run `gateway connect`
I can see the connector for the amm_arb, but not for pure_market_making. The screenshot that you attached is showing amm_arb strategy, not pure_market_making! Which is the one that can't find the connector for me

**Comment by rapcmia** [comment]
@LautaroNavarro our pure market making strategy is meant for platforms like Binance, Kucoin etc.. that use order books to match buyers and sellers. Since Uniswap doesn't have an order book, you can't use it therefore the v1 strategy we design for connectors like uniswap is using amm_arb and amm_v3_lp (with gateway). Closing this ticket
