### ISSUE TITLE
XEMM Order amount is stuck/ wrong order amount

### ISSUE THREAD

**Issue by acoronado11-work** [hummingbot/hummingbot#7156]
### Describe the bug

Order amount in strategy is set to .00014 however, it keeps trying to submit limit ask and sell order amounts at .00000526, which is below exchange minimums and not even close to the order amount I'm trying to execute. I've changed all order size settings between max and minimum, turned on and off adjust order, and tried creating new configs to set the order amount again but it remains stuck trying to put in orders at .00000526 . 

(some limit maker buys are set at the correct .00014 but the majority of order amounts are incorrect). Happy to try any potential remedies. 

### Steps to reproduce

1. 
2. 
3. 

### Release version

2.0.0

### Type of installation

Source

### Attach required files

![Screenshot (87)](https://github.com/user-attachments/assets/6275a282-8b20-41c6-abe9-dda8cbe8ab16)
![Screenshot (88)](https://github.com/user-attachments/assets/fdfb1db5-4542-43a1-82d5-a342cc649fcf)

**Comment by rapcmia** [comment]
Hi @acoronado11-work xemm v1 has not been maintain for the longest time therefore probably issues with it and the foundation team focused improving our v2 strategies. I would recommend to have a look with our [v2_xemm.py](https://github.com/hummingbot/hummingbot/blob/master/scripts/v2_xemm.py)

Below screenshot shows how you can setup

![image](https://github.com/user-attachments/assets/3a2edfe3-104c-4982-baae-28ce31b4305d)
- Set target_profitability to 0.0005 (or 0.05%)
- Set min_profitability to 0.0001 (or 0.01%)
- Set max_profitability to 0.015 (or 1.5%)
- Order amount in quote asset to 50usdt

**Comment by acoronado11-work** [comment]
Hey @rapcmia ,

it looks like I am currently using xemm v2. Checkout my script. (v2 scripts on right screen to show they are the same) 
![Screenshot (94)](https://github.com/user-attachments/assets/11d0097d-4557-48a2-aa0a-e32e4f3c148a)
