### ISSUE TITLE
I can't see the gateway

### ISSUE THREAD

**Issue by hack3rcon** [hummingbot/hummingbot#7168]
Hello,
I did:
```
# docker compose up -d
# docker compose ps
NAME         IMAGE                          COMMAND                  SERVICE      CREATED          STATUS          PORTS
gateway      hummingbot/gateway:latest      "docker-entrypoint.s…"   gateway      33 seconds ago   Up 30 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:15888->15888/tcp, :::15888->15888/tcp
hummingbot   hummingbot/hummingbot:latest   "/bin/bash -lc 'cond…"   hummingbot   33 seconds ago   Up 31 seconds   
```
Then, I did:
`# docker attach hummingbot
`

I see the message **Gateway: ONLINE**, but when I browse **localhost:8080**, then I just see the **Swagger UI**.

Any idea?

Thank you.

**Comment by rapcmia** [comment]
We have templates for github support which are bug report, bounty and feature request. Kindly follow the correct way of submitting github issues

**Comment by hack3rcon** [comment]
> We have templates for github support which are bug report, bounty and feature request. Kindly follow the correct way of submitting github issues

Hello,
Is this a bug? Why you closed this thread?
