### ISSUE TITLE
Bybit Perpetual - Upgrade API to V5

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#7179]
### Description

Bounty to update bybit_perpetual connector API to V5

Bybit had a newsletter where is officially informed that they will suspend the use of our old version openAPI service. This decision was made in order to reduce unnecessary maintenance and cost, and also to ensure the stability bybit platform. 
Users can migrate to [V5 API](https://bybit-exchange.github.io/docs/v5/intro), which has the full ability.

> 
> Details regarding to offline plan:
> 
> 1. Offline market Rest API endpoints and public websocket stream on 16 OCT 2023
> 
> USDC Option V1 [Market Data Rest API Endpoints](https://bybit-exchange.github.io/docs-legacy/usdc/option/#t-marketdata) , [Public Topics](https://bybit-exchange.github.io/docs-legacy/usdc/option/#public-topics)
> 
> USDC Perpetual V1 [Market Data Endpoints](https://bybit-exchange.github.io/docs-legacy/usdc/perpetual/#t-marketdata) , [Public Topics](https://bybit-exchange.github.io/docs-legacy/usdc/perpetual/#t-publictopics)
> 
> Spot V1 [Market Data Endpoints](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-marketdata) , [Public Topics V1](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-publictopics) , [Public Topics V2](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-publictopics_v2)
> 
> Inverse Perpetual V2 [Market Data Endpoints](https://bybit-exchange.github.io/docs-legacy/futuresV2/inverse/#t-marketdata) , [Public Topics](https://bybit-exchange.github.io/docs-legacy/futuresV2/inverse/#t-publictopics)
> 
> Inverse Futures V2 [Market Data Endpoints](https://bybit-exchange.github.io/docs-legacy/futuresV2/inverse_futures/#t-marketdata) , [Public Topics](https://bybit-exchange.github.io/docs-legacy/futuresV2/inverse_futures/#t-publictopics)
> 
> USDT Perpetual V2 [Market Data Endpoints](https://bybit-exchange.github.io/docs-legacy/futuresV2/linear/#t-marketdata) , [Public Topics](https://bybit-exchange.github.io/docs-legacy/futuresV2/linear/#t-publictopics)
> 
> 
> 2. Offline private Rest API endpoints and private websocket stream on 30 OCT 2023
> 
> USDC Option V1 [Account Data Rest API Endpoints](https://bybit-exchange.github.io/docs-legacy/usdc/option/#t-accountdata) , [Private Topics](https://bybit-exchange.github.io/docs-legacy/usdc/option/#private-topics)
> 
> USDC Perpetual V1 [Account Data Endpoints](https://bybit-exchange.github.io/docs-legacy/usdc/perpetual/#t-accountdata) , [Private Topics](https://bybit-exchange.github.io/docs-legacy/usdc/perpetual/#t-privatetopics)
> 
> Spot V1 [Account Data Endpoints](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-accountdata) , [Wallet Data Endpoints](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-wallet) , [Leveraged Token Endpoints](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-lt) , [Cross Margin Trading Endpoints](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-crossmargintrading) , [Private Topics](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-privatetopics)
> 
> Asset V1 [Transfer Data Endpoints](https://bybit-exchange.github.io/docs-legacy/account_asset/v1/#t-transfer_api) , [Withdraw and Deposit Endpoints](https://bybit-exchange.github.io/docs-legacy/account_asset/v1/#t-withdraw_and_deposit)
> 
> Inverse Perpetual V2 [Account Data Endpoints](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-accountdata) , [Wallet Data Endpoints](https://bybit-exchange.github.io/docs-legacy/spot/v1/#t-wallet) , [Private Topics](https://bybit-exchange.github.io/docs-legacy/futuresV2/inverse/#t-privatetopics)
> 
> Inverse Futures V2 [Account Data Endpoints](https://bybit-exchange.github.io/docs-legacy/futuresV2/inverse_futures/#t-accountdata) , [Wallet Data Endpoints](https://bybit-exchange.github.io/docs-legacy/futuresV2/inverse_futures/#t-wallet) , [Private Topics](https://bybit-exchange.github.io/docs-legacy/futuresV2/inverse_futures/#t-privatetopics)
> 
> USDT Perpetual V2 [Account Data Endpoints](https://bybit-exchange.github.io/docs-legacy/futuresV2/linear/#t-accountdata) , [Wallet Data Endpoints](https://bybit-exchange.github.io/docs-legacy/futuresV2/linear/#t-wallet) , [Private Topics](https://bybit-exchange.github.io/docs-legacy/futuresV2/linear/#t-privatetopics)
> 
> 
> Thank you for your continued support and understanding.
> 
> Best regards,
> 
> The Bybit Team

![image](https://github.com/hummingbot/hummingbot/assets/83953535/86c2ee60-ed78-418e-b5e4-25a4936d2e49)

### Bounty

Sponsor: Funded by [Hummingbot community sponsors](https://hummingbot.org/bounties/sponsors/)
Bounty Amount: 470 USDC
Developer Payment: 376 USDC [(80%)](https://hummingbot.org/bounties/sponsors/#handling-fee)

**Comment by tomasgaudino** [comment]
hi @nikspz can i get this one please?

**Comment by nikspz** [comment]
Assigned to @tomasgaudino, please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by tomasgaudino** [comment]
Thanks! I'll notify any update on this topic

**Comment by tomasgaudino** [comment]
https://github.com/hummingbot/hummingbot/pull/7196

**Comment by cardosofede** [comment]
should we close this one? @nikspz

**Comment by nikspz** [comment]
@cardosofede I think there's some updates from bybit side, I created this one and asked @tomasgaudino to check if he could use the connector https://github.com/hummingbot/hummingbot/issues/7267

**Comment by nikspz** [comment]
![image](https://github.com/user-attachments/assets/f382891b-4ab7-4013-b56b-eae598ee76fb)
For me I currently failed to connect updated account (newest one)
For the previous one I was not able to place orders

**Comment by nikspz** [comment]
> ![image](https://private-user-images.githubusercontent.com/83953535/381023451-f382891b-4ab7-4013-b56b-eae598ee76fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzkwMzgsIm5iZiI6MTczMDg3ODczOCwicGF0aCI6Ii84Mzk1MzUzNS8zODEwMjM0NTEtZjM4Mjg5MWItNGFiNy00MDEzLWI1NmItZWFlNTk4ZWU3NmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA3Mzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyY2FkM2YwMzMzMDI4ZTY1MWRmZWM1YmRjMWE1ZDViN2Q5Yjk2Yzc4OTAyYTA5NjYyNDMyMDk2NzE4NzVjOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mogjnJy9watpv6Rd8EtyNn_sGkCeJNfOKiWyvFMT4I0) For me I currently failed to connect updated account (newest one) For the previous one I was not able to place orders

https://github.com/hummingbot/hummingbot/issues/7267

Fix merged. Update API to V5 (for unified trading accounts) available in the latest development branch (dev-2.2.0) and will be fully available in the next release 2.2.0

**Comment by tomasgaudino** [comment]
thanks guys!
