### ISSUE TITLE
Repository cannot be downloaded during installation (error rpc failed, fatal: early EOF)

### ISSUE THREAD

**Issue by alrog2000** [hummingbot/hummingbot#7206]
### Describe the bug

Repository cannot be downloaded during installation.
Pls see the attached screen.
<img width="602" alt="Снимок экрана 2024-09-04 в 17 50 40" src="https://github.com/user-attachments/assets/141d69d7-599e-41f9-bde8-6d348ea1d7c8">

### Steps to reproduce

1. open terminal
2. insert: git clone https://github.com/hummingbot/hummingbot
3. press Enter

### Release version

i suppose git clone https://github.com/hummingbot/hummingbot downloading the current version

### Type of installation

Docker

### Attach required files

<img width="602" alt="Снимок экрана 2024-09-04 в 17 50 40" src="https://github.com/user-attachments/assets/f2176171-096d-4a6c-8939-5b51080ea3ee">

**Comment by nikspz** [comment]
I think issue related to github. @alrog2000 To resolve you could try to download again until downloaded successfully
![image](https://github.com/user-attachments/assets/6bb2c277-2b5a-44da-95ec-97d617264e46)

**Comment by alrog2000** [comment]
Thanks! Today it's downloaded. We can close the issue.
