### ISSUE TITLE
coinbase_advanced_trade connector not able to connect.

### ISSUE THREAD

**Issue by luke-tt** [hummingbot/hummingbot#7208]
### Describe the bug

Within the client, after entering `connect coinbase_advanced_trade` and entering in the API key and API secret key it returns the following error message: `Error: module 'coinbase.constants' has no attribute 'REST_SERVICE'`. Screenshot attached 
<img width="726" alt="hb_cb_error" src="https://github.com/user-attachments/assets/761dd7b9-7a3b-4a9e-86a9-ba12bfedf494">

Tried with v2.0.1, v2.0.0 and last v1 release too.

### Steps to reproduce

1. enter hummingbot terminal
2. enter commend: connect coinbase_advanced_trade
3. enter api key and secret key

### Release version

v2.0.1

### Type of installation

Source

### Attach required files

Logs from upon starting up the client.

[logs_hummingbot.log](https://github.com/user-attachments/files/16924239/logs_hummingbot.log)

**Comment by rapcmia** [comment]
![image](https://github.com/user-attachments/assets/d4dd03d8-d042-4faf-a84e-53e1eaafb7fb)
- Able to connect old API keys used for testing on latest ver 2.0.1
- Create new API key and added ok, see video [here](https://www.loom.com/share/aa720a19ba9d48508c9a05f5d1a885ab)

**Comment by luke-tt** [comment]
Please ignore, I reinstalled from source and it is now working!
