### ISSUE TITLE
bybit Spot - Failed to connect API to dashboard

### ISSUE THREAD

**Issue by Chebaoshan** [hummingbot/hummingbot#7209]
I just follow the quick start and created api of my test account but it doesnt work
![image](https://github.com/user-attachments/assets/3236f0e4-1f56-464f-96b9-1258ce9a772f)
![image](https://github.com/user-attachments/assets/895cf2f3-8809-42de-a688-1a512e3d03c4)

**Comment by rapcmia** [comment]
Hi @Chebaoshan this is related to our hummingbot lib currently not updated to the latest version, our team is still working for  the fix 🙏🏼

**Comment by Chebaoshan** [comment]
Thank you for your response sir.
Appreciate

**Comment by CloverEc** [comment]
When will this issue be solved?　@rapcmia

**Comment by nikspz** [comment]
![image](https://github.com/user-attachments/assets/c81f489e-e066-4875-a6b0-8bb107ef5fe5)
![image](https://github.com/user-attachments/assets/306e98b9-4426-4bac-bea8-425f4fc9eb18)

However was able to login from Client (latest development)
![image](https://github.com/user-attachments/assets/b2f89701-1302-4c04-ad97-30e8d575fed5)



Please check the restricted areas as well. 
https://www.bybit.com/en/help-center/article/Service-Restricted-Countries

**Comment by nikspz** [comment]
![image](https://github.com/user-attachments/assets/b1711fd2-b898-48e5-bcd2-19cd443fdbdf)
backend-api

**Comment by nikspz** [comment]
Works on other connectors for latest development (dashboard)
![image](https://github.com/user-attachments/assets/75cd1ddc-bdba-42f3-93d7-f7afec971657)
![image](https://github.com/user-attachments/assets/3bb0ab84-22e6-47d2-8859-45a0d4afba8c)
![image](https://github.com/user-attachments/assets/345cdce8-7358-43ce-bf3a-f995def5eec3)

**Comment by CloverEc** [comment]
The testnet failed but the mainnet succeeded. Thank you.

**Comment by CloverEc** [comment]
As expected, I can't connect to the bybit API from the dashboard. When will this be fixed? Is there a way to solve this now? @nikspz

**Comment by nikspz** [comment]
we need to update pypi dependencies (hummingbot) for dashboard. so after it's updated should work most likely @CloverEc

**Comment by nikspz** [comment]
currently working on it, I will notify and close this issue when updated

**Comment by CloverEc** [comment]
> dependencies

What parts specifically need to be updated? hummingbot/dashboard?

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/issues/7233 duplicated here

**Comment by nikspz** [comment]
> What parts specifically need to be updated? hummingbot/dashboard?[https://github.com/hummingbot/deploy？](https://github.com/hummingbot/deploy%EF%BC%9F)

This dependency need to be updated
https://pypi.org/project/hummingbot/20240713/#history

**Comment by rapcmia** [comment]
Library updated and bybit spot should be available on dashboard
![image](https://github.com/user-attachments/assets/1951297a-355e-4909-908c-e04d3acf891a)
