### ISSUE TITLE
Connects to Uniswap exchange instead of PancakeSwap

### ISSUE THREAD

**Issue by pifagorsoft** [hummingbot/hummingbot#7241]
### Describe the bug

Set up the **amm_arb** strategy for 2 exchanges: **binance_paper_trade** and **pancakeswap_binance-smart-chain_testnet**:
![Screenshot_1](https://github.com/user-attachments/assets/6c1b94f4-3f46-4112-a0d4-56641c621c12)
I launch the strategy - an error occurs:
![Screenshot_2](https://github.com/user-attachments/assets/4f959731-cd43-4ce7-af07-8412fc4a9600)
The error shows that the bot is trying to connect to the Uniswap exchange instead of the PancakeSwap exchange.

### Steps to reproduce

1. Using the command **create** create a new strategy based on **amm_arb**
2. Set PancakeSwap exchange as connector2
3. Start strategy

### Release version

2.0.1

### Type of installation

Source

**Comment by cardosofede** [comment]
@fengtality did you know about this issue?

**Comment by fengtality** [comment]
Pancakeswap uses the `Uniswapish` class so it might use code in the Uniswap folder, so this may not be a bug.

If a bug actually exists, run AMM-ARB on actual pools that exist on Binance Smart Chain (mainnet NOT testnet), and show us the pool address with transaction links and logs from your runs.
