### ISSUE TITLE
Current project status? 

### ISSUE THREAD

**Issue by joeyfigaro** [hummingbot/hummingbot#7257]
### Describe the bug

Is Hummingbot still actively maintained? There's a flood of open PRs with no engagement and the copyright year on the docs site is still 2023. 

### Steps to reproduce

N/A

### Release version

N/A

### Type of installation

Source

### Attach required files

N/A

**Comment by archnerd420** [comment]
Check the development branch for recent commits if you're having issues. They're fixing the big stuff but are stretched thin.

**Comment by nikspz** [comment]
> ### Describe the bug
> Is Hummingbot still actively maintained? 

Yes, next release (2.0.2) is in November

> There's a flood of open PRs with no engagement 

All prs (except bug fixes) should go through governance process

https://hummingbot.org/governance/
https://hummingbot.org/governance/proposals/

> and the copyright year on the docs site is still 2023.
> 

Thanks for report this minor bug. will fix

**Comment by joeyfigaro** [comment]
Thanks @archnerd420 / @nikspz – do you guys accept PRs for minor docs issues (typos, etc.)? Would be happy to put up changes as I find.

**Comment by nikspz** [comment]
yes sure, we have this PRs also to update docs
https://github.com/hummingbot/hummingbot-site/pulls
