### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xuyaoGitHub** [hummingbot/hummingbot#7259]
### Feature Suggestion

Did hummingbot provide function for placing orders in batch?
self.buy or self.sell need to wait the return value of order id and may not be the best choice.

### Impact

improve the efficiency for strategies such as market making.

**Comment by cardosofede** [comment]
It's supported by some exchanges (check injective for example)! if you want, you can adapt the code for the exchange that you want and submit a PR or post a bounty for someone to implement it.
