### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by liveseed** [hummingbot/hummingbot#7263]
### Feature Suggestion

I want Japanese exchanges(coincheck or zaif) to be added to the hummingbot connector!

### Impact

I want Japanese exchanges(coincheck or zaif) to be added to the hummingbot connector!

**Comment by nikspz** [comment]
If you want to sponsor bounty for connector development please review: 
https://hummingbot.org/bounties/external/

**Comment by nikspz** [comment]
@liveseed 
If you referring to this PR https://github.com/hummingbot/hummingbot/pull/7240
then to add these connectors:
1. dev needs to add unit tests and it should pass github checks
2. dev / community should submit snapshot vote and it should pass 
(https://hummingbot.org/governance/proposals/#new-connector-proposals)

**Comment by liveseed** [comment]
I need a developer who can do this.

**Comment by nikspz** [comment]
> I need a developer who can do this.

You could fund a bounty to add connector 
Please review:
https://hummingbot.org/bounties/lifecycle/

https://hummingbot.org/bounties/external/
