### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xuyaoGitHub** [hummingbot/hummingbot#7264]
### Feature Suggestion

do hummingbot provide instant or cancel placing order function.
if not, please add this feature.

### Impact

accurate control for order management

**Comment by nikspz** [comment]
Yes, hummingbot supports placing and cancel order function
you could see list of the docs/ exchanges supported here:
https://hummingbot.org/docs/

**Comment by xuyaoGitHub** [comment]
> Yes, hummingbot supports placing and cancel order function you could see list of the docs/ exchanges supported here: https://hummingbot.org/docs/

I mean Instant or cancel (IOC) function, I saw MARKET, LIMIT, LIMIT_MAKER, but not IOC
