### ISSUE TITLE
bybit_perpetual - Failed to place order, stuck on insufficient balance

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#7267]
### Describe the bug

bybit_perpetual - Failed to place order, stuck on insufficient balance / failed to connect unified 

### Steps to reproduce

1. Clone and install latest dev branch (dev-2.0.2)
2. connect bybit_perpetual
3. create/start strategy using bybit perpetual

Actual: 
Review that client failed to start placing orders

### Release version

dev-2.0.2

### Type of installation

Source

### Attach required files

1. Failed to place order, however have balance on exchange
[logs_bybit.log](https://github.com/user-attachments/files/17522323/logs_bybit.log)

2. changed account to unified, failed to connect with error: retcode <10001> accountType only support UNIFIEDaccount 

![image](https://github.com/user-attachments/assets/6275eb3b-d9ff-4196-81c2-b28488c059dd)

**Comment by nikspz** [comment]
Sponsor: HB Foundation
Bounty Amount: 10K HBOT
Developer Payment: 10K HBOT

**Comment by nikspz** [comment]
Fix merged and available in the latest development branch (dev-2.2.0) and will be available in the next release 2.2.0

**Comment by mitchbarks** [comment]
Currently running the bot from deploy.. is there anyway I can update this file manually or do I have to wait till the next release?
