### ISSUE TITLE
bybit_perpetual - error: retcode <10001> accountType only support UNIFIEDaccount

### ISSUE THREAD

**Issue by mmtau** [hummingbot/hummingbot#7278]
### Describe the bug

Hallow. When i connecting to bybit_perpetual i got error: retcode <10001> accountType only support UNIFIEDaccount.  When connecting to bybit then ok. Got balance. 

### Steps to reproduce

1. Load hummingbot
2. Enter api info
3. Get error

### Release version

2.1.0

### Type of installation

Docker

**Comment by nikspz** [comment]
Thanks for the report,
Duplicated with this error
https://github.com/hummingbot/hummingbot/issues/7267
