### ISSUE TITLE
okx_perpetual position mode setting issue

### ISSUE THREAD

**Issue by louiswanglu** [hummingbot/hummingbot#7281]
### Describe the bug

class path: https://github.com/hummingbot/hummingbot/tree/master/hummingbot/connector/derivative/okx_perpetual/okx_perpetual_derivative.py   
 def start(self, clock: Clock, timestamp: float):
        super().start(clock, timestamp)
        if self._domain == CONSTANTS.DEFAULT_DOMAIN and self.is_trading_required:
            self.set_position_mode(PositionMode.HEDGE)
            
ASK: Why is it enforced as `PositionMode.HEDGE` here? Is there an issue with the logic?

### Steps to reproduce

1. 
2. 
3. 

### Release version

latest

### Type of installation

Source

**Comment by rapcmia** [comment]
There is a ongoing refactor of okx perpetual that can be found on here https://github.com/hummingbot/hummingbot/pull/7120, perhaps you may ask the assigned community-dev
