### ISSUE TITLE
是不是没人维护啊，https://hummingbot.org/scripts/examples/#v2-funding-rate-arbitrage 链接地址是404了

### ISSUE THREAD

**Issue by phpmac** [hummingbot/hummingbot#7309]
### Describe the bug

是不是没人维护啊，https://hummingbot.org/scripts/examples/#v2-funding-rate-arbitrage 链接地址是404了

一起加油啊

### Steps to reproduce

是不是没人维护啊，https://hummingbot.org/scripts/examples/#v2-funding-rate-arbitrage 链接地址是404了

一起加油啊

### Release version

latest

### Type of installation

Docker

**Comment by rapcmia** [comment]
Working on docs
![image](https://github.com/user-attachments/assets/e605fc76-7e69-4f5c-93a5-f39af215abe8)
