### ISSUE TITLE
unsupported operand type(s) for *: 'float' and 'decimal.Decimal'

### ISSUE THREAD

**Issue by MotherSoraka** [hummingbot/hummingbot#7317]
### Describe the bug

So i just installed the latest version of Hummingbot on WSL2+Ubuntu+Docker on Windows 10.
All the 3 Containers run and i can get into the Dashboard and donwload some candles, 
When trying to run a backtest using almost any of the controllers i get this cursed error:

`unsupported operand type(s) for *: 'float' and 'decimal.Decimal'`

am i doing anything wrong?

### Steps to reproduce

Try to run the backtest of controllers

### Release version

Streamlit v1.33.0

### Type of installation

Docker

**Comment by rapcmia** [comment]
Our test server is running on Ubuntu24.04 and did a fresh install (purged all docker containers,etc) and still manage to backtest. Kindly try to do a clean installation to see if this works 

![image](https://github.com/user-attachments/assets/312c8eb3-3cef-4745-82a0-8ab127719419)
