### ISSUE TITLE
Not able to connect to DEX like uniswap

### ISSUE THREAD

**Issue by Aiquant1** [hummingbot/hummingbot#7338]
### Describe the bug

When i'm running command connect DEX is not listed
here is the command: 
                                                                                      
  >>>  connect                                                                        
                                                                                      
  Testing connections, please wait...                                                 
      +-------------------------------+----------------+--------------------+         
      | Exchange                      |   Keys Added   |   Keys Confirmed   |         
      |-------------------------------+----------------+--------------------|         
      | ascend_ex                     | No             | No                 |         
      | binance                       | No             | No                 |         
      | binance_perpetual             | No             | No                 |         
      | binance_perpetual_testnet     | No             | No                 |         
      | binance_us                    | No             | No                 |         
      | bitfinex                      | No             | No                 |         
      | bitget_perpetual              | No             | No                 |         
      | bitmart                       | No             | No                 |         
      | bitrue                        | No             | No                 |         
      | bitstamp                      | No             | No                 |         
      | btc_markets                   | No             | No                 |         
      | bybit                         | No             | No                 |         
      | bybit_perpetual               | No             | No                 |         
      | bybit_perpetual_testnet       | No             | No                 |         
      | bybit_testnet                 | No             | No                 |         
      | coinbase_advanced_trade       | No             | No                 |         
      | cube                          | No             | No                 |         
      | dexalot                       | No             | No                 |         
      | dydx_v4_perpetual             | No             | No                 |         
      | foxbit                        | No             | No                 |         
      | gate_io                       | No             | No                 |         
      | gate_io_perpetual             | No             | No                 |         
      | hashkey                       | No             | No                 |         
      | hashkey_global_testnet        | No             | No                 |         
      | hashkey_perpetual             | No             | No                 |         
      | hashkey_perpetual_testnet     | No             | No                 |         
      | htx                           | No             | No                 |         
      | hyperliquid_perpetual         | No             | No                 |         
      | hyperliquid_perpetual_testnet | No             | No                 |         
      | injective_v2                  | No             | No                 |         
      | injective_v2_perpetual        | No             | No                 |         
      | kraken                        | No             | No                 |         
      | kucoin                        | No             | No                 |         
      | kucoin_hft                    | No             | No                 |         
      | kucoin_perpetual              | No             | No                 |         
      | mexc                          | No             | No                 |         
      | ndax                          | No             | No                 |         
      | ndax_testnet                  | No             | No                 |         
      | okx                           | No             | No                 |         
      | okx_perpetual                 | No             | No                 |         
      | polkadex                      | No             | No                 |         
      | tegro                         | No             | No                 |         
      | tegro_testnet                 | No             | No                 |         
      | vega_perpetual                | No             | No                 |         
      | vega_perpetual_testnet        | No             | No                 |         
      | vertex                        | No             | No                 |         
      | vertex_testnet                | No             | No                 |         
      | xrpl                          | No             | No                 |         
      +-------------------------------+----------------+--------------------+         

### Steps to reproduce

1. first of all i activate the environment using conda activate hummingbot
2. then i run the scripts compile and then start
3. after starting the hummingbot when i'm running connect command i don't see any DEX exchange(like uniswap)

### Release version

v2

### Type of installation

Source

**Comment by Jarrel-doe** [comment]
Hello @Aiquant1  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by nikspz** [comment]
> Hello @Aiquant1 A support ticket has been opened for you. Kindly Talk to Support on the 

scam

**Comment by nikspz** [comment]
> ### Describe the bug

> 3. after starting the hummingbot when i'm running connect command i don't see any DEX exchange(like uniswap)
> 

hi @Aiquant1 Use gateway for DEX connectors like uniswap

https://hummingbot.org/gateway/
https://hummingbot.org/dex-connectors/
