### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by realsetvin** [hummingbot/hummingbot#7349]
### Describe the bug

profit and loss does not work when paired against a non stablecoin
![image](https://github.com/user-attachments/assets/5f532063-84b0-480d-935f-90777c6838db)
im guesing its due to the ammount of decimals?
0.0000000445 XMR is the current price

### Steps to reproduce

pepew / xmr pair on xeggex 

### Release version

https://github.com/reubenyap/hummingbot

### Type of installation

Source

**Comment by gordonkoehn** [comment]
Decimals are a good guess :) This is a UX bug. 

Hummingbot does handle small amounts just fine, but the reporting of P&L or traded amounts can be suboptimal. This also happens on the `dashboard` currently (actually, there, the quote is always assumed to be USD).

Most markets are against quote USD, so don't go in the `<10^-3` range; hence, this was probably not a big issue. I am not sure how many have this problem; I have it, too, for one. 

Someone with a better macro view may be the one to judge if non-USD quotes are getting more popular and if this is worth a new feature here. I already made the feature request here:
- https://github.com/hummingbot/dashboard/issues/219

It could be solved with an if statement to revert to scientific notation. I am interested to look into it myself at some point.

Perhaps I could kindly suggest renaming your `Issue` to be more specific, like `UX Bug – P&L 0.00 for non-Stable Quote`.

**Comment by realsetvin** [comment]
> Decimals are a good guess :) This is a UX bug.
> 
> Hummingbot does handle small amounts just fine, but the reporting of P&L or traded amounts can be suboptimal. This also happens on the `dashboard` currently (actually, there, the quote is always assumed to be USD).
> 
> Most markets are against quote USD, so don't go in the `<10^-3` range; hence, this was probably not a big issue. I am not sure how many have this problem; I have it, too, for one.
> 
> Someone with a better macro view may be the one to judge if non-USD quotes are getting more popular and if this is worth a new feature here. I already made the feature request here:
> 
>     * [Feature request – Support for Trading Pairs with Non-USD Quote / Scientific Notation dashboard#219](https://github.com/hummingbot/dashboard/issues/219)
> 
> 
> It could be solved with an if statement to revert to scientific notation. I am interested to look into it myself at some point.
> 
> Perhaps I could kindly suggest renaming your `Issue` to be more specific, like `UX Bug – P&L 0.00 for non-Stable Quote`.

![image](https://github.com/user-attachments/assets/45e46250-0537-405d-bb28-a3f675d09205)
after doing a trivial amount of trades I finally accumulated enough trading data to show some fees pair xmr, i think it may be fine the way it is at the time of the report the trading data would have been so minimal as to show 0 when rounding

**Comment by realsetvin** [comment]
the lowest xmr value is piconero  10^-12  0.000000000001

realistically thats not a value most people use 

the lowest transcation fee is 0.000006 so im quite satisfied with the current display

**Comment by gordonkoehn** [comment]
@realsetvin 
Thanks for sharing this. It's informative for me.
Sounds perfectly sufficient indeed, then.
My issue was more with the `dashboard`.
