### ISSUE TITLE
[New Exchange Connector] Deribit

### ISSUE THREAD

**Issue by msmrz7** [hummingbot/hummingbot#900]
## Exchange Details :pencil2:
* **Name of exchange**: Deribit
* **Exchange URL**: https://deribit.com
* **Link to API docs**: https://docs.deribit.com
* **Type of exchange**: Centralized
* **Requester details**: Are you affiliated with the exchange? No

## Rationale / impact :pencil2:
Deribit is a platform with relatively low volume and liquidity. It provides maker rebate fees of 0.025% for the perpetual and 0.02% for the futures contracts, similar to the bitmex fee structure. Unlike bitmex, it does not become unresponsive during high-volatility market moves, which greatly reduces the risk of market making there.
I think it adding support for it would provide a great way for the community to generate some income, and an option to reduce counterparty risk by providing an additional exchange.

## Additional information :pencil2:
(Provide any other useful information that may be helpful to know about this exchange)

- - -
:warning: **_Note: do not modify below here_**

## Developer notes
This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
* [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
* [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
1. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  1. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  1. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
1. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  1. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
* Python
* Previous Cython experience is a plus (optional)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ranecy) by [Unito](https://www.unito.io)

**Comment by Sirlupinwatson1** [comment]
> Exchange Details ✏️
> 
> Name of exchange: Deribit
> Exchange URL: https://deribit.com
> Link to API docs: https://docs.deribit.com
> Type of exchange: Centralized
> Requester details: Are you affiliated with the exchange? No
> 
> Rationale / impact ✏️
> Deribit is a platform with relatively low volume and liquidity. It provides maker rebate fees of 0.025% for the perpetual and 0.02% for the futures contracts, similar to the bitmex fee structure. Unlike bitmex, it does not become unresponsive during high-volatility market moves, which greatly reduces the risk of market making there.
> I think it adding support for it would provide a great way for the community to generate some income, and an option to reduce counterparty risk by providing an additional exchange.
> Additional information ✏️
> (Provide any other useful information that may be helpful to know about this exchange)
> 
> ⚠️ Note: do not modify below here
> Developer notes
> This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.
> Resources
> 
> Exchange connector developer guide
> Discord forum
> 
> Deliverables
> 
> A complete set of exchange connector files as listed above.
> Unit tests (see existing unit tests):
> Exchange market test (example)
> Order book tracker (example)
> User stream tracker (example)
> Documentation:
> Code commenting (particularly for any code that is materially different from the templates/examples)
> Any specific instructions for the use of that exchange connector (example)
> 
> Required skills
> 
> Python
> Previous Cython experience is a plus (optional)

Wow , you guys are cool, I wish I was here before.  @msmrz7 @martinkou @PtrckM

**Comment by akhavr** [comment]
Is there any ongoing development to create Deribit connector?

**Comment by mifeng** [comment]
We plan to begin adding support for derivatives exchanges in mid-late 2020

**Comment by paimpozhil** [comment]
Thanks to the community for this wonderful project, any ETA/or dev version or news of this exchange being supported ?
